### ISSUE TITLE
未知原因报错

### ISSUE THREAD

**Issue by tomyxy** [TophantTechnology/ARL#100]
以如下配置再同一个任务输入100个ip，运行一段时间后提示error
以docker方式启动，2核4G云服务器
域名爆破类型 ：测试
端口扫描类型 ：全端口
端口扫描
服务识别
操作系统识别
站点识别
SSL证书
站点截图
![image](https://user-images.githubusercontent.com/17066506/111267241-a81a1580-8666-11eb-8554-3458144bf119.png)
报错如下：
[error.txt](https://github.com/TophantTechnology/ARL/files/6146771/error.txt)

**Comment by 1c3z** [comment]
日志里看就是没有正常输出结果，看是不是 被系统kill 了
宿主机上执行

```
dmesg | grep -i kill
```

另外可以尝试将，服务识别，操作系统识别 关闭看下有结果么。
