### ISSUE TITLE
下个版本考虑分布式吗

### ISSUE THREAD

**Issue by 0ps** [TophantTechnology/ARL#104]
Rt

**Comment by ShmilySec** [comment]
RT +1是否考虑分布式

**Comment by 1c3z** [comment]
@0ps @ShmilySec 
其实一直都支持的，请看这个
https://github.com/TophantTechnology/ARL/wiki/ARL-%E5%88%86%E5%B8%83%E5%BC%8F%E9%83%A8%E7%BD%B2%E8%AF%A6%E7%BB%86%E8%AF%B4%E6%98%8E
