### ISSUE TITLE
5003访问不了

### ISSUE THREAD

**Issue by liao10086** [TophantTechnology/ARL#105]
在Mac机器上使用了docker环境 5003访问不了
在kali上搭建5003也访问不了。

以前好像不用增加网桥的
![image](https://user-images.githubusercontent.com/37523122/111867429-d07b7a00-89ae-11eb-8938-ab7d07d90ea3.png)

![image](https://user-images.githubusercontent.com/37523122/111870810-c747d880-89c1-11eb-9a34-aef6bdeeaac0.png)

前几天在公司搭建的没问题。
现在看到昨天的docker-compose.yml有更新，不知道是不是这个缘故

**Comment by york-cmd** [comment]
MAC上遇到同样的问题，用kali也是打不开，请问老哥解决了吗？

**Comment by liao10086** [comment]
> MAC上遇到同样的问题，用kali也是打不开，请问老哥解决了吗？

等他们修复吧。

**Comment by wzwz96** [comment]
+1，访问不了

**Comment by ymbzd** [comment]
+1  特意在vps上搭建同样的问题

**Comment by 1c3z** [comment]
@liao10086  @york-cmd   @wzwz96 
 麻烦各位执行 docker  images 看下 镜像有没有更新。
如果没有的话，看`/etc/docker/daemon.json` 有没有配置源，有的话把配置删除重启docker生效。

**Comment by liao10086** [comment]
已经解决。我把原来的阿里云的镜像源改为官方的就可以了。

**Comment by skr-rks** [comment]
请问下。我的镜像已经更新到最新了。5003还是访问不到，是怎么回事呀？
日志如下：
![截图](https://user-images.githubusercontent.com/57212526/112496801-feeac200-8dbf-11eb-9154-2b92f4136ad5.png)

**Comment by Wwon1oung** [comment]
首先，删除.json镜像源里的所有内容。
![image](https://user-images.githubusercontent.com/55070231/112571082-40ac5480-8e22-11eb-8807-fb037651192b.png)
确保git pull是最新，否则执行git pull
然后更新 docker 镜像
docker-compose pull
再次新建并启动容器
docker-compose up -d
5003访问成功！

**Comment by skr-rks** [comment]
![截图1](https://user-images.githubusercontent.com/57212526/112596717-233db180-8e47-11eb-8731-37323f27763b.png)
![截图2](https://user-images.githubusercontent.com/57212526/112596778-3badcc00-8e47-11eb-881a-0a6a7c9ea14c.png)
![截图3](https://user-images.githubusercontent.com/57212526/112596957-7a438680-8e47-11eb-925a-862a1826758b.png)
如图，镜像是最新的，容器也是新建的。还是不行呀。不知道是哪一步出了问题

**Comment by 1c3z** [comment]
@skr-rks 
执行下, 看下是不是有输出， 没有输出说明镜像不是最新的。 
`docker inspect tophant/arl | grep 1d88064` 

如果有输出
`docker-compose exec web bash`

进入容器执行下面的命令看下是否都有输出结果
```
curl -v https://127.0.0.1 -k
curl -v http://127.0.0.1:5003
curl -v http://127.0.0.1
```

**Comment by skr-rks** [comment]
![1](https://user-images.githubusercontent.com/57212526/112606839-77e72980-8e53-11eb-8b15-57e724ef8807.png)
![2](https://user-images.githubusercontent.com/57212526/112606845-7a498380-8e53-11eb-994b-e56ed9de1e60.png)
![3](https://user-images.githubusercontent.com/57212526/112606850-7c134700-8e53-11eb-9480-328afbf4ee9d.png)

**Comment by 1c3z** [comment]
nginx 启动有点问题。。 
重新启动看下
```
docker-compose down  
docker-compose up -d 
```

**Comment by skr-rks** [comment]
重启了也还是一样的报错。。。

**Comment by 1c3z** [comment]
重启后等几分钟呢？ 

这里还是一样的错误？ 
https://github.com/TophantTechnology/ARL/issues/105#issuecomment-808047756

**Comment by skr-rks** [comment]
恩，等几分钟也还是这样。。

**Comment by qianxun0** [comment]
![image](https://user-images.githubusercontent.com/43699132/112928550-63ec4200-9149-11eb-9840-17a571f734fa.png)
这到底是哪里出了问题？上面的评论操作了一遍，docker起来了，死活访问不了5003端口，快吐了

**Comment by 1c3z** [comment]
@qianxun0 

麻烦加下群吧  
 
![image](https://user-images.githubusercontent.com/9052484/112929621-62bc1480-914b-11eb-8292-9cd87eb4261c.png)
