### ISSUE TITLE
资产监控钉钉消息推送问题

### ISSUE THREAD

**Issue by ArthurSun1** [TophantTechnology/ARL#107]
设置了签名值和access_token但是在资产监控任务完成时并没有获得推送，测试了在test文件夹下的test_util_push.py,发现无法导入库，不知道是什么原因

**Comment by 1c3z** [comment]
麻烦截图提供下错误信息看下。

**Comment by ic3z** [comment]
刚看了下是容器没打好（少了test文件夹）

**Comment by 1c3z** [comment]
刚看了下，有点问题，容器里面没有test文件夹。

**Comment by union-cmd** [comment]
解决了么

**Comment by union-cmd** [comment]
我也遇到同样的问题

**Comment by 1c3z** [comment]
@ArthurSun1 

可以在资产分组详情里删除几个域名，删除原先的监控任务，再新建一个然后过一会就会触发一个监控任务（任务管理里可以看到），这个时候可以观察日志`arl_worker.log`看有什么错误输出

**Comment by 1c3z** [comment]
容器里面没有test文件夹问题已修复，已推送镜像。 

如有空可以尝试先pull, 再 up -d 进行更新。

另外可以 docker inspect tophant/arl | grep 3b104ffb 看下是不是有输出， 没有输出说明镜像不是最新的
