### ISSUE TITLE
新版本启动以后，无法访问

### ISSUE THREAD

**Issue by Oldman19** [TophantTechnology/ARL#108]
![image](https://user-images.githubusercontent.com/58176451/112239899-5125c900-8c82-11eb-9086-88fabbd458e1.png)
![image](https://user-images.githubusercontent.com/58176451/112239940-613da880-8c82-11eb-807e-e3aa0f0a5739.png)
防火墙开放了此端口，而且当把内部的80端口映射到5003访问时，版本是2.2.1，不知道为啥，映射443就不能访问，

**Comment by liao10086** [comment]
看已关闭的issue

**Comment by Oldman19** [comment]
> 看已关闭的issue
不太理解，可否给个官方镜像源，辛苦了

**Comment by 1c3z** [comment]
@Oldman19 
官方构建的源就是放在 Docker hub 的https://hub.docker.com/r/tophant/arl
如果为了加速用了第三方对Docker hub镜像的源， 但是这个第三方的源没有实时同步，拉取的latest 就不是最新的。
