### ISSUE TITLE
资产搜索timeout of 12000ms exceeded

### ISSUE THREAD

**Issue by test2504** [TophantTechnology/ARL#111]
使用“任务管理”、“资产搜索”功能，当数据量大时，会报超时“timeout of 12000ms exceeded”。
请问要修改哪个地方，自定义超时时间？

**Comment by 1c3z** [comment]
这个超时目前无法修改。
多少条数据?
机器配置？
硬盘使用情况检查下。

**Comment by test2504** [comment]
问题已解决！
我这边才700+条数据，机器配置8G 16G。
估计是之前硬盘满了，导致到数据库重启了。docker-compose restart重启就可以了。:）
