### ISSUE TITLE
设置了签名值和access_token但是在资产监控任务完成时并没有获得推送，测试了在test文件夹下的test_util_push.py

### ISSUE THREAD

**Issue by union-cmd** [TophantTechnology/ARL#112]
<img width="439" alt="image" src="https://user-images.githubusercontent.com/61687719/112723499-d7bffc00-8f49-11eb-99cf-38b2ae2f8814.png">

**Comment by union-cmd** [comment]
有解决方案了么？

**Comment by 1c3z** [comment]
这个命令是在容器里执行的，但是test文件夹忘记打包进镜像了。
临时解决方案
```
docker-compose exec worker  bash
mkdir test
touch test/__init__.py
vi test/test_utils_push.py
```

test_utils_push.py 是下面这个文件
https://github.com/TophantTechnology/ARL/blob/master/test/test_utils_push.py

然后再执行
```
python3.6 -m test.test_utils_push
```

**Comment by 1c3z** [comment]
但是在资产监控任务完成时并没有获得推送， 可以再资产库里删除几个域名，删除原先的监控任务，再新建一个然后过一会就会触发一个监控任务，这个时候可以观察日志`arl_worker.log`看有什么错误输出

**Comment by union-cmd** [comment]
<img width="569" alt="image" src="https://user-images.githubusercontent.com/61687719/112828664-9b63db80-90c2-11eb-99e8-5466e640d957.png">

**Comment by union-cmd** [comment]
我进入了docker 然后按照你这样做 到最后一步的时候遇到了这个 请问这是正常的么

**Comment by union-cmd** [comment]
问一下 如果我的资产进行了第二次扫描，然后如果扫出了新的域名信息或者其他的新信息 会有提示么 如果有在哪提示？

**Comment by 1c3z** [comment]
> 我进入了docker 然后按照你这样做 到最后一步的时候遇到了这个 请问这是正常的么


配置位置没写对，是在 docker/config-docker.yaml 这个文件

**Comment by 1c3z** [comment]
> 问一下 如果我的资产进行了第二次扫描，然后如果扫出了新的域名信息或者其他的新信息 会有提示么 如果有在哪提示？

二次扫描？ 第二次下同一个域名的任务？如果是这样的话，可以点击任务操作里的同步按钮
![image](https://user-images.githubusercontent.com/9052484/112924834-68adf780-9143-11eb-94b4-7667fa346df3.png)
如果有新的资产话，可以在资产分组详情里看到， 注意看更新时间。 
![image](https://user-images.githubusercontent.com/9052484/112924899-8b401080-9143-11eb-9ce6-db161464882e.png)

**Comment by union-cmd** [comment]
<img width="763" alt="image" src="https://user-images.githubusercontent.com/61687719/112926211-b0ce1980-9145-11eb-8ba5-59c0c28afadc.png">

**Comment by union-cmd** [comment]
<img width="946" alt="image" src="https://user-images.githubusercontent.com/61687719/112926337-e246e500-9145-11eb-86d0-b1badcbc809d.png">

**Comment by union-cmd** [comment]
还是不可以

**Comment by union-cmd** [comment]
是要进入哪个docker容器里面实现么？

**Comment by 1c3z** [comment]
![image](https://user-images.githubusercontent.com/9052484/112929835-ca725f80-914b-11eb-8e72-68ac818d25d9.png)

ACCESS_TOKEN 配置错了。

**Comment by union-cmd** [comment]
还是报那个错误

**Comment by union-cmd** [comment]
<img width="598" alt="image" src="https://user-images.githubusercontent.com/61687719/112982205-cf0c3780-918e-11eb-893f-a96d2a21c8b7.png">

**Comment by union-cmd** [comment]
<img width="568" alt="image" src="https://user-images.githubusercontent.com/61687719/112982287-e4816180-918e-11eb-9f13-bf27c1587fcd.png">

**Comment by 1c3z** [comment]
错误日志再往前面翻点， 
不如我这里填了，但是填错了，会打印错误

![image](https://user-images.githubusercontent.com/9052484/113080741-f522ed80-9209-11eb-90ab-ef2e01383ea4.png)

**Comment by 1c3z** [comment]
另外为了确保填对了位置， 可以进入容器查看确定。
```
docker-compose exec worker  bash
 cat /code/app/config.yaml
```
![image](https://user-images.githubusercontent.com/9052484/113080962-5f3b9280-920a-11eb-8b9a-7473953117ad.png)

**Comment by union-cmd** [comment]
我按照你的方法 去了/code/app/config.yaml文件里去填上token，但还是报错

**Comment by union-cmd** [comment]
<img width="916" alt="image" src="https://user-images.githubusercontent.com/61687719/113082704-8778c080-920d-11eb-8844-2fdf37848c19.png">

**Comment by union-cmd** [comment]
<img width="911" alt="image" src="https://user-images.githubusercontent.com/61687719/113082741-995a6380-920d-11eb-8731-a77b115462aa.png">

**Comment by union-cmd** [comment]
<img width="666" alt="image" src="https://user-images.githubusercontent.com/61687719/113082821-babb4f80-920d-11eb-807d-5226245834ee.png">

**Comment by union-cmd** [comment]
<img width="920" alt="image" src="https://user-images.githubusercontent.com/61687719/113082890-d6bef100-920d-11eb-9d5f-6c80f1aab8f1.png">

**Comment by union-cmd** [comment]
我想我应该解决了问题了 我的qq邮箱信息填写处有点问题 我不用qq邮箱发送 只保留钉钉的token信息 成功发送到了

**Comment by union-cmd** [comment]
但是 还是会报这个错误

**Comment by union-cmd** [comment]
<img width="679" alt="image" src="https://user-images.githubusercontent.com/61687719/113083299-8e540300-920e-11eb-9e02-9d2419804c0f.png">

**Comment by union-cmd** [comment]
我不知道会不会影响到我后面的信息发送的操作

**Comment by 1c3z** [comment]
这个不影响的， 失败一个不影响另一个。

**Comment by 1c3z** [comment]
容器里面没有test文件夹问题已修复，已推送镜像。 

如有空可以尝试先pull, 再 up -d 进行更新。

另外可以 docker inspect tophant/arl | grep 3b104ffb 看下是不是有输出， 没有输出说明镜像不是最新的
