### ISSUE TITLE
关于分布式的问题

### ISSUE THREAD

**Issue by Oldman19** [TophantTechnology/ARL#113]
问题：分布式部署以后，是会将1个任务（例如a任务中包含端口扫描，域名扫描，服务扫描）分开进行，就是1台机器会管域名扫描，另一个服务器管端口扫描，还是说，这个任务由一台服务器执行，如果有第二个任务，就会由其他服务器执行呢

**Comment by 1c3z** [comment]
这个任务由一台服务器执行，如果有第二个任务，就会由其他服务器执行。
