### ISSUE TITLE
子域名暴破建议添加泛域名解析判断处理

### ISSUE THREAD

**Issue by wdsjxh** [TophantTechnology/ARL#116]
如题，默认情况下没有针对泛域名解析的情况做判断，导致有很多子域名资产误报

**Comment by 1c3z** [comment]
这个有考虑到这种情况，测试了一些子域名不多的情况下，确实看起来都是误报，下个版本准备优化下。

**Comment by 1c3z** [comment]
已发布新版本，访问更新。
