### ISSUE TITLE
用户记录BUG

### ISSUE THREAD

**Issue by ymbzd** [TophantTechnology/ARL#117]
![image](https://user-images.githubusercontent.com/39881690/113136485-0265c980-9256-11eb-9256-10caa54f2698.png)
这里退出后，账号密码是自动记录的，再次点击可直接登录
![image](https://user-images.githubusercontent.com/39881690/113136546-13163f80-9256-11eb-84b5-9987e4e579f8.png)

**Comment by 1c3z** [comment]
这是浏览器自动的填充的，保存密码了。

**Comment by ymbzd** [comment]
确定不是自动填充…
