### ISSUE TITLE
大佬你好，想要修改扫描类型，请问在哪个文件中修改，如何生效？

### ISSUE THREAD

**Issue by wtt502** [TophantTechnology/ARL#126]

**Comment by 1c3z** [comment]
目前任务类型只有这里可以指定。
![image](https://user-images.githubusercontent.com/9052484/113699762-962d0f00-9708-11eb-9be1-7c2399fc8fb6.png)

**Comment by wtt502** [comment]
不是任务类型，是添加任务时，选择的扫描类型，应该是在代码里面才能改，但是找了很多，没找到这段代码
![image](https://user-images.githubusercontent.com/50694663/113796445-d5e40d00-9781-11eb-937b-38b505a4faad.png)

**Comment by 1c3z** [comment]
这个是被翻译了，是端口扫描类型。
可以改这个文件， 重启生效

docker/config-docker.yaml


![image](https://user-images.githubusercontent.com/9052484/114650333-aa7a9880-9d14-11eb-854d-38266a83e0db.png)
