### ISSUE TITLE
进行资产监控任务时，扫描结束后子域名等信息全部为空

### ISSUE THREAD

**Issue by BetterDefender** [TophantTechnology/ARL#128]
进行资产监控任务时，扫描结束后子域名等信息全部为空
![image](https://user-images.githubusercontent.com/59255707/114486493-98c7c100-9c40-11eb-82b4-04da21296067.png)
![image](https://user-images.githubusercontent.com/59255707/114486568-ba28ad00-9c40-11eb-9c93-b969552b711c.png)

**Comment by BetterDefender** [comment]
间隔24小时执行一次，所有监控任务的扫描结果都为空

**Comment by 1c3z** [comment]
这个是正常现象，监控任务只有发现新增的资产才会显示的。。

**Comment by BetterDefender** [comment]
好的 谢谢
