### ISSUE TITLE
api/doc  swagger无法访问

### ISSUE THREAD

**Issue by tollytu** [TophantTechnology/ARL#129]
error tips:  No API definition provided.
![image](https://user-images.githubusercontent.com/47838420/114645217-92eae200-9d0b-11eb-8c82-0625d9b7d31e.png)

**Comment by 1c3z** [comment]
感谢反馈，nginx 转发没配置好，下个版本修复。

**Comment by xtzxtz** [comment]
您好，这个api访问的nginx如何手动进行修复

**Comment by 1c3z** [comment]
@xtzxtz   
进入web容器，修改 /etc/nginx/nginx.conf 文件
![image](https://user-images.githubusercontent.com/9052484/118748798-eb734900-b88e-11eb-9670-f92927bc812f.png)
```
proxy_set_header   X-Forwarded-Proto $scheme; 
```

然后重启nginx 即可  nginx -s reload

**Comment by 1c3z** [comment]
问题已解决，已发布新版本，访问更新。
