### ISSUE TITLE
求完整的本地部署文档

### ISSUE THREAD

**Issue by zhengjim** [TophantTechnology/ARL#13]
星光哥，求一份完整的本地部署文档

**Comment by 1c3z** [comment]
可以参考下面几个
https://github.com/TophantTechnology/ARL/blob/master/Readme.md#%E6%9C%AC%E5%9C%B0%E5%AE%89%E8%A3%85
https://github.com/TophantTechnology/ARL/blob/master/docker/worker/Dockerfile


配置RabbitMQ
```
rabbitmqctl add_user arl arlpassword
rabbitmqctl add_vhost arlvhost
rabbitmqctl set_user_tags arl arltag
rabbitmqctl set_permissions -p arlvhost arl ".*" ".*" ".*"

```

添加并修改配置文件
```
cp app/config.yaml.example app/config.yaml
```

WEB 服务启动
```
gunicorn -b 0.0.0.0:5003 app.main:arl_app -w 3 --access-logfile arl_web.log
```

CELERY 启动
```
celery -A app.celerytask.celery worker -l info -Q arltask -n arltask -c 2 -O fair -f arl_worker.log
```

**Comment by zhengjim** [comment]
感谢星光哥
记录了下源码搭建的过程：https://www.cnblogs.com/zhengjim/p/13678257.html
