### ISSUE TITLE
端口识别严重不全！！！

### ISSUE THREAD

**Issue by ym2011** [TophantTechnology/ARL#131]
此图为同一个资产，ARL识别的结果。
![image](https://user-images.githubusercontent.com/14217880/115202320-e0f74f80-a128-11eb-97bb-61ee91d93e1a.png)

此图为同一个资产，goby识别的结果。
![image](https://user-images.githubusercontent.com/14217880/115202564-18fe9280-a129-11eb-96cb-81feb7a40a38.png)

为啥会出现这么大的误差@_@

**Comment by ym2011** [comment]
此为nmap手动扫描结果：
![image](https://user-images.githubusercontent.com/14217880/115217048-ad6ff180-a137-11eb-8fb2-d7b5852343a7.png)

**Comment by 1c3z** [comment]
感谢耐心测评和反馈。
根据最后一张图，扫描时间大概花了44分钟，这个目标主机对全端口扫描有一定的干扰。
端口扫描的参数针对的是批量IP的扫描，设置了超时参数和重试次数，全端口在有些情况下自测也发现结果会漏掉端口（和目标息息相关），针对像给的这个目标，目前还不知道怎么在尽可能短的时间情况下扫描的端口多，结果又准。

**Comment by ym2011** [comment]
修改了部分代码，调整nmap参数后，在任务管理执行任务可以识别到所有端口，但是在资产监控任务还是识别端口不全。
portScan.py

class PortScan:
    def __init__(self, targets, ports=None, service_detect = False, os_detect = False):
        self.targets = " ".join(targets)
        self.ports = ports
        #self.alive_port = "22,80,443,3389,8007-8011,8443,9090,8080-8091,8093,8099,5000-5004,2222,3306,1433,21,25"
        self.alive_port = "22,80,443,3389,8007-8011,8443,9090,8080-8091,8093,8099,5000-5004,2222,3306,1433,21,25"
        #self.nmap_arguments = "-sS -n --open --defeat-rst-ratelimit"
        self.nmap_arguments = "-sS -n --open"
        self.max_retries = 3
        self.host_timeout = 60*5
        if service_detect:
            self.host_timeout += 60 * 5
            self.nmap_arguments += " -sV"

        if os_detect:
            self.host_timeout += 60 * 4
            self.nmap_arguments += " -O"

        if len(self.ports.split(",")) > 60:
            self.nmap_arguments += " -PE -PS{}".format(self.alive_port)
            self.max_retries = 2
        else:
            if self.ports != "0-65535":
                self.nmap_arguments += " -Pn"

        if self.ports == "0-65535":
           #self.nmap_arguments += " -PE -PS{}".format(self.alive_port)
            self.host_timeout += 60 * 20
            self.max_retries = 2

        #self.nmap_arguments += " --max-rtt-timeout 320ms  --initial-rtt-timeout 100ms"
        #self.nmap_arguments += " --min-rate 64"
        #self.nmap_arguments += " --script-timeout 6s"
        #self.nmap_arguments += " --host-timeout {}s".format(self.host_timeout)
        #self.nmap_arguments += " --min-parallelism 32"
        self.nmap_arguments += " --max-retries {}".format(self.max_retries)

**Comment by 1c3z** [comment]
资产监控任务，端口默认传的是test 。

**Comment by NothingButStupid** [comment]
> 修改了部分代码，调整nmap参数后，在任务管理执行任务可以识别到所有端口，但是在资产监控任务还是识别端口不全。
> portScan.py
> 
> class PortScan:
> def **init**(self, targets, ports=None, service_detect = False, os_detect = False):
> self.targets = " ".join(targets)
> self.ports = ports
> #self.alive_port = "22,80,443,3389,8007-8011,8443,9090,8080-8091,8093,8099,5000-5004,2222,3306,1433,21,25"
> self.alive_port = "22,80,443,3389,8007-8011,8443,9090,8080-8091,8093,8099,5000-5004,2222,3306,1433,21,25"
> #self.nmap_arguments = "-sS -n --open --defeat-rst-ratelimit"
> self.nmap_arguments = "-sS -n --open"
> self.max_retries = 3
> self.host_timeout = 60*5
> if service_detect:
> self.host_timeout += 60 * 5
> self.nmap_arguments += " -sV"
> 
> ```
>     if os_detect:
>         self.host_timeout += 60 * 4
>         self.nmap_arguments += " -O"
> 
>     if len(self.ports.split(",")) > 60:
>         self.nmap_arguments += " -PE -PS{}".format(self.alive_port)
>         self.max_retries = 2
>     else:
>         if self.ports != "0-65535":
>             self.nmap_arguments += " -Pn"
> 
>     if self.ports == "0-65535":
>        #self.nmap_arguments += " -PE -PS{}".format(self.alive_port)
>         self.host_timeout += 60 * 20
>         self.max_retries = 2
> 
>     #self.nmap_arguments += " --max-rtt-timeout 320ms  --initial-rtt-timeout 100ms"
>     #self.nmap_arguments += " --min-rate 64"
>     #self.nmap_arguments += " --script-timeout 6s"
>     #self.nmap_arguments += " --host-timeout {}s".format(self.host_timeout)
>     #self.nmap_arguments += " --min-parallelism 32"
>     self.nmap_arguments += " --max-retries {}".format(self.max_retries)
> ```




> 修改了部分代码，调整nmap参数后，在任务管理执行任务可以识别到所有端口，但是在资产监控任务还是识别端口不全。
> portScan.py
> 
> class PortScan:
> def **init**(self, targets, ports=None, service_detect = False, os_detect = False):
> self.targets = " ".join(targets)
> self.ports = ports
> #self.alive_port = "22,80,443,3389,8007-8011,8443,9090,8080-8091,8093,8099,5000-5004,2222,3306,1433,21,25"
> self.alive_port = "22,80,443,3389,8007-8011,8443,9090,8080-8091,8093,8099,5000-5004,2222,3306,1433,21,25"
> #self.nmap_arguments = "-sS -n --open --defeat-rst-ratelimit"
> self.nmap_arguments = "-sS -n --open"
> self.max_retries = 3
> self.host_timeout = 60*5
> if service_detect:
> self.host_timeout += 60 * 5
> self.nmap_arguments += " -sV"
> 
> ```
>     if os_detect:
>         self.host_timeout += 60 * 4
>         self.nmap_arguments += " -O"
> 
>     if len(self.ports.split(",")) > 60:
>         self.nmap_arguments += " -PE -PS{}".format(self.alive_port)
>         self.max_retries = 2
>     else:
>         if self.ports != "0-65535":
>             self.nmap_arguments += " -Pn"
> 
>     if self.ports == "0-65535":
>        #self.nmap_arguments += " -PE -PS{}".format(self.alive_port)
>         self.host_timeout += 60 * 20
>         self.max_retries = 2
> 
>     #self.nmap_arguments += " --max-rtt-timeout 320ms  --initial-rtt-timeout 100ms"
>     #self.nmap_arguments += " --min-rate 64"
>     #self.nmap_arguments += " --script-timeout 6s"
>     #self.nmap_arguments += " --host-timeout {}s".format(self.host_timeout)
>     #self.nmap_arguments += " --min-parallelism 32"
>     self.nmap_arguments += " --max-retries {}".format(self.max_retries)
> ```
按照这样改完之后好慢呀

**Comment by 1c3z** [comment]
建议先本地手动调用nmap测试，看下效果怎么样，后面版本迭代过程中会把这些参数放到前端策略任务中   @NothingButStupid

**Comment by NothingButStupid** [comment]
> 建议先本地手动调用nmap测试，看下效果怎么样，后面版本迭代过程中会把这些参数放到前端策略任务中 @NothingButStupid

嗯嗯。 我也在那个py脚本里不断的调试 看效果。

**Comment by NothingButStupid** [comment]
> 建议先本地手动调用nmap测试，看下效果怎么样，后面版本迭代过程中会把这些参数放到前端策略任务中 @NothingButStupid

请问师傅，关于端口扫描不全这个问题 近期会出新版本改善吗，

**Comment by 1c3z** [comment]
@NothingButStupid  

由于公网的链路环境比较复杂，目前还没找到很好的解决方法，不知道你这边测试的怎么样了。

**Comment by NothingButStupid** [comment]
> 修改了部分代码，调整nmap参数后，在任务管理执行任务可以识别到所有端口，但是在资产监控任务还是识别端口不全。
> portScan.py
> 
> class PortScan:
> def **init**(self, targets, ports=None, service_detect = False, os_detect = False):
> self.targets = " ".join(targets)
> self.ports = ports
> #self.alive_port = "22,80,443,3389,8007-8011,8443,9090,8080-8091,8093,8099,5000-5004,2222,3306,1433,21,25"
> self.alive_port = "22,80,443,3389,8007-8011,8443,9090,8080-8091,8093,8099,5000-5004,2222,3306,1433,21,25"
> #self.nmap_arguments = "-sS -n --open --defeat-rst-ratelimit"
> self.nmap_arguments = "-sS -n --open"
> self.max_retries = 3
> self.host_timeout = 60*5
> if service_detect:
> self.host_timeout += 60 * 5
> self.nmap_arguments += " -sV"
> 
> ```
>     if os_detect:
>         self.host_timeout += 60 * 4
>         self.nmap_arguments += " -O"
> 
>     if len(self.ports.split(",")) > 60:
>         self.nmap_arguments += " -PE -PS{}".format(self.alive_port)
>         self.max_retries = 2
>     else:
>         if self.ports != "0-65535":
>             self.nmap_arguments += " -Pn"
> 
>     if self.ports == "0-65535":
>        #self.nmap_arguments += " -PE -PS{}".format(self.alive_port)
>         self.host_timeout += 60 * 20
>         self.max_retries = 2
> 
>     #self.nmap_arguments += " --max-rtt-timeout 320ms  --initial-rtt-timeout 100ms"
>     #self.nmap_arguments += " --min-rate 64"
>     #self.nmap_arguments += " --script-timeout 6s"
>     #self.nmap_arguments += " --host-timeout {}s".format(self.host_timeout)
>     #self.nmap_arguments += " --min-parallelism 32"
>     self.nmap_arguments += " --max-retries {}".format(self.max_retries)
> ```
您好，您的nmap参数十分有效，但是我在linux运行这些参数 查到的东西很少，但是windows下却能查询出所有的端口，请问您知道原因吗

**Comment by 1c3z** [comment]
> > 修改了部分代码，调整nmap参数后，在任务管理执行任务可以识别到所有端口，但是在资产监控任务还是识别端口不全。
> > portScan.py
> > class PortScan:
> > def **init**(self, targets, ports=None, service_detect = False, os_detect = False):
> > self.targets = " ".join(targets)
> > self.ports = ports
> > #self.alive_port = "22,80,443,3389,8007-8011,8443,9090,8080-8091,8093,8099,5000-5004,2222,3306,1433,21,25"
> > self.alive_port = "22,80,443,3389,8007-8011,8443,9090,8080-8091,8093,8099,5000-5004,2222,3306,1433,21,25"
> > #self.nmap_arguments = "-sS -n --open --defeat-rst-ratelimit"
> > self.nmap_arguments = "-sS -n --open"
> > self.max_retries = 3
> > self.host_timeout = 60*5
> > if service_detect:
> > self.host_timeout += 60 * 5
> > self.nmap_arguments += " -sV"
> > ```
> >     if os_detect:
> >         self.host_timeout += 60 * 4
> >         self.nmap_arguments += " -O"
> > 
> >     if len(self.ports.split(",")) > 60:
> >         self.nmap_arguments += " -PE -PS{}".format(self.alive_port)
> >         self.max_retries = 2
> >     else:
> >         if self.ports != "0-65535":
> >             self.nmap_arguments += " -Pn"
> > 
> >     if self.ports == "0-65535":
> >        #self.nmap_arguments += " -PE -PS{}".format(self.alive_port)
> >         self.host_timeout += 60 * 20
> >         self.max_retries = 2
> > 
> >     #self.nmap_arguments += " --max-rtt-timeout 320ms  --initial-rtt-timeout 100ms"
> >     #self.nmap_arguments += " --min-rate 64"
> >     #self.nmap_arguments += " --script-timeout 6s"
> >     #self.nmap_arguments += " --host-timeout {}s".format(self.host_timeout)
> >     #self.nmap_arguments += " --min-parallelism 32"
> >     self.nmap_arguments += " --max-retries {}".format(self.max_retries)
> > ```
> 
> 您好，您的nmap参数十分有效，但是我在linux运行这些参数 查到的东西很少，但是windows下却能查询出所有的端口，请问您知道原因吗


看下nmap版本，是不是版本太低了。

**Comment by NothingButStupid** [comment]
> > > 修改了部分代码，调整nmap参数后，在任务管理执行任务可以识别到所有端口，但是在资产监控任务还是识别端口不全。
> > > portScan.py
> > > class PortScan:
> > > def **init**(self, targets, ports=None, service_detect = False, os_detect = False):
> > > self.targets = " ".join(targets)
> > > self.ports = ports
> > > #self.alive_port = "22,80,443,3389,8007-8011,8443,9090,8080-8091,8093,8099,5000-5004,2222,3306,1433,21,25"
> > > self.alive_port = "22,80,443,3389,8007-8011,8443,9090,8080-8091,8093,8099,5000-5004,2222,3306,1433,21,25"
> > > #self.nmap_arguments = "-sS -n --open --defeat-rst-ratelimit"
> > > self.nmap_arguments = "-sS -n --open"
> > > self.max_retries = 3
> > > self.host_timeout = 60*5
> > > if service_detect:
> > > self.host_timeout += 60 * 5
> > > self.nmap_arguments += " -sV"
> > > ```
> > >     if os_detect:
> > >         self.host_timeout += 60 * 4
> > >         self.nmap_arguments += " -O"
> > > 
> > >     if len(self.ports.split(",")) > 60:
> > >         self.nmap_arguments += " -PE -PS{}".format(self.alive_port)
> > >         self.max_retries = 2
> > >     else:
> > >         if self.ports != "0-65535":
> > >             self.nmap_arguments += " -Pn"
> > > 
> > >     if self.ports == "0-65535":
> > >        #self.nmap_arguments += " -PE -PS{}".format(self.alive_port)
> > >         self.host_timeout += 60 * 20
> > >         self.max_retries = 2
> > > 
> > >     #self.nmap_arguments += " --max-rtt-timeout 320ms  --initial-rtt-timeout 100ms"
> > >     #self.nmap_arguments += " --min-rate 64"
> > >     #self.nmap_arguments += " --script-timeout 6s"
> > >     #self.nmap_arguments += " --host-timeout {}s".format(self.host_timeout)
> > >     #self.nmap_arguments += " --min-parallelism 32"
> > >     self.nmap_arguments += " --max-retries {}".format(self.max_retries)
> > > ```
> > 
> > 
> > 您好，您的nmap参数十分有效，但是我在linux运行这些参数 查到的东西很少，但是windows下却能查询出所有的端口，请问您知道原因吗
> 
> 看下nmap版本，是不是版本太低了。

请问是看我服务器本身的nmap版本 嘛， 还是说docker镜像里也有nmap。。

**Comment by 1c3z** [comment]
@NothingButStupid 

我还以为你手工测试的， 如果是单个IP，建议手工执行nmap比对测试下，看结果是不是一样。

**Comment by NothingButStupid** [comment]
感谢回复 我还在继续测试&nbsp; 感觉linux上的nmap 不如windows上的全。。 不知道为啥 我VPS上扫出来的东西少




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "TophantTechnology/ARL"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年9月13日(星期一) 上午10:44
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [TophantTechnology/ARL] 端口识别严重不全！！！ (#131)





 
@NothingButStupid
 
我还以为你手工测试的， 如果是单个IP，建议手工执行nmap比对测试下，看结果是不是一样。
 
—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by jhhd88** [comment]
> 感谢回复 我还在继续测试&nbsp; 感觉linux上的nmap 不如windows上的全。。 不知道为啥 我VPS上扫出来的东西少
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "TophantTechnology/ARL" ***@***.***&gt;; 发送时间:&nbsp;2021年9月13日(星期一) 上午10:44 ***@***.***&gt;; ***@***.******@***.***&gt;; 主题:&nbsp;Re: [TophantTechnology/ARL] 端口识别严重不全！！！ (#131) @NothingButStupid 我还以为你手工测试的， 如果是单个IP，建议手工执行nmap比对测试下，看结果是不是一样。 — You are receiving this because you were mentioned. Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android.

建议用虚拟机再测一遍，如果和你的VPS结果不一样 ，那么可能你需要换个VPS，或者调整VPS的网络安全策略

**Comment by NothingButStupid** [comment]
感谢您的回复，这个问题已经困扰我很长时间了，用windows能扫出来的东西 我的VPS就是不行，&nbsp; 请问我应当调整VPS的哪些属性呢。




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "TophantTechnology/ARL"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年9月13日(星期一) 中午12:33
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [TophantTechnology/ARL] 端口识别严重不全！！！ (#131)





  
感谢回复 我还在继续测试&nbsp; 感觉linux上的nmap 不如windows上的全。。 不知道为啥 我VPS上扫出来的东西少
 …
 ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "TophantTechnology/ARL" @.&gt;; 发送时间:&nbsp;2021年9月13日(星期一) 上午10:44 @.&gt;; @.@.&gt;; 主题:&nbsp;Re: [TophantTechnology/ARL] 端口识别严重不全！！！ (#131) @NothingButStupid 我还以为你手工测试的， 如果是单个IP，建议手工执行nmap比对测试下，看结果是不是一样。 — You are receiving this because you were mentioned. Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android.
  
建议用虚拟机再测一遍，如果和你的VPS结果不一样 ，那么可能你需要换个VPS，或者调整VPS的网络安全策略
 
—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by TARI0510** [comment]
@1c3z 想问问师傅为啥设计上不把 nmap 先用 SYN (`-sS`参数) 去扫呀？我看代码里是 `-sT`，这样扫描速度理论上应该会慢很多。像平常自己用 nmap 主要是先半开放 SYN 扫完然后在 -A 去扫版本这些。

**Comment by 1c3z** [comment]
@TARI0510  `-sS` 参数测试的时候碰到有部分目标会误报， `-sT` 的情况下不会，然后就直接用了`-sT`了

**Comment by TARI0510** [comment]
原来如此
