### ISSUE TITLE
导出报告端口拆分

### ISSUE THREAD

**Issue by Martin2877** [TophantTechnology/ARL#132]
![image](https://user-images.githubusercontent.com/26109420/115332700-ed33e900-a1ca-11eb-9d42-032c599a265b.png)

1、ip和端口拆开来看比较好，原表是ip端口合并的，最好最后有去重后的ip个数和清单

2、表里面建议修改文字字体是consolas，方便区分0和O

**Comment by 1c3z** [comment]
这个准备在下个版本改下。

**Comment by 1c3z** [comment]
已更改，已发布新版本，访问更新。
