### ISSUE TITLE
不知道什么原因docker启动不起来

### ISSUE THREAD

**Issue by mantianxing-liming** [TophantTechnology/ARL#133]
![image](https://user-images.githubusercontent.com/71966189/115362519-351b3600-a1f4-11eb-8cea-c8115a2b284f.png)

**Comment by mantianxing-liming** [comment]
我也重新安装了服务器配置也是可以的就是启动不起来

**Comment by mantianxing-liming** [comment]
换个系统还是启动不起来

**Comment by banmabanm** [comment]
我也一样的问题

**Comment by banmabanm** [comment]
docker volume create arl_db

**Comment by 1c3z** [comment]
@mantianxing-liming  解决了么？

**Comment by mantianxing-liming** [comment]
font{
        line-height: 1.6;
    }
    ul,ol{
        padding-left: 20px;
        list-style-position: inside;
    }


    
    已经解决了
        
    
        
            
        
    
    
         
        
            
    
        font{
            line-height: 1.6;
        }
    
星辰    渗透工程师缘于兴趣忠于热爱

    

        
    
     

    在2021年4月21日 ***@***.***> 写道： 



docker volume create arl_db
