### ISSUE TITLE
资产分组-资产范围不能添加IP

### ISSUE THREAD

**Issue by ym2011** [TophantTechnology/ARL#134]
请问资产分组-资产范围为啥不能添加IP，只能添加域名？？？IP不算资产吗？有些资产只有一个外网IP，没有域名。。

**Comment by ym2011** [comment]
![image](https://user-images.githubusercontent.com/14217880/115849777-cb9b6180-a457-11eb-8a00-b049a4455c4f.png)

**Comment by 1c3z** [comment]
资产分组这个概念是为了监控域名的实现才有的，目前只能监控域名, IP段这个就省掉了。
