### ISSUE TITLE
未授权访问漏洞的检测

### ISSUE THREAD

**Issue by ym2011** [TophantTechnology/ARL#136]
请问可以增加一些未授权访问漏洞的检测吗？例如redis，Mongodb、Memcached、ZooKeeper、Elasticsearch、Kibana、Docker Remote API 、ActiveMQ、druid等等。。

**Comment by 1c3z** [comment]
问题已解决，已发布新版本，访问更新。

**Comment by ym2011** [comment]
> 问题已解决，已发布新版本，访问更新。

厉害厉害
