### ISSUE TITLE
安装运行异常

### ISSUE THREAD

**Issue by littlebin404** [TophantTechnology/ARL#139]
师傅，使用如下安装方法：

```
git clone https://github.com/TophantTechnology/ARL
cd ARL/docker
docker-compose up -d
```

发现运行异常：
![1](https://user-images.githubusercontent.com/54022042/119109441-bf54f500-ba53-11eb-9825-35cc0dd4df35.png)
![2](https://user-images.githubusercontent.com/54022042/119109452-c1b74f00-ba53-11eb-84d4-dfdc1e3b5f51.png)
![3](https://user-images.githubusercontent.com/54022042/119109840-1d81d800-ba54-11eb-996f-5dfbb4278811.jpg)

https://127.0.0.1:5003  可以访问，但是功能都是无法使用的，还会报错，请问师傅要怎么解决呢？

**Comment by 1c3z** [comment]
rabbitmq 这个容器都运行异常了，最后一张图，docker daemon都运行异常了。

检查下硬盘是不是满了， 重启虚拟机试试。
