### ISSUE TITLE
[无法访问]Docker 部署 arl_web和arl_worker 一直处于 Restarting 状态

### ISSUE THREAD

**Issue by No-Github** [TophantTechnology/ARL#14]
1. 采用docker部署方式，clone git仓库
2. 按照 https://github.com/TophantTechnology/ARL/issues/3 提供的方法修改docker/docker-compose.yml 中services web image 和 services worker image 对应的镜像地址为 tophant/arl:latest
![Snipaste_2020-09-16_14-49-03](https://user-images.githubusercontent.com/18167071/93301958-c9bb5100-f82b-11ea-8c47-44fc3edbb775.png)
3. docker-compose up -d  启动
```
docker-compose up -d 
Starting arl_mongodb  ... done
Starting arl_rabbitmq ... done
Starting arl_web      ... done
Starting arl_worker   ... done
```
4. 查看容器状况,发现arl_web和arl_worker 一直处于 Restarting 状态
```
docker-compose ps
```
![Snipaste_2020-09-16_14-51-19](https://user-images.githubusercontent.com/18167071/93302154-199a1800-f82c-11ea-8e60-be917838b0fe.png)
5.宿主机无占用80端口的进程,selinux已关
![Snipaste_2020-09-16_14-52-24](https://user-images.githubusercontent.com/18167071/93302276-4a7a4d00-f82c-11ea-955f-e056014f67cf.png)
6. 系统版本
```
[root@localhost docker]# uname -a
Linux localhost.localdomain 3.10.0-1062.18.1.el7.x86_64 #1 SMP Tue Mar 17 23:49:17 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
```
7. Docker版本
```
[root@localhost docker]# docker --version
Docker version 1.13.1, build cccb291/1.13.1

[root@localhost docker]# docker-compose --version
docker-compose version 1.25.0, build 0a186604
```
8.配置
- 4C8G

**Comment by 1c3z** [comment]
最后解决了么？

可以看下

```
docker logs -f  arl_web
```

**Comment by No-Github** [comment]
等了个几分钟，它竟然又UP了，我也不知道什么情况😂，能用就行能用就行🙏

**Comment by jinqi520** [comment]
docker内存不够了 需要清理下不用的镜像

**Comment by TibbersV6** [comment]
这俩，他妈的怎么一直在重启中啊
