### ISSUE TITLE
灯塔开了全端口扫描会导致网络堵塞没网，能否设置全端口扫描的最大线程

### ISSUE THREAD

**Issue by Iagain** [TophantTechnology/ARL#140]
灯塔开了全端口扫描会导致网络堵塞没网，但是top 1000端口扫描就可以。全端口扫描 上限线程是多少？
（ps：本地小型机房部署灯塔系统）

**Comment by 1c3z** [comment]
0. 单任务的上限扫描速率代码中没有设置，nmap会根据网络波动调整。

1. 可以尝试将任务中的IP段分开下发看是否堵塞能否缓解

2. 可以先将worker容器中下面的代码手动调整下，重启容器生效
https://github.com/TophantTechnology/ARL/blob/master/app/services/portScan.py#L31

3. 后面版本迭代考虑将端口扫描参数暴露在前端可供设置。
