### ISSUE TITLE
任务长时间停留在“port_scan”，“site_spider”

### ISSUE THREAD

**Issue by aguai778** [TophantTechnology/ARL#141]
同时运行8给个任务
7个在 port_scan
1个在 site_spider
超过十二个小时了

**Comment by aguai778** [comment]
中途重启过arl_worker的docker  需要重新运行吗？

**Comment by 1c3z** [comment]
中途重启，任务就终止了（这个场景的状态没有考虑到）， 可以把任务删除再下发，如果要观察任务是否运行，可以下个子域名，参数调小。  另外也可以观察arl_worker.log。

**Comment by aguai778** [comment]
好的
