### ISSUE TITLE
在 alt_dns 十小时了，arl_worker.log无先相关记录

### ISSUE THREAD

**Issue by aguai778** [TophantTechnology/ARL#142]
在 alt_dns 十小时了，arl_worker.log无先相关记录

**Comment by aguai778** [comment]
又11个小时了

**Comment by 1c3z** [comment]
alt_dns 这步如果目标子域名比较多会生成比较大的字典。 
麻烦提供下最后的日志。

**Comment by aguai778** [comment]
日志有点多 没有看到相关的 是否跟同时运行的任务比较多有关

**Comment by aguai778** [comment]
之前2.1版本没有出现这些情况，最近升级后才出现这个情况 扫描的同一个域名

**Comment by 1c3z** [comment]
默认只能运行两个任务， 这块逻辑没改过。 日志减少了一些打印数据。 

可以看下是不是被系统杀了， `dmesg | grep kill`

**Comment by aguai778** [comment]
我这同时运行了五六个 没改过配置

**Comment by 1c3z** [comment]
测试了下，超过两个任务就会等待
![image](https://user-images.githubusercontent.com/9052484/119432965-d9d6e900-bd47-11eb-8703-282000e83940.png)

是不是服务器内存不够？ 
还有检查下硬盘是不是快满了。

**Comment by aguai778** [comment]
好的 我排查下

**Comment by aguai778** [comment]
我重新运行 很快就过了alt_dns 进入port_scan 应该是之前因为某些原因挂掉了

**Comment by aguai778** [comment]
![image](https://user-images.githubusercontent.com/35590848/119435688-41436780-bd4d-11eb-8a46-2a0630cb74d0.png)


 arl_worker 容器内只剩下三个进程 nmap应该是挂掉了
![image](https://user-images.githubusercontent.com/35590848/119435749-5fa96300-bd4d-11eb-81fb-8b2546e7854e.png)


扫描的top1000端口 跟扫描端口多有关吗

**Comment by 1c3z** [comment]
top1000, 一般都没有问题，可以吧服务识别关了，操作系统识别也关了， 正常情况下nmap  都比较稳的， 可以先确定下nmap进程是否还在，不过大概率是挂了。

**Comment by aguai778** [comment]
nmap进程挂了

**Comment by aguai778** [comment]
namp一般不会挂 应该是有原因的 不知道啥原因 内存硬盘都够

**Comment by 1c3z** [comment]
可以先把原先的任务都停止，  再把arl_worker.log清空，重启下arl， 
下一个子目标， 配置开最小，看是否工作正常
再下出现问题的目标，观察日志看是否有异常。 并观察系统CPU，内存是否有异常情况。

**Comment by aguai778** [comment]
所有任务停止 然后重启服务器 
目前来看正常了
