### ISSUE TITLE
500 Internal Privoxy Error

### ISSUE THREAD

**Issue by manchesxia** [TophantTechnology/ARL#143]
用docker安装了，但是访问本机5003端口显示500 Internal Privoxy Error，不知道是哪出了问题

![image](https://user-images.githubusercontent.com/17880581/119364710-b015b780-bc9e-11eb-9af4-14e2f6e36d87.png)
![image](https://user-images.githubusercontent.com/17880581/119365445-75f8e580-bc9f-11eb-96b1-6be789fc2eb6.png)
![image](https://user-images.githubusercontent.com/17880581/119365543-8b6e0f80-bc9f-11eb-944a-3209048d48f6.png)

**Comment by manchesxia** [comment]
![image](https://user-images.githubusercontent.com/17880581/119365659-afc9ec00-bc9f-11eb-9c53-dc7a45e57a7d.png)

**Comment by 1c3z** [comment]
这个镜像没有更新。
麻烦看/etc/docker/daemon.json 有没有配置镜像源，有的话把配置删除重启docker生效
然后再使用下面的命令更新

```
docker pull tophant/arl
docker volume create arl_db
docker-compose up -d
```
