### ISSUE TITLE
大佬你好。

### ISSUE THREAD

**Issue by just805** [TophantTechnology/ARL#145]
问问 能否扫描三级、四级等子域名， 另外导出IP的时候可不可以，只导出IP，不要端口。

**Comment by 1c3z** [comment]
如果下发的是 def.example.com ，那么将会用字典去爆破 a.def.example.com b.def.example.com

选中一个任务，选择IP导出
![image](https://user-images.githubusercontent.com/9052484/119459161-07d02380-bd70-11eb-82aa-9da3ceee43fd.png)

**Comment by just805** [comment]
谢谢大佬
