### ISSUE TITLE
资产搜索里有重复数据

### ISSUE THREAD

**Issue by manchesxia** [TophantTechnology/ARL#146]
资产搜索里有重复数据，每天巡检的话，时间长了可能有不少重复数据，这个能不能去重啊~
![捕获](https://user-images.githubusercontent.com/17880581/119594845-21747800-be0f-11eb-81bd-9c384c95b865.PNG)

**Comment by 1c3z** [comment]
资产搜索里会去查询每个任务的结果。
可以用资产分组+资产监控的功能，来完成每日的监控。 
新建完资产分组，先手动在任务信息里同步下，再添加监控任务。

可以看下这个文档。
https://github.com/TophantTechnology/ARL/wiki/%E8%B5%84%E4%BA%A7%E5%88%86%E7%BB%84%E5%92%8C%E7%9B%91%E6%8E%A7%E5%8A%9F%E8%83%BD%E4%BD%BF%E7%94%A8%E8%AF%B4%E6%98%8E

**Comment by manchesxia** [comment]
我们子域名比较多，为了防止爬虫爬不全，所以我会把子域名全都放进资产范围里
但是资产监控只能按照一个个域名添加，有点麻烦，每个子域名会生成一个监控任务，点击同步
能否针对一个资产组（里面有很多域名），就下一个任务？自动监控整个资产组

**Comment by 1c3z** [comment]
@manchesxia  把主域名写上就可以了，如qq.com

**Comment by 1c3z** [comment]
先下一个目标为主域名的任务，新建资产分组时添加一个主域名就行，再从任务里同步过来数据，然后资产分组里就有数据了，然后就只需要建一个监控任务了，如果自动发现不够的话可以手动添加缺失的子域名。
![image](https://user-images.githubusercontent.com/9052484/119600074-d8c1bc80-be18-11eb-9abe-2fd7d33feff0.png)

**Comment by 1c3z** [comment]
可能新建资产分组里的提示有误导。 只要输入主域名就行。

**Comment by manchesxia** [comment]
> 先下一个目标为主域名的任务，新建资产分组时添加一个主域名就行，再从任务里同步过来数据，然后资产分组里就有数据了，然后就只需要建一个监控任务了，如果自动发现不够的话可以手动添加缺失的子域名。

如果发现不够，手动添加缺失其域名的话，还需要对缺失的子域名单独添加监控任务不~？   还是原来的监控任务会在下次自动扫进去~~？

**Comment by 1c3z** [comment]
监控任务这个是为了发现新的域名，只维护一份数据，前面提到的重复问题就不会出现。 如果新添加了子域名，新的任务会用到添加的数据。
