### ISSUE TITLE
docker-compose up -d失败

### ISSUE THREAD

**Issue by safebaseline** [TophantTechnology/ARL#15]
/usr/local/lib/python3.5/dist-packages/paramiko/transport.py:33: CryptographyDeprecationWarning: Python 3.5 support will be dropped in the next release ofcryptography. Please upgrade your Python.
  from cryptography.hazmat.backends import default_backend
Pulling worker (arl_worker:v2)...
ERROR: The image for the service you're trying to recreate has been removed. If you continue, volume data could be lost. Consider backing up your data before continuing.

Continue with the new image? [yN]

**Comment by 1c3z** [comment]
请重新更新项目

或者 按照这个更新
https://github.com/TophantTechnology/ARL/blob/master/docker/docker-compose.yml#L5 

或者查看这个 #3
