### ISSUE TITLE
提一个需求，导入域名建议搞个上传txt文本的功能

### ISSUE THREAD

**Issue by MaxSecurity** [TophantTechnology/ARL#154]
有些导入域名很多容易卡死目前导入的。

**Comment by 1c3z** [comment]
卡死时什么表现？  页面没反应？
另外资产分组里大概有多少数据？

**Comment by MaxSecurity** [comment]
> 卡死是什么表现？页面没反应？
> 其他表里大概有多少数据？

卡死就是页面不动了刷新才可以，子域名数据差不多5000-8000+的数据 并不止一个域名的

**Comment by 1c3z** [comment]
加子域名时，如果添加的子域名有点多的话判断过程有点慢，前端会超时，下个版本优化下。
减少一次添加的数量，如果报错了不要重复添加，WEB后端还在运行的，判断域名有没有执行到添加过程可以查看任务管理里有没有添加域名的任务。

**Comment by MaxSecurity** [comment]
> 加子域名时，如果添加的子域名有点多的话判断过程有点慢，前端会超时，下个版本优化下。
> 减少一次添加的数量，如果报错了不要重复添加，WEB后端还在运行的，判断域名有没有执行到添加过程可以查看任务管理里有没有添加域名的任务。

OK
