### ISSUE TITLE
安装后登录报错

### ISSUE THREAD

**Issue by BlacknessDevil** [TophantTechnology/ARL#155]
![image](https://user-images.githubusercontent.com/83154235/122079398-f12d6180-ce2f-11eb-95b2-f22de8dc8c5f.png)
默认密码登录和修改了密码登录都是显示timeout of12000ms exceeded

**Comment by BlacknessDevil** [comment]
求大佬帮解一下 非常感谢

**Comment by 1c3z** [comment]
1. 检查下硬盘看是不是满了。 
2. 可以执行下面的三条命令并尝试触发错误观察输出有什么异常。
```
docker-compose ps 
docker-compose logs -f  --tail=10
tail -f *.log
```

**Comment by BlacknessDevil** [comment]
清完重启了下服务器和docker就好了
感谢大佬🤧
