### ISSUE TITLE
fofa_search一直卡顿问题

### ISSUE THREAD

**Issue by Jfirm** [TophantTechnology/ARL#158]
像这种已经扫了快一周了，一直停顿在fofa查询中是怎么回事呢？
![image](https://user-images.githubusercontent.com/40061336/122663188-2be61f80-d1cb-11eb-8037-1addc059c3fa.png)

**Comment by 1c3z** [comment]
任务应该是挂了，可能fofa_search 对应目标的结果比较大，内存不够用导致任务异常。

**Comment by Jfirm** [comment]
> 任务应该是挂了，可能fofa_search 对应目标的结果比较大，内存不够用导致任务异常。

有对应的解决办法吗？我刚买的服务器是2核4G呢，按理说内存符合平台配置要求呀

**Comment by Jfirm** [comment]
我们这边测试了，是目前最新版的问题只要新建的任务多了或是并发太大就会挂掉，回退到以前的版本同样的配置要求和扫描类型是不会出现任务挂掉的问题，况且2核4G完全够用啦。

**Comment by chibd2000** [comment]
> 我们这边测试了，是目前最新版的问题只要新建的任务多了或是并发太大就会挂掉，回退到以前的版本同样的配置要求和扫描类型是不会出现任务挂掉的问题，况且2核4G完全够用啦。

我想问下回退的版本是多少 我这边也遇到了相同的情况

**Comment by Jfirm** [comment]
回退到2.1就没问题，我也是纳闷呢，为啥没人反馈这个问题以为大家都是可以正常扫，2.3一扫就挂。

**Comment by 1c3z** [comment]
我这边看了下代码， 2.1和2.3 fofa调用逻辑没有变，然后端口扫描看起来变化不大， 2.3 多了个 --defeat-rst-ratelimit 参数。

2.3 端口扫描

https://github.com/TophantTechnology/ARL/blob/v2.3/app/services/portScan.py#L8 


2.1端口扫描
https://github.com/TophantTechnology/ARL/blob/v2.1/app/services/portScan.py#L7

**Comment by 0cat-r** [comment]
同经常遇到fofa search卡死 最新版本

**Comment by Jfirm** [comment]
> 同经常遇到fofa search卡死 最新版本

经过测试，本人解决办法有两个。第一降低端口扫描类型选择TOP100，千万别选全端口否则会卡死，缺点就是资产会变少；第二扫描任务量降低，每次要扫的域名资产单个单个扫不要两个同时扫，他的多线程并发同样会存在卡顿问题，缺点就是扫的慢。服务器配置2核4g完全够啦，当前这么做的话确实能将扫描任务完成。

**Comment by 1c3z** [comment]
@Jfirm 

2.4 版本出了一个fofa 任务的功能，可以很好的对接fofa 。
可以查看文档。
https://github.com/TophantTechnology/ARL/wiki/ARL-2.4-%E6%96%B0%E6%B7%BB%E5%8A%A0%E5%8A%9F%E8%83%BD%E8%AF%A6%E7%BB%86%E8%AF%B4%E6%98%8E#fofa-%E4%BB%BB%E5%8A%A1%E4%B8%8B%E5%8F%91
