### ISSUE TITLE
灯塔可以导出扫描结果吗

### ISSUE THREAD

**Issue by gogogo2022** [TophantTechnology/ARL#159]
如何将结果作为报告导出

**Comment by 1c3z** [comment]
任务界面可以导出
![image](https://user-images.githubusercontent.com/9052484/122728995-44c60200-d2ab-11eb-8f20-00162cf00f8a.png)

**Comment by gogogo2022** [comment]
> 任务界面可以导出
> ![image](https://user-images.githubusercontent.com/9052484/122728995-44c60200-d2ab-11eb-8f20-00162cf00f8a.png)

文件泄露没有办法导出吗？

**Comment by 1c3z** [comment]
是的，目前还不支持。
