### ISSUE TITLE
新功能建议

### ISSUE THREAD

**Issue by NowSec1** [TophantTechnology/ARL#160]
建议在任务添加功能中添加模版批量导入功能

**Comment by 1c3z** [comment]
麻烦细说下场景，模版批量导入？已知域名导入？

**Comment by NowSec1** [comment]
@1c3z

**Comment by NowSec1** [comment]
@1c3z 例如下图这样，通过在表中填入对于字段的值，下面的扫描选项可以使用0/1选择是否启用，如不填则使用默认配置
![image](https://user-images.githubusercontent.com/59020659/123358515-32dfaa00-d59e-11eb-84a4-800920118a6d.png)

**Comment by 1c3z** [comment]
这个功能可以用策略配置来实现 
先添加策略
![image](https://user-images.githubusercontent.com/9052484/123398617-532b5b00-d5d6-11eb-8873-4f92be702969.png)

任务下发，选资产侦查任务
![image](https://user-images.githubusercontent.com/9052484/123398698-6807ee80-d5d6-11eb-92f1-792b26dacc0d.png)
