### ISSUE TITLE
资产扫描一直不动

### ISSUE THREAD

**Issue by chendaso** [TophantTechnology/ARL#161]
![image](https://user-images.githubusercontent.com/49139768/123406332-5fff7d00-d5dd-11eb-8a49-806a998a4b0f.png)
![image](https://user-images.githubusercontent.com/49139768/123406366-68f04e80-d5dd-11eb-91e0-ddb260315ac4.png)

**Comment by 1c3z** [comment]
十分钟了确实有点久，看下进程还在不
```
ps axf | grep massdns 

```
日志看下是怎样的。
```
tail -f arl_worker.log
```

**Comment by chendaso** [comment]
------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "TophantTechnology/ARL"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年6月25日(星期五) 下午5:56
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [TophantTechnology/ARL] 资产扫描一直不动 (#161)





 
十分钟了确实有点久，看下进程还在不
 ps axf | grep massdns   
日志看下是怎样的。
 tail -f arl_worker.log

**Comment by chendaso** [comment]
用的是centos7虚拟机加docker搭建的




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "TophantTechnology/ARL"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年6月25日(星期五) 下午5:56
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [TophantTechnology/ARL] 资产扫描一直不动 (#161)





 
十分钟了确实有点久，看下进程还在不
 ps axf | grep massdns   
日志看下是怎样的。
 tail -f arl_worker.log

**Comment by chendaso** [comment]
![image](https://user-images.githubusercontent.com/49139768/123505127-dceb2f00-d68f-11eb-9ab7-1c25b741af57.png)

**Comment by 1c3z** [comment]
后面任务结束了么？ 截图里的任务站点应该是没有了， 域名看下有不？ 域名爆破久的话， 猜测可能网络不太好。

**Comment by chendaso** [comment]
好的，应该是虚拟机的问题。之前用的云服务器没有过这种情况。我换云服务器试试
