### ISSUE TITLE
希望增加指定时间段启动扫描的功能

### ISSUE THREAD

**Issue by Richard-Tang** [TophantTechnology/ARL#163]
希望能指定时间段启动扫描任务，如: `每周几` `每天几点`之类的。:)

**Comment by 1c3z** [comment]
这个是因为目标只能特定时间段才能扫描么？

**Comment by Richard-Tang** [comment]
> 这个是因为目标只能特定时间段才能扫描么？

是的，周期性和指定时间段进行扫描。

**Comment by ym2011** [comment]
+1，同样希望增加定时扫描功能。需要是：业务低峰期或者非工作时间进行扫描，不影响业务正常运行。

**Comment by ym2011** [comment]
定时功能：任务管理-添加任务和风险巡航任务都能进行定时。非常感谢。
