### ISSUE TITLE
一些任务无法删除

### ISSUE THREAD

**Issue by horseworkbench** [TophantTechnology/ARL#164]
某些任务，显示一直waiting，停止后无法进行删除

**Comment by 1c3z** [comment]
前端页面有报错不？Burp代理看下，后端有返回什么错误么

**Comment by horseworkbench** [comment]
一直显示这个，停止后显示成功，但还是无法删除，容器重启依然无法删除。

------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "TophantTechnology/ARL"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年6月28日(星期一) 上午10:58
***@***.***&gt;;
***@***.******@***.******@***.***&gt;;
主题:&nbsp;Re: [TophantTechnology/ARL] 一些任务无法删除 (#164)





 
前端页面有报错不？Burp代理看下，后端有返回什么错误么

**Comment by 1c3z** [comment]
显示啥？ 没看到图片。

**Comment by horseworkbench** [comment]
------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "TophantTechnology/ARL"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年6月28日(星期一) 中午11:03
***@***.***&gt;;
***@***.******@***.******@***.***&gt;;
主题:&nbsp;Re: [TophantTechnology/ARL] 一些任务无法删除 (#164)





 
显示啥？ 没看到图片。

**Comment by 1c3z** [comment]
上号发吧，邮件回复可能有点问题。

**Comment by horseworkbench** [comment]
https://42.192.48.56:5003/login&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; admin/ma182131




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "TophantTechnology/ARL"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年6月28日(星期一) 中午11:06
***@***.***&gt;;
***@***.******@***.******@***.***&gt;;
主题:&nbsp;Re: [TophantTechnology/ARL] 一些任务无法删除 (#164)





 
上号发吧，邮件回复可能有点问题。

**Comment by 1c3z** [comment]
我进入到系统了，第一条任务删除了，这个是因为下发任务的时候rabbitmq server连不上，任务没有下发成功。

现在只能手动删除了
#47

**Comment by 1c3z** [comment]
已更新，加了判断。
