### ISSUE TITLE
qq邮箱接收问题

### ISSUE THREAD

**Issue by WhyUBullyMeXcc** [TophantTechnology/ARL#167]
qq邮箱是不是接收不了了，我这一直显示授权码
![image](https://user-images.githubusercontent.com/46983382/124243772-ce4dbd80-db50-11eb-8735-1fe19284fad2.png)

**Comment by 1c3z** [comment]
可以接手的，qq 邮箱不是密码，要生成授权码，打开里面的URL看下。

https://service.mail.qq.com/cgi-bin/help?subtype=1&id=28&no=1001256

**Comment by WhyUBullyMeXcc** [comment]
ok了解了，我以为填的qq密码
