### ISSUE TITLE
资产监控增加域名截图

### ISSUE THREAD

**Issue by 0d9y** [TophantTechnology/ARL#171]
资产监控功能挺好用的，不过能不能增加截图功能？ 
更灵活点就是能不能把配置开放出来，譬如这个资产需要 截图、扫描端口top1000......

**Comment by 1c3z** [comment]
截图这个在任务里已经有了资产组里面不打算加了，新发现的子域名，页面状态变化会比较快，建议人工查看的频繁点。

**Comment by 0d9y** [comment]
能开放自定义么？把配置开放出来
