### ISSUE TITLE
功能建议

### ISSUE THREAD

**Issue by 8October8** [TophantTechnology/ARL#176]
建议增加访问频率控制，防止网站有访问频率限制
建议增加扫描代理功能，访问封ip

**Comment by 1c3z** [comment]
感谢建议，网站访问有多个地方采用多线程访问，一般情况下是没有问题。 
对防守严格的地方，一般是端口扫描或者服务识别就会封IP，这块代理功能加了也没有用，还是放弃对抗吧。 可以选择不扫端口。
