### ISSUE TITLE
没有重新扫描的功能吗

### ISSUE THREAD

**Issue by kN6jq** [TophantTechnology/ARL#177]
比如服务器重启了一次，然后现在就停了
![image](https://user-images.githubusercontent.com/27048404/126290831-5cc03826-deec-4782-8f00-38ee0e74bfbc.png)
到这里就不动了，有重新扫描的解决办法吗

**Comment by 1c3z** [comment]
只能重新下发了。 如果没有改配置的话，最多只有两个任务在运行。

**Comment by 1c3z** [comment]
已添加。  请更新。
