### ISSUE TITLE
timeout of 12000ms exceeded

### ISSUE THREAD

**Issue by wifislax** [TophantTechnology/ARL#179]
timeout of 12000ms exceeded

**Comment by 1c3z** [comment]
看下日志， 看容器是不是启动正常。

**Comment by fool-sir** [comment]
![image](https://user-images.githubusercontent.com/58167489/140266095-cf34f137-f223-4018-9dfd-c901d5af12e9.png)
mongodb 容器突然无线重启，请问这个是什么导致的啊

**Comment by fool-sir** [comment]
@1c3z

**Comment by 1c3z** [comment]
@fool-sir 
参考这个看下吧
https://mkyong.com/mongodb/mongodb-failed-to-unlink-socket-file-tmpmongodb-27017/

**Comment by fool-sir** [comment]
@1c3z  这个方法我可以理解为进到mongodb容器内操作的；但是无限重启状态是无法进入操作的

**Comment by 1c3z** [comment]
那你试试 
```
docker-compose down
docker-compose up -d
```

**Comment by fool-sir** [comment]
@1c3z 我是用的这个方法解决的，但是不知道是什么原因引起的，环境昨天搭建的，今天就出现这个错误，很奇怪又不知道什么原因导致的

**Comment by 1c3z** [comment]
没有遇到过，不太清楚。 可能是docker 的bug吧。

**Comment by fool-sir** [comment]
@1c3z  请教一个问题，任务管理中已经完成的资产监控端口扫描，如果后来的监控扫描结果没有新值产生，那么任务管理中已完成的任务就不会有结果显示？

**Comment by 1c3z** [comment]
@fool-sir 

是这样的。
