### ISSUE TITLE
增加任务超时机制

### ISSUE THREAD

**Issue by d1nfinite** [TophantTechnology/ARL#18]
alt_dns已经跑了超过一天了

**Comment by 1c3z** [comment]
可能进程被kill了。 
tail -f arl_worker.log 看看任务还有日志输出不。

**Comment by k4ubb** [comment]
我的已经在port_scan卡了4个小时。看arl_worker.log里进行到nmap扫描就没输出了，现在查进程还有nmap

**Comment by d1nfinite** [comment]
建议改用masscan作为端口扫描，存活端口再用nmap识别指纹

**Comment by 1c3z** [comment]
@d1nfinite  masscan 扫描不稳定，漏端口比较多。

**Comment by 1c3z** [comment]
@k4ubb   @d1nfinite   获取的IP可能比较多，然后服务识别和操作系统识别是最耗时的。
