### ISSUE TITLE
 error:failed to resolve broker hostname

### ISSUE THREAD

**Issue by ROCKLEE-1998** [TophantTechnology/ARL#181]
您好，启用任务的时候出现了这个错误
 error:failed to resolve broker hostname
![97ed403fd406f0e897f3ac99e78630e](https://user-images.githubusercontent.com/52626219/127100976-d4b0771a-c308-4b59-90d4-330f065adff3.png)
环境：debian10 64 vmware16 桥接 4G/2h

**Comment by 1c3z** [comment]
看下rabbitmq 容器起来了么。 这个提示是DNS解析失败


可以进入web 容器测试下


```
docker exec -ti arl_web  bash
ping rabbitmq
```

![image](https://user-images.githubusercontent.com/9052484/127103366-8d0a6513-5a42-4be4-8d3a-cdf847117d1b.png)

**Comment by ROCKLEE-1998** [comment]
![image](https://user-images.githubusercontent.com/52626219/127104321-a07f05a7-860d-4d9a-8518-f7d99e7ca5a3.png)

![image](https://user-images.githubusercontent.com/52626219/127104574-63f6bc87-1a9f-4a77-9cd5-df5de4da22ca.png)
显示启动失败

**Comment by 1c3z** [comment]
可以看下日志
```
docker-compose logs -f  --tail=10
```

**Comment by ROCKLEE-1998** [comment]
Attaching to arl_scheduler, arl_web, arl_worker, arl_mongodb, arl_rabbitmq
arl_mongodb  | 2021-07-27T05:31:31.426+0000 I NETWORK  [listener] connection accepted from 172.18.0.4:45758 #5 (5 connections now open)
arl_mongodb  | 2021-07-27T05:31:31.426+0000 I NETWORK  [conn5] received client metadata from 172.18.0.4:45758 conn5: { driver: { name: "PyMongo", version: "3.7.1" }, os: { type: "Linux", name: "Linux", architecture: "x86_64", version: "4.19.0-17-amd64" }, platform: "CPython 3.6.8.final.0" }
arl_mongodb  | 2021-07-27T05:31:31.428+0000 I NETWORK  [listener] connection accepted from 172.18.0.4:45760 #6 (6 connections now open)
arl_mongodb  | 2021-07-27T05:31:31.428+0000 I NETWORK  [conn6] received client metadata from 172.18.0.4:45760 conn6: { driver: { name: "PyMongo", version: "3.7.1" }, os: { type: "Linux", name: "Linux", architecture: "x86_64", version: "4.19.0-17-amd64" }, platform: "CPython 3.6.8.final.0" }
arl_mongodb  | 2021-07-27T05:31:31.435+0000 I ACCESS   [conn6] Successfully authenticated as principal admin on admin
arl_mongodb  | 2021-07-27T05:31:44.520+0000 I NETWORK  [listener] connection accepted from 172.18.0.4:45764 #7 (7 connections now open)
arl_mongodb  | 2021-07-27T05:31:44.520+0000 I NETWORK  [conn7] received client metadata from 172.18.0.4:45764 conn7: { driver: { name: "PyMongo", version: "3.7.1" }, os: { type: "Linux", name: "Linux", architecture: "x86_64", version: "4.19.0-17-amd64" }, platform: "CPython 3.6.8.final.0" }
arl_mongodb  | 2021-07-27T05:31:44.522+0000 I NETWORK  [listener] connection accepted from 172.18.0.4:45766 #8 (8 connections now open)
arl_mongodb  | 2021-07-27T05:31:44.523+0000 I NETWORK  [conn8] received client metadata from 172.18.0.4:45766 conn8: { driver: { name: "PyMongo", version: "3.7.1" }, os: { type: "Linux", name: "Linux", architecture: "x86_64", version: "4.19.0-17-amd64" }, platform: "CPython 3.6.8.final.0" }
arl_mongodb  | 2021-07-27T05:31:44.530+0000 I ACCESS   [conn8] Successfully authenticated as principal admin on admin
arl_rabbitmq | 
arl_rabbitmq | Please use a configuration file instead; visit https://www.rabbitmq.com/configure.html to learn more
arl_rabbitmq | 
arl_rabbitmq | error: RABBITMQ_DEFAULT_PASS is set but deprecated
arl_rabbitmq | error: RABBITMQ_DEFAULT_USER is set but deprecated
arl_rabbitmq | error: RABBITMQ_DEFAULT_VHOST is set but deprecated
arl_rabbitmq | error: deprecated environment variables detected
arl_rabbitmq | 
arl_rabbitmq | Please use a configuration file instead; visit https://www.rabbitmq.com/configure.html to learn more
arl_rabbitmq | 
arl_web      | [2021-07-27 13:30:24 +0800] [12] [INFO] Using worker: sync
arl_web      | [2021-07-27 13:30:24 +0800] [15] [INFO] Booting worker with pid: 15
arl_web      | [2021-07-27 13:30:24 +0800] [16] [INFO] Booting worker with pid: 16
arl_web      | [2021-07-27 13:30:24 +0800] [17] [INFO] Booting worker with pid: 17
arl_web      | [2021-07-27 13:31:44] [INFO] [MainThread] [task.py:115] {'name': 'title', 'target': 'target', 'start_time': '-', 'end_time': '-', 'task_tag': 'task', 'service': [], 'status': 'waiting', 'options': {'domain_brute': True, 'domain_brute_type': 'big', 'port_scan_type': 'top100', 'port_scan': True, 'service_detection': False, 'service_brute': None, 'os_detection': False, 'site_identify': False, 'site_capture': False, 'file_leak': False, 'search_engines': False, 'site_spider': False, 'arl_search': True, 'riskiq_search': True, 'alt_dns': True, 'github_search_domain': None, 'ssl_cert': False, 'fetch_api_path': None, 'fofa_search': False, 'sub_takeover': None, 'crtsh_search': True, 'skip_scan_cdn_ip': None}, 'type': 'domain'}
arl_web      | [2021-07-27 13:31:45] [INFO] [MainThread] [task.py:228] 下发失败 target
arl_web      | [2021-07-27 13:32:05] [INFO] [MainThread] [task.py:115] {'name': 'badu', 'target': 'baidu.com', 'start_time': '-', 'end_time': '-', 'task_tag': 'task', 'service': [], 'status': 'waiting', 'options': {'domain_brute': True, 'domain_brute_type': 'big', 'port_scan_type': 'top100', 'port_scan': True, 'service_detection': False, 'service_brute': None, 'os_detection': False, 'site_identify': False, 'site_capture': False, 'file_leak': False, 'search_engines': False, 'site_spider': False, 'arl_search': True, 'riskiq_search': True, 'alt_dns': True, 'github_search_domain': None, 'ssl_cert': False, 'fetch_api_path': None, 'fofa_search': False, 'sub_takeover': None, 'crtsh_search': True, 'skip_scan_cdn_ip': None}, 'type': 'domain'}
arl_web      | [2021-07-27 13:32:06] [INFO] [MainThread] [task.py:228] 下发失败 baidu.com
arl_web      | [2021-07-27 13:32:12] [INFO] [MainThread] [task.py:115] {'name': 'badu', 'target': 'baidu.com', 'start_time': '-', 'end_time': '-', 'task_tag': 'task', 'service': [], 'status': 'waiting', 'options': {'domain_brute': True, 'domain_brute_type': 'big', 'port_scan_type': 'top100', 'port_scan': True, 'service_detection': False, 'service_brute': None, 'os_detection': False, 'site_identify': False, 'site_capture': False, 'file_leak': False, 'search_engines': False, 'site_spider': False, 'arl_search': True, 'riskiq_search': True, 'alt_dns': True, 'github_search_domain': None, 'ssl_cert': False, 'fetch_api_path': None, 'fofa_search': False, 'sub_takeover': None, 'crtsh_search': True, 'skip_scan_cdn_ip': None}, 'type': 'domain'}
arl_web      | [2021-07-27 13:32:16] [INFO] [MainThread] [task.py:228] 下发失败 baidu.com
arl_scheduler | [2021-07-27 14:47:01] [INFO] [MainThread] [scheduler.py:174] 1627368421.1214068
arl_scheduler | [2021-07-27 14:47:31] [INFO] [MainThread] [scheduler.py:174] 1627368451.1425009
arl_scheduler | [2021-07-27 14:48:01] [INFO] [MainThread] [scheduler.py:174] 1627368481.1445832
arl_scheduler | [2021-07-27 14:48:31] [INFO] [MainThread] [scheduler.py:174] 1627368511.1482434
arl_scheduler | [2021-07-27 14:49:01] [INFO] [MainThread] [scheduler.py:174] 1627368541.163011
arl_scheduler | [2021-07-27 14:49:31] [INFO] [MainThread] [scheduler.py:174] 1627368571.188051
arl_scheduler | [2021-07-27 14:50:01] [INFO] [MainThread] [scheduler.py:174] 1627368601.2203028
arl_scheduler | [2021-07-27 14:50:31] [INFO] [MainThread] [scheduler.py:174] 1627368631.2540321
arl_scheduler | [2021-07-27 14:51:01] [INFO] [MainThread] [scheduler.py:174] 1627368661.2790582
arl_scheduler | [2021-07-27 14:51:31] [INFO] [MainThread] [scheduler.py:174] 1627368691.3031826
arl_worker   | - *** --- * --- .> concurrency: 2 (prefork)
arl_worker   | -- ******* ---- .> task events: OFF (enable -E to monitor tasks in this worker)
arl_worker   | --- ***** ----- 
arl_worker   |  -------------- [queues]
arl_worker   |                 .> arltask          exchange=arltask(direct) key=arltask
arl_worker   |                 
arl_worker   | 
arl_worker   | [tasks]
arl_worker   |   . app.celerytask.arl_task
arl_worker   | 
arl_rabbitmq exited with code 1
arl_scheduler | [2021-07-27 14:52:01] [INFO] [MainThread] [scheduler.py:174] 1627368721.3337846
arl_scheduler | [2021-07-27 14:52:31] [INFO] [MainThread] [scheduler.py:174] 1627368751.3670309
arl_scheduler | [2021-07-27 14:53:01] [INFO] [MainThread] [scheduler.py:174] 1627368781.39994

**Comment by 1c3z** [comment]
需要手动改下docker/docker-compose.yml ，将image改成 rabbitmq:3.8.19-rc.1-management-alpine

![image](https://user-images.githubusercontent.com/9052484/127112797-648a6a08-985b-40c3-99d1-960f5d2b174b.png)

然后再
```
docker-compose pull
docker-compose up -d
docker-compose ps
```
![image](https://user-images.githubusercontent.com/9052484/127113014-97b0e7ae-21f5-430d-8896-ea8365dafe01.png)

**Comment by ROCKLEE-1998** [comment]
已启用，感谢
![image](https://user-images.githubusercontent.com/52626219/127115069-382ee53f-070c-4dc9-b365-f2ebc09fe2bd.png)
