### ISSUE TITLE
关于配置文件中ip黑名单的疑问

### ISSUE THREAD

**Issue by whami-root** [TophantTechnology/ARL#187]
https://github.com/TophantTechnology/ARL/blob/f57dae568ee893611d93fb396f988b492b96a142/docker/config-docker.yaml#L49
1、直接将100.0.0.0/8加入黑名单太广泛了，我查到特殊的情况下将100.64.0.0/10加入黑名单获取合理一点
2、10.0.0.0/8、192.168.0.0/16直接加入黑名单没有问题

**Comment by 1c3z** [comment]
草率了，感谢。
