### ISSUE TITLE
下完任务一直处于等待状态

### ISSUE THREAD

**Issue by xibeiwangxue** [TophantTechnology/ARL#189]
先任务时提示timeout 0f 12000ms exceeded,然后刷新之后任务一直处于等待状态，点击停止任务提示没有找打celery id

**Comment by 1c3z** [comment]
这个应该是rabbitmq 没起来。 
2.4 版本这个错误已经修了，可以升级一下

#164

**Comment by xibeiwangxue** [comment]
嗯嗯，就是用的2.4的 rabbi一直处于重启状态



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年8月4日(星期三) 下午2:39
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [TophantTechnology/ARL] 下完任务一直处于等待状态 (#189)





 
这个应该是rabbitmq 没起来。
 2.4 版本这个错误已经修了，可以升级一下
 
#164
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by 1c3z** [comment]
可以看下报错日志。

**Comment by xibeiwangxue** [comment]
我删除容器重新拉了一下，然后服务都起来了还是那样，不知道数据没清干净还是怎么回事，然后删了docker，现在docker装不上了




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年8月4日(星期三) 下午2:49
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [TophantTechnology/ARL] 下完任务一直处于等待状态 (#189)





 
可以看下报错日志。
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by 1c3z** [comment]
可以看下下面的文档
https://github.com/TophantTechnology/ARL/wiki/Docker-%E7%8E%AF%E5%A2%83%E5%AE%89%E8%A3%85-ARL  

安装脚本参考
https://github.com/TophantTechnology/ARL/blob/master/misc/setup-docker-arl.sh


另外再确定下 docker/docker-compose.yml 文件里rabbitmq 版本是不是   rabbitmq:3.8.19-rc.1-management-alpine 

![image](https://user-images.githubusercontent.com/9052484/128135198-dff284fb-2ae3-40d1-ab17-add0a2f826be.png)

**Comment by xibeiwangxue** [comment]
好的




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年8月4日(星期三) 下午2:55
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [TophantTechnology/ARL] 下完任务一直处于等待状态 (#189)





 
可以看下下面的文档
 https://github.com/TophantTechnology/ARL/wiki/Docker-%E7%8E%AF%E5%A2%83%E5%AE%89%E8%A3%85-ARL
 
安装脚本参考
 https://github.com/TophantTechnology/ARL/blob/master/misc/setup-docker-arl.sh
 
另外再确定下 docker/docker-compose.yml 文件里rabbitmq 版本是不是   rabbitmq:3.8.19-rc.1-management-alpine
 

 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
