### ISSUE TITLE
docker-compose up -d失败

### ISSUE THREAD

**Issue by yige666** [TophantTechnology/ARL#19]
报这个错

ERROR: Version in "./docker-compose.yml" is unsupported. You might be seeing this error because you're using the wrong Compose file version. Either specify a version of "2" (or "2.0") and place your service definitions under the `services` key, or omit the `version` key and place your service definitions at the root of the file to use version 1.
For more on the Compose file format versions, see https://docs.docker.com/compose/compose-file/

**Comment by 1c3z** [comment]
这个是因为本地docker-compose版本比较低导致的。

可以把这个3 手动修改为2.  
https://github.com/TophantTechnology/ARL/blob/master/docker/docker-compose.yml#L1

**Comment by yige666** [comment]
已启动，多谢了
