### ISSUE TITLE
资产侦察任务，很慢，12小时看不到结果，还没有过程可查看

### ISSUE THREAD

**Issue by fool-sir** [TophantTechnology/ARL#192]
资产侦察任务，很慢，12小时看不到结果，还没有过程可查看；能否提供一些使用手册供参考

**Comment by 1c3z** [comment]
看日志有没有继续打印
看进程是不是在跑，如nmap 。 

可以参考下面这个文档
https://github.com/TophantTechnology/ARL/wiki/Docker-%E7%8E%AF%E5%A2%83%E5%AE%89%E8%A3%85-ARL#faq

**Comment by fool-sir** [comment]
nmap进程再跑的
![image](https://user-images.githubusercontent.com/58167489/128452257-5b5baed2-f7e2-457d-b3e0-3dca9c0fab36.png)

**Comment by fool-sir** [comment]
![image](https://user-images.githubusercontent.com/58167489/128469153-241f5f5b-5583-4ef2-bb73-c1bbb3d9f31e.png)
很多次，扫描出来结果啥都没有

**Comment by 0cat-r** [comment]
还会遇到fofa search卡死情况

**Comment by 1c3z** [comment]
> ![image](https://user-images.githubusercontent.com/58167489/128469153-241f5f5b-5583-4ef2-bb73-c1bbb3d9f31e.png)
> 很多次，扫描出来结果啥都没有

这个IP ,手工用Nmap 扫描会出结果么？

**Comment by 1c3z** [comment]
> 还会遇到fofa search卡死情况

这个有两种情况，一种是进程被杀了，一种是nmap 还在跑，另外端口不要开太多。

2.4 版本出了一个fofa 任务的功能，可以很好的对接fofa 。
可以查看文档。
https://github.com/TophantTechnology/ARL/wiki/ARL-2.4-%E6%96%B0%E6%B7%BB%E5%8A%A0%E5%8A%9F%E8%83%BD%E8%AF%A6%E7%BB%86%E8%AF%B4%E6%98%8E#fofa-%E4%BB%BB%E5%8A%A1%E4%B8%8B%E5%8F%91

**Comment by fool-sir** [comment]
> 还会遇到fofa search卡死情况



> > ![image](https://user-images.githubusercontent.com/58167489/128469153-241f5f5b-5583-4ef2-bb73-c1bbb3d9f31e.png)
> > 很多次，扫描出来结果啥都没有
> 
> 这个IP ,手工用Nmap 扫描会出结果么？

有的，直接nmap是有结果的，好像就不能用全端口扫描一样，端口少的时候还能扫出来点，全端口我是一次没有扫出来过端口

**Comment by 1c3z** [comment]
> > 还会遇到fofa search卡死情况
> 
> > > ![image](https://user-images.githubusercontent.com/58167489/128469153-241f5f5b-5583-4ef2-bb73-c1bbb3d9f31e.png)
> > > 很多次，扫描出来结果啥都没有
> > 
> > 
> > 这个IP ,手工用Nmap 扫描会出结果么？
> 
> 有的，直接nmap是有结果的，好像就不能用全端口扫描一样，端口少的时候还能扫出来点，全端口我是一次没有扫出来过端口

1.可以看下扫描结果端口是否在top1000 里面
2. 另外不知道手动扫描的时候是否加了-Pn 参数，或者其他参数。 
3. 保险起见可以在容器里手工用nmap 再测试下 。
4.  另外麻烦提供下状态里面port_scan 时间
5.  这个站点:0 ,只是表示没有发现站点，可能开放的端口非http, 点进去看下IP 标签是不是真的没有端口扫描出来。
