### ISSUE TITLE
怎么关闭禁止域名

### ISSUE THREAD

**Issue by Jfirm** [TophantTechnology/ARL#193]

**Comment by Jfirm** [comment]
![image](https://user-images.githubusercontent.com/40061336/128964014-121092e3-2394-45d7-8ba9-43f495533d54.png)

**Comment by 1c3z** [comment]
兄弟，授权了么？没有授权别改了。 

改这里的配置可以删除禁止域名。 

https://github.com/TophantTechnology/ARL/blob/master/docker/config-docker.yaml#L52

**Comment by Jfirm** [comment]
> 兄弟，授权了么？没有授权别改了。

![image](https://user-images.githubusercontent.com/40061336/128966530-dfa8182d-41c5-44e1-8c3c-4e89830724e2.png)
注释掉了还是不能扫
![image](https://user-images.githubusercontent.com/40061336/128966589-e5eccf54-7c8a-478b-b7bb-2d13380add40.png)

**Comment by 1c3z** [comment]
> > 兄弟，授权了么？没有授权别改了。
> 
> ![image](https://user-images.githubusercontent.com/40061336/128966530-dfa8182d-41c5-44e1-8c3c-4e89830724e2.png)
> 注释掉了还是不能扫
> ![image](https://user-images.githubusercontent.com/40061336/128966589-e5eccf54-7c8a-478b-b7bb-2d13380add40.png)

改完配置要重启才能生效。

**Comment by Jfirm** [comment]
好的，已解决

**Comment by NowSec1** [comment]
@1c3z 请问这是哪个配置文件

**Comment by 1c3z** [comment]
@NowSec1 
是这个文件
https://github.com/TophantTechnology/ARL/blob/master/docker/config-docker.yaml

**Comment by baoyang95** [comment]
![1634628099(1)](https://user-images.githubusercontent.com/91418209/137862462-0dfed773-2f91-452b-9ae9-c31c4f494f82.jpg)
![1634628173(1)](https://user-images.githubusercontent.com/91418209/137862472-9543be60-3b2a-417f-bc41-b47892dd93c9.jpg)
您好，我这文件里为什么没有禁止域名的那一段，但是也是显示禁止?

**Comment by fumengze** [comment]
已经解决了，更改了yaml文件和py文件，重启后生效了

**Comment by fumengze** [comment]
建议增加个API功能，可以通过API接口实现任务的创建和获取

**Comment by 1c3z** [comment]
@fumengze 
有API的，可以访问 api/doc这个路径查看文档。
