### ISSUE TITLE
全端口扫描

### ISSUE THREAD

**Issue by Zard-ethan** [TophantTechnology/ARL#194]
每次全端口扫描的时候，都没有结果，同一批资产，如果选择的是测试就有结果

**Comment by 1c3z** [comment]
这个在单机的情况下真的很无力，尤其是大量的公网IP情况下。

**Comment by lapalipi** [comment]
呜呜呜，扫描速度有点感人哇。

**Comment by 1c3z** [comment]
> 呜呜呜，扫描速度有点感人哇。

是太慢了么？ 建议先手工nmap扫扫比对下速度。

**Comment by lapalipi** [comment]
默认端口扫描还好，我全端口扫描直接挂了。
![image](https://user-images.githubusercontent.com/66582830/129364052-90cec2fb-a256-44b0-829d-32f465863eb1.png)
后面两个任务扫描的IP跟第一个任务IP是同样的（都是一个端的全端口）

**Comment by 1c3z** [comment]
@lapalipi    error 的是报错了，可以查看下日志。

**Comment by bubbleatgit** [comment]
> > 呜呜呜，扫描速度有点感人哇。
> 
> 是太慢了么？ 建议先手工nmap扫扫比对下速度。

大佬有考虑先用 `Masscan ` 来扫描端口，然后再用`nmap`对获取到的端口进行服务识别吗？

**Comment by 1c3z** [comment]
> > > 呜呜呜，扫描速度有点感人哇。
> > 
> > 
> > 是太慢了么？ 建议先手工nmap扫扫比对下速度。
> 
> 大佬有考虑先用 `Masscan ` 来扫描端口，然后再用`nmap`对获取到的端口进行服务识别吗？

masscan 漏报太多了。
