### ISSUE TITLE
如何自定义Request Header

### ISSUE THREAD

**Issue by xiaochao** [TophantTechnology/ARL#196]
如题

**Comment by 1c3z** [comment]
现在还不行，可以说下你的需求场景么？

**Comment by xiaochao** [comment]
> 现在还不行，可以说下你的需求场景么？

我探测的系统都是基于header里的字段认证的，在一个统一的认证网关后面

**Comment by 1c3z** [comment]
目前所有的HTTP协议的请求，都会走这个请求，可以先手动改下。 
https://github.com/TophantTechnology/ARL/blob/master/app/utils/conn.py#L19

**Comment by xiaochao** [comment]
> 目前所有的HTTP协议的请求，都会走这个函数，可以先手动改下。
> https://github.com/TophantTechnology/ARL/blob/master/app/utils/conn.py#L19

好的
