### ISSUE TITLE
怎么感觉界面怪怪的。

### ISSUE THREAD

**Issue by just805** [TophantTechnology/ARL#198]
目前使用的版本是ARL 2.4，谷歌浏览器最新版。
如果界面缩小到80%就不会存在
![1](https://user-images.githubusercontent.com/18697510/130029189-15d6125a-fc51-4254-b07c-fdf0bfb2b95a.png)

**Comment by pangyu360es** [comment]
确实，我也发现了 更新后的BUG吧

**Comment by 1c3z** [comment]
这个是正常的，下面有滚动条，可以拖。

**Comment by just805** [comment]
我感觉我要换一个电脑显示器了。
