### ISSUE TITLE
fofa_search就卡死了

### ISSUE THREAD

**Issue by void-ll** [TophantTechnology/ARL#200]
fofa_search阶段就卡死不动了，希望能加一个超时，这样fofa_search卡死也能跑下一个模块，不然fofa_search模块卡死了又要从新开始。

**Comment by 1c3z** [comment]
可以看下nmap 进程是不是还在跑， fofa_search 获取到的IP可能有点多。

**Comment by liayou9** [comment]
nmap确实还在跑着，那我是不是就要关掉fofa搜索功能或者是等待更长的时间就可以了
