### ISSUE TITLE
功能优化建议

### ISSUE THREAD

**Issue by Wnltc** [TophantTechnology/ARL#202]
1. 资产分组
   1. 添加站点功能,可否增加,批量添加功能
   2. 添加子域名时,可否增加,下发任务时使用自定义扫描策略功能
2. 指纹管理
   1. 添加指纹功能,可否增加批量添加功能,通过导入json、csv文件的方式进行批量添加

**Comment by 1c3z** [comment]
1. 资产分组
   1. 添加站点功能, 这个后期添加
   2. 添加子域名时, 要自定义策略的话， 可以先在任务管理里添加任务，然后在任务右边进行同步操作到资产组
2. 指纹管理
   1. 添加指纹功能, 后期添加批量导入导出功能。

**Comment by Wnltc** [comment]
> 1. 资产分组
>    
>    1. 添加站点功能, 这个后期添加
>    2. 添加子域名时, 要自定义策略的话， 可以先在任务管理里添加任务，然后在任务右边进行同步操作到资产组
> 2. 指纹管理
>    
>    1. 添加指纹功能, 后期添加批量导入导出功能。

好的,感谢大佬!
刚刚尝试了一下,同步结果到资产组也只能一个个同步,后期可否考虑加入批量同步的功能呢

**Comment by 1c3z** [comment]
@Wnltc 
1.目前资产组可以同一个域名可以加到多个，批量同步逻辑实现起来有点别扭， 后面打算在策略里加个关联到资产组的选项。 

2.其实资产组这个功能添加只是为了资产监控的，站点截图显示这个就不打算加进去了。

**Comment by Wnltc** [comment]
> @Wnltc
> 1.目前资产组可以同一个域名可以加到多个，批量同步逻辑实现起来有点别扭， 后面打算在策略里加个关联到资产组的选项。
> 
> 2.其实资产组这个功能添加只是为了资产监控的，站点截图显示这个就不打算加进去了。

好的,感谢大佬.
1. 在策略中添加关联资产组,可以理解成是添加任务时把目标资产跟资产组做关联吗,那样的话,感觉方便了许多

2. 在资产组中添加站点截图,我前面的表述不太准确; 我想表达的是,在查看资产分组详情页中,加入站点截图显示,这样在有多个目标且每个目标都有多个域名时,可以把这些域名的扫描结果放到一个资产组中进行查看,其实,既然资产监控模块都把对做站点识别了,任务扫描结果也能同步至资产组进行查看,那在资产分组详情页再加入站点截图显示,体验应该会更好些
![image](https://user-images.githubusercontent.com/29775532/132151555-9c6322f4-8d05-4c55-95aa-11e7310c1200.png)

**Comment by 1c3z** [comment]
1. 是的
2. 批量查看的话可以在资产搜索里查看，他是按照时间顺序来的， 搜索的话可以通过域名等筛选。 
3. 这个还不行，等1实现了，3应该就没用了。
