### ISSUE TITLE
结果数量异常

### ISSUE THREAD

**Issue by Oldman19** [TophantTechnology/ARL#204]
我有两台vps，其中一台2h4g 8m带宽，另外一台1h2g 1m带宽，现在的问题就是低配服务器扫出来的资产数量结果要比高配服务器的结果要多很多。相同的主域名，低配服务器开扫top1000时，可以扫到800多的域名，而且大量200状态，高配服务器扫全端口，只扫到200多的子域名，200状态的也少之又少

**Comment by 1c3z** [comment]
1. 两个任务域名相关配置一样么？
2. 多IP扫描的时候最好也不要用全端口，效果不好。
3. 在域名标签页看下，右边的来源种类和相关数量对比看下， 可以对比下面这些 riskIQ，altdns ，arl ， crtsh， domain_brute 来源的子域名数量。

**Comment by Oldman19** [comment]
> 1. 两个任务域名相关配置一样么？
> 2. 多IP扫描的时候最好也不要用全端口，效果不好。
> 3. 在域名标签页看下，右边的来源种类和相关数量对比看下， 可以对比下面这些 riskIQ，altdns ，arl ， crtsh， domain_brute 来源的子域名数量。

回复3：数量相同，但是在开始扫端口后，就不一样了，top1000数量还是太少了。

**Comment by 1c3z** [comment]
我看你前面说 ，低配可以扫到 可以扫到800多的域名，高配只能扫到200多的子域名。 

数量相同，但是在开始扫端口后，就不一样了，top1000数量还是太少了。 这个是什么少？

**Comment by Oldman19** [comment]
> 我看你前面说 ，低配可以扫到 可以扫到800多的域名，高配只能扫到200多的子域名。
> 
> 数量相同，但是在开始扫端口后，就不一样了，top1000数量还是太少了。 这个是什么少？

是这样，低配与高配扫出来的子域名数量一样，但是站点数量差距很大

**Comment by 1c3z** [comment]
站点差距大是，可能全端口有些IP一个端口都没扫出来。 
针对公网多IP 全端口扫描目前还是先放弃吧。 后面会开放端口扫描的参数，看能不能通过调节参数让扫描效果好点。
