### ISSUE TITLE
关于自定义hosts文件域名解析的问题

### ISSUE THREAD

**Issue by thinkoaa** [TophantTechnology/ARL#206]
你好，目前版本不是没有ip监控吗？我想换个思路简单用下，在hosts文件中把想扫描的ip和一个自定义域名对应了起来，但是ARL扫描时不能把自定义的域名解析为想扫的IP，修改宿主机和docker arl_worker、arl_web、arl_scheduler中的host文件也不行，请问还有什么注意的地方吗？容器中ping自定义域名是解析到了指定的ip，但是ARL什么也扫不出来。

**Comment by 1c3z** [comment]
1. IP / IP段这个监控下个版本就要上了。 
2. 改Host文件不生效是因为用的dns.resolver， 这个直接请求的DNS服务器。
