### ISSUE TITLE
功能优化建议 

### ISSUE THREAD

**Issue by Ajmd007** [TophantTechnology/ARL#208]
优化指纹识别 
添加与逻辑

**Comment by 1c3z** [comment]
目前只能写首页的特征还要ico_hash, 这个优化能不能详细说下？

**Comment by 2418298040** [comment]
> 现在只能写首页的其他配件ico_hash，这个优化能不能详细说下？

举个例子：
body="aaaa"&body="cccc"

**Comment by 2418298040** [comment]
> 现在只能写首页的这个其他配饰ico_hash，优化能不能详细说下？

再或者
title="aaa"&body="ddddd"
这样

**Comment by 1c3z** [comment]
目前只是可以用或的逻辑，与的逻辑不行

比如  body="aaaa" || body="cccc"
