### ISSUE TITLE
自定义字典过大，导致超时

### ISSUE THREAD

**Issue by shenhanqing** [TophantTechnology/ARL#210]
PRECONDITION_FAILED - delivery acknowledgement on channel 1 timed out. Timeout value used: 1800000 ms. This timeout value can be configured, see consumers doc guide to learn more

这个超时配置具体在那个文件下呀？

**Comment by 1c3z** [comment]
我本地测过600万的字典，没有问题的， 
你这边试试吧服务器上的agent 都关了，在测测看看。

**Comment by 1c3z** [comment]
```
docker-compose exec rabbitmq bash 
vi /etc/rabbitmq/rabbitmq.conf 
```
把这个加进去看下,    3000分钟超时
consumer_timeout = 180000000
