### ISSUE TITLE
一直卡在file_leak

### ISSUE THREAD

**Issue by Ivan52** [TophantTechnology/ARL#211]
![image](https://user-images.githubusercontent.com/25704146/133053362-fbf18ad6-2212-4c6b-9bae-69dbc086945f.png)
卡在这里2-3天

**Comment by 2418298040** [comment]
+1

**Comment by 1c3z** [comment]
这个模块比较慢， 这个任务站点有多少？
看下arl_worker.log 这个文件还要相关file_leak 的输出么？

**Comment by 2418298040** [comment]
> 这个模块比较慢， 这个任务站点有多少？
> 看下arl_worker.log 这个文件还有相关file_leak 的输出么？

![image](https://user-images.githubusercontent.com/62884583/133227891-43bd60af-49dd-4846-9f9b-33c4767a8ab4.png)

**Comment by 2418298040** [comment]
![image](https://user-images.githubusercontent.com/62884583/133228065-53460fd1-13d4-44dc-abff-8895045ad7e8.png)
![image](https://user-images.githubusercontent.com/62884583/133228123-5814e586-ca36-431b-91ec-e49903c2adeb.png)

**Comment by 1c3z** [comment]
@2418298040 
1. 任务可以点进去看, 拉到最下面在站点选项卡可以看到站点总数
2.  用tail -f  arl_web.log 可以看（不过看你截图好像是windows ，可以百度查查看）
3. 如果容器关过的，任务可能就没执行了， 这个状态不会更新。

**Comment by 2418298040** [comment]
> @2418298040
> 
> 1. 任务可以点进去看, 拉到最下面在站点选项卡可以看到站点总数
> 2. 用tail -f  arl_web.log 可以看（不过看你截图好像是windows ，可以百度查查看）
> 3. 如果容器关过的，任务可能就没执行了， 这个状态不会更新。

这是xftp  ,我任务停止了重新开一个半个小时就好了

**Comment by 2418298040** [comment]
![image](https://user-images.githubusercontent.com/62884583/133454821-21260049-8716-4435-a17f-3ce50bc14910.png)
同一个域名，同样的设置

**Comment by Burt2o2o** [comment]
> > @2418298040
> > 
> > 1. 任务可以点进去看, 拉到最下面在站点选项卡可以看到站点总数
> > 2. 用tail -f  arl_web.log 可以看（不过看你截图好像是windows ，可以百度查查看）
> > 3. 如果容器关过的，任务可能就没执行了， 这个状态不会更新。
> 
> 这是xftp ,我任务停止了重新开一个半个小时就好了

请问下卡住之后，停止重新开，是自己重新下发一个任务，还是接着之前的来？接着来再开始好像没有这功能矣

**Comment by 2418298040** [comment]
> > > @2418298040
> > > 
> > > 1. 任务可以点进去看, 拉到最下面在站点选项卡可以看到站点总数
> > > 2. 用tail -f  arl_web.log 可以看（不过看你截图好像是windows ，可以百度查查看）
> > > 3. 如果容器关过的，任务可能就没执行了， 这个状态不会更新。
> > 
> > 
> > 这是xftp ,我任务停止了重新开一个半个小时就好了
> 
> 请问下卡住之后，停止重新开，是自己重新下发一个任务，还是接着之前的来？接着来再开始好像没有这功能矣

是自己重新下发一个任务
