### ISSUE TITLE
几个不成熟的bug反馈和功能小建议

### ISSUE THREAD

**Issue by sftrwo** [TophantTechnology/ARL#213]
用了一段时间发现ARL不管是功能还是界面都用着非常的舒服，由于本人开发水平有限，只能厚着脸皮给你们提一些不成熟的小建议。

### 资产监控任务
1. 通过资产监控扫描出来的子域名，来源字段全部是monitor，这里是不是应该还是标注为真实的来源比较直观。
2. 添加任务扫描完成后，再将目标添加到资产监控，会导致资产搜索结果中出现两个重复的子域名，一个来自任务扫描出来的记录，一个来自资产监控的结果。
![image](https://user-images.githubusercontent.com/49747619/133878104-bf96a204-f783-4d64-a06d-b90a1815ff2c.png)
3. 接着上面的使用场景，任务扫描完成之后，再将目标添加到资产监控，在添加了钉钉推送的情况下，会收到资产监控得到的所有子域名（这里我猜应该是资产监控的第一次扫描会出现这个情况），可不可以在资产监控的过程中先在数据库搜索一遍之前任务扫描出来的结果，再对新增的域名进行推送。
4. 我发现添加任务扫描出来的子域名比第一次资产监控扫描出来的子域名少很多，遇到了几次，不知道是不是这两个功能在扫描逻辑上有区别，还是碰巧扫描的时候网络超时了。
![image](https://user-images.githubusercontent.com/49747619/133878408-86aaa698-3bac-4291-8523-156e2b6563d3.png)

### 域名查询增加多个接口
对比了一下Oneforall这个子域名爆破工具的结果，发现有些ARL扫描不到的子域名大部分都来自于SecurityTrailsAPIQuery这个接口，还有小部分来自IP138和AlienVaultQuery，我只测试了一个域名，可能还有其他的接口也能搜出更多结果。

### 任务重新开始
比如我添加了一个任务扫描，然后扫描的结果可能出现问题，我还想以相同的配置项对这个目标重新扫描一次，就懒得又重新添加任务重新勾选配置项了。

### Web界面增加日志功能
这样可以比较方便排查出现问题的点，就不用每次上服务器去看日志了。

### 手工新增或者编辑或者批量导入资产
有时候自动化扫描出来的可能不全或者不准确，人工测试发现的域名可以新增到资产中。包括人工发现的Web的指纹、CMS、真实IP等等，比如我看到很多人提issue说全端口扫描的结果不准备，那就自己通过masscan或者nmap扫描出来的结果批量导入到资产中。
甚至可以将人工测试发现的各种漏洞放在对应的资产里面，最后就能够比较直接的看到所有掌握的目标的信息了，然后形成一个简单的报告。
当然这个就有点像项目的管理了，可能不太符合你们产品的定位。

**Comment by 1c3z** [comment]
1.  监控任务域名来源这个确实有点问题，我后面看看能不能优化下
2.  每个任务之间是独立的，下了多个任务就会有多个结果
3.  新建资产分组后，里面是没有数据，可以通过任务管理界面进行手动同步， 考虑到可能有好多域名同步比较麻烦，在ARL 2.4.1 (在路上了) 中添加了可以通过策略关联到资产组，选择策略下发任务的时候然后会自动同步过去。
![image](https://user-images.githubusercontent.com/9052484/133886417-0367e8b9-97eb-4754-9e85-f93d33d5f767.png)

4. 监控任务和资产发现的任务配置项是不一样的，从结果来看，站点缺少数据应该是端口扫描没有结果，后面监控任务的选项也是可以配置的
5.  SecurityTrails 的免费API 可用次数太少，觉得加的意义不大，建议多测试几个域名。 
6.  任务重新开始准备在下下个版本加上
7. Web 日志展示开发成本有点高，这个就不加了。
8. 可以在资产分组里进行管理资产，可以添加站点和子域名， 站点里面有打标签的功能，可以通过在标签里面加入指纹信息进行管理。
