### ISSUE TITLE
想咨询一下灯塔的那个config-docker.yaml

### ISSUE THREAD

**Issue by heiheip** [TophantTechnology/ARL#214]
我在使用了一个默认的config-docker,yaml启动了一个容器，然后发现需要配置这个config-docker.yaml，我配置完之后是需要重新建立一个容器还是 重启原来的容器就好了

**Comment by 1c3z** [comment]
重启容器就好。

**Comment by dabai123456** [comment]
> 重载就好。

这个是怎么重载呢
