### ISSUE TITLE
建议自定义添加域名查询接口扩展

### ISSUE THREAD

**Issue by ppbibo** [TophantTechnology/ARL#216]
建议添加自定义域名查询接口扩展
保证域名更加全面

fofa shodan -> domains = set() -> 下发任务

**Comment by 1c3z** [comment]
是说的这种模式么？ 留好扩展接口，用户自己写代码实现收集过程？

**Comment by SuperXiaoxiong** [comment]
用户直接导入已经收集（或者整理好）的域名

**Comment by 1c3z** [comment]
> 用户直接导入已经收集（或者整理好）的域名

现在可以的呀，要先新建资产分组，然后再添加子域名（不要选策略，这里有个BUG）

![image](https://user-images.githubusercontent.com/9052484/143975139-e2cc5d4d-ffc0-4b8e-bf04-2527031bb3b2.png)

**Comment by 1c3z** [comment]
有域名查询插件实现了类似功能，先关闭。
