### ISSUE TITLE
资产监控时，没有检测到任何信息，但手动添加任务可以，版本2.4.1

### ISSUE THREAD

**Issue by thinkoaa** [TophantTechnology/ARL#217]
如图所示，监控资产没有任何结果，域名是可以手动访问到的
![image](https://user-images.githubusercontent.com/65639454/135240126-e877dad8-a1e9-4d6b-afd9-54deb300807b.png)

**Comment by 1c3z** [comment]
我刚试了下可以，程序默认是一次性查询10000条数据，需要高级会员。

**Comment by thinkoaa** [comment]
risk的api配置的有，FOFA的高级会员token也配置的有，同样一个域名，一模一样的配置，手动添加任务执行就可以，但定时任务执行就没有结果
