### ISSUE TITLE
资产监控中，域名资产监控可以创建1个任务么

### ISSUE THREAD

**Issue by Pa55w0rd** [TophantTechnology/ARL#219]
资产分组  - 》 资产监控，一下子创建几千个任务。。。。每个任务跑完了看详情还得挨个点，是我使用的姿势不对么

**Comment by 1c3z** [comment]
为啥会有这么多。。 资产范围里面写的子域名么？，一般写主域名就可以。 

任务结果可以通过资产搜索里面看，或者资产分组详情里看。

**Comment by Pa55w0rd** [comment]
> 为啥会有这么多。。 资产范围里面写的子域名么？，一般写主域名就可以。
> 
> 任务结果可以通过资产搜索里面看，或者资产分组详情里看。

这是从乙方角度来看的，如果换成甲方角度，我就可以拿到dns解析列表，就不用去子域名收集了，可以把列表归属到资产范围里面
