### ISSUE TITLE
ARL是否可以添加删除历史记录模块

### ISSUE THREAD

**Issue by ROCKLEE-1998** [TophantTechnology/ARL#22]
您好，之前arl进行采集过的历史纪录无法删除，后续更新是否可以增加删除历史记录模块

**Comment by striveben** [comment]
问下，咱们前段具体是用哪些框架开发的，想添加点页面，谢谢。

**Comment by 1c3z** [comment]
@ROCKLEE-1998   删除任务记录下个版本会考虑加上的。

**Comment by 1c3z** [comment]
@striveben 用的Vue.js  具体是啥页面？

**Comment by 1c3z** [comment]
删除功能已添加，请更新
https://github.com/TophantTechnology/ARL/releases/tag/v2.1

**Comment by ROCKLEE-1998** [comment]
感谢
