### ISSUE TITLE
用的时候发现的两个bug

### ISSUE THREAD

**Issue by heiheip** [TophantTechnology/ARL#220]
1.网络资产的域名数据到3439条就不会增加了，并且会把原来的域名数据清楚掉
2.ip到处异常，页面显示有13w的ip到处时只有6k左右的ip

**Comment by 1c3z** [comment]
1. 没有太明白，
2. 13w ip 里面有重复的，导出的时候只会导出前1万条，点击第二页会导出第二个2万，最终结果会去重。通过任务管理里面的批量导出IP功能不会有这个问题。
