### ISSUE TITLE
更新之后一直无法启动

### ISSUE THREAD

**Issue by TheTh1nk3r** [TophantTechnology/ARL#223]
![image](https://user-images.githubusercontent.com/42456962/136685551-251af23c-b6f0-47c8-855a-b90b524c8a62.png)

**Comment by TheTh1nk3r** [comment]
![image](https://user-images.githubusercontent.com/42456962/136686310-f41fd65f-9417-4f52-ab4e-117df2a80a44.png)
![image](https://user-images.githubusercontent.com/42456962/136686317-a02d5126-74a7-4389-9e2b-42f85a6a204c.png)
mongo这个容器一直重启，
![image](https://user-images.githubusercontent.com/42456962/136686345-cbdf9ee1-3fe7-4f50-bd75-f889dc2cdef3.png)

**Comment by 1c3z** [comment]
@TheTh1nk3r 
rabbitmq 和mongo 一直起不来，看下更详细的日志。 

另外请首先检查下硬盘是不是满了。
