### ISSUE TITLE
使用一键安装脚本出现出错

### ISSUE THREAD

**Issue by Leekeey** [TophantTechnology/ARL#225]
前面都是没问题的，就在安装这个包时出错： 
Running setup.py install for psutil ... error
    ERROR: Command errored out with exit status 1:
     command: /usr/bin/python3 -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-dczv9agi/psutil_4f09cd822c594a0580d5245be0979b03/setup.py'"'"'; __file__='"'"'/tmp/pip-install-dczv9agi/psutil_4f09cd822c594a0580d5245be0979b03/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-ap0ov8t4/install-record.txt --single-version-externally-managed --compile --install-headers /usr/local/include/python3.6m/psutil
         cwd: /tmp/pip-install-dczv9agi/psutil_4f09cd822c594a0580d5245be0979b03/

**Comment by 1c3z** [comment]
看前面的日志是psutil 没有安装成功，具体原因不太清楚
日志中有个 /usr/local/include/python3.6m,  这里是python3.6 和你提供的python3.7 有点出入。
建议用纯净的centos7安装。
