### ISSUE TITLE
ARL 2.4.1 docker镜像有两个容器一直重启

### ISSUE THREAD

**Issue by ltfafei** [TophantTechnology/ARL#226]
你好，ARL 2.4.1 docker镜像更新有问题，查看日志是rabbitmp的守护进程没有起来。

![image](https://user-images.githubusercontent.com/43526141/137437511-720ff044-ca84-499d-940e-be9d016edbb0.png)

**Comment by TheTh1nk3r** [comment]
看看是不是内存不足了，我之前就是

**Comment by ltfafei** [comment]
> 这个是web 和scheduler 没有启动。 观察下这个输出，看有没有错误信息
> 
> ```
> docker-compose logs -f  --tail=10
> ```

图中查看了日志，好像是rabbitmq守护进程没有起来。并且这两个容器一直在重启。也没有发现端口被占用情况

**Comment by 1c3z** [comment]
git pull 下载的源码没有用到，这步只是更新了 `docker/docker-compose.yml` 中的配置。
再pull 镜像看看能不能启动。

**Comment by ltfafei** [comment]
> git pull 下载的源码没有用到，这步只是更新了 `docker/docker-compose.yml` 中的配置。 再pull 镜像看看能不能启动。

更新到2.4.1之后，无法扫描了，一直在等待中。

![image](https://user-images.githubusercontent.com/43526141/137590131-2d0f515e-394a-4a32-a063-b995a044b199.png)
