### ISSUE TITLE
github 监控和常规资产扫描任务冲突

### ISSUE THREAD

**Issue by Mr-xn** [TophantTechnology/ARL#230]
场景：资产扫描任务一直在运行，有大量的处于等待状态的任务没有完成，此时新加 github 任务或者 github 监控任务都是处于等待状态。
预期：github 任务或者 github 监控任务应该和资产的分开，不用统一加入一个 worker 管理或者说 github 监控有单独的 worker 可以配置

**Comment by 1c3z** [comment]
目前实现的是全部任务都放在一个队列里面了，如果任务不够用可以调worker数量。 但是刚开始下的任务比较多的话，肯定会有个高峰期的。 耐心等待完成就好。

**Comment by Mr-xn** [comment]
增加 worker 数量估计也不行 因为资产任务数量太多 总是排在前面的。。。还是希望后期可以使用单独的 worker 配置

**Comment by 1c3z** [comment]
已优化。
