### ISSUE TITLE
github只允许设置一个token吗

### ISSUE THREAD

**Issue by tangxiaofeng7** [TophantTechnology/ARL#231]
![image](https://user-images.githubusercontent.com/45926593/140039192-eec97e57-896e-42af-b9d5-a848254cd57b.png)

**Comment by 1c3z** [comment]
是的。

**Comment by Godsuche** [comment]
怎么设置token呀

**Comment by 1c3z** [comment]
@Godsuche 
麻烦看下这个 

https://github.com/TophantTechnology/ARL/wiki/ARL-2.4.1-%E6%96%B0%E6%B7%BB%E5%8A%A0%E5%8A%9F%E8%83%BD%E8%AF%A6%E7%BB%86%E8%AF%B4%E6%98%8E#%E4%B8%89github-%E4%BB%BB%E5%8A%A1%E5%92%8C%E7%9B%91%E6%8E%A7
