### ISSUE TITLE
docker 容器部署下存储空间清理

### ISSUE THREAD

**Issue by fool-sir** [TophantTechnology/ARL#232]
应用系统每天除资产新增和日志会占用存储空间，还有有其他的吗？ 如何定期清理？

**Comment by 1c3z** [comment]
如果开截图了的话还有docker/image 文件夹下会有截图文件。

**Comment by jinqi520** [comment]
还有清除其他数据（如垃圾或历史数据）的方法吗 删了几个G的图片 感觉还是不太够

**Comment by 1c3z** [comment]
@jinqi520 

保持arl 运行, 执行下面的试试

```
docker system prune
```
