### ISSUE TITLE
web 指纹识别增强

### ISSUE THREAD

**Issue by LandGrey** [TophantTechnology/ARL#234]
现在 web 指纹识别过于简单，建议
1. 加入默认从 http header 里拿出 Server、X-Powered-By 字段值 value，然后 value.split("/")[0] 作为指纹的逻辑
2. 正则表达式匹配用户加入的指纹，不区分大小写

**Comment by 1c3z** [comment]
指纹规则已强化，欢迎更新v2.6.1 ， issue 先关闭。
