### ISSUE TITLE
资产重复

### ISSUE THREAD

**Issue by LandGrey** [TophantTechnology/ARL#236]
资产搜索 侧边栏，站点、子域名、ip 三个标签下都没有去重，多次操作或者同步会导致重复的记录一直增加

**Comment by 1c3z** [comment]
资产搜索可以看出任务的汇总，这里没有去重的。

**Comment by LandGrey** [comment]
> 资产搜索可以看出任务的汇总，这里没有去重的。

没有去重太难受了，重复的记录没有意思。建议加个去重按钮或者加一个定时(比如 30 分钟)去重任务，任务空闲时候筛除掉重复目标和记录。

**Comment by 1c3z** [comment]
1.资产搜索这个功能去重不太好搞，后面还要考虑翻页的事情。 
2. 如果要对特点资产保持不重复，可以用资产分组的功能。
