### ISSUE TITLE
支持批量任务下发

### ISSUE THREAD

**Issue by LandGrey** [TophantTechnology/ARL#237]
资产搜索侧边栏里，除了风险任务支持对一批站点下发任务外，其余的策略配置都不支持批量下发，只能填域名和ip，不能选择资产分组或者一批站点统一下发。
比如对资产搜索里的一批目标，或者资产分组里的一个分组，批量执行 服务(python)识别 任务。

**Comment by 1c3z** [comment]
为了批量执行 `服务(python)识别 `可以有两个选择
1. 先从资产分组中把IP导出来，然后再通过策略批量下发。 
2. 下发单个主域名，并确保对应的资产分组中有子域名资产，再策略中记得要勾选`ARL 历史查询`, 通过策略下发这个主域名就可以

也就是任务结果里出现的IP都会进行 服务(python)识别 。

**Comment by LandGrey** [comment]
> 为了批量执行 `服务(python)识别 `可以有两个选择
> 
> 1. 先从资产分组中把IP导出来，然后再通过策略批量下发。
> 2. 下发单个主域名，并确保对应的资产分组中有子域名资产，再策略中记得要勾选`ARL 历史查询`, 通过策略下发这个主域名就可以
> 
> 也就是任务结果里出现的IP都会进行 服务(python)识别 。

第一个方法不太方便，导出后域名 ip 太多，一次性填入超过几千个地址，提交任务时候 web 前端直接超时了，需要个导入文件之类的方法来支持大批量目标；
第二个方法是可行的，就是有点曲折；但对于通过标签筛选出来的，一批目标不是一个主域名的情况还是不适用。

**Comment by 1c3z** [comment]
1. 我刚试了下，IP的方式这个很快呀。 

![image](https://user-images.githubusercontent.com/9052484/140698239-4e0616fa-0dd7-4453-b3ea-ca80c0a8cadd.png)

2. 域名的方式不曲折吧，那把域名发现开全点，不是一个主域名的情况，那就把所有的主域名都放进去。
