### ISSUE TITLE
资产搜索--IP端口导出不全

### ISSUE THREAD

**Issue by fool-sir** [TophantTechnology/ARL#238]
资产搜索里的IP端口导出，怎么每次只能导出很少一部分，每次导出的数量还不一致？

**Comment by 1c3z** [comment]
这个导出只能导出1万条数据并去重。 应该是每次在不同的页数导出的。 或者是有搜索条件。

**Comment by fool-sir** [comment]
@1c3z 资产搜索里攻击240条数据，但是导出的时候却能导出257条数据 出来。。。导出来好像是混乱的

**Comment by 1c3z** [comment]
你可以看下数据里面是带端口的，一个IP可能有多个开放端口， 界面看到的数目是IP这个维度的。

**Comment by fool-sir** [comment]
@1c3z 计划任务扫描出的资产可以增加时间标签吗？ 不然资产搜索里看到很多重复资产，都不知道什么时候发现的，比较不友好

**Comment by fool-sir** [comment]
@1c3z 计划任务扫描出的资产可以增加时间标签吗？ 不然资产搜索里看到很多重复资产，都不知道什么时候发现的，比较不友好

**Comment by fool-sir** [comment]
@1c3z ARL中可以主机发现吗? 探测网段内存活的主机数？ 22端口已关闭的情况下

**Comment by 1c3z** [comment]
> @1c3z 计划任务扫描出的资产可以增加时间标签吗？ 不然资产搜索里看到很多重复资产，都不知道什么时候发现的，比较不友好

这个后面可以考虑加下。 




> @1c3z ARL中可以主机发现吗? 探测网段内存活的主机数？ 22端口已关闭的情况下
可以呀，ping 扫描。 还有TCP 常用端口开放了，认为是存活的。

**Comment by fool-sir** [comment]
@1c3z 策略里哪个是ping扫描？
