### ISSUE TITLE
站点爬取失效

### ISSUE THREAD

**Issue by h2so0o4** [TophantTechnology/ARL#239]
在修改子域名、文件泄露字典后，新添加的任务扫描出的结果站点都为0
![image](https://user-images.githubusercontent.com/49434585/140872499-561db8ff-8c42-4112-aa17-fea9e394ff94.png)

**Comment by 1c3z** [comment]
修改子域名、文件泄露字典后和站点0检出是没有关系的， 看下是不是全端口扫描或者别的操作被目标封了，还有可以试下不勾选端口扫描看是否有站点检出。
