### ISSUE TITLE
目标设置成IP、IP段部分结果为空

### ISSUE THREAD

**Issue by Wuy1f4n** [TophantTechnology/ARL#24]
（1）在将目标设置成IP段时，IP扫描结果结果只有IP、Geo和AS字段，其他开放端口、操作系统、关联域名为空，另外的SSL证书、子域名、站点、服务、文件泄露和URL信息也为空
（2）在将目标设置IP时，所有的结果均为空
对比masscan扫描结果确实存在IP和端口等

**Comment by 1c3z** [comment]
感谢测试，可以关闭服务识别和操作系统识别，端口选top 100再测试一下。 有些IP可能有防火墙拦截。

**Comment by 1c3z** [comment]
已更新了新版本，对端口扫描功能进行了优化，可以麻烦再测试下是否有一样的问题

https://github.com/TophantTechnology/ARL/releases/tag/v2.2
