### ISSUE TITLE
建议增加ubuntu或redhat环境下的docker支持

### ISSUE THREAD

**Issue by harris2015** [TophantTechnology/ARL#240]
如题  没有centos系统 所以比较难进行docker部署

**Comment by 1c3z** [comment]
建议看下下官方文档

ubuntu 操作系统docekr 环境安装 
https://docs.docker.com/engine/install/ubuntu/

这里有个总览的
https://docs.docker.com/engine/install/

**Comment by harris2015** [comment]
docker我安装了 但是你们只适配了centos。。。

**Comment by 1c3z** [comment]
> docker我安装了 但是你们只适配了centos。。。

理解错了，只要是安装了 docker 环境都可以的跑的。

**Comment by harris2015** [comment]
报错啊。。。。

**Comment by 1c3z** [comment]
> 报错啊。。。。

报什么错呀？
