### ISSUE TITLE
资产导出只有10000个，怎么办

### ISSUE THREAD

**Issue by test502git** [TophantTechnology/ARL#242]
资产导出只有10000个，没办法导出其他的了，请问如何导出全部的

**Comment by 1c3z** [comment]
在当前页面点击下一页，然后再点导出可以导出第二个1万条数据。

**Comment by test502git** [comment]
以此类推是吗，
假如有10W，点10次下一页

**Comment by test502git** [comment]
有交流群吗，想入群

**Comment by 1c3z** [comment]
@test502git 

![e9316761983971204e6bdd668bc6aef](https://user-images.githubusercontent.com/9052484/142792659-2aeb1e60-da8a-4ad1-8241-21c73e088746.jpg)

**Comment by Howind** [comment]
交流群的可以再分享一下吗 过期了

**Comment by Howind** [comment]
@1c3z 交流群的二维码可以再分享一下吗 过期了

**Comment by 1c3z** [comment]
@Howind 

![image](https://user-images.githubusercontent.com/9052484/145750291-43e2f094-01f2-4aee-ad86-bc6e170a2af1.png)
