### ISSUE TITLE
ARL調用post方法如何傳參數

### ISSUE THREAD

**Issue by QF1837895299** [TophantTechnology/ARL#245]
ARL調用post方法如何傳參數

**Comment by 1c3z** [comment]
http_req 函数?

**Comment by QF1837895299** [comment]
对啊,用requests传post的body参数  好像http_req的用法不一样。可以麻烦解答一下吗  谢谢

**Comment by 1c3z** [comment]
> 对啊,用requests传post的body参数 好像http_req的用法不一样。可以麻烦解答一下吗 谢谢

method='post',  然后其他方法参考requests就行
