### ISSUE TITLE
arl_web和arl_worker一直启动不了

### ISSUE THREAD

**Issue by Ka1G** [TophantTechnology/ARL#252]
您好，这两个一直启动不起来，重装很多遍了，用的是centos7.6，python3.6.8，请问怎么样才能解决呢？
![image](https://user-images.githubusercontent.com/63583320/145748850-9e422fda-a65a-4218-be2b-2c4bb1990381.png)

**Comment by 1c3z** [comment]
1. 是安装的docker-ce 版本么
2. 排查下宿主机是否开启了selinux , 将selinux功能关闭即可

**Comment by Ka1G** [comment]
@1c3z 哥哥牛逼！！！装了两天都不如问你一遍，谢谢谢谢。
