### ISSUE TITLE
任务管理需要一个单独查看风险结果和文件泄露的选项

### ISSUE THREAD

**Issue by heywiorld** [TophantTechnology/ARL#256]
如题
不然扫很多网段 需要一个个点击查看风险结果和文件泄露

**Comment by 1c3z** [comment]
#243 

麻烦看下这个
https://github.com/TophantTechnology/ARL/issues/243#issuecomment-969681266

**Comment by heywiorld** [comment]
> 

但是这个是需要一个个点进去才能看到
如果任务很多的话 是个很麻烦的事情 所以建议单独一个选项或页面做个聚合

**Comment by heywiorld** [comment]
> #243
> 
> 麻烦看下这个 [#243 (comment)](https://github.com/TophantTechnology/ARL/issues/243#issuecomment-969681266)

但是这个是需要一个个点进去才能看到
如果任务很多的话 是个很麻烦的事情 所以建议单独一个选项或页面做个聚合

**Comment by 1c3z** [comment]
@heywiorld 
麻烦先认真看下，再试下。

**Comment by heywiorld** [comment]
> @heywiorld 麻烦先认真看下，再试下。

原来在这里 多谢
