### ISSUE TITLE
arl2.5 升级后问题

### ISSUE THREAD

**Issue by fool-sir** [TophantTechnology/ARL#264]
升级到2.5版本后，发现扫描任务时间延长很多，容易卡死，2.4版本的扫描任务20分钟完成，新版的需要2小时以上，还不一定

**Comment by 1150037361** [comment]
升级到2.5版本，策略组处没有host碰撞选项

**Comment by 1c3z** [comment]
勾选了什么配置呀？ 
还有状态里的时间可以对比下。 


![image](https://user-images.githubusercontent.com/9052484/147532288-7e186c25-0d77-498e-88c9-b0197277d085.png)

**Comment by 1c3z** [comment]
@1150037361 
是的，策略里没有这个配置项。

**Comment by fool-sir** [comment]
@1c3z 只是IP的B段地址扫描22和3389两个端口而已
![image](https://user-images.githubusercontent.com/58167489/147533627-f309c853-04ce-42fa-aba2-5792fe3504ed.png)

**Comment by fool-sir** [comment]
@1c3z  我还原回2.4.1 就没有这个问题

**Comment by 1c3z** [comment]
端口扫描这个改动不大，根据你的描述猜测是max_hostgroup 默认值设置小了。
https://github.com/TophantTechnology/ARL/blob/master/app/services/portScan.py#L13

下个版本看看怎么优化下。

**Comment by 1c3z** [comment]
更新了2.5.1 端口扫描改了下，有时间可以重新看下。  max_hostgroup  调成128了。
