### ISSUE TITLE
连接Fofa API异常

### ISSUE THREAD

**Issue by MarkKC** [TophantTechnology/ARL#269]
<img width="552" alt="image" src="https://user-images.githubusercontent.com/28827108/148687835-8b27a535-7e58-47ef-ad4b-e0c6179513fa.png">

**Comment by 1c3z** [comment]
可能不是高级会员。

**Comment by MarkKC** [comment]
我试过十条都不行

**Comment by jhhd88** [comment]
> 我试过十条都不行

你先看看是不是你的VPS ip被fofa给封了

**Comment by 1c3z** [comment]
> 我试过十条都不行

这个和测试结果数应该是没关系的，硬编码写了个size=10000

用这个工具吧。 

https://github.com/xiecat/fofax/blob/main/README.zh-CN.md
