### ISSUE TITLE
多任务运行时候部分任务会卡死在一个状态

### ISSUE THREAD

**Issue by hu185396** [TophantTechnology/ARL#270]
通过策略下发多任务运行时候，部分任务会卡死在一个状态，必须手动停止后才能开始后续任务

**Comment by 1c3z** [comment]
可以看下arl_worker.log日志。 应该是还在运行。 

任务上看到的是什么状态？
端口扫描全端口？

**Comment by hu185396** [comment]
是全端口扫描
任务看到没有进展最多是port_scan、file_leak、weak_brute

**Comment by 1c3z** [comment]
file_leak 如果站点比较多的话，是比较费时间的。 
weak_brute 如果识别到的服务比较多，也是比较费时间的。
