### ISSUE TITLE
无扫描结果

### ISSUE THREAD

**Issue by kkll5875** [TophantTechnology/ARL#273]
1、新建任务无扫描结果。
![image](https://user-images.githubusercontent.com/52806749/149438979-23d40740-da22-48e6-8c03-cae0a578963f.png)
![image](https://user-images.githubusercontent.com/52806749/149439019-6b7200be-7e4d-44da-bcfa-f0c233121b50.png)
2、尝试修改dns文件，并重启。
![image](https://user-images.githubusercontent.com/52806749/149439367-1af5b538-d9d1-4d66-88ad-b5cd2f334e05.png)
3、查看arl_worker.log日志：
![image](https://user-images.githubusercontent.com/52806749/149439146-01fe588d-5c3e-408b-bf95-c9bf52105caf.png)
![image](https://user-images.githubusercontent.com/52806749/149439253-8b90b109-dfaa-4f02-bb8f-100d407c865b.png)

**Comment by 1c3z** [comment]
1. 爆破的时候会用dnsserver.txt的域名服务器，
2.最后一步会用本地服务器的DNS， 可以手动ping 下看域名能解析么。 
3. 还有这个目标域名是不是就是没有子域名。

**Comment by myqf23** [comment]
你好，我和你遇到了相同的问题，请问你解决了么
