### ISSUE TITLE
灯塔更新2.5版本后的一些问题

### ISSUE THREAD

**Issue by almighty-zhao** [TophantTechnology/ARL#274]
不知道是不是作者大大动了哪一部分的代码，导致2.5版本的综合性能都不如之前的版本好用了。突出的问题是站点存活识别率太低了，端口扫描，站点存活扫描时长要比之前要长，fofa api那个显示异常之前版本就存在问题，望下一个版本可以改进一下这些问题，加油！

![image](https://user-images.githubusercontent.com/72288982/149661172-5a9ad9a9-ee6e-4458-9f04-d9e1876e172e.png)

**Comment by almighty-zhao** [comment]
初步判断不是目标的问题，因为两个版本分别扫描得出来的结果差距很大

**Comment by 1c3z** [comment]
1.第一个任务看起来时间确实有点长。
2. 端口扫描是全端口？
3. 站点存活扫描时长要比之前要长， 可以把IP 端口导出来，看下是不是有大量开放端口的情况。
4. fofa api那个显示异常， FOFA 任务下发界面的测试按钮是否工作正常？账号是否是高级会员？

**Comment by almighty-zhao** [comment]
扫描常规端口，目标是正常的

**Comment by 1c3z** [comment]
> 扫描常规端口，目标是正常的

这个描述，我这里也不好排查。 

最好提供下这两个截图，还有下发的域名，我本地复现下。 
![image](https://user-images.githubusercontent.com/9052484/149861688-3d4ea40a-ff19-4d35-a3dd-413da4b3ccbd.png)
![image](https://user-images.githubusercontent.com/9052484/149861703-90c7c149-4686-4554-8a3a-818a74261320.png)

**Comment by myrecollect** [comment]
有什么结果吗，我想回退，但之前的包没有了，哪里可以下载2.41的啊，没有找到

**Comment by fool-sir** [comment]
一样的体验，升级好扫描功能没有以前好用

**Comment by myrecollect** [comment]
怎么在保存数据的情况下回退到2.41呀，我保留了rabbitmq和mongodb，直接重装的2.41。但是完成后还是2.5

**Comment by fool-sir** [comment]
> 怎么在保存数据的情况下回退到2.41呀，我保留了rabbitmq和mongodb，直接重装的2.41。但是完成后还是2.5

修改docker-compose.yml文件，指定镜像版本

**Comment by myrecollect** [comment]
麻烦问一下，这里具体数值怎么填啊
![image](https://user-images.githubusercontent.com/48248485/149890550-0ffa931f-a106-4b81-9605-89de0e6b616d.png)

**Comment by fool-sir** [comment]
> 麻烦问一下，这里具体数值怎么填啊 ![image](https://user-images.githubusercontent.com/48248485/149890550-0ffa931f-a106-4b81-9605-89de0e6b616d.png)

docker pull tophant/arl:v2.4.1    可以填写v2.4.1 试试

**Comment by 1c3z** [comment]
更新了2.5.1 端口扫描改了下，有时间可以重新看下。

**Comment by fool-sir** [comment]
@1c3z 刚刚更新了，发现版本还是2,5

**Comment by 1c3z** [comment]
没有pull 吧？ 页面上可能需要强制刷新下。

**Comment by fool-sir** [comment]
已解决

**Comment by fool-sir** [comment]
@1c3z  需要手动更改版本为v2.5.1，使用latest不行，怎么pull都是2.5

**Comment by 1c3z** [comment]
我刚找了台机器试了下可以，可能是前面没更新好。
