### ISSUE TITLE
arl_web.log isn't writable

### ISSUE THREAD

**Issue by condesings** [TophantTechnology/ARL#275]
wait-for-it.sh: mongodb:27017 is available after 0 seconds
Error: Error: 'arl_web.log' isn't writable [PermissionError(13, 'Permission denied')]

**Comment by 1c3z** [comment]
1. 是安装的docker-ce 版本么
2. 排查下宿主机是否开启了selinux , 将selinux功能关闭即可

**Comment by sv3nbeast** [comment]
同问，我的报IsADirectoryError: [Errno 21] Is a directory: '/code/arl_worker.log'
selinux已关闭

**Comment by 1c3z** [comment]
@sv3nbeast 

应该是 arl_worker.log 文件不存在， touch 下。
