### ISSUE TITLE
新版本任务并行数量是在yml文件的第41行吗？

### ISSUE THREAD

**Issue by t1gress** [TophantTechnology/ARL#277]
![图片](https://user-images.githubusercontent.com/41327526/150100768-7068890d-4a93-4f41-83e3-c56d04fa2260.png)

**Comment by 1c3z** [comment]
是的。

**Comment by cheng1107** [comment]
> 是的。

好的，谢谢师傅，请问一下默认是不能扫描edu吗，如何解除限制呢

**Comment by 1c3z** [comment]
兄弟，授权了么？没有授权别改了。

#193
