### ISSUE TITLE
关于config-docker.yaml

### ISSUE THREAD

**Issue by ipsecc** [TophantTechnology/ARL#278]
感谢作者提供的工具！
1、爆破文件和爆破域名的字典具体要怎么配置，配置成物理机的字典文件发现没有生效
2、爆破文件时，能否加入递归爆破的功能，像dirsearch、wfuzz那样可以自定义递归目录的深度

**Comment by 1c3z** [comment]
1. 可以覆盖文件 参考 #36， 或者修改 docker/config-docker.yaml 这个文件，路径也是容器里面的。 
2. 现在爆破比较费时间，而且递归爆破的效果也不是像十年前有用了， 如果有需要的话可以把站点导出来，用其他工具手动跑。
