### ISSUE TITLE
搭建在服务器上出现无法访问

### ISSUE THREAD

**Issue by jiaocoll** [TophantTechnology/ARL#279]
![image](https://user-images.githubusercontent.com/62785738/151299761-5402fa80-d01b-45be-9f8b-db4624e347fd.png)

使用https出现如下结果：
![image](https://user-images.githubusercontent.com/62785738/151299871-3674f07b-7c1c-4ffe-a585-92720207bce8.png)

**Comment by 1c3z** [comment]
直接键盘敲入这11个字符：thisisunsafe
（鼠标点击当前页面任意位置，让页面处于最上层即可）

**Comment by jiaocoll** [comment]
谢谢！
