### ISSUE TITLE
一些建议，望采纳

### ISSUE THREAD

**Issue by BetterDefender** [TophantTechnology/ARL#28]
1.建议增加任务的重复扫描 和 周期性的定时扫描计划
2.建议增加扫描结果较上次相比发现新域名时通过邮箱进行通知

**Comment by Oldman19** [comment]
md，绝了，跟我想法一样

**Comment by 1c3z** [comment]
想法很好。可以考虑添加。

**Comment by 1c3z** [comment]
资产监控功能已添加。

https://github.com/TophantTechnology/ARL/releases/tag/v2.2
