### ISSUE TITLE
提问

### ISSUE THREAD

**Issue by Shellc0d** [TophantTechnology/ARL#284]
1.任务扫描扫到的资产不会自动资产分组吗
2.我需要对某个任务扫到的所有资产进行单独风险巡航怎么做呢 
3.资产搜索可否增加搜索指定任务名收集到的所有资产呢 这样方便第二点

**Comment by 1c3z** [comment]
1. 需要自己在任务管理页面里手动点击操作里面的同步按钮，或者策略配置里面关联选择一个资产分组，后面通过这个策略下发的任务新资产都会自动同步过去。
2. 
![image](https://user-images.githubusercontent.com/9052484/153563960-7831674c-9367-40ab-8100-caea43990eed.png)

3. 将不同的任务同步到同一个资产分组里面去，在资产分组里面搜索。

**Comment by Shellc0d** [comment]
> 1. 需要自己在任务管理页面里手动点击操作里面的同步按钮，或者策略配置里面关联选择一个资产分组，后面通过这个策略下发的任务新资产都会自动同步过去。
> 
> ![image](https://user-images.githubusercontent.com/9052484/153563960-7831674c-9367-40ab-8100-caea43990eed.png)
> 
> 3. 将不同的任务同步到同一个资产分组里面去，在资产分组里面搜索。

感谢师傅！给师傅添麻烦了
