### ISSUE TITLE
黑名单的问题

### ISSUE THREAD

**Issue by Maysec** [TophantTechnology/ARL#285]
![image](https://user-images.githubusercontent.com/53160265/153609899-cd5713a2-0ee7-45c7-a7be-b7368b0ee28f.png)
在config-docker.yaml中forbidden_domains移除掉edu和org的域名后再添加的时候变成了
![image](https://user-images.githubusercontent.com/53160265/153610178-71c1ab5b-6cb2-4d41-b282-0c56a411d597.png)
怎么解决呢

**Comment by 1c3z** [comment]
添加的域名里面有个错误的域名。
