### ISSUE TITLE
导出ip时如何排除cdn

### ISSUE THREAD

**Issue by testa010** [TophantTechnology/ARL#286]
需求是导出所有不是CDN的IP
现在只有搜索CDN的功能，无法反向搜索
<img width="816" alt="Snipaste_32-20" src="https://user-images.githubusercontent.com/64741288/153610773-0ae2cada-0273-4470-8dca-806b771e5c46.png">

**Comment by 1c3z** [comment]
目前搜索不支持排除的功能。 
只能手动筛选了，可以选择500条/页， 然后表格里的内容复制下，用sublime 选择包含CDN的行并删除

**Comment by 1c3z** [comment]
更新了2.5.1  ，任务导出时可以导出CDN字段。
