### ISSUE TITLE
网站里跑完没有任何数据

### ISSUE THREAD

**Issue by 188150486** [TophantTechnology/ARL#289]
可以访问网站，，但跑完没有任何数据

**Comment by 188150486** [comment]
作者你好 有交流群嘛 小白百度搜到落泪

**Comment by 1c3z** [comment]
可以issue搜索下
https://github.com/TophantTechnology/ARL/search?p=2&q=%E6%B2%A1%E6%95%B0%E6%8D%AE&type=issues


https://github.com/TophantTechnology/ARL/issues/87
