### ISSUE TITLE
工具很好用，在这里提一些建议，望采纳

### ISSUE THREAD

**Issue by Oldman19** [TophantTechnology/ARL#29]
1、希望可以开发一个实时监控子域名的功能，例如这个爆破子域任务刚完成后就立刻重新爆破或者可以设置过多久再爆破
2、希望可以对相同域名的新增域名有个明显标注，例如我今天对baidu.com扫完后，明天在扫，扫出新的子域名后，可以一眼看出来哪个是新发现的子域名。

**Comment by 1c3z** [comment]
想法很好。可以考虑添加。

**Comment by 1c3z** [comment]
资产监控功能已添加

https://github.com/TophantTechnology/ARL/releases/tag/v2.2
