### ISSUE TITLE
能否前端域名爆破添加多个选项？

### ISSUE THREAD

**Issue by czn-soon** [TophantTechnology/ARL#290]
如下，这里前端使用的时候，能否来个自定义添加字典选项，不然这里只能指定两个，有点少
![image](https://user-images.githubusercontent.com/61613298/154208125-f230d13e-5b74-4d89-b987-8ae4e95b3e33.png)

**Comment by 1c3z** [comment]
我懂你意思，这个目前是前端静态写好的，改起来有点麻烦。

**Comment by czn-soon** [comment]
那前端静态默认的时候，能多添加几个吗？

**Comment by 1c3z** [comment]
> 那前端静态默认的时候，能多添加几个吗？

名字也不能自定义，会分不清哪个是哪个


或者每次手动改这个配置项目，也比较麻烦。 
https://github.com/TophantTechnology/ARL/blob/master/docker/config-docker.yaml#L67
