### ISSUE TITLE
fofa任务下发异常

### ISSUE THREAD

**Issue by haoyes0v0** [TophantTechnology/ARL#291]
因为fofa域名更改为fofa.info，导致fofa.so域名的api不可用。我通过docker exec -it [id] bash进入到项目的容器中。我找到了app/services/fofaClient.py中错误的地方
```
self.base_url = "https://fofa.so"

```
修改为
```
self.base_url = "https://fofa.info"
```
但是，这样不起作用。我重启容器之后，fofaClient.py文件被还原为我修改前的样子。请问这个问题如何解决呢，谢谢你们

**Comment by 1c3z** [comment]
1. 在修了。 
2. 是改的worker 的容器么？   怎么重启的？ 按理应该不会。

**Comment by haoyes0v0** [comment]
> 1. 在修了。
> 
>     2. 是改的worker 的容器么？   怎么重启的？ 按理应该不会。

我现在已经解决了这个问题，是这样的，我修改了三个容器arl_worker  arl_scheduler arl_web的fofaClient.py文件，现在fofa 可以正常下发任务了。
fofaClient.py文件被还原可能因为我使用了docker-compose down

**Comment by 1c3z** [comment]
嗯 down是会把容器删除。

**Comment by zzz6792x** [comment]
> > 1. 在修了。
> >    
> >    2. 是改的工人的容器么？怎么重启的？按理应该不会。
> 
> 我已经解决了这个问题，现在是这样的，我修改了三个容器arl_worker arl_scheduler arl_web的fofaClient.py文件，现在fofa可以正常下发任务了。 fofaClient.py文件被可能因为我使用了docker-compose向下

怎么解决的，我也是修改了app/services/中的fofaClient.py文件，但是不行

**Comment by 1c3z** [comment]
更新了2.5.1 ，已修改了域名。
