### ISSUE TITLE
系统异常

### ISSUE THREAD

**Issue by Jim2g** [TophantTechnology/ARL#293]
![image](https://user-images.githubusercontent.com/52034185/154791390-2e43c9be-4561-443d-b45f-c744e030c05c.png)
![image](https://user-images.githubusercontent.com/52034185/154791444-06e585bd-4dd1-4438-9bd6-d4802c6f6541.png)

**Comment by 1c3z** [comment]
下发的是什么内容呀？

**Comment by Jim2g** [comment]
> 下发的是什么内容呀？

就是我添加任务以及添加子域名和资产范围都会爆这个错，我之前设置了一下钉钉然后就这样了

**Comment by 1c3z** [comment]
稳定复现？ 可以把内容复制下么?

**Comment by Jim2g** [comment]
> 稳定复现？ 可以把内容复制下么?

例如我这样
![image](https://user-images.githubusercontent.com/52034185/154886395-2110c44c-db77-41f6-b36b-f35348ee0ea8.png)
ch
查看日志
![image](https://user-images.githubusercontent.com/52034185/154886413-6e49c4fe-df97-425f-b0cd-426e7e752427.png)

**Comment by 1c3z** [comment]
我本地试了下没有问题。 

应该是Forbidden_domains没改好。  

![image](https://user-images.githubusercontent.com/9052484/154887080-09cd550d-1e1e-42c1-b3f9-537a43ab067b.png)

**Comment by Jim2g** [comment]
嗷嗷好的谢谢

> 我本地试了下没有问题。
> 
> 应该是Forbidden_domains没改好。
> 
> ![image](https://user-images.githubusercontent.com/9052484/154887080-09cd550d-1e1e-42c1-b3f9-537a43ab067b.png)

好的的确是这个问题，已经解决了谢谢

**Comment by 1c3z** [comment]
更新了2.5.1 ， 这个地方如果是None的话会跳过。
