### ISSUE TITLE
自定义证书 教程

### ISSUE THREAD

**Issue by Ran-Xing** [TophantTechnology/ARL#296]
## 存储证书
将 自定义的证书复制到 arl 目录，并命名为 `arl_web.crt` `arl_web.key`
![image](https://user-images.githubusercontent.com/73819467/155485470-527f7ad6-1426-41ab-80a2-13ff046094d7.png)

## 更新 nginx 信息
```diff
- ssl_dhparam /etc/ssl/certs/dhparam.pem;
+ # ssl_dhparam /etc/ssl/certs/dhparam.pem;
```

## 更新 `docker-compose.yml` 
```diff
+        entrypoint: ["sh", "-c", "nginx; wait-for-it.sh mongodb:27017; gunicorn -b 0.0.0.0:5003 app.main:arl_app -w 3 --access-logfile arl_web.log"]
-        # entrypoint: ["sh", "-c", "gen_crt.sh; nginx; wait-for-it.sh mongodb:27017; gunicorn -b 0.0.0.0:5003 app.main:arl_app -w 3 --access-logfile arl_web.log"]
```

## 检查错误

```bash
docker-compose up -d web
docker logs arl_web
```

![image](https://user-images.githubusercontent.com/73819467/155485824-80ad604d-db30-4d51-a23b-5110bc068f57.png)
![image](https://user-images.githubusercontent.com/73819467/155485887-78523550-dd21-4319-945e-fcaa12606dd4.png)

**Comment by XRSec** [comment]
这里得说一下官方，启动命令这里搞了一个 `gen_crt.sh` 又没说明，我说怎么老是覆盖我自己的key，还有一个问题，「如果有多级证书 需要使用最后一级的服务证书」

**Comment by XRSec** [comment]
置顶谢谢，我怕自己忘了
