### ISSUE TITLE
我希望新增一个批量导入站点的功能

### ISSUE THREAD

**Issue by ThestaRY7** [TophantTechnology/ARL#297]
资产分组-某某资产-添加站点 旁边可以再做一个功能点，批量添加。

我看了一下 添加站点的功能说明
![image](https://user-images.githubusercontent.com/48352738/155828944-bf54d3c5-02bd-42ac-9074-33c0c89dc35f.png)

我觉得非常好啊，那我就可以从别的地方获取资产，比如subfinder-httpx，获取到站点之后，再批量导入到灯塔里，可视化UI操作更舒服。

只是缺少一个批量添加站点的功能，我发现可以批量添加子域名，但我这边有些站点是http://baidu.com:9090/这种站点，就不能单纯的添加子域名了。

望采纳，谢谢！

**Comment by leslieWangg** [comment]
+10086

**Comment by ratt3n** [comment]
+10086

**Comment by 1c3z** [comment]
已添加。
