### ISSUE TITLE
资产信息展示优化，域名探测信息查看时太过麻烦

### ISSUE THREAD

**Issue by fool-sir** [TophantTechnology/ARL#298]
根据策略下发任务时，批量域名资产的探测结果只能一条一条的展示(针对服务识别等信息)，资产搜索中只能展示站点、子域名、IP信息，无法展示更多信息，需要手动去任务中一条一条查看，非常不友好

**Comment by 1c3z** [comment]
点击一个任务，把task_id 参数删除即可，

或者直接访问这个路径就
/taskList/taskDetail

#243 
#256
