### ISSUE TITLE
config-docker.yaml代理问题

### ISSUE THREAD

**Issue by onEpAth936** [TophantTechnology/ARL#299]
![59a6d249e20b414134f821510b28bdb](https://user-images.githubusercontent.com/63861767/156022589-7d48bfdb-a03b-4785-bf75-59fd37b30ecc.png)
本地挂着clash可用的外国节点
config-docker.yaml文件配置了本地代理
docker内使用不了本地代理
![e3fee8f22e5c6ab241ba8194bd43413](https://user-images.githubusercontent.com/63861767/156023726-d588b09d-b966-46f0-8976-69368bd12b49.png)
是只支持使用外部代理池吗？还是我姿势不对？

**Comment by 1c3z** [comment]
1. 这个IP地址不能填127.0.0.1, 这里填127.0.0.1就是指docker 容器本身的本地循环地址了， 要填宿主机的一个IP 地址，
2. clash默认应该是只监听再本地的，要改下监听IP， 
3. 测试配置是否生效
```
docker-compose exec worker bash
python3.6 -m test.test_proxy_url
```

**Comment by onEpAth936** [comment]
> 1. 这个IP地址不能填127.0.0.1, 这里填127.0.0.1就是指docker 容器本身的本地循环地址了， 要填宿主机的一个IP 地址，
> 2. clash默认应该是只监听再本地的，要改下监听IP，
> 3. 测试配置是否正常工作
> 
> ```
> docker-compose exec worker bash
> python3.6 -m test.test_proxy_url
> ```
> 
> 4. 重启生效

请教一下
config-docker.yaml文件填写宿主机ip
![eb32fbf4b9f49841015ec7d4158f894](https://user-images.githubusercontent.com/63861767/156137412-901106df-6a52-4714-9ee5-6f7d28265aa3.png)
clash监听地址填写docker的IP吗？
![da7928d7726694c7e699e3ec745c592](https://user-images.githubusercontent.com/63861767/156138449-b35673c6-4bff-43d8-98a1-528081f0ccce.png)

**Comment by onEpAth936** [comment]
网卡信息如下
![279f3411fbc929fa17629ab669a836d](https://user-images.githubusercontent.com/63861767/156138684-208f3ba1-4259-429e-a1d5-bfe49bd1bc99.png)

**Comment by 1c3z** [comment]
10.0.20.4 和172.17.0.1 以及 172.18.0.1 都是可以的。 @onEpAth936

**Comment by onEpAth936** [comment]
> 10.0.20.4 和172.17.0.1 以及 172.18.0.1 都是可以的。 @onEpAth936

感谢
