### ISSUE TITLE
arl_worker还没有公开吗

### ISSUE THREAD

**Issue by UnnameBao** [TophantTechnology/ARL#3]
ERROR: pull access denied for arl_worker, repository does not exist or may require 'docker login': denied: requested access to the resource is denied

**Comment by NAXG** [comment]
同问

**Comment by 1c3z** [comment]
镜像公开了呢。
docker pull tophant/arl
  
然后修改`docker/docker-compose.yml` 中services web image 和 services worker image 对应的镜像地址。

**Comment by UnnameBao** [comment]
搞定了 大佬说的两个位置改成 image: tophant/arl:latest就行了

**Comment by 1c3z** [comment]
已经修改为默认镜像了，不用再手工修改了。
