### ISSUE TITLE
一些建议 finger字段可以手动编辑

### ISSUE THREAD

**Issue by Oldman19** [TophantTechnology/ARL#30]
希望finger字段可以手动编辑，有的时候某个站的指纹没有探测全，就可以手动添加上，方便以后查找

**Comment by 1c3z** [comment]
这个后期资产管理功能加了会添加这个功能。

**Comment by 1c3z** [comment]
资产分组功能已添加，请查看

https://github.com/TophantTechnology/ARL/releases/tag/v2.2

**Comment by 1c3z** [comment]
已更新，可以打标签了。
