### ISSUE TITLE
您好，关于树莓派docker启动问题？

### ISSUE THREAD

**Issue by chachajx** [TophantTechnology/ARL#300]
您好，我使用树莓派--Raspberry Pi OS 64 位进行部署，arl_scheduler、arl_web、arl_worker三个节点在启动后一直处于restarting状态，系统中无SELINUX，请问是什么原因导致的，万分感谢。
![image](https://user-images.githubusercontent.com/65016180/156152557-eabf844d-81a7-4106-bcec-bf31ac6e2316.png)

arl_worker执行docker logs 的日志如下：

![image](https://user-images.githubusercontent.com/65016180/156152743-ab7dfd5e-9efe-4f3e-a38d-8e134a6483e6.png)
arl_web执行docker logs日志如下：

![image](https://user-images.githubusercontent.com/65016180/156152844-36ca2051-d42a-4072-b3d0-4bd590ab22f7.png)
arl_schedule执行docker logs日志如下：

![image](https://user-images.githubusercontent.com/65016180/156152981-6cbc1417-92cd-41ed-8211-5a6d9850beab.png)

**Comment by 1c3z** [comment]
@chachajx 
https://itsdangerous.palletsprojects.com/en/2.1.x/changes
itsdangerous 新版本把 json 模块删除了， 我把版本固定在了 2.0.1
镜像更新了，可以重新试下
