### ISSUE TITLE
资产去重与计划任务问题

### ISSUE THREAD

**Issue by AnYi-Sec** [TophantTechnology/ARL#303]
1.资产去重方面，当添加一个任务后，扫描结果为b.baidu.com ，但是计划任务里的资产执行扫描后，结果在资产搜索功能中会显示出2条b.baidu.com 这个是否可以进行资产去重，仅保留最新扫描结果或者？

2.计划任务功能是否可以在添加计划任务时，输入目标框处可以选择资产分组处的资产？ 这样不用再二次导入资产了，不然还要手动复制粘贴一遍。

3.资产搜索功能中是否可以添加一个删除资产的功能？ 很多脏数据没办法删除就很难搞，站点 子域名 IP三个都希望可以加上删除资产的功能。

**Comment by 1c3z** [comment]
1. 目前任务和任务直接结果是独立的
2. 这个可以考虑实现下
3. 任务里面是可以删除部分数据的，可以用资产分组统一管理


#236 
#213
#146

**Comment by AnYi-Sec** [comment]
还有一个问题就是 资产分组的时候，我导入了大概3w条子域名 现在资产分组页面能打开，但是数据一直出不来  应该是数据太多的问题 等了20分钟还没有出来  使用什么命令可以把添加的分组删除掉

**Comment by 1c3z** [comment]
> 还有一个问题就是 资产分组的时候，我导入了大概3w条子域名 现在资产分组页面能打开，但是数据一直出不来 应该是数据太多的问题 等了20分钟还没有出来 使用什么命令可以把添加的分组删除掉

0.一起性导入太多子域名可能页面超时了，
2. 资产分组管理页面可以删除资产分组。
