### ISSUE TITLE
你好，请问扫描资产的时候提示timeout of 12000ms exceeded(用docker搭建的)

### ISSUE THREAD

**Issue by zi0n8** [TophantTechnology/ARL#304]
系统:macbook m1 docker搭建
<img width="511" alt="截屏2022-03-03 下午1 08 42" src="https://user-images.githubusercontent.com/65099918/156500264-d6b146c7-ccf9-4a6d-b229-1e7531467a81.png">

**Comment by 1c3z** [comment]
执行下面的，看看日志，
```
docker-compose logs -f  --tail=10
tail -f *.log
```
