### ISSUE TITLE
指纹无法添加

### ISSUE THREAD

**Issue by timwhitez** [TophantTechnology/ARL#305]
指纹中带有等于号无法添加
例如：
![image](https://user-images.githubusercontent.com/36320909/156508844-5cf22be9-79db-4814-951c-2b341f03c852.png)

**Comment by 1c3z** [comment]
是个BUG .

**Comment by 1c3z** [comment]
指纹规则已强化，欢迎更新v2.6.1 ， issue 先关闭。
