### ISSUE TITLE
资产IP组问题

### ISSUE THREAD

**Issue by 5icorgi** [TophantTechnology/ARL#306]
任务里支持这么写1.1.1.1-10
[![bUl4c8.jpg](https://s4.ax1x.com/2022/03/04/bUl4c8.jpg)](https://imgtu.com/i/bUl4c8)
但资产分组里不支持这么写
[![bUlDXD.jpg](https://s4.ax1x.com/2022/03/04/bUlDXD.jpg)](https://imgtu.com/i/bUlDXD)
另外对于扫描IP的任务能否也同步至资产分组里的IP资产

**Comment by 1c3z** [comment]
是的，不支持，目前只支持添加站点，用- 这种方式判断是不是在范围内比较麻烦。 
IP 资产分组里的数据可以通过添加资产监控任务来实现添加的效果。
