### ISSUE TITLE
访问400报错

### ISSUE THREAD

**Issue by stcs3475** [TophantTechnology/ARL#307]
400 Bad Request
The plain HTTP request was sent to HTTPS port
nginx/1.20.1

**Comment by scylamb** [comment]
me too
<html>
<head><title>400 The plain HTTP request was sent to HTTPS port</title></head>
<body>
<center><h1>400 Bad Request</h1></center>
<center>The plain HTTP request was sent to HTTPS port</center>
<hr><center>nginx/1.20.1</center>
</body>
</html>
view-source:http://0.0.0.0:5003/

**Comment by geekmc** [comment]
解决了吗

**Comment by stcs3475** [comment]
解决了，用https访问

万人往 ***@***.***> 于 2022年3月6日周日 14:40写道：

**Comment by stcs3475** [comment]
解决了，用https访问

scylamb ***@***.***> 于 2022年3月4日周五 22:32写道：
