### ISSUE TITLE
有没有关于ARL服务器迁移的方案

### ISSUE THREAD

**Issue by NowSec1** [TophantTechnology/ARL#309]

**Comment by 1c3z** [comment]
1. 应该就备份下数据就可以

参考https://github.com/TophantTechnology/ARL/wiki/ARL-2.3-%E6%96%B0%E6%B7%BB%E5%8A%A0%E5%8A%9F%E8%83%BD%E8%AF%A6%E7%BB%86%E8%AF%B4%E6%98%8E#%E4%BA%8C-%E6%95%B0%E6%8D%AE%E5%A4%87%E4%BB%BD%E5%92%8C%E8%BF%81%E7%A7%BB%E5%88%B0%E5%AD%98%E5%82%A8%E5%8D%B7

2. 还有可以只把子域名导出来，然后再在新服务器上导入，看你需求。
