### ISSUE TITLE
建议指纹信息支持逻辑与

### ISSUE THREAD

**Issue by ssrsec** [TophantTechnology/ARL#312]
建议指纹信息支持逻辑与

或者干脆就让用户自定义表达式，如：

body="xxx" && title="xxx"

**Comment by heikanet** [comment]
只有逻辑或的话，感觉误报太大了。光单个的话，又不精准

**Comment by 1c3z** [comment]
这个我们后面后期在优化下。

**Comment by 1c3z** [comment]
指纹规则已强化，欢迎更新v2.6.1 ， issue 先关闭。
