### ISSUE TITLE
建议指纹支持重复判断

### ISSUE THREAD

**Issue by heikanet** [TophantTechnology/ARL#313]
建议指纹支持重复判断，比如说我本地更新后，批量上传后检测一下重复。

或者干脆来一个一键清空功能。这样发现大量指纹需要优化的时候，本地直接弄好一起上传了

**Comment by 1c3z** [comment]
1. 添加的时候会有重复判断的
2. 现在有个批量删除的功能，右下角可以选择500条/页 （就是麻烦了一点）
