### ISSUE TITLE
建议可以批量同步任务数据到资产分组

### ISSUE THREAD

**Issue by heikanet** [TophantTechnology/ARL#315]

**Comment by 1c3z** [comment]
1. 这个批量同步有点麻烦，目标资产分组是不知道的，需要根据当前任务的域名进行筛选
2. 可以自定义策略，通过资产组配置进行关联，然后再通过当前策略下发任务，任务结束后，新增的域名资产就会同步过去
![image](https://user-images.githubusercontent.com/9052484/158522427-e1114498-406b-4f98-84c8-11a53fe2a741.png)
