### ISSUE TITLE
关于站点识别的疑问

### ISSUE THREAD

**Issue by testa010** [TophantTechnology/ARL#319]
ARL如何发现诸如https://example.com:8081格式的站点？我目前想到的有两种方式，或者还有其它？

方法一：逐个遍历example.com:port1、example.com:port2、example.com:port3
方法二：先对example.com做ip解析，再对ip做端口扫描，最后遍历example.com:truePort1、example.com:truePort2

如果是第二种方式，那么ARL的策略 “CDN IP 跳过端口扫描” 会不会影响站点识别结果的准确性？

**Comment by 1c3z** [comment]
1.第二种方式

这里假定了CDN的80,443 端口是开放的。

**Comment by testa010** [comment]
所以如果ip解析结果是cdn，那么除了80和443以外的端口不会被扫描，诸如https://example.com:8081格式的站点将不会被识别到？

**Comment by 1c3z** [comment]
IP 是 CDN的话，一般不存在https://example.com:8081 吧。

**Comment by testa010** [comment]
存在的，我随便搜了2个

http://warship-game3.sgamez.com.srip.net:8004/
http://ftp.luckscout.com:8880/

<img width="776" alt="Snipaste_20-43" src="https://user-images.githubusercontent.com/64741288/160407290-798614b1-0c45-4c32-89f8-bfba6c554ce5.png">
<img width="796" alt="Snipaste_21-07" src="https://user-images.githubusercontent.com/64741288/160407457-edc3471a-e729-491b-828b-74c2b6a288d8.png">

ARL认定该ip是cdn，因此即便我使用了全端口模式，也无法收集全目标域名的站点。

另外，当前的CDN判断方式并不能很准确的得出结论，感觉意义不是很大；建议对 “CDN IP 跳过端口扫描” 的策略添加一个开关，让用户手动选择是否开启这种模式。
