### ISSUE TITLE
扫资产速度慢

### ISSUE THREAD

**Issue by tiantop** [TophantTechnology/ARL#321]
灯塔我是配置在服务器中，服务器是高性能配置，但是不知道为什么扫资产速度太慢。例如扫描IP段为：1.1.1.1/22。大约用了四个小时，服务器CPU和带宽几乎没跑起来
![819F6E5F-7117-46ED-9967-551332A916BA](https://user-images.githubusercontent.com/31196759/160813337-7822c7ba-a025-4d77-9b96-dd2d9eb12527.jpeg)

**Comment by cloud-jie** [comment]
我来补充一些具体的东西，当然，我感觉速度快是有代价的，比如误报和漏报。
反正都是云服务器，倒是感觉可以牺牲速度换取准确率（反正睡大觉，快慢也感觉不出来）
以下是我的情况，
云服务器配置 ：4核4G，docker部署ARL，手工配置近600万子域名字典，1万敏感文件字典。
![uTools_1648745077325](https://user-images.githubusercontent.com/63632785/161113034-0be94e64-0020-479f-ae2a-f6c504cd4f52.png)
下图是运行时的服务器资源使用情况（同时多个任务，但可进行参考）
![uTools_1648746180793](https://user-images.githubusercontent.com/63632785/161114100-461a1e46-1b5c-43a9-8127-f80ee43ef2f4.png)

**Comment by 1c3z** [comment]
@tiantop 

大部分时间都是文件泄露模块占用。 

可以收工尝试改下这个配置项。

https://github.com/TophantTechnology/ARL/blob/master/app/services/fileLeak.py#L18

**Comment by tiantop** [comment]
> @tiantop
> 
> 大部分时间都是文件泄露模块占用。
> 
> 可以手工尝试改下这个配置项。
> 
> https://github.com/TophantTechnology/ARL/blob/master/app/services/fileLeak.py#L18

已改用xunfeng

**Comment by cloud-jie** [comment]
> 

像我这种情况的，师傅能否给我一些建议，提升准确率或者速度的

**Comment by cloud-jie** [comment]
> 我来补充一些具体的东西，当然，我感觉速度快是有代价的，比如误报和漏报。 反正都是云服务器，倒是感觉可以牺牲速度换取准确率（反正睡大觉，快慢也感觉不出来） 以下是我的情况， 云服务器配置 ：4核4G，docker部署ARL，手工配置近600万子域名字典，1万敏感文件字典。 ![uTools_1648745077325](https://user-images.githubusercontent.com/63632785/161113034-0be94e64-0020-479f-ae2a-f6c504cd4f52.png) 下图是运行时的服务器资源使用情况（同时多个任务，但可进行参考） ![uTools_1648746180793](https://user-images.githubusercontent.com/63632785/161114100-461a1e46-1b5c-43a9-8127-f80ee43ef2f4.png)

像我这种情况的，师傅能否给我一些建议，提升准确率或者速度的。
晚上睡觉的时间加上白天上班的时间，时间太充裕了。

**Comment by 1c3z** [comment]
@cloud-jie 
1.现在资产发现工具太卷了，对于一般的SRC自动手段发现的结果并不会给人带来太多的惊喜。
2.另一方面自动化手段也不能做到100%完全发现，需要人工参与，这个每家SRC的情况是不一样的，需要自己积累。 
3. 可以考虑对特定的资产进行长时间的监控，等待厂商更新发现新的资产，这个效果怎么样每家SRC的情况也是不一样的。
4. 可以对特定SRC收集一些对于自动化某方面手段缺失的场景，进行人工+半自动化去补充， 这个效果怎么样每家SRC的情况也是不一样的。
