### ISSUE TITLE
ajax报Network Error问题

### ISSUE THREAD

**Issue by thinkoaa** [TophantTechnology/ARL#323]
edge浏览器浏览时，页面放一会就报这个错，ajax请求没发出去，后台服务没有问题，是证书的问题？还是l浏览器什么问题，请问可以强制让http访问吗?
![image](https://user-images.githubusercontent.com/65639454/161392602-e4ef65ad-6447-40a2-b133-6bd01766cee0.png)
![image](https://user-images.githubusercontent.com/65639454/161392633-50706ea2-0462-4359-a094-2ee8024de3e1.png)

**Comment by 1c3z** [comment]
应该是挂上了代理。
