### ISSUE TITLE
建议在资产分组添加一个手动添加子域名黑名单功能

### ISSUE THREAD

**Issue by heisefangkuai** [TophantTechnology/ARL#324]
在SRC漏洞挖掘的时候有些子域名SRC是不收的，如果去爬了这些子域名反而还会被封IP，比如限定了（*.aa.domain.com）不允许爬虫访问，如果爬虫访问了这些子域名，ARL就会被封禁，导致爬了半天一点东西都没有，所以能不能添加个手动添加子域名黑名单的功能呢！

**Comment by 1c3z** [comment]
可以加这里面 

https://github.com/TophantTechnology/ARL/blob/master/app/dicts/blackdomain.txt
