### ISSUE TITLE
Worker exited prematurely: signal 9 (SIGKILL).

### ISSUE THREAD

**Issue by cloud-jie** [TophantTechnology/ARL#325]
报错了，怎么办？
服务器资源占用情况
![image](https://user-images.githubusercontent.com/63632785/161932005-17efab75-e505-4e47-a695-d268b7b28b71.png)
日志
[arl_worker.log](https://github.com/TophantTechnology/ARL/files/8425074/arl_worker.log)

**Comment by cloud-jie** [comment]
> 报错了，怎么办？ 
![image](https://user-images.githubusercontent.com/63632785/161932578-fbd45f6e-916d-4e5b-9ebd-feeb9b2123b4.png)
服务器资源占用情况 
![image](https://user-images.githubusercontent.com/63632785/161932005-17efab75-e505-4e47-a695-d268b7b28b71.png) 
日志 
[arl_worker.log](https://github.com/TophantTechnology/ARL/files/8425074/arl_worker.log)

**Comment by cloud-jie** [comment]
![image](https://user-images.githubusercontent.com/63632785/161932956-ce76a679-ebba-4e94-a5a7-2fad581fbb07.png)
时间有点长了

**Comment by 1c3z** [comment]
看了下日志加载了500万的字典，应该是内存不够导致被kill了，
可以执行dmesg -T 找找相关错误日志。

**Comment by cloud-jie** [comment]
> 看了下日志加载了500万的字典，应该是内存不够导致被kill了，
> 可以执行dmesg -T 找找相关错误日志。
![image](https://user-images.githubusercontent.com/63632785/162119790-70eb6735-9b87-4902-94c2-f0009ac01474.png)
多谢师傅
