### ISSUE TITLE
任务详情 批量删除问题

### ISSUE THREAD

**Issue by FanMagnum** [TophantTechnology/ARL#327]
任务详情页面
![image](https://user-images.githubusercontent.com/45158597/162601830-e660ec00-69e3-4064-898c-4b296c2b7c96.png)
所有分页批量删除调用的都是/api/site/delete/接口
有些分页实现了批量删除接口，但并没有被调用
有些分页并没有实现批量删除接口(服务、url信息、服务(python)、C段)

**Comment by 1c3z** [comment]
是这样的，有些没有实现。
