### ISSUE TITLE
站点识别和资产监控的问题

### ISSUE THREAD

**Issue by ipsecc** [TophantTechnology/ARL#329]
感谢作者提供的工具，在使用过程中，我发现了几点有疑问的地方
1）站点识别有时会将目录名显示出来，但实际上我后续导入awvs等扫描器时，只需要http(s)://test.com:port的格式，感觉可以优化一下。
![image](https://user-images.githubusercontent.com/40918024/162620813-ea6cb36c-8861-4829-868e-ce8d619d4b3b.png)

2）资产监控限制了最少间隔6小时，这个限制能取消掉让用户自住选择吗？
![image](https://user-images.githubusercontent.com/40918024/162620895-c9440ae0-9e2a-49fc-90c9-bcee909f8983.png)

3）使用host碰撞模式时，我如何知道哪些域名是通过host碰撞获得的，有没有批量导出host碰撞获得的域名的方法？

**Comment by 1c3z** [comment]
1. 这个带目录是第一次访问时302的，然后又访问了一次。 

2. 这个前端和后端都有限制的。 我一般都是24小时。 
3.  Host碰撞功能的结果在风险里显示。 

https://github.com/TophantTechnology/ARL/wiki/ARL-2.5-%E6%96%B0%E6%B7%BB%E5%8A%A0%E5%8A%9F%E8%83%BD%E8%AF%A6%E7%BB%86%E8%AF%B4%E6%98%8E#host-%E7%A2%B0%E6%92%9E%E6%A3%80%E6%B5%8B%E5%8A%9F%E8%83%BD

**Comment by ipsecc** [comment]
@1c3z 
可以取消掉最小间隔的限制吗，有时会有更短的周期执行需求

**Comment by 1c3z** [comment]
@ipsecc 

更短的话就新建个策略，在策略中关联上该资产组，然后用这个策略多下几次任务。  
有更多结果的话在资产分组中可以看到新增的资产。
