### ISSUE TITLE
自己会停掉是什么情况

### ISSUE THREAD

**Issue by ByCold** [TophantTechnology/ARL#33]
![image](https://user-images.githubusercontent.com/49861259/96536825-770c0380-12c7-11eb-87e3-e0fe1c1cd990.png)

很多都是端口扫描后就是0了

**Comment by ByCold** [comment]
https://s1.ax1x.com/2020/10/20/BS1TfO.png

**Comment by ByCold** [comment]
> ![image](https://user-images.githubusercontent.com/49861259/96536825-770c0380-12c7-11eb-87e3-e0fe1c1cd990.png)
> 
> 很多都是端口扫描后就是0了

**Comment by 1c3z** [comment]
这个是端口扫描没有结果，后面的流程没有来源数据了。也可以关闭端口扫描，会根据80,443自动发现站点。 
对公网IP请关闭服务识别和操作系统识别，端口选top 100或者top 1000。

**Comment by ByCold** [comment]
> 这个是端口扫描没有结果，后面的流程没有来源数据了。也可以关闭端口扫描，会根据80,443自动发现站点。
> 对公网IP请关闭服务识别和操作系统识别，端口选top 100或者top 1000。

是服务器配置问题嘛，选择全端口扫描会出现这个情况

**Comment by 1c3z** [comment]
@ByCold 目标服务器可能存在防护措施。

**Comment by ByCold** [comment]
> @ByCold 目标服务器可能存在防护措施。

添加Fofa IP查询会一直卡在Fofa那是什么情况

**Comment by 1c3z** [comment]
@ByCold 可以看下 tail -f arl_worker.log , 应该是在扫端口。

**Comment by 1c3z** [comment]
端口扫描功能已优化，可以再测试下

https://github.com/TophantTechnology/ARL/releases/tag/v2.2
