### ISSUE TITLE
我通过对比rengine、oneforall跟arl获取的站点数量发现arl少了很多

### ISSUE THREAD

**Issue by thisismyusernameHH** [TophantTechnology/ARL#330]
我通过对比rengine、oneforall跟arl获取的站点数量发现arl少了很多，是否考虑可以像rengine一样，加入oneforall,subfinder等发现资产的手段，毕竟发现资产的范围是非常重要的。

**Comment by 1c3z** [comment]
这个数据差别有点大，能否分析下数据。

1.看看标题有没有重复的很多，
2.一个域名开放很多端口的数据
3.域名泛解析的问题。

**Comment by thisismyusernameHH** [comment]
hello 作者， rengine跑的存活站点太多了，我只能把所有存活站点导出来,然后我去重了一下,发现还存活50多w个站点,就算在除2,去掉80跟443内容一样的站点也还有25w站点,这是在相同的资产域名下我跑了一周多后的结果。

我也用oneforall跟arl对比了一下,一般情况下还是oneforall收集的资产比较多。

![image](https://user-images.githubusercontent.com/32993375/162922369-35e1d7c1-8fa4-405f-9962-7c4deed42da4.png)

![image](https://user-images.githubusercontent.com/32993375/162922707-2a34ac57-b351-4156-bbb8-29188ae726be.png)

**Comment by thisismyusernameHH** [comment]
@testa010  可以的,可以自定义的

**Comment by testa010** [comment]
@thisismyusernameHH 请问具体是怎么配置的？我把端口设置成top-1000后，端口扫描正常，但在urls - all endpoints里没有除80、443之外的站点

**Comment by 1c3z** [comment]
> hello 作者， rengine跑的存活站点太多了，我只能把所有存活站点导出来,然后我去重了一下,发现还存活50多w个站点,就算在除2,去掉80跟443内容一样的站点也还有25w站点,这是在相同的资产域名下我跑了一周多后的结果。
> 
> 我也用oneforall跟arl对比了一下,一般情况下还是oneforall收集的资产比较多。
> 
> ![image](https://user-images.githubusercontent.com/32993375/162922369-35e1d7c1-8fa4-405f-9962-7c4deed42da4.png)
> 
> ![image](https://user-images.githubusercontent.com/32993375/162922707-2a34ac57-b351-4156-bbb8-29188ae726be.png)


<img width="1371" alt="image" src="https://user-images.githubusercontent.com/9052484/163306332-875a2e88-c01c-48d8-9963-a86c17486932.png">
给的截图我就看到了3个重复的站点，先分析下数据吧

**Comment by thisismyusernameHH** [comment]
哈喽作者, 我处理过数据arl还是少了很多,我感觉可以引入 subfinder,oneforall等来收集资产,arl还是挺好用的,谢谢作者的工具。

**Comment by thisismyusernameHH** [comment]
> @thisismyusernameHH 请问具体是怎么配置的？我把端口设置成top-1000后，端口扫描正常，但在urls - all endpoints里没有除80、443之外的站点

我也没改过配置,但是应该是能自定义端口的

**Comment by 1c3z** [comment]
@thisismyusernameHH 

1.这里不会盲目添加，否则会有好多重复的步骤，需要找到关键的地方。
2.也可以把其他工具发现的手动添加进去
3.另外不知道测试的时候riskiq  API token有没有单独配置。

**Comment by stupid-h4er** [comment]
> @thisismyusernameHH
> 
> 1.这里不会盲目添加，否则会有好多重复的步骤，需要找到关键的地方。 2.也可以把其他工具发现的手动添加进去 3.另外不知道测试的时候riskiq API token有没有单独配置。

请问如何手动添加子域名

**Comment by 1c3z** [comment]
@stupid-h4er 

需要新建资产分组

<img width="1069" alt="image" src="https://user-images.githubusercontent.com/9052484/190311995-c8580292-61a1-44f7-ac5c-7eb33706ab5d.png">
