### ISSUE TITLE
显示错误

### ISSUE THREAD

**Issue by hunter-00** [TophantTechnology/ARL#333]
![image](https://user-images.githubusercontent.com/67944000/163308052-3da3a1c6-0ca2-4c7d-9cde-43f9f7ab41d8.png)

**Comment by 1c3z** [comment]
啥错误？

**Comment by hunter-00** [comment]
![image](https://user-images.githubusercontent.com/67944000/163758329-161bbfa3-8534-4097-a8c6-7555cab3e64d.png)
为什么是分开的

**Comment by 1c3z** [comment]
比较诡异，强刷看下，
或者用别的浏览器打开看下。
