### ISSUE TITLE
风险巡航类型计划任务不会被调度任务

### ISSUE THREAD

**Issue by FanMagnum** [TophantTechnology/ARL#334]
![image](https://user-images.githubusercontent.com/45158597/163961242-166eba21-9dd3-4784-b376-d61b3bc64d2c.png)
根据源码风险巡航类型计划任务根本不会被调度，请问这里是判断有误，还是就是这样设计的，如果就是不能调度前端为什么没有屏蔽掉？

**Comment by 1c3z** [comment]
这里应该是个BUG， 感谢反馈，我们在下个版本修复。

**Comment by 1c3z** [comment]
已修复。
