### ISSUE TITLE
已经配置github的token，但添加任务后状态为error

### ISSUE THREAD

**Issue by farleyking** [TophantTechnology/ARL#336]
已经配置github的token，永久不不过期，
但添加任务后状态为error
![image](https://user-images.githubusercontent.com/103157009/164676054-94d95a3b-3330-44a0-a099-ef85487bb725.png)

**Comment by 1c3z** [comment]
看看日志。

**Comment by Lc1ee** [comment]
![image](https://user-images.githubusercontent.com/94050918/217471909-f3634034-632f-4314-a89d-d851d7a5c76b.png)
我也是会报错

**Comment by Lc1ee** [comment]
![image](https://user-images.githubusercontent.com/94050918/217473074-3146d92a-4c93-48d3-aa2d-063021bcba96.png)
![image](https://user-images.githubusercontent.com/94050918/217473197-3d760993-b8f6-4715-b007-82dfcccee299.png)
tian'jia'l
添加了以后但是说token为空

**Comment by 1c3z** [comment]
要重启下容器。
