### ISSUE TITLE
安装部署问题

### ISSUE THREAD

**Issue by devsecops-SRC** [TophantTechnology/ARL#34]

**Comment by devsecops-SRC** [comment]
由于官方政策更新请前往maxmind 注册下载GeoLite2-City.tar.gz，GeoLite2-ASN.tar.gz 解压。
在config.yaml中配置好相关路径

这个怎么做  确定是config.yaml 这个在哪个目录下

**Comment by 1c3z** [comment]
源码安装？可以参考这个 https://www.cnblogs.com/zhengjim/archive/2004/01/13/13678257.html
