### ISSUE TITLE
任务管理界面展示BUG

### ISSUE THREAD

**Issue by s0nd9r** [TophantTechnology/ARL#342]
问题描述：2k分辨率下，浏览器全屏，任务管理界面，操作栏按钮展示超出表格范围，导致翻页按钮被覆盖，无法点击
复现环境1：笔记本2560*1660分辨率下，foxfire全屏状态下显示正常
![image](https://user-images.githubusercontent.com/31186294/167529801-f78c8f69-f4b6-41b2-8a01-a37ad1141845.png)
复现环境2：台式电脑2560*1440分辨率下，foxfire非全屏状态下显示正常
![image](https://user-images.githubusercontent.com/31186294/167530113-1143d504-77c7-41cc-8e3d-592cff9d88b1.png)
foxfire全屏状态下出现问题
![image](https://user-images.githubusercontent.com/31186294/167530350-f580bdad-e6ba-4370-bfbd-0fb348ae8c16.png)
已测试其他浏览器（edge，搜狗）均出现此问题

**Comment by 1c3z** [comment]
感谢反馈。 

屏幕比较大的情况下可以放大显示来缓解下，

**Comment by 1c3z** [comment]
已修复
