### ISSUE TITLE
批量删除监控无效任务

### ISSUE THREAD

**Issue by kaking4** [TophantTechnology/ARL#344]
![image](https://user-images.githubusercontent.com/64488830/168419096-bea7d1a2-0c8e-4d62-9ec9-54aa3191c7dc.png)
是否可添加个筛选项删除此类没有结果的监控任务

**Comment by 1c3z** [comment]
我刚测试了下，可以批量删除的。刷新再试试？ 

监控任务可以直接删除的，数据在资产分组里有保存的。

**Comment by 1c3z** [comment]
已更新，可以筛选。
