### ISSUE TITLE
建议优化指纹识别

### ISSUE THREAD

**Issue by light-Life** [TophantTechnology/ARL#345]
经过：通过测试，域名网站一但挂上cdn就无法识别cms，猜测通过ip识别cms
验证：以wordpress为例去fofa搜几个站用多地ping验证是否有cdn，分别放入arl看看能否识别
指纹：body="wp-admin"

验证成功的师傅留个言呀让开发看见，我的验证方法有问题也请提醒我一下，谢谢。

**Comment by 1c3z** [comment]
<img width="919" alt="image" src="https://user-images.githubusercontent.com/9052484/169948399-1a94267b-ac21-4b5d-af47-bf9f8a9674c8.png">

刚测试了下是可以识别wordpress的

<img width="1330" alt="image" src="https://user-images.githubusercontent.com/9052484/169948551-024773c3-39fc-4e41-936d-e2fb6314eda3.png">
