### ISSUE TITLE
无法使用钉钉推送

### ISSUE THREAD

**Issue by shijiajiao** [TophantTechnology/ARL#346]
邮箱推送可以正常使用
报错信息
<img width="1259" alt="QQ20220521-113409@2x" src="https://user-images.githubusercontent.com/105959204/169633893-f3bedda2-9ff0-4846-ad96-1afb2555af3f.png">

TOKEN无任何问题已通过python进行测试

**Comment by 1c3z** [comment]
<img width="274" alt="image" src="https://user-images.githubusercontent.com/9052484/169947713-3f9cbd63-6342-4b77-ba93-6f74fa9cbd3a.png">

可能token配错位置了。 
配置文件名和内容麻烦再检查下。
