### ISSUE TITLE
资产监控的站点结果有遗漏

### ISSUE THREAD

**Issue by testa010** [TophantTechnology/ARL#349]
ARL在资产监控时仅扫描新增加的子域名
有的子域名在第1个监控周期开了443端口，第2个监控周期开了443和8080端口，这种情况8080端口的web站点就被遗漏了。

另外ARL的子域名收集接口有点少，作者是否考虑引入更多的接口呢？
比如securitytrails就很不错，虽然免费账号每月查询额度只有50次，但可以做成subfinder那样一个接口配置多个账号的key去弥补。

**Comment by 1c3z** [comment]
1. 域名的资产监控，主要是为了新增域名来考虑的，没有到端口这个维度，
2. 其他接口在规划中
