### ISSUE TITLE
希望后期可以通过多个代理的方式进行资产发现。

### ISSUE THREAD

**Issue by Oldman19** [TophantTechnology/ARL#35]
在使用此工具的过程中，我发现有的时候会被目标给办掉，无法访问目标，如果可以添加一个自动获取免费代理节点，通过这些节点去资产发现，会更全面。而且你们也可以再增加一个专属代理节点，付费内种，咳咳。

**Comment by 1c3z** [comment]
域名发现过程一般不受目标防火墙影响，HTTP相关的流量后期可以考虑添加这个功能，不过这个优先级比较低。

**Comment by Oldman19** [comment]
> 域名发现过程一般不受目标防火墙影响，HTTP相关的流量后期可以考虑添加这个功能，不过这个优先级比较低。

行吧，你们内个文件泄露还挺好用的，靠他赚了好几千了，就是如果有代理的话，可能会更好

**Comment by Oldman19** [comment]
> 域名发现过程一般不受目标防火墙影响，HTTP相关的流量后期可以考虑添加这个功能，不过这个优先级比较低。

突然想到如果可以将文件泄露单拎，可以我们导入一个包含域名的文件，然后使用文件泄露功能去扫描就很完美

**Comment by 1c3z** [comment]
@Oldman19  后面可以整理出一个单独可运行的py出来。

**Comment by 1c3z** [comment]
可以单独运行的文件泄露已经发布了。。

https://github.com/TophantTechnology/ARL/blob/master/arl_tool/fileleakV2.py
