### ISSUE TITLE
离线升级ARL

### ISSUE THREAD

**Issue by ashou-1997** [TophantTechnology/ARL#351]
请问如何在保证之前扫描的数据不丢失情况下在内网中进行离线升级ARL。(docker环境搭建的)

**Comment by 1c3z** [comment]
1先更新这个文件，https://github.com/TophantTechnology/ARL/blob/master/docker/docker-compose.yml
有细微的改动。 

2. 再找一台可以联网的机器先进行pull ，然后在save 将镜像保存到文件，再到内网主机进行load 操作  （关键）


https://docs.docker.com/engine/reference/commandline/save/
https://docs.docker.com/engine/reference/commandline/load/
