### ISSUE TITLE
2.5.1 fofa连接异常

### ISSUE THREAD

**Issue by xxfire111** [TophantTechnology/ARL#353]
![image](https://user-images.githubusercontent.com/50986622/171167209-d35e9039-719b-47a8-b706-41885dfe9c58.png)
![image](https://user-images.githubusercontent.com/50986622/171167348-3daeb453-0fe0-4aeb-bace-d2298506c44e.png)

**Comment by xxfire111** [comment]
重启也一样，好奇怪。

**Comment by xxfire111** [comment]
重启还是一样，奇怪了。

**Comment by 1c3z** [comment]
版本没更新。
