### ISSUE TITLE
域名字典换成了100w的，但是跑了5个小时还是没结果。

### ISSUE THREAD

**Issue by yange6666** [TophantTechnology/ARL#355]
服务器配置L：1g2h的
域名字典换成了100w的，但是跑了5个小时还是没结果。
设置了3000分钟超时。
如何查看程序是否正常运。

**Comment by 1c3z** [comment]
大概率内存不足。

可以看下面文档的最后面。
https://github.com/TophantTechnology/ARL/wiki/Docker-%E7%8E%AF%E5%A2%83%E5%AE%89%E8%A3%85-ARL#faq

**Comment by ketchup1995** [comment]
> 大概率内存不足。
> 
> 可以看下面文档的最后面。 https://github.com/TophantTechnology/ARL/wiki/Docker-%E7%8E%AF%E5%A2%83%E5%AE%89%E8%A3%85-ARL#faq

我4G的内存跑了一个星期都一直卡在domain_brute状态

**Comment by 1c3z** [comment]
> > 大概率内存不足。
> > 可以看下面文档的最后面。 https://github.com/TophantTechnology/ARL/wiki/Docker-%E7%8E%AF%E5%A2%83%E5%AE%89%E8%A3%85-ARL#faq
> 
> 我4G的内存跑了一个星期都一直卡在domain_brute状态

应该任务异常了，可以看上面的文档手动排查下原因。
