### ISSUE TITLE
钉钉为何无法推送

### ISSUE THREAD

**Issue by HiIK-666** [TophantTechnology/ARL#356]
![屏幕截图 2022-06-24 122738](https://user-images.githubusercontent.com/69377487/175462268-a6aa1900-5fe5-4091-852a-31cd153c92ee.png)

**Comment by 1c3z** [comment]
看看是不是哪里写错了

![image](https://user-images.githubusercontent.com/9052484/175529419-f287a058-12dc-4733-a6bb-e588ddd183f3.png)
