### ISSUE TITLE
无法正常扫描  "message": "invalid credentials"

### ISSUE THREAD

**Issue by undefined72** [TophantTechnology/ARL#359]
当开启域名解析扫描时候  出现了访问

HTTPSConnectionPool(host='api.passivetotal.org', port=443): Max retries exceeded with url: /v2/account/quota (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f4119fc53c8>: Failed to establish a new connection: [Errno -2] Name or service not known',))

单独访问  api.passivetotal.org  提示  invalid credentials

**Comment by 1c3z** [comment]
1. 当时访问DNS解析出错了
2. 单独访问 api.passivetotal.org 提示 invalid credentials 这个是正常的。

**Comment by undefined72** [comment]
好比域名扫描时候  获取不到子域名了 就是i提示这个问题

**Comment by undefined72** [comment]
怎么解决这个问题

**Comment by 1c3z** [comment]
是要解决什么问题？ 
我刚看了下默认的 passivetotal api  没有配额了，自己注册配置一个吧 。
