### ISSUE TITLE
建议可以使用自己的字典进行爆破子域名或

### ISSUE THREAD

**Issue by Oldman19** [TophantTechnology/ARL#36]
建议可以使用自己的字典进行爆破子域名或者建议你们使用字典：https://gist.github.com/jhaddix/86a06c5dc309d08580a018c66354a056，与你们的字典进行去重合并。这才算大字典。

**Comment by 1c3z** [comment]
可以执行下面的命令将自己的字典覆盖掉内置字典。

`docker cp mydict.txt arl_worker:/code/app/dicts/domain_2w.txt`

**Comment by 1c3z** [comment]
自定义字典功能已添加

https://github.com/TophantTechnology/ARL/blob/master/docker/config-docker.yaml#L40
