### ISSUE TITLE
请问灯塔如何添加钉钉推送资产新增的消息。

### ISSUE THREAD

**Issue by ViewOweiV** [TophantTechnology/ARL#363]

**Comment by 1212lxw** [comment]
https://github.com/TophantTechnology/ARL/wiki/ARL-2.3-%E6%96%B0%E6%B7%BB%E5%8A%A0%E5%8A%9F%E8%83%BD%E8%AF%A6%E7%BB%86%E8%AF%B4%E6%98%8E#%E6%B7%BB%E5%8A%A0%E6%9C%BA%E5%99%A8%E4%BA%BA

已经找到配置文档链接谢谢。
