### ISSUE TITLE
新版还是fofa api异常

### ISSUE THREAD

**Issue by chenchen-cpu** [TophantTechnology/ARL#365]
新版还是fofa api异常，docker-compose.yml是默认的fofa.info，为什么还是会错误了
![image](https://user-images.githubusercontent.com/73785589/185341076-6f39469d-ecb3-419d-b4e3-a94b09e3c95c.png)

**Comment by 1c3z** [comment]
1. 是改的docker/config-docker.yaml文件么
2. 是不是ARL版本没有升级？

**Comment by moosee19** [comment]
大佬，我也有同样的问题，设置确认是对的，在阿里云上建的arl

**Comment by 1c3z** [comment]
@moosee19 
这个2.5.1 才可以设置。

**Comment by wanzhoukaoyu** [comment]
我也遇到这个问题
<img width="1439" alt="image" src="https://user-images.githubusercontent.com/22409317/215774748-f2e71bbf-5281-48c2-9ef2-a182d741dffb.png">

**Comment by 1c3z** [comment]
@wanzhoukaoyu  根据错误是DNS解析错误。

看在宿主机上和容器内看能不能ping通
