### ISSUE TITLE
不能批量删除么。。。

### ISSUE THREAD

**Issue by zhegege** [TophantTechnology/ARL#37]
一个一个删除我快死了

**Comment by rebootORZ** [comment]
me too...

**Comment by 1c3z** [comment]
@zhegege  @rebootORZ  

目前前端还不支持，不过可以 Burp 启动

**Comment by root0er** [comment]
@1c3z 前端是用了什么框架吗，感觉很清爽

**Comment by 1c3z** [comment]
@root0er 
用的Vue.js 和 Ant Design

**Comment by 1c3z** [comment]
批量删除功能已添加，请查看

https://github.com/TophantTechnology/ARL/releases/tag/v2.2
