### ISSUE TITLE
替换了敏感字典后扫描开始不了了

### ISSUE THREAD

**Issue by wqe0520** [TophantTechnology/ARL#370]
添加上去的所有站状态都是 domain_brute 替换了DNS 重启了容器也是这个状态

**Comment by 1c3z** [comment]
看下异常任务排查那里，看有什么错误信息么。 

https://github.com/TophantTechnology/ARL/wiki/Docker-%E7%8E%AF%E5%A2%83%E5%AE%89%E8%A3%85-ARL
