### ISSUE TITLE
老哥，为什么我在使用过程中经常碰到site_capture，这块就停止不动了呢？等了好久还是显示site_capture这个，请问这是什么情况？

### ISSUE THREAD

**Issue by OnlycAreYou666** [TophantTechnology/ARL#371]
老哥，为什么我在使用过程中经常碰到site_capture，这块就停止不动了呢？等了好久还是显示site_capture这个，请问这是什么情况？

**Comment by 1c3z** [comment]
这个是网站截图。这块比较费CPU 和内存。

**Comment by NaTsUk0** [comment]
我也是，就是卡在这里就不动了，但是也不是所有的任务都会卡，很玄学，我的服务器4h8g的喔，也会卡住？
[2023-02-21 15:04:21,770: INFO/ForkPoolWorker-3] app.celerytask.arl_task[aa56c799-b944-4245-90b9-16d06d0c0646]: start screen shot 568
这条以后任务就不往下走了，明明截图全都截完了呀

**Comment by 1c3z** [comment]
@NaTsUk0 

日志应该是在截图。可能有点慢。
可以看看 phantomjs   还在运行么，隔一段时间看看 后面的URL看有没有变
```
ps axf | grep  phantomjs  
```

**Comment by NaTsUk0** [comment]
但是它今天卡了好几个小时，有点离谱，就五百多个图而已啊
