### ISSUE TITLE
源码安装后运行都正常，但是页面是404

### ISSUE THREAD

**Issue by safebaseline** [TophantTechnology/ARL#373]
![image](https://user-images.githubusercontent.com/38883009/184524349-b3a54602-96bd-4523-af2f-6814f0552cc2.png)
![image](https://user-images.githubusercontent.com/38883009/184524359-65918651-494f-4280-a78e-673f47329489.png)
不得其解

**Comment by 1c3z** [comment]
5013 是api的接口 。

要访问nginx 的5003 端口。 https://ip:5003/

**Comment by safebaseline** [comment]
那是我的5003端口没起来，我看了netstat 没有5003 但是arl-web Status是正常的


------------------ 原始邮件 ------------------
发件人: 1c3z ***@***.***&gt;
发送时间: 2022年8月17日 15:50
收件人: TophantTechnology/ARL ***@***.***&gt;
抄送: safebaseline ***@***.***&gt;, Author ***@***.***&gt;
主题: Re: [TophantTechnology/ARL] 源码安装后运行都正常，但是页面是404 (Issue #373)





 
5013 是api的接口 。
 
要访问nginx 的5003 端口。 https://ip:5003/

**Comment by 1c3z** [comment]
@safebaseline 
看下nginx 是不是没启动来。

**Comment by bashrc21** [comment]
怎么源码安装 能给个教程么

**Comment by 1c3z** [comment]
@bashrc21 

可以跑这个脚本看看。 

https://github.com/TophantTechnology/ARL/blob/master/misc/setup-arl.sh

**Comment by safebaseline** [comment]
已收到
