### ISSUE TITLE
菜鸟求助，添加任务报错timeout of 12000ms exceeded

### ISSUE THREAD

**Issue by QtidusQ** [TophantTechnology/ARL#38]
如题，今天添加任务的时候提示timeout of 12000ms exceeded，刷新页面，看到任务已添加，但是状态为waiting 等待，且无法删除，现在任务列表里一堆状态为waiting 的，均无法删除

**Comment by QtidusQ** [comment]
对了，删除状态为waiting的任务是，提示not found celery_id。。。这是哪里错了

**Comment by 1c3z** [comment]
不要慌， 可能是worker没起来。

docker-compose ps 看下
![image](https://user-images.githubusercontent.com/9052484/97834190-2d350b80-1d12-11eb-8a06-4fadbe71fc48.png)

**Comment by QtidusQ** [comment]
谢谢解答，我用了最笨的方法，重新安装
