### ISSUE TITLE
 Restarting

### ISSUE THREAD

**Issue by Party-A** [TophantTechnology/ARL#380]
为什么重启docker的时候总有两个docker是 Restarting 状态，而且怎样都重启不了，查看日志显示consumer: Cannot connect to amqp://arl:**@rabbitmq:5672/arlv2host: failed to resolve broker hostname.
但是rabbitmq那个容器又是正常运行的
![image](https://user-images.githubusercontent.com/112337223/187341103-20b8f0a1-ca46-42c8-a117-5f176d87a875.png)
![image](https://user-images.githubusercontent.com/112337223/187341160-947804c5-6b97-48e1-9575-1ff1e4c1e7a1.png)

**Comment by 1c3z** [comment]
是什么操作系统呀？

麻烦提供下下面的输出，我看能复现下么。 
`docker version` 
`
docker-compose logs -f  --tail=10
`

`
tail -f *.log
`

**Comment by Party-A** [comment]
我在新系统上拉又行了，莫名其妙的很，centos7 的

从 Windows 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>发送

发件人: ***@***.***>
发送时间: 2022年8月31日 16:57
收件人: ***@***.***>
抄送: ***@***.***>; ***@***.***>
主题: Re: [TophantTechnology/ARL] Restarting (Issue #380)


是什么操作系统呀？

麻烦提供下下面的输出，我看能复现下么。
docker version
docker-compose logs -f --tail=10

tail -f *.log

―

**Comment by 1c3z** [comment]
旧的系统，原先的没有down导致的么？

**Comment by Party-A** [comment]
估计是，我再测试测试几次看看

从 Windows 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>发送

发件人: ***@***.***>
发送时间: 2022年8月31日 16:59
收件人: ***@***.***>
抄送: ***@***.***>; ***@***.***>
主题: Re: [TophantTechnology/ARL] Restarting (Issue #380)


旧的系统，原先的没有down导致的么？

―
