### ISSUE TITLE
docker compose 安装镜像没有更新

### ISSUE THREAD

**Issue by Pa55w0rd** [TophantTechnology/ARL#381]
docker compose 安装镜像没有更新

**Comment by 1c3z** [comment]
这样执行看下呢。
```
docker-compose down  
docker rmi tophant/arl:latest
docker-compose pull
docekr-compose up -d
```

**Comment by Betsy0** [comment]
应该是你的镜像没有push上去，导致我们pull的还是原来2.5版本的镜像

**Comment by 1c3z** [comment]
是有更新的
https://hub.docker.com/layers/tophant/arl/latest/images/sha256-322c295262cb40a95ce6a84815de8695ee6b8a09d9d1a382483b2973281022bc?context=explore

是不是配置了镜像源？

**Comment by Pa55w0rd** [comment]
> l的

使用的阿里云的镜像源
