### ISSUE TITLE
任务长时间停留在 “site_spider”,怎么优化？

### ISSUE THREAD

**Issue by 5279314** [TophantTechnology/ARL#382]
任务长时间停留在 “site_spider” 

Worker 日志
```
[2022-09-01 02:49:00,284: ERROR/MainProcess] Process 'ForkPoolWorker-1' pid:52 exited with 'signal 9 (SIGKILL)'
[2022-09-01 02:49:00,567: ERROR/MainProcess] Task handler raised error: WorkerLostError('Worker exited prematurely: signal 9 (SIGKILL).',)
billiard.exceptions.WorkerLostError: Worker exited prematurely: signal 9 (SIGKILL).
```

**dmesg -T**
```
[Thu Sep  1 02:48:07 2022] Out of memory: Kill process 19079 (celery) score 659 or sacrifice child
[Thu Sep  1 02:48:07 2022] Killed process 19079 (celery), UID 0, total-vm:3849996kB, anon-rss:2555040kB, file-rss:0kB, shmem-rss:0kB
```

服务器为腾讯云轻量级：`4核4g`。有什么优化方法嘛？

**Comment by 1c3z** [comment]
1. OOM了，跑的什么站点呀。 
2. 另外服务器上还跑了什么其他系统么。

**Comment by 5279314** [comment]
> 1. OOM了，跑的什么站点呀。
> 2. 另外服务器上还跑了什么其他系统么。

跑的`某度`站点，其他就跑了hexo博客，外加twikoo评论系统，通过云监控发现内存在十几分钟就突然上来了
![image](https://user-images.githubusercontent.com/27267683/188048588-0d8d40f2-a231-40c6-b09a-cc9275639ce8.png)

**Comment by 5279314** [comment]
![image](https://user-images.githubusercontent.com/27267683/188048799-f2b22c24-dd05-41ba-860c-8a28e25ff090.png)
![image](https://user-images.githubusercontent.com/27267683/188048835-c8e9a3eb-d096-4d0b-bb21-8fb07506be71.png)

**Comment by 1c3z** [comment]
Worker 日志, 能提供下么？ 我分析下看看。

**Comment by 5279314** [comment]
Worker 日志
[arl_worker.log](https://github.com/TophantTechnology/ARL/files/9475106/arl_worker.log)

**Comment by 5279314** [comment]
> Worker 日志, 能提供下么？ 我分析下看看。 可能是某个站点比较特别吧。

那太感谢了
[arl_worker.log](https://github.com/TophantTechnology/ARL/files/9475106/arl_worker.log)
