### ISSUE TITLE
nuclei根本无法发现漏洞

### ISSUE THREAD

**Issue by purple-WL** [TophantTechnology/ARL#383]
在容器单独使用nuclei可以发现漏洞，从ARL web端勾选nuclei后无法发现漏洞

**Comment by li-baige** [comment]
+1

**Comment by purple-WL** [comment]
XMD，去nuclei_scan.py文件里修改下命令，默认的命令参数有问题

**Comment by 1c3z** [comment]
加这些过滤只是为了过滤一些没什么大用的的检出，另外还可以减少一些请求。

**Comment by purple-WL** [comment]
是的

**Comment by testa010** [comment]
@purple-WL 哥们可以详细说下吗，是改arl_worker里的文件还是改哪里？

**Comment by purple-WL** [comment]
> @purple-WL 哥们可以详细说下吗，是改arl_worker里的文件还是改哪里？

我是源码部署，修改的"/opt/ARL/app/services/nuclei_scan.py"

**Comment by testa010** [comment]
@1c3z 试了下改docker里的文件没有成功，请问docker部署如何修改？源码部署目前只支持centos

**Comment by 1c3z** [comment]
@testa010 

改worker 里的代码就行，然后再restart。
