### ISSUE TITLE
端口扫描卡住了

### ISSUE THREAD

**Issue by li-baige** [TophantTechnology/ARL#384]
十几个小时了等了，只输出了子域名，一直显示端口扫描，重启docker，重启ARL都没有反应

**Comment by li-baige** [comment]
然后刷新发现，Network Error错误，心态崩了，我是部署在Centos服务器上面的

**Comment by 1c3z** [comment]
1.全端口扫描么？
2.执行docker ps 看容器是不是自动重启了。

**Comment by phpmac** [comment]
docker下没有其他解决方案吗，或者提高内存？

**Comment by 1c3z** [comment]
> docker下没有其他解决方案吗，或者提高内存？

@phpmac 

进worker 容器把这个400改小一点看看，
https://github.com/TophantTechnology/ARL/blob/master/app/services/portScan.py#L38
