### ISSUE TITLE
域名爆破卡死

### ISSUE THREAD

**Issue by purple-WL** [TophantTechnology/ARL#386]
看日志发现在域名爆破阶段因为顶级域名存在安全防护，爆破出了1万多个子域名，导致在dns识别的时候时间过长导致卡死，换了一个域名看日志是爆破100多个子域名，这个是正常的，问下域名爆破具体实现的代码在哪个里呢

**Comment by 1c3z** [comment]
https://github.com/TophantTechnology/ARL/blob/master/app/services/massdns.py
