### ISSUE TITLE
数据迁移后任务重启相关

### ISSUE THREAD

**Issue by Mr-xn** [TophantTechnology/ARL#392]
从2.5 迁移升级到最新 2.5.2之后，之前waiting状态或者进行一半的任务没有任何动作了，直接停了，但是点击停止，重启是可以正常完成的，是否可以有一键停止-重启所有特地状态的任务

**Comment by 1c3z** [comment]
任务管理界面可以批量停止和删除。然后再重新下任务了。

**Comment by Mr-xn** [comment]
我知道可以批量停止和删除，没有批量重启 加一个或许更好，不然批量停止后 想再次重启这些因为迁移停止的任务就只能一个个点后面的重启
