### ISSUE TITLE
某些未完成的配置项，导致整个任务停滞在那个状态

### ISSUE THREAD

**Issue by Mr-xn** [TophantTechnology/ARL#397]
比如在执行 file_leak 的时候超长时间后，任务被自动终止后，前端显示的是终止时的状态，这个没毛病，但是 统计 以及 任务详情里顶部的 tab 栏是空的，数据实际上是有的，这个算 bug 么？可以不可以修
- 实际上的数据（已完成项）
<img width="184" alt="image" src="https://user-images.githubusercontent.com/18260135/189530589-95bb2d22-968d-49eb-966e-b460f3a950ef.png">
- 任务列表
<img width="437" alt="image" src="https://user-images.githubusercontent.com/18260135/189530463-6bb4f161-aac2-492b-bd9c-1dccb8f38804.png">
-任务详情
<img width="1086" alt="image" src="https://user-images.githubusercontent.com/18260135/189530519-670fa60a-5ae4-4e22-a975-3a50fac60681.png">

**Comment by 1c3z** [comment]
统计信息是在所有的步骤结束后才统计的， 这个任务还没执行完，所以统计步骤还没执行。 

看这边提供的信息数据量比较少 file_leak 应该不会挂的。 

`dmesg -T`
worker.log 看有什么错误信息么。
