### ISSUE TITLE
更新版本后无法登录

### ISSUE THREAD

**Issue by Hhhnee** [TophantTechnology/ARL#400]
![图片](https://user-images.githubusercontent.com/84834363/190167011-de2dc937-72bd-4d69-9118-aa171cdd41ff.png)
如题，且用一台新VPS安装新版本后(尝试默认密码admin/arlpass)也无法登录显示超时1200

**Comment by 1c3z** [comment]
@Hhhnee 解决了么？

有错误日志么， 这个应该是mongo没连上。

**Comment by Hhhnee** [comment]
work和scheduler不断重启，报错说的是rabbitmq连不上


后面不断修改config-docker.yaml文件，发现不能修改QUERY_PLUGIN:


只要一修改就会导致连接不上。
目前又有了新问题，fofa key 邮箱都是正确的情况下，无法调用api



&nbsp;



***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年9月15日(星期四) 上午10:52
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [TophantTechnology/ARL] 更新版本后无法登录 (Issue #400)





 
@Hhhnee 解决了么？
 
有错误日志么， 这个应该是mongo没连上。

**Comment by 1c3z** [comment]
先down，再up -d 观察看看。 

实在不行重新安装看下。
#389

**Comment by Hhhnee** [comment]
已重装，无效

 

&nbsp; EMAIL: ***@***.***"
&nbsp; KEY: "8dd6513bc664c8ca76aa389a7e644b0e"
应该不存在是我fofa问题吧？！


&nbsp;



***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年9月15日(星期四) 中午11:02
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [TophantTechnology/ARL] 更新版本后无法登录 (Issue #400)





 
先down，再up -d 观察看看。
 
实在不行重新安装看下。
 #389

**Comment by Hhhnee** [comment]
目前已解决，配置文件修改还是得在linux里面用vim改才不会被转换编码。
之前是直接从windows上传了配置文件到服务器的，导致不是lf格式
改过来就OK了
