### ISSUE TITLE
登录后不能操作，一直显示超时

### ISSUE THREAD

**Issue by yingk77** [TophantTechnology/ARL#401]
![image](https://user-images.githubusercontent.com/85225750/190575896-82cd3afc-fb5d-407b-b56a-458118d51123.png)

**Comment by yuhaoze002** [comment]
同问  我也是这个问题  555~

**Comment by 1c3z** [comment]
@yuhaoze002 
@yingk77 

搞好了么

执行下面的看有没有异常。
```
docker-compose ps 
docker-compose logs -f  --tail=10
tail -f *.log
```

实在不行重装，并检测是否设置了镜像源
#389

**Comment by yingk77** [comment]
最近重装了服务器，换了ubuntu系统，好了
