### ISSUE TITLE
restarting

### ISSUE THREAD

**Issue by niuTT** [TophantTechnology/ARL#406]
<img width="1044" alt="企业微信截图_1fdd8289-55dd-4431-8cb1-b284dcf3a788" src="https://user-images.githubusercontent.com/41726904/191692933-b8682ed9-6fda-4264-8452-b1de11b123bc.png">
环境：macbook pro M1 MAX 
Docker Engine v20.10.17

**Comment by niuTT** [comment]
<img width="1028" alt="企业微信截图_820cb409-9778-4ee2-8609-1d862b406094" src="https://user-images.githubusercontent.com/41726904/191693590-199e84ee-c371-4fcf-ae87-24ecaf9fe3c3.png">
作者在么，帮忙看看 =. =

**Comment by 1c3z** [comment]
抱歉，ARM 的镜像有问题

可以用 amd64 的机器缓解下。

#391

**Comment by T3nk0** [comment]
> 抱歉，ARM 的成员有问题
> 
> 可以用 d64 的机器减轻 amd64。
> 
> #391

请问arm镜像多久能更新呢

**Comment by duzhaofa** [comment]
可单独启动ARL_WEB容器，进入后重新安装markupsafe和jinja2
python3 -m pip install markupsafe==2.0.1
python3 -m pip install jinja2==2.11.3

**Comment by 1c3z** [comment]
@T3nk0 
@niuTT 

ARM镜像已经更新了
