### ISSUE TITLE
想提个资产打标备注的建议

### ISSUE THREAD

**Issue by apsry** [TophantTechnology/ARL#408]
就是对于一个域名资产，除了这些外
<img width="1180" alt="image" src="https://user-images.githubusercontent.com/55017061/192678897-54e0fdda-50fc-4446-a1c0-986546aa62de.png">

希望能添加一个对资产自己做标记备注的功能，就是比如一个OA系统，可能指纹扫描没有扫描出来，但是我可以手动添加备注，或者对于一个域名我可以添加备注，备注这是我的核心系统或者是OA系统，然后再添加搜索功能，这样我就可以通过搜索来筛选我想要的系统，可能从甲方的纬度来说，如果能够有这个功能，会舒服很多，而白帽子也可以当一个OA出现漏洞时，他能从资产库快速搜索出这个OA的资产，希望得到采纳。

**Comment by apsry** [comment]
这样会让自己对于一个域名资产有了很大的可操作性，备注可以备注很多东西，包括上面说的指纹，核心系统，或者这个系统是干什么的，或者扫描到的一些目录等等

**Comment by 1c3z** [comment]
现在可以对站点进行打标签。 
![image](https://user-images.githubusercontent.com/9052484/194689767-5ccc3087-71e7-4b95-a33b-0ff547ef33c9.png)
