### ISSUE TITLE
arl_web无法启动

### ISSUE THREAD

**Issue by duzhaofa** [TophantTechnology/ARL#411]
cannot import name ‘Markup‘ from ‘jinja2‘
cannot import name 'soft_unicode' from 'markupsafe'
最新版的这两包里面已经无法正常导入，需要重新安装并指定版本，可行版本：
jinja2==2.11.3
markupsafe==2.0.1

**Comment by duzhaofa** [comment]
机器为树莓派4B
Linux kali 5.15.44-Re4son-v8l+ #1 SMP PREEMPT Debian kali-pi (2022-07-03) aarch64 GNU/Linux

**Comment by 1c3z** [comment]
感谢，ARL镜像已经更新了。
