### ISSUE TITLE
docker compose up -d启动项目异常

### ISSUE THREAD

**Issue by yanliang941225** [TophantTechnology/ARL#416]
启动命令：
docker compose up -d

日志：
arl_web        | [2022-10-10 14:55:28 +0800] [1820] [INFO] Worker exiting (pid: 1820)
arl_web        | Parse config.yaml error 'RISKIQ'
arl_web        | [2022-10-10 14:55:28 +0800] [1826] [INFO] Booting worker with pid: 1826
arl_web        | [2022-10-10 14:55:28 +0800] [1822] [INFO] Worker exiting (pid: 1822)
arl_web        | Parse config.yaml error 'RISKIQ'
arl_web        | [2022-10-10 14:55:28 +0800] [1828] [INFO] Booting worker with pid: 1828
arl_web        | [2022-10-10 14:55:28 +0800] [1825] [INFO] Worker exiting (pid: 1825)
arl_web        | Parse config.yaml error 'RISKIQ'
arl_web        | [2022-10-10 14:55:28 +0800] [1831] [INFO] Booting worker with pid: 1831
arl_web        | Parse config.yaml error 'RISKIQ'
arl_web        | [2022-10-10 14:55:28 +0800] [1826] [INFO] Worker exiting (pid: 1826)

进程状态：
[root@localhost docker]# docker compose ps
NAME                COMMAND                  SERVICE             STATUS              PORTS
arl_mongodb         "docker-entrypoint.s…"   mongodb             running             27017/tcp
arl_rabbitmq        "docker-entrypoint.s…"   rabbitmq            running             4369/tcp, 5671-5672/tcp, 15671-15672/tcp, 15691-15692/tcp, 25672/tcp
arl_scheduler       "sh -c 'wait-for-it.…"   scheduler           restarting          
arl_web             "sh -c 'gen_crt.sh; …"   web                 running             0.0.0.0:5003->443/tcp, :::5003->443/tcp
arl_worker          "sh -c 'wait-for-it.…"   worker              restarting

**Comment by 1c3z** [comment]
是不是忘记pull 了
是不是配置镜像源了

#379

**Comment by WaNg-21** [comment]
我也是这个问题，重装成2.5.1没问题，装2.5.2版本arl_scheduler和arl_worker老是在Restarting
![image](https://user-images.githubusercontent.com/57787511/196373489-ccedc401-844a-4bf0-ae19-1a818cb08565.png)

**Comment by 1c3z** [comment]
@WaNg-21  
可以看下arl_worker.log 的日志。 

镜像应该没更新。 

#389

**Comment by nicetomeetnode** [comment]
我也是这个问题，看来确实是容器有问题

**Comment by nicetomeetnode** [comment]
换了几台服务器，都有问题。centos7的。都是相同问题，也换了2.5.1，也是报这个错

**Comment by WaNg-21** [comment]
> @WaNg-21 可以看下arl_worker.log 的日志。
> 
> 镜像应该没更新。
> 
> #389

可以尝试下从2.5.1直接更新配置升级到2.5.2试试？我是2核2G服务器不知道有没有影响

**Comment by asdlijinquan** [comment]
我也是这个错误，一直解决不了

**Comment by asdlijinquan** [comment]
> 换了几台服务器，都有问题。centos7的。都是相同问题，也换了2.5.1，也是报这个错

你解决这个错误了吗

**Comment by hack2012** [comment]
可能的原因是新版本中将RISKIQ的配置重新校验了，导致异常，可以尝试使用上一个版本的配置。config-docker.yaml

**Comment by lingjiexun** [comment]
> > 可能的原因是新版本中将RISKIQ的配置重新校验了，导致异常，可以尝试使用上一个版本的配置。config-docker.yaml
> 
> 是的，国内镜像配置文件可能不对，添上RISKIQ可以了

2.5.4怎么办的，我的也这样，是4g2核，一直重启
