### ISSUE TITLE
Request failed with status code 502

### ISSUE THREAD

**Issue by D3ngX1n** [TophantTechnology/ARL#42]
docker部署完成之后，页面返回502
![image](https://user-images.githubusercontent.com/45932886/98351430-a22c7c00-2057-11eb-8966-8a7c49b24479.png)

**Comment by 1c3z** [comment]
可以了不？
我抽空在kali上复现下。

**Comment by D3ngX1n** [comment]
不可以

**Comment by 1c3z** [comment]
![image](https://user-images.githubusercontent.com/9052484/98958145-f0042100-253c-11eb-88d1-da23f9e2c2f2.png)
 
![image](https://user-images.githubusercontent.com/9052484/98958442-3d808e00-253d-11eb-82ce-925a1b6c9f4b.png)

试了下没有发现问题。
是安装的docker-ce？ 不是的话可以参考这个官方教程 https://docs.docker.com/engine/install/


@D3ngX1n

**Comment by coffeehb** [comment]
其实。。真正的原因在于端口上面吧。我猜楼主和我一样，尝试修改部署的端口5003，而没有修改完整。问题出在docker镜像         image: tophant/arl:latest，里面nginx.conf 写死了5003端口，所以要修改部署为其他的端口需要修改:
1、docker-compose.yml 里面web的参数（5003）,同时新增：volumes的配置，替换镜像里面的nginx.conf
```
- ./nginx.conf:/etc/nginx/nginx.conf
```
2、nginx.conf 里面的proxy_pass地址
3、docker-compose up -d 
搞定～

**Comment by FebLocke** [comment]
在k8s里面装的，这个5003端口确实不用改，改了就报502错
