### ISSUE TITLE
风险那一栏没有用，检测不出来，比如redis漏洞

### ISSUE THREAD

**Issue by phpmac** [TophantTechnology/ARL#420]
风险那一栏没有用，检测不出来，比如redis漏洞

**Comment by HoldOnToYourHeart** [comment]
加1，遇到同样的问题，测试了好几个未授权，都无法检测

**Comment by 1c3z** [comment]
@phpmac  @HoldOnToYourHeart 

我刚测试了下redis未授权这个确实没检出。

**Comment by 1c3z** [comment]
> 加1，遇到同样的问题，测试了好几个未授权，都无法检测

也是redis么？ 其他我测了下是可以的。 

![image](https://user-images.githubusercontent.com/9052484/196588058-e584d559-f1b8-40ed-822c-b6c5d851966e.png)

不过redis在服务里面有识别出来。 
![image](https://user-images.githubusercontent.com/9052484/196588151-80b5233d-44f2-4878-bc07-e6c70710e6e7.png)

**Comment by 1c3z** [comment]
> > @phpmac @HoldOnToYourHeart
> > 我刚测试了下redis未授权这个确实没检出。
> 
> 不止redis还有mongodb的未授权也没有检测出来。

是的，Memcached ，ZooKeeper  未授权访问 应该也是检测不出来的。 其他HTTP协议的没有问题。

**Comment by 1c3z** [comment]
> > @phpmac @HoldOnToYourHeart
> > 我刚测试了下redis未授权这个确实没检出。
> 
> 不止redis还有mongodb的未授权也没有检测出来。

是的，下个版本打算修下。

**Comment by 1c3z** [comment]
v2.5.3 已修复。
