### ISSUE TITLE
arm镜像站点识别没有执行

### ISSUE THREAD

**Issue by gdft2112** [TophantTechnology/ARL#421]
我这边有个问题，我苹果m1处理器拉的arm镜像跑了下发现站点识别没有运行，我还特地找我朋友测了下，也是一样的。
![image](https://user-images.githubusercontent.com/37747628/196591731-9614f255-de1d-44eb-9dc0-bdde36e64312.png)

**Comment by 1c3z** [comment]
这样下发看看
![image](https://user-images.githubusercontent.com/9052484/196593404-4701a8a7-73c7-4f13-ad5c-2079dc8f35b4.png)

这是我这边在arm 服务器上的结果。 
![image](https://user-images.githubusercontent.com/9052484/196593476-7ace3de5-f747-4d74-bb43-843446c18d8d.png)

可以看看arl_worker.log 日志内容
```
tail -n 20  arl_worker.log
```
![image](https://user-images.githubusercontent.com/9052484/196593755-1c2b395c-8521-4332-9a8e-06ce9e412214.png)

**Comment by gdft2112** [comment]
end start check http 0  不知道为什么，我是直接拉直接跑的，你可以找人用m1的mac试试看。
<img width="1439" alt="image" src="https://user-images.githubusercontent.com/37747628/196600507-c06b7138-8dee-4cc8-b75f-ecec9deb2f2a.png">

**Comment by 1c3z** [comment]
看来确实有点问题，我找时间分析下。

**Comment by 1c3z** [comment]
@gdft2112 

我试了下没有问题呢，是不是当时网络问题。 

<img width="760" alt="image" src="https://user-images.githubusercontent.com/9052484/197329058-06e006f4-d03d-46c1-96ed-0d585b59cf81.png">

<img width="1369" alt="image" src="https://user-images.githubusercontent.com/9052484/197329140-a097c456-6cb9-46a2-b928-880bbd9b0a24.png">

<img width="797" alt="image" src="https://user-images.githubusercontent.com/9052484/197329337-86cdb6fa-eab5-4974-8187-2b356401067e.png">

**Comment by gdft2112** [comment]
重新再拉了一次居然好了。。
<img width="1233" alt="image" src="https://user-images.githubusercontent.com/37747628/197474105-270f8112-c938-4dd7-875d-65fa3104c014.png">
可能是网络的乌龙事件，还是谢谢你的帮助
