### ISSUE TITLE
风险任务报错，卡在截图那步，求答疑

### ISSUE THREAD

**Issue by geek-zuizui** [TophantTechnology/ARL#422]
下发风险任务就会报这个错
![image](https://user-images.githubusercontent.com/105526408/196663894-8963478a-8562-4ab4-b3f2-438b7d9d2a52.png)

随后到网站截图功能
![image](https://user-images.githubusercontent.com/105526408/196665181-c63b07c4-a1aa-4136-b9f9-a5ac05b84bdf.png)

到网站截图时就会无限报这个错，点进去查看截图已经全部截完了
![image](https://user-images.githubusercontent.com/105526408/196664157-ccb0ba03-1ddd-46d7-ab0a-e50e741ee0be.png)

服务器centos7   4c8g
docker version
![image](https://user-images.githubusercontent.com/105526408/196664593-bb7d95bd-5765-4ef0-9377-3aa0226cf685.png)

相关操作
就添加过指纹，改了子域名字典和文件泄露字典

**Comment by geek-zuizui** [comment]
补充 ： 我之前搭建在2c2g的服务器并没有这个问题

**Comment by 1c3z** [comment]
1.截图这个报错是正常会出现的情况，应该是还在运行，可能有点慢。

如何判断任务是否还在运行
1.任务状态长时间没有改变，并且后下发的多个（大于等于2）任务都已经执行了，当前任务肯定是异常了。
2.根据下面的异常任务原因排查看任务日志是否有持续输出。
3.根据网络带宽，CPU，内存占用情况判断任务是否还在运行。

https://github.com/TophantTechnology/ARL/wiki/Docker-%E7%8E%AF%E5%A2%83%E5%AE%89%E8%A3%85-ARL#faq

**Comment by Pinus97** [comment]
@1c3z 大佬，这个错误咋解决：consumer: Cannot connect to amqp://arl:**@rabbitmq:5672/arlv2host: [Errno 111] Connection refused
