### ISSUE TITLE
更改配置文件后，出现连接超时，密码错误

### ISSUE THREAD

**Issue by xiaotaolone** [TophantTechnology/ARL#430]
你好 我想反馈在更改config-docker.yaml 此配置文件后无法正常登录登录先提示超时，用户名和密码错误，在进入数据库修改密码后还是提示密码错误，能不能大概的给出一个解决的方法·
![image](https://user-images.githubusercontent.com/26355575/201503074-bc62f365-db0f-48e2-87f1-7d8a418007e9.png)

**Comment by xiaotaolone** [comment]
此为更改密码后提示

**Comment by xiaotaolone** [comment]
![image](https://user-images.githubusercontent.com/26355575/201503094-90959306-a332-4b52-9ed2-a233fe9ca48e.png)
此为更改密码命令

**Comment by 1c3z** [comment]
这个超时应该是mongodb没连上。  可能需要看看容器运行的状态。
