### ISSUE TITLE
error  RISKIQ

### ISSUE THREAD

**Issue by asdlijinquan** [TophantTechnology/ARL#432]
<img width="455" alt="屏幕截图 2022-11-15 142316" src="https://user-images.githubusercontent.com/52305513/201842318-26b82a70-28dc-48b0-ba6b-e5357a693d7d.png">
一直报错连接超时，检查发现是RISKIQ报错，这是什么原因呢？

**Comment by 1c3z** [comment]
镜像不是最新的,  配置了镜像源的话删除下。
``` 
docker rmi tophant/arl:latest
docker pull tophant/arl:latest
docker-compose down
docker-compose up -d 
```

**Comment by asdlijinquan** [comment]
也许是挂了镜像？但不挂镜像下载太慢啦，有什么其他的办法吗

**Comment by 1c3z** [comment]
你看下这个哈。 把latest 版本改成一个具体的版本号，看能下载下来么，我没试。 

https://github.com/TophantTechnology/ARL/issues/379#issuecomment-1310496678

**Comment by 1c3z** [comment]
在docker-config.yaml  把RISKIQ 这个配置项目手动加上吧 。应该就不会报错了。 

https://github.com/TophantTechnology/ARL/blob/8dd790df6afa22b57591ba20f11a4b3b5570130d/docker/config-docker.yaml#LL11-L11C8

**Comment by asdlijinquan** [comment]
> 在docker-config.yaml 把RISKIQ 这个配置项目手动加上吧 。应该就不会报错了。
> 
> https://github.com/TophantTechnology/ARL/blob/8dd790df6afa22b57591ba20f11a4b3b5570130d/docker/config-docker.yaml#LL11-L11C8

确实是这个问题，已解决！是镜像版本的问题，可以手动配置上
