### ISSUE TITLE
钉钉推送异常

### ISSUE THREAD

**Issue by li-baige** [TophantTechnology/ARL#434]
1.按照之前其他人提的issues找到了钉钉的配置选项：
<img width="497" alt="截屏2022-11-17 上午11 46 48" src="https://user-images.githubusercontent.com/76275424/202350237-6eba2bf4-3cb0-4787-967b-4b6459b0518c.png">
2.通过命令也可以触发触发钉钉推送的测试，这证明了钉钉的配置是没有问题的，
<img width="443" alt="截屏2022-11-17 上午11 48 34" src="https://user-images.githubusercontent.com/76275424/202350352-1070bc6c-0943-4046-ab55-5d68aa5e5fb0.png">
3.然而当我的任务完成时，却不推送任务完成。（已经多次尝试按照图2的方式，重启容器，依然不行）

**Comment by 1c3z** [comment]
目前推送只是针对监控任务发现新资产的时候。 ε=ε=ε=┏(゜ロ゜;)┛
