### ISSUE TITLE
docker-compose 安装后提示“用户名或密码错误”

### ISSUE THREAD

**Issue by striveben** [TophantTechnology/ARL#438]
使用github上下载的源码里的docker文件；常见的几个log文件均正常，mongodb链接也没问题，但登录时会提示“用户名或密码错误”：

`arl_web      | [2022-11-20 13:34:25 +0800] [4027] [INFO] Booting worker with pid: 4027
arl_web      | wait-for-it.sh: waiting 15 seconds for mongodb:27017
arl_web      | wait-for-it.sh: mongodb:27017 is available after 1 seconds
arl_web      | [2022-11-20 13:34:34 +0800] [30] [INFO] Starting gunicorn 20.1.0
arl_web      | [2022-11-20 13:34:34 +0800] [30] [INFO] Listening at: http://0.0.0.0:5003 (30)
arl_web      | [2022-11-20 13:34:34 +0800] [30] [INFO] Using worker: sync
arl_web      | [2022-11-20 13:34:34 +0800] [33] [INFO] Booting worker with pid: 33
arl_web      | [2022-11-20 13:34:34 +0800] [35] [INFO] Booting worker with pid: 35
arl_web      | [2022-11-20 13:34:34 +0800] [36] [INFO] Booting worker with pid: 36`

<img width="949" alt="image" src="https://user-images.githubusercontent.com/61238912/202887354-b1cb7d24-e560-4819-8c91-ad4402b5d79d.png">

**Comment by 1c3z** [comment]
1. 旧数据是不是没删除? 用旧密码看看。
2. 或者直接重置密码
https://tophanttechnology.github.io/ARL-doc/forget_pass/

**Comment by striveben** [comment]
我是在新环境弄的，而且重置密码后，链接也是这样，很奇怪

**Comment by 1c3z** [comment]
进mongo 把 arl use 集合的内容查询出来看是否符合预期。 
实在不行重装下看看 
```
docker-compose down 
docker volume rm arl_db
```
然后再重装。
