### ISSUE TITLE
[ERROR] [MainThread] [dns_query.py:35] quake_360: xxxxxxxxxxxx QuakeToken is invalid

### ISSUE THREAD

**Issue by alixiaowei** [TophantTechnology/ARL#439]
[ERROR] [MainThread] [dns_query.py:35] quake_360: xxxxxxxxxx QuakeToken is invalid
如题本地测试token是有效的 配置后test提示无效

**Comment by 1c3z** [comment]
1. 他们的域名变了。 

原先是 quake.360.cn 


https://quake.360.net/api/v3/search/quake_service

**Comment by 1c3z** [comment]
v2.5.3 已修复。
