### ISSUE TITLE
docker 启动报错

### ISSUE THREAD

**Issue by Minggle** [TophantTechnology/ARL#44]
docker-compose 启动后，arl_worker和arl_web无限重启，查看docker logs后，发现
```shell
PermissionError: [Errno 13] Permission denied: '/code/arl_worker.log'
```
修改docker-compose.yml进入docker后发现arl_web.log没权限
```
-rw-r--r--. 1 root root   0 Nov 19 08:33 arl_web.log
```

**Comment by 1c3z** [comment]
麻烦提供下操作系统版本 docker， docker-compose 版本。

**Comment by 1c3z** [comment]
猜测是docker没装好，或者把docker目录下的arl_worker.log 和 arl_web.log 权限改成777 。

**Comment by Minggle** [comment]
Docker version 1.13.1, build 0be3e21/1.13.1
docker-compose version 1.26.2,

**Comment by Minggle** [comment]
[root@arl docker]# chmod 777 arl_w*
[root@arl docker]# ll
总用量 16
-rwxrwxrwx. 1 root root    0 11月 18 11:30 arl_web.log
-rwxrwxrwx. 1 root root    0 11月 18 11:30 arl_worker.log
-rw-r--r--. 1 root root  540 11月 18 11:30 config-docker.yaml
-rw-r--r--. 1 root root 1839 11月 23 14:39 docker-compose.yml
drwxr-xr-x. 4 root root   64 11月 18 11:30 frontend
drwxr-xr-x. 2 root root    6 11月 18 17:07 image
-rw-r--r--. 1 root root   96 11月 18 11:30 mongo-init.js
-rw-r--r--. 1 root root 1293 11月 18 11:30 nginx.conf
drwxr-xr-x. 2 root root   24 11月 18 11:30 worker
依然报错。
PermissionError: [Errno 13] Permission denied: '/code/arl_worker.log'

**Comment by Minggle** [comment]
[root@arl docker]# cat /etc/redhat-release
CentOS Linux release 7.5.1804 (Core)

**Comment by SecReXus** [comment]
我也是遇到这个问题，启动不起来。按照前面的方法操作不行。

**Comment by SecReXus** [comment]
Arl_web报错：
Error: Error: 'arl_web.log' isn't writable [PermissionError(13, 'Permission denied')]
Arl_worker报错：
Parse config.yaml error [Errno 13] Permission denied: '/code/app/config.yaml'

**Comment by 1c3z** [comment]
@Minggle   
麻烦卸载centos 仓库里提供的docker
安装下面的
https://docs.docker.com/engine/install/centos/

装完以后是这样的。
![image](https://user-images.githubusercontent.com/9052484/100054266-b7c5e200-2e5c-11eb-8988-84843e524d49.png)

另外安装docker过程可能会有点满，可以添加清华的源来进行加速下载，具体修改源的方法请查看下面的URL
https://mirrors.tuna.tsinghua.edu.cn/help/docker-ce/



@SecReXus

**Comment by Minggle** [comment]
![image](https://user-images.githubusercontent.com/35053182/100294556-19ec2780-2fc2-11eb-8963-364a4ac2ad67.png)
大佬，依然不行啊

**Comment by 1c3z** [comment]
不知道解决了么，可以先把docker停止，然后把 `/var/lib/docker ` 这个目录清空，然后重新下载镜像看下能不能启动。

**Comment by 1c3z** [comment]
@Minggle   @SecReXus   

这个权限报错可能是selinux功能导致的，可以关了试下。
