### ISSUE TITLE
端口扫描日志不更新

### ISSUE THREAD

**Issue by samartfang** [TophantTechnology/ARL#441]
在云服务器部署的，每次fofa下发任务后，arl_worker更新了几条后就不更新了，几个小时也不动。请问这种情况是正常的吗？
服务器也重启过，ARL也重装过。都是这种情况

[2022-11-22 12:49:32,756: INFO/MainProcess] Connected to amqp://arl:**@rabbitmq:5672/arlv2host
[2022-11-22 12:49:32,757: INFO/MainProcess] Connected to amqp://arl:**@rabbitmq:5672/arlv2host
[2022-11-22 12:49:32,770: INFO/MainProcess] mingle: searching for neighbors
[2022-11-22 12:49:32,774: INFO/MainProcess] mingle: searching for neighbors
[2022-11-22 12:49:33,801: INFO/MainProcess] mingle: all alone
[2022-11-22 12:49:33,802: INFO/MainProcess] mingle: all alone
[2022-11-22 12:49:33,829: INFO/MainProcess] celery@arltask ready.
[2022-11-22 12:49:33,833: INFO/MainProcess] celery@arlgithub ready.
[2022-11-22 12:50:48,191: INFO/MainProcess] Received task: app.celerytask.arl_task[dd7fc1a7-fa52-4b3e-a95f-fda78b84612c]  
[2022-11-22 12:50:48,193: INFO/ForkPoolWorker-1] app.celerytask.arl_task[dd7fc1a7-fa52-4b3e-a95f-fda78b84612c]: run_task action:fofa_task time: 1669092648.1931176
[2022-11-22 12:50:48,193: INFO/ForkPoolWorker-1] app.celerytask.arl_task[dd7fc1a7-fa52-4b3e-a95f-fda78b84612c]: name:srcedu, target:Fofa ip 1932, task_id:637c5528141eb900210c4863
[2022-11-22 12:50:48,386: INFO/ForkPoolWorker-1] app.celerytask.arl_task[dd7fc1a7-fa52-4b3e-a95f-fda78b84612c]: nmap target 210.47.10.210 121.32  ports 1000,10000,10001,100  arguments -sT -n --open -PE -PS22,80,443,843,3389,8007-8011,8443,9090,8080-8091,8093,8099,5000-5004,2222,3306,1433,21,25 --max-rtt-timeout 800ms --min-rate 60 --script-timeout 6s --max-hostgroup 128 --host-timeout 300s --min-parallelism 32 --max-retries 2

**Comment by samartfang** [comment]
docker日志补充（会是arl_rabbitmq 关闭所有连接的原因吗）
Attaching to arl_worker, arl_scheduler, arl_web, arl_rabbitmq, arl_mongodb
arl_mongodb  | 2022-11-22T04:49:44.153+0000 I NETWORK  [listener] connection accepted from 172.18.0.5:60586 #10 (7 connections now open)
arl_mongodb  | 2022-11-22T04:49:44.153+0000 I NETWORK  [conn10] received client metadata from 172.18.0.5:60586 conn10: { driver: { name: "PyMongo", version: "3.7.1" }, os: { type: "Linux", name: "Linux", architecture: "x86_64", version: "5.4.0-132-generic" }, platform: "CPython 3.6.8.final.0" }
arl_mongodb  | 2022-11-22T04:49:44.154+0000 I NETWORK  [listener] connection accepted from 172.18.0.5:60594 #11 (8 connections now open)
arl_mongodb  | 2022-11-22T04:49:44.154+0000 I NETWORK  [conn11] received client metadata from 172.18.0.5:60594 conn11: { driver: { name: "PyMongo", version: "3.7.1" }, os: { type: "Linux", name: "Linux", architecture: "x86_64", version: "5.4.0-132-generic" }, platform: "CPython 3.6.8.final.0" }
arl_mongodb  | 2022-11-22T04:49:44.163+0000 I ACCESS   [conn11] Successfully authenticated as principal admin on admin from client 172.18.0.5:60594
arl_mongodb  | 2022-11-22T04:50:48.195+0000 I NETWORK  [listener] connection accepted from 172.18.0.6:44792 #12 (9 connections now open)
arl_mongodb  | 2022-11-22T04:50:48.196+0000 I NETWORK  [conn12] received client metadata from 172.18.0.6:44792 conn12: { driver: { name: "PyMongo", version: "3.7.1" }, os: { type: "Linux", name: "Linux", architecture: "x86_64", version: "5.4.0-132-generic" }, platform: "CPython 3.6.8.final.0" }
arl_mongodb  | 2022-11-22T04:50:48.197+0000 I NETWORK  [listener] connection accepted from 172.18.0.6:44806 #13 (10 connections now open)
arl_mongodb  | 2022-11-22T04:50:48.197+0000 I NETWORK  [conn13] received client metadata from 172.18.0.6:44806 conn13: { driver: { name: "PyMongo", version: "3.7.1" }, os: { type: "Linux", name: "Linux", architecture: "x86_64", version: "5.4.0-132-generic" }, platform: "CPython 3.6.8.final.0" }
arl_mongodb  | 2022-11-22T04:50:48.206+0000 I ACCESS   [conn13] Successfully authenticated as principal admin on admin from client 172.18.0.6:44806
arl_scheduler | wait-for-it.sh: waiting 15 seconds for mongodb:27017
arl_scheduler | wait-for-it.sh: mongodb:27017 is available after 1 seconds
arl_scheduler | /usr/local/lib/python3.6/site-packages/OpenSSL/crypto.py:14: CryptographyDeprecationWarning: Python 3.6 is no longer supported by the Python core team. Therefore, support for it is deprecated in cryptography and will be removed in a future release.
arl_scheduler |   from cryptography import utils, x509
arl_scheduler | [2022-11-22 12:49:23] [INFO] [MainThread] [scheduler.py:220] start scheduler server 
arl_rabbitmq | 2022-11-22 04:52:32.797 [info] <0.1131.0> Closing all channels from connection '172.18.0.6:57600 -> 172.18.0.2:5672' because it has been closed
arl_rabbitmq | 2022-11-22 04:52:40.255 [error] <0.1030.0> closing AMQP connection <0.1030.0> (172.18.0.5:41184 -> 172.18.0.2:5672):
arl_rabbitmq | missed heartbeats from client, timeout: 60s
arl_rabbitmq | 2022-11-22 04:52:40.255 [info] <0.1136.0> Closing all channels from connection '172.18.0.5:41184 -> 172.18.0.2:5672' because it has been closed
arl_rabbitmq | 2022-11-22 04:52:40.263 [error] <0.1043.0> closing AMQP connection <0.1043.0> (172.18.0.5:41188 -> 172.18.0.2:5672):
arl_rabbitmq | missed heartbeats from client, timeout: 60s
arl_rabbitmq | 2022-11-22 04:52:40.264 [info] <0.1140.0> Closing all channels from connection '172.18.0.5:41188 -> 172.18.0.2:5672' because it has been closed
arl_rabbitmq | 2022-11-22 04:53:48.188 [error] <0.1070.0> closing AMQP connection <0.1070.0> (172.18.0.5:39682 -> 172.18.0.2:5672):
arl_rabbitmq | missed heartbeats from client, timeout: 60s
arl_rabbitmq | 2022-11-22 04:53:48.188 [info] <0.1159.0> Closing all channels from connection '172.18.0.5:39682 -> 172.18.0.2:5672' because it has been closed
arl_web      | wait-for-it.sh: mongodb:27017 is available after 1 seconds
arl_web      | [2022-11-22 12:49:22 +0800] [28] [INFO] Starting gunicorn 20.1.0
arl_web      | [2022-11-22 12:49:22 +0800] [28] [INFO] Listening at: http://0.0.0.0:5003 (28)
arl_web      | [2022-11-22 12:49:22 +0800] [28] [INFO] Using worker: sync
arl_web      | [2022-11-22 12:49:22 +0800] [31] [INFO] Booting worker with pid: 31
arl_web      | [2022-11-22 12:49:22 +0800] [32] [INFO] Booting worker with pid: 32
arl_web      | [2022-11-22 12:49:22 +0800] [33] [INFO] Booting worker with pid: 33
arl_web      | /usr/local/lib/python3.6/site-packages/OpenSSL/crypto.py:14: CryptographyDeprecationWarning: Python 3.6 is no longer supported by the Python core team. Therefore, support for it is deprecated in cryptography and will be removed in a future release.
arl_web      |   from cryptography import utils, x509
arl_web      | [2022-11-22 12:50:48] [INFO] [MainThread] [taskFofa.py:146] target:637c5528141eb900210c4863 celery_id:dd7fc1a7-fa52-4b3e-a95f-fda78b84612c
arl_worker   | wait-for-it.sh: waiting 15 seconds for mongodb:27017
arl_worker   | wait-for-it.sh: mongodb:27017 is available after 1 seconds
arl_worker   | wait-for-it.sh: waiting 15 seconds for rabbitmq:5672
arl_worker   | wait-for-it.sh: rabbitmq:5672 is available after 10 seconds

**Comment by 1c3z** [comment]
nmap target  ，这个是nmap在扫描端口，没结束没有日志输出。
