### ISSUE TITLE
部署问题

### ISSUE THREAD

**Issue by lvxingren** [TophantTechnology/ARL#442]
ARL部署中发现权限不足，无法连接rabbitmq的问题

**Comment by lvxingren** [comment]
![image](https://user-images.githubusercontent.com/42830802/203496104-0136704e-01e6-4f56-85db-aec3ddc405ff.png)

**Comment by 1c3z** [comment]
这个应该是正常的吧。 在23:04 起来了。

**Comment by woshi-Tom** [comment]
**支持podman+docker-compose部署吗？**
我尝试使用此组合在本地部署，发现有报错，如果官方不支持的话，那我就转去docker了

**Comment by 1c3z** [comment]
@woshi-Tom  podman没有测过呢。

**Comment by woshi-Tom** [comment]
> @woshi-Tom podman没有测过呢。

我在kali中测试了，没有部署成功；但是还是希望官方能测试在podman下的一些部署细节；
两种可能：
1、不支持podman
2、支持podman，但需要特定的环境

主要原因还是docker被k8s抛弃，现在有不少人转向podman来运行容器；如果必须docker环境的话，那么使用podman的人就知道需要搭建一个新的（docker）环境，可以节省大量时间。

另外非常感谢开发人员的贡献。

**Comment by 1c3z** [comment]
@woshi-Tom  
podman 可以装的，参考。

https://tophanttechnology.github.io/ARL-doc/system_install/#podman-arl
