### ISSUE TITLE
按c段添加ip后扫完没有资产

### ISSUE THREAD

**Issue by 188150486** [TophantTechnology/ARL#446]
xx.xx.xx.0/24 添加ip扫描后没有资产 多个ip都这样
另外，腾讯云天天通知我违规，请问有没有更好的部署灯塔的办法

**Comment by 1c3z** [comment]
1. IP被对面封了吧 ？

2. 还有可能被人投诉了。 

3. 我一般只是域名爆破，然后扫100个端口，没有什么事。
