### ISSUE TITLE
ARL 用国内服务器安装后，无法使用正常

### ISSUE THREAD

**Issue by test502git** [TophantTechnology/ARL#449]
ARL 用国内服务器安装后，一访问就进主界面，无需登录~
但功能也无法使用，超时

![image](https://user-images.githubusercontent.com/50769953/206077120-28013c67-7297-4856-a4fa-2b77dd5038e3.png)

**Comment by test502git** [comment]
timeout of 12000ms exceede

**Comment by test502git** [comment]
docker ps 
![image](https://user-images.githubusercontent.com/50769953/206077703-add8335f-b0d4-4831-a10d-3f530ccb25cb.png)

**Comment by 1c3z** [comment]
这两条命令看看有什么错误输出么？
```
docker-compose logs -f  --tail=10
tail -f *.log
```

**Comment by test502git** [comment]
已解决，更换Cenots8完美
