### ISSUE TITLE
问题

### ISSUE THREAD

**Issue by cloud-jie** [TophantTechnology/ARL#451]
扫描完成后，使用2.5.2版本新增功能导入自己收集的资产并对其截图的功能时，勾选端口扫描或文件泄露会重复扫描吗？（我收集到的子域未与arl结果去重）如果会，可否修改为时间小于一小时，不再重复扫描

**Comment by 1c3z** [comment]
如果是在资产分组里导入的，会先根据资产分组里的域名进行比对， 不存在的域名才会下发任务的。

如果是直接下的任务，下发的是什么就会扫描什么。这块没有去重操作的。

**Comment by 1c3z** [comment]
1. 第一个是扫描指定的站点，不会扫描端口
2. 添加子域名到资产分组， 不存在的子域名会下发一个任务。
