### ISSUE TITLE
docker-compose启动之后，状态都是UP 连接提示400，麻烦了谢谢

### ISSUE THREAD

**Issue by tangsai1993** [TophantTechnology/ARL#454]
![image](https://user-images.githubusercontent.com/41147420/206895650-4cff25ad-2378-4563-8ad0-d5c82e1c0a48.png)
![image](https://user-images.githubusercontent.com/41147420/206895663-2cf7bdcb-8687-4fd0-9c07-e277861e281e.png)

**Comment by 1c3z** [comment]
请使用HTTPS 访问 。 

这个我后面优化下。

**Comment by 1c3z** [comment]
v2.5.3 已修复。
