### ISSUE TITLE
doker 安装出现 Parse config.yaml error 'RISKIQ'

### ISSUE THREAD

**Issue by lunatic1213546a** [TophantTechnology/ARL#455]
![41a56414af2a7421f964dc8b62e01a6](https://user-images.githubusercontent.com/90127234/207547502-809d0321-c0c6-473a-8551-e131ad8e150c.png)

**Comment by lunatic1213546a** [comment]
已经解决，删除旧镜像，在docker-compose.yml修改拉取最新版镜像既可

**Comment by 1c3z** [comment]
OK。 先关闭，有问题可以再反馈。
