### ISSUE TITLE
docker-compose后原来UP的一会后就变成restarting

### ISSUE THREAD

**Issue by panda1994zhang** [TophantTechnology/ARL#456]
![9c1cac8bb1dc0040a86f5e8ce962f75](https://user-images.githubusercontent.com/46433260/208127602-3d94271d-bcac-4ded-b8ea-eb6c25cff826.png)
这个要怎么解决，麻烦大佬解答下

**Comment by 1c3z** [comment]
可以看下日志，大概率镜像没更新。

**Comment by guolora** [comment]
启动后，镜像资源（arl_worker，arl_scheduler）状态一直在Restarting中，查看日志显示Parse config.yaml error 'RISKIQ'的问题。
从https://community.riskiq.com/中注册账户信息，目前已官方已关闭riskiq的注册接口，目前riskiq属于微软，使用defender的账户无法登录riskiq，请问如何更新或者替换riskiq的功能，希望得到作者的回复，非常感谢。

**Comment by 1c3z** [comment]
@guolora 
是不是忘记pull 了
是不是配置镜像源了

#379
#389

**Comment by panda1994zhang** [comment]
> 可以看下日志，大概率镜像没更新。

前段时间羊了 现在才来看 不好意思
git clone https://github.com/TophantTechnology/ARL
cd ARL/docker/
docker volume create arl_db
docker-compose pull
docker-compose up -d 
我是跟着这个走的步骤，这个链接是最新的吗，还有哪里要更新镜像

**Comment by 1c3z** [comment]
最好用这个吧 @panda1994zhang 
https://github.com/TophantTechnology/ARL/releases/download/v2.5.3/docker.zip

如果拉不下来镜像，过段时间用这个命令看看。 
`docker-compose pull --no-parallel`

参考：
https://tophanttechnology.github.io/ARL-doc/faq/#12-docker

**Comment by Lc1ee** [comment]
更新config-docker.yaml以后docker-compose up需要重新拉镜像嘛？

**Comment by 1c3z** [comment]
@Lc1ee 

不用，要重启下。
