### ISSUE TITLE
修改了字典，运行报错

### ISSUE THREAD

**Issue by xz-zone** [TophantTechnology/ARL#458]
![image](https://user-images.githubusercontent.com/19305748/208840183-02a10e9a-7f66-4bab-a463-9bad4dc8b162.png)

**Comment by 1c3z** [comment]
这个和修改了字典没关系， 是搜索引擎调用功能的报错。 

后期优化。

**Comment by xz-zone** [comment]
好的
&nbsp;


小洲
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年12月22日(星期四) 中午1:47
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [TophantTechnology/ARL] 修改了字典，运行报错 (Issue #458)





 
这个和修改了字典没关系， 是搜索引擎调用功能的报错。
 
后期优化。
