### ISSUE TITLE
是否可以添加模块独立运行功能

### ISSUE THREAD

**Issue by siberiah0h** [TophantTechnology/ARL#46]
比如爆破域名时候我不希望文件泄露探测，但搜索完成后，我又想对部分域名进行文件泄露探测，这就需要一个模块对其独立运行

**Comment by 1c3z** [comment]
这个功能不出意外还要等到下下个版本了。

目前的话如果要比较快速的调用文件泄露功能，可以仅仅勾选ARL历史查询，会跳过域名爆破仅仅从数据库读取域名。
![image](https://user-images.githubusercontent.com/9052484/100054750-a7facd80-2e5d-11eb-88f7-2fad3ded7c7b.png)

**Comment by siberiah0h** [comment]
新问题：可否考虑添加一个扫描任务模板（类似于AWVS自定义扫描策略），比如，我在新建任务时候，我可以加载扫描模板直接扫描，扫描模板记录了添加的任务配置，这样我需要添加不同域名的时候就能直接加载模板进行扫描，而不需要每次都点击添加任务的钩子或者选项
![image](https://user-images.githubusercontent.com/73219025/100179801-baceda00-2f11-11eb-980f-6d715975b088.png)

**Comment by 1c3z** [comment]
这个在操作上有一点点优化，前期会先关注功能。

**Comment by siberiah0h** [comment]
任务似乎没有批量停止功能，当我要批量删除任务的时候，一直提示需要停止任务后才能删除，我尝试过重启docker但似乎任务还是一直在等着中并未停止，任务比较多要一个一个的手动停止比较麻烦，希望增加一个批量停止的功能，类似于批量删除的一样
![image](https://user-images.githubusercontent.com/73219025/105115823-812ae180-5b04-11eb-961e-18f689ac3f1d.png)

**Comment by 1c3z** [comment]
已添加策略功能，欢迎更新
