### ISSUE TITLE
截图失败

### ISSUE THREAD

**Issue by viplurker** [TophantTechnology/ARL#460]
系统版本：CentOS7
软件部署方式：采用脚本安装，非Docker版本，关闭SeLinux，未关闭firewalld，全部结果均“截图失败”
![image](https://user-images.githubusercontent.com/34469177/209761135-ee46ca2c-01dc-42fc-aa0d-dc968f755d9b.png)

**Comment by 1c3z** [comment]
phantomjs 命令存在么？

这个有报错么
phantomjs /opt/ARL/app/tools/screenshot.js  -u=https://www.baidu.com -s=baidu.jpg

**Comment by viplurker** [comment]
> phantomjs 命令存在么？
> 
> 这个有报错么 phantomjs /opt/ARL/app/tools/screenshot.js -u=https://www.baidu.com -s=baidu.jpg

破案了，确实没这个命令，我先部署下该工具，然后试试看~

**Comment by viplurker** [comment]
OK，已经解决，感谢

**Comment by linsihao7788** [comment]
![screenshot-20230313-161839](https://user-images.githubusercontent.com/46431972/224644935-7a5e45ad-6e6d-457b-98aa-3ad172bf24fb.png)

大佬，我这边也没有报错，但是生成的baidu.jpg是空白的，任务启动的扫描也还是显示截图失败
