### ISSUE TITLE
Docker 搭建ARL显示mongodb连接不上

### ISSUE THREAD

**Issue by monitor403** [TophantTechnology/ARL#462]
![image](https://user-images.githubusercontent.com/45124775/210232208-b7594093-f5e0-4643-8e7d-09dadbd8c669.png)
![image](https://user-images.githubusercontent.com/45124775/210232249-e3464c01-c5b3-4c2d-bc18-bc2056f41cac.png)

**Comment by monitor403** [comment]
无任何配置上的修改，用的官方的docker文件

**Comment by 1c3z** [comment]
docker-compose down 
docker volume rm arl_db

然后再重来试试呢？
