### ISSUE TITLE
弱口令爆破

### ISSUE THREAD

**Issue by muddlelife** [TophantTechnology/ARL#464]
我自己搭了几个环境，ssh、mysql服务，都是弱口令，也在/opt/ARL-NPoC/xing/dicts路径下将弱口令字典加上了，但是执行弱口令扫描，就是爆破不出来，这个问题是一直存在的吗，还是说我的设置有问题，我是根据
![image](https://user-images.githubusercontent.com/79511104/210474354-3f08921d-5724-4543-91bb-59fc942bbee5.png)
设置的，另外我是在内网环境，只扫描IP段
![image](https://user-images.githubusercontent.com/79511104/210474190-eb0f50fb-a00d-4315-a597-2c21fe79e254.png)
![image](https://user-images.githubusercontent.com/79511104/210474280-74d950fd-11cd-495d-9a0e-5c7349b09a50.png)
![image](https://user-images.githubusercontent.com/79511104/210474298-11c477b7-2ac0-46af-876a-6b8f8d2db2d4.png)
![image](https://user-images.githubusercontent.com/79511104/210474238-44039671-a908-4f06-bf8c-4e68869b23ad.png)

**Comment by 1c3z** [comment]
弱口令是可以检出的。  

1. 先看结果里面端口扫描结果，还有服务那一栏的结果可以是否有对应的结果。 
2. 将弱口令字典加上容器是改的worker容器么？
3. 改完以后应该可以检出，我以mysql 为例, 目标要带上协议。 

```
docker exec -ti arl_worker bash
xing brute -n mysql -t mysql://ip:3306
```


![image](https://user-images.githubusercontent.com/9052484/210691017-bda697b7-8436-4228-a55f-a394ad624c30.png)
