### ISSUE TITLE
调用/user/login 用户登录接口

### ISSUE THREAD

**Issue by renjiutong** [TophantTechnology/ARL#465]
![1](https://user-images.githubusercontent.com/66993288/210910865-19b50ffa-8c58-48ab-9a83-1dcf33c99112.png)

**Comment by renjiutong** [comment]
帮忙看一下，谢谢了

**Comment by renjiutong** [comment]
你好，那如何解决这个问题呢？

**Comment by 1c3z** [comment]
0. 前端不要跨域调用API
1. 用nginx 反代下
2. 开发的时候前端工具也可以提供反代
https://juejin.cn/post/6844904033874886663

**Comment by renjiutong** [comment]
你好，token失效时间？，目前登录后大约几分钟后，就得重新登录一次

**Comment by renjiutong** [comment]
你好，接口验证token可以取消么？

**Comment by renjiutong** [comment]
解决了 谢谢
