### ISSUE TITLE
2.5.3版本更新问题

### ISSUE THREAD

**Issue by bigdogdo** [TophantTechnology/ARL#467]
版本更新重新搭建，配置文件里面启用了三方接口，但是实际使用的时候好像没有启用接口查询，只有域名爆破,alt_dns。我有设置[true](enable: true) 是不是新版的配置文件要把apikey ''用单引号圈起来？

**Comment by 1c3z** [comment]
1. 改完没重启？ 
2.  还有可能三方接口没有查询到新的域名。 

或者可以看下这个，可以进入容器测试
https://tophanttechnology.github.io/ARL-doc/config_option/#token

**Comment by bigdogdo** [comment]
可以了，测试发现在新版里面一定要把apikey圈起来才行，用老版本的那种写法就会有问题
