### ISSUE TITLE
连接FOFA API异常

### ISSUE THREAD

**Issue by uknowwhoam1** [TophantTechnology/ARL#468]
ARL是用的最新版的而且FOFA是会员，但还是无法使用FOFA API，这是为什么？
![uTools_1673177871629](https://user-images.githubusercontent.com/99535521/211194070-0cb25ba6-e044-4f82-abec-667348a23780.png)
![uTools_1673177881705](https://user-images.githubusercontent.com/99535521/211194074-e224e7d6-a68d-4a29-a3a3-f08505f4b616.png)

**Comment by 159357fule** [comment]
擦，我也是这样的

**Comment by 159357fule** [comment]
重启一下容器就行了

**Comment by whoiiii** [comment]
> 

感觉有点治标不治本，昨天重启后能用，今天一翻还是无法使用，已经重启过了,fofaAPI还是无法使用
![uTools_1673235849341](https://user-images.githubusercontent.com/99535521/211237794-af37fc78-62d4-49d2-b833-8aaed39bb1e8.png)

**Comment by 159357fule** [comment]
> > 
> 
> 感觉有点治标不治本，昨天重启后能用，今天一翻还是无法使用，已经重启过了,fofaAPI还是无法使用 ![uTools_1673235849341](https://user-images.githubusercontent.com/99535521/211237794-af37fc78-62d4-49d2-b833-8aaed39bb1e8.png)

好吧，那得问问作者了

**Comment by 1c3z** [comment]
我本地一直是可以用的。
![image](https://user-images.githubusercontent.com/9052484/211545595-2cde49e4-e0b6-4dd6-b094-5d2ed3d59ec5.png)

**Comment by whoiiii** [comment]
> 

我是部署在Ubuntu服务器上的，但就很奇怪

**Comment by panda1994zhang** [comment]
解决了吗 同ubuntu提示账号无效。emmm

**Comment by zmxw** [comment]
> 我本地一直是可以用的。 ![图像](https://user-images.githubusercontent.com/9052484/211545595-2cde49e4-e0b6-4dd6-b094-5d2ed3d59ec5.png)
我本地测试可以但是导入啥也没有，你们的能导入吗？
![图片](https://user-images.githubusercontent.com/57754437/225420344-3aa71520-c52b-4960-a64b-5dd0ba077feb.png)
![图片](https://user-images.githubusercontent.com/57754437/225420552-d140d5a9-044b-4f0d-a9c8-de3fbe9f6713.png)
容器测试也是能爬取
python3.6 -m test.test_query_plugin
![图片](https://user-images.githubusercontent.com/57754437/225421528-043d8b63-9a28-4b60-a249-5d2d2b597fd8.png)

**Comment by gongyu0217** [comment]
>
<img width="264" alt="微信图片_20240329145817" src="https://github.com/TophantTechnology/ARL/assets/55569414/bb0f3c3e-8a7a-4fe3-8d5e-01e5a344042b">
<img width="224" alt="微信图片_20240329145852" src="https://github.com/TophantTechnology/ARL/assets/55569414/026b65d2-dc92-48bb-b69d-9f7f97c203f4">
请问链接fofa出现这个问题？是需要fofa必须开会员才可以链接上吗？

**Comment by 1c3z** [comment]
@gongyu0217  查看这个

#745
