### ISSUE TITLE
v2.5.3 arm64 docker 镜像中缺少 phantomjs

### ISSUE THREAD

**Issue by Tardis07** [TophantTechnology/ARL#475]
如题，v2.5.3 arm64 docker 镜像中缺少 phantomjs 文件。并且使用 `apt install phantomjs` 安装后仍然无法调用其进行截图，报错如下：
```
qt.qpa.xcb: could not connect to display
qt.qpa.plugin: Could not load the Qt platform plugin "xcb" in "" even though it was found.
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

Available platform plugins are: eglfs, linuxfb, minimal, minimalegl, offscreen, vnc, xcb.

PhantomJS has crashed. Please read the bug reporting guide at
<http://phantomjs.org/bug-reporting.html> and file a bug report.
Aborted
```
麻烦排查一下问题原因，

**Comment by 1c3z** [comment]
arm的一直没支持截图，官网的也没提供下载。
https://phantomjs.org/download.html

可以看下这个能不能解决。 
https://stackoverflow.com/questions/71250718/qt-qpa-xcb-could-not-connect-to-display-qt-qpa-plugin-could-not-load-the-qt-pl

**Comment by Tardis07** [comment]
尝试了这些操作，都没有解决问题，我觉得和使用的设备应该也有点关系，目前考虑找个别的x86的设备了。phantomjs官方没有发布arm64二进制文件，但是我从apt库和自编译都不能正常使用，希望有朝一日能够解决吧。

**Comment by 1c3z** [comment]
phantomjs 作者没维护了。

**Comment by Tardis07** [comment]
要不考虑用 [mozilla/geckodriver](https://github.com/mozilla/geckodriver) 吧，这个渲染的结果比 phantomjs 更接近真实的浏览器画面，包括遇到返回 xml 的情况 😉
