### ISSUE TITLE
nuclei_scan.py在执行时可能出现一个错误

### ISSUE THREAD

**Issue by muddlelife** [TophantTechnology/ARL#481]
https://github.com/TophantTechnology/ARL/blob/a7e59db720a3bb200f215d97f31b4d171afc1f05/app/services/nuclei_scan.py#L66

我尝试用nuclei工具进行扫描，通过字典中取关键字方式取value值
![image](https://user-images.githubusercontent.com/79511104/217417066-ea7a23ae-8662-40c9-96ae-3d81d0d33911.png)
发现"curl_command"可能key不存在，则程序会报错，我通过nuclei的扫描结果中发现，"curl_command"字段并不是全部存在的
![image](https://user-images.githubusercontent.com/79511104/217417192-127379e3-3009-4e8c-bf84-06cb98afb4f3.png)
建议将代码修改为get方法，这样如果没有key，返回值为None，如
![image](https://user-images.githubusercontent.com/79511104/217417257-624b9ff5-e9f8-4119-92a6-bfd20308750e.png)

**Comment by 1c3z** [comment]
感谢反馈， @chasenz 已经提交了PR 了。 

https://github.com/TophantTechnology/ARL/pull/480
