### ISSUE TITLE
安装的最新版v2.5.3，但是打开系统发现还是显示“Powered by TCC(Tophant Competence Center) ARL 2.5.2 ”

### ISSUE THREAD

**Issue by atomxw** [TophantTechnology/ARL#483]
安装的最新版v2.5.3，但是打开系统发现还是显示“Powered by TCC(Tophant Competence Center) ARL 2.5.2 ”

**Comment by 1c3z** [comment]
1. 可能镜像没更新成功
2. 前端页面没更新，页面F5疯狂刷新试试

**Comment by atomxw** [comment]
用的新镜像全新安装的，应该是新镜像没有做好。&nbsp;


Atlanteans
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年2月13日(星期一) 上午10:13
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [TophantTechnology/ARL] 安装的最新版v2.5.3，但是打开系统发现还是显示“Powered by TCC(Tophant Competence Center) ARL 2.5.2 ” (Issue #483)





  
可能镜像没更新成功
 
前端页面没更新，页面F5疯狂刷新试试
