### ISSUE TITLE
不懂就问，怎么在centos9玩arl

### ISSUE THREAD

**Issue by 1160062997** [TophantTechnology/ARL#484]
一直提示mongodb 4.0安装不成，如何解决

**Comment by 1c3z** [comment]
来自chatgpt . 我没试过 

如果您想在 CentOS 9 上安装 MongoDB 4，可以按照以下步骤操作：

导入 MongoDB 的公共 GPG 密钥：
```
sudo rpm --import https://www.mongodb.org/static/pgp/server-4.4.asc
```
创建一个新的 YUM 存储库文件：
```
sudo nano /etc/yum.repos.d/mongodb-org-4.4.repo
```
在文件中粘贴以下内容：
```
[mongodb-org-4.4]
name=MongoDB Repository
baseurl=https://repo.mongodb.org/yum/redhat/$releasever/mongodb-org/4.4/x86_64/
gpgcheck=1
enabled=1
gpgkey=https://www.mongodb.org/static/pgp/server-4.4.asc
```

安装 MongoDB：
```
sudo yum install -y mongodb-org
```
启动 MongoDB 服务并设置开机启动：
```
sudo systemctl start mongod
sudo systemctl enable mongod
```
验证 MongoDB 是否已正常安装：
```
sudo systemctl status mongod
```
如果一切顺利，您将看到 MongoDB 服务处于运行状态。现在您可以使用 MongoDB 进行开发和测试了。


或者你可以安装 6 

https://technixleo.com/install-mongodb-on-centos-alma-rhel-9/

注意：请确保您已经配置了防火墙，以允许远程连接到 MongoDB。

**Comment by 1160062997** [comment]
> 来自chatgpt .我没试过
> 
> 如果您想在 CentOS 9 上安装 MongoDB 4，可以按照以下步骤操作：
> 
> 导入 MongoDB 的公共 GPG 密钥：
> 
> ```
> sudo rpm --import https://www.mongodb.org/static/pgp/server-4.4.asc
> ```
> 
> 创建一个新的 YUM 存储库文件：
> 
> ```
> sudo nano /etc/yum.repos.d/mongodb-org-4.4.repo
> ```
> 
> 在文件中粘贴以下内容：
> 
> ```
> [mongodb-org-4.4]
> name=MongoDB Repository
> baseurl=https://repo.mongodb.org/yum/redhat/$releasever/mongodb-org/4.4/x86_64/
> gpgcheck=1
> enabled=1
> gpgkey=https://www.mongodb.org/static/pgp/server-4.4.asc
> ```
> 
> 安装 MongoDB：
> 
> ```
> sudo yum install -y mongodb-org
> ```
> 
> 启动 MongoDB 服务并设置开机启动：
> 
> ```
> sudo systemctl start mongod
> sudo systemctl enable mongod
> ```
> 
> 验证 MongoDB 是否已正常安装：
> 
> ```
> sudo systemctl status mongod
> ```
> 
> 如果一切顺利，您将看到 MongoDB 服务处于运行状态。现在您可以使用 MongoDB 进行开发和测试了。
> 
> 或者你可以安装 6
> 
> https://technixleo.com/install-mongodb-on-centos-alma-rhel-9/
> 
> 注意：请确保您已经配置了防火墙，以允许远程连接到 MongoDB。

你他娘的太潮了🤣
