### ISSUE TITLE
更改了域名字典，有的域名爆破之后就报error

### ISSUE THREAD

**Issue by yut0u** [TophantTechnology/ARL#486]
arl_worker.log中日志：
![image](https://user-images.githubusercontent.com/9363698/219251478-2798feb8-7960-4ff5-a5a6-58533f839d60.png)
有什么解决办法嘛？

**Comment by 1c3z** [comment]
大字典，爆破时间太久了，超时了。

**Comment by yut0u** [comment]
> 400万字典，爆破时间太久了，超时了。

有什么配置可以修改这个超时时间嘛？

**Comment by 1c3z** [comment]
可以把这个值改大点。 

https://github.com/TophantTechnology/ARL/blob/master/app/utils/__init__.py#L37

**Comment by yut0u** [comment]
> 可以把这个值改大点。
> 
> https://github.com/TophantTechnology/ARL/blob/master/app/utils/__init__.py#L37

好嘞，我修改下试试。修改完需要把容器都重启下嘛？
另外，arl有没有使用的交流群呢？

**Comment by 1c3z** [comment]
是的。

有群，但是没什么人说话。 
![612a78b8a40f3bc2c6cc4b90e3d56f5](https://user-images.githubusercontent.com/9052484/219263928-2b3267de-3553-4f55-926f-053592f6f9ad.jpg)
