### ISSUE TITLE
如何跳过扫描单个子域名？

### ISSUE THREAD

**Issue by testa010** [TophantTechnology/ARL#488]
比如跳过扫描map.baidu.com，试了下在config-docker.yaml文件里配置"禁止域名"没有生效。这里貌似是只能配置主域名，对子域名无效。
![image](https://user-images.githubusercontent.com/64741288/220262377-185f5a19-11bf-47c6-9e31-41701506ddb7.png)

**Comment by 1c3z** [comment]
将`.map.baidu.com`添加到 `app/dicts/blackdomain.txt` 文件中，将会忽略 map.baidu.com下的所有域名。
