### ISSUE TITLE
2.5.3版本风险巡航任务一直是”waiting“状态

### ISSUE THREAD

**Issue by Ancientmemory** [TophantTechnology/ARL#489]
在2.5.3版本的时候，我下发风险巡航任务的时候，一直是”waitting“状态，是我的设置有问题，还是我该如何解决？

**Comment by 1c3z** [comment]
waitting 状态的话，可能是worker  不够用。

**Comment by Ancientmemory** [comment]
我把其他任务都挺了，只运行风险巡航，但是还是“waitting”状态，我是不是要回退版本啊

**Comment by Ancientmemory** [comment]
我查看日志：
arl_worker   |   phantomjs://code/screenshot.js:37 in pageRender
arl_worker   | Error: cannot access member `evaluate' of deleted QObject
arl_worker   | 
arl_worker   |   phantomjs://code/screenshot.js:37 in pageRender
arl_worker   | Error: cannot access member `evaluate' of deleted QObject
arl_worker   | 
arl_worker   |   phantomjs://code/screenshot.js:37 in pageRender
arl_worker   | Error: cannot access member `evaluate' of deleted QObject
arl_worker   | 
arl_worker   |   phantomjs://code/screenshot.js:37 in pageRender
arl_worker   | Error: cannot access member `evaluate' of deleted QObject
arl_worker   | 
arl_worker   |   phantomjs://code/screenshot.js:37 in pageRender
报这样的错误，我该如何解决呢
