### ISSUE TITLE
一些建议

### ISSUE THREAD

**Issue by smithjat** [TophantTechnology/ARL#49]
对于企业级信息收集目前的架构是不能保证信息收集全的
1.收域名枚举的关键字除了开源的关键字库外，需要用到的已经资产的关键字库
2，ICP备案查询也可以用上
3，整体用的信息技术比较单一，没有将这些工具搜集到的东西组合好
4，fofa没有用好，fofa的搜索语法较简单
5，可以看看fofa的api 其实可以获取更多的信息
6 ，指纹识别能力太弱了，用到的指纹库不行，除了库以前，方法也存在较大问题

**Comment by 1c3z** [comment]
感谢关注本项目。   
1.  已经资产的关键字库是指？可以举个例子么？
2. ICP备案查询直接去爬别人的库有点风险，另外添加了这个在任务下发是增加了复杂度。不过可以自己写一些自用的脚本根据ICP备案信息反查出 更多主域名，然后再利用ARL API可以自动下发任务。 
3. 没有将这些工具搜集到的东西组合好， 这个可以举个例子么？
4. fofa api 利用确实有点偏差。
