### ISSUE TITLE
timeout of 12000ms exceeded

### ISSUE THREAD

**Issue by fengjh0075** [TophantTechnology/ARL#491]
![image](https://user-images.githubusercontent.com/82223797/221366504-a637fbfc-ff9b-4dee-bace-873a3428a54e.png)
![屏幕截图 2023-02-25 234854](https://user-images.githubusercontent.com/82223797/221366511-46826bf7-efa2-4ae8-9385-749b549dc880.png)

**Comment by fengjh0075** [comment]
centos7,kali搭建都是这个问题。
> ![image](https://user-images.githubusercontent.com/82223797/221366504-a637fbfc-ff9b-4dee-bace-873a3428a54e.png) ![屏幕截图 2023-02-25 234854](https://user-images.githubusercontent.com/82223797/221366511-46826bf7-efa2-4ae8-9385-749b549dc880.png)

**Comment by fengjh0075** [comment]
kali，centos7，ubuntu搭建都是这个问题。

**Comment by 1c3z** [comment]
镜像没有更新。先手动`docker pull tophant/arl` 更新镜像

然后再 
```
docker-compose down
docker-compose up -d
```

**Comment by Deep0** [comment]
<img width="721" alt="图片" src="https://user-images.githubusercontent.com/25843151/221489136-a5129b74-ef52-462e-be36-84784b64d047.png">
我也是这个情况，但是报错不一样

**Comment by fengjh0075** [comment]
> 镜像没有更新。先手动`docker pull tophant/arl` 更新镜像
> 
> 然后再
> 
> ```
> docker-compose down
> docker-compose up -d
> ```
 oK 已经弄好了

**Comment by wdnmd0399** [comment]
请问你怎么解决的

**Comment by fengjh0075** [comment]
> 请问你怎么解决的
镜像更新一下就好了，
