### ISSUE TITLE
一个局部变量没有被调用

### ISSUE THREAD

**Issue by li-baige** [TophantTechnology/ARL#498]
```
# app/utils/__init__.py

def domain_parsed(domain, fail_silently = True):
    domain = domain.strip()
    logger = get_logger()
    try:
        res = get_tld(domain, fix_protocol=True,  as_object=True)
        item = {
            "subdomain": res.subdomain,
            "domain":res.domain,
            "fld": res.fld
        }
        return item
    except Exception as e:
        if not fail_silently:
            raise e
```
这是否意味着域名解析的部分日志没有记录呢

**Comment by li-baige** [comment]
logger = get_logger()

**Comment by li-baige** [comment]
关于该文件中的正则表达式是否存在表达式正则出错的问题：
这里我们把函数拿出来做一个测试：
```
import re

site = "https://www.baidu.com"

def gen_filename(site):
    # 将site中的 :// 替换为下划线
    filename = site.replace('://', '_')

    # 将字符串中的所有非字母、数字、下划线、短横线、点号和空格字符用下划线 _ 替换掉
    return re.sub('[^\w\-_\. ]', '_', filename)  # 这是源码中的正则

gen_filename(site)

print(gen_filename(site))
```

结果如下：https_www.baidu.com

但是如果把正则修改为：[^\w\-_ ]

结果为：https_www_baidu_com

如果为"."是否影响了文件的存储

**Comment by 1c3z** [comment]
> ```
> logger = get_logger()
> ```

这行后面删除，
domain_parsed 这个函数用来判断是否是合法的域名，然后没让他报错。

**Comment by 1c3z** [comment]
> 关于该文件中的正则表达式是否存在表达式正则出错的问题： 这里我们把函数拿出来做一个测试：
> 
> ```
> import re
> 
> site = "https://www.baidu.com"
> 
> def gen_filename(site):
>     # 将site中的 :// 替换为下划线
>     filename = site.replace('://', '_')
> 
>     # 将字符串中的所有非字母、数字、下划线、短横线、点号和空格字符用下划线 _ 替换掉
>     return re.sub('[^\w\-_\. ]', '_', filename)  # 这是源码中的正则
> 
> gen_filename(site)
> 
> print(gen_filename(site))
> ```
> 
> 结果如下：https_[www.baidu.com](http://www.baidu.com)
> 
> 但是如果把正则修改为：[^\w\-_ ]
> 
> 结果为：https_www_baidu_com
> 
> 如果为"."是否影响了文件的存储

这个. 应该不影响，不过正则可以优化下。

**Comment by 1c3z** [comment]
发布了2.5.4 ，稍微改了一下。
