### ISSUE TITLE
大B段扫描

### ISSUE THREAD

**Issue by flyinbedxyz** [TophantTechnology/ARL#499]
你好，想搭建ARL平台作为甲方内网资产巡检平台，想了解一下针对大B段有没有做扫描网关的优化的策略？类似fscan的优化方式

**Comment by 1c3z** [comment]
什么优化？ 发现存活的C 段？ 

建议先人工用其他工具收集下C 段。

**Comment by flyinbedxyz** [comment]
是的，就是用网关扫出C段再细扫，已经了解到没有这个功能了
