### ISSUE TITLE
更换字典失败

### ISSUE THREAD

**Issue by hysec00** [TophantTechnology/ARL#501]
你好，我用自己的字典覆盖了内置的字典，没有重启，就一直卡死。 req => https://xxxx.com/not_found_2222_111日志里面显示这样。我重新启动镜像他就又变回之前的字典了，这是为什么

**Comment by 1c3z** [comment]
这个是在跑文件目录爆破，站点多这块比较慢。

**Comment by hysec00** [comment]
为啥我自己添加的文件泄露字典，1万跑没啥问题，一多点2万左右，有些路径就跑不出来

**Comment by 1c3z** [comment]
没考虑过这么大的字典，可能OOM了。
