### ISSUE TITLE
any chance to english edition ?

### ISSUE THREAD

**Issue by cdprf** [TophantTechnology/ARL#503]
Hello! I recently discovered your program and I am really impressed with what you have created. I wanted to reach out and let you know that I think it's a great tool that has a lot of potential.

I noticed that the program interface is currently only available in Chineese. Do you have any plans to add support for other languages in the future? As someone who speaks multiple languages, I think it would be really useful to have the option to switch between languages within the program.

Additionally, I noticed that there are a few minor bugs in the current version of the program that I wanted to bring to your attention. Specifically, I have noticed that sometimes when I try to [perform a certain action], the program crashes or freezes. Is this a known issue that you are working on fixing?

Thank you for all of your hard work on this program, and I look forward to seeing what new features and improvements you have in store for the future!

**Comment by 1c3z** [comment]
We appreciate your feedback about adding support for other languages, but unfortunately, we currently do not have plans to add additional language options at this time.

Regarding the bugs you have encountered, we apologize for any inconvenience this may have caused. 
By the way, based on my experience, if the VPS is located outside of China, it would be best to modify the domain name server addresses in app/dicts/dnsserver.txt.

Again, thank you for your interest in our program and please feel free to reach out if you have any further questions or feedback.
