### ISSUE TITLE
Connection refused.

### ISSUE THREAD

**Issue by Ancientmemory** [TophantTechnology/ARL#506]
我的arl_worker.log日志中，报这个错误，我该怎么解决，我web页面也返回不出数据
<img width="1535" alt="image" src="https://user-images.githubusercontent.com/46920942/225852156-0557f4a1-a4fa-4880-8ad6-04bf005daa18.png">

**Comment by 1c3z** [comment]
1. 看看rabbitmq 这个容器是不是还存活,并启动了
2. 进worker 容器看是否能 ping rabbitmq 
3. 看 docker logs -f arl_rabbitmq 有什么错误日志。
4. 是不是在跑任务扫端口？

**Comment by Ancientmemory** [comment]
我的mongo和rabbitmq容器，好像崩溃了，我该怎么操作？
<img width="1246" alt="image" src="https://user-images.githubusercontent.com/46920942/225858037-bd437a7a-2556-49d2-a048-596f36ce3b34.png">
<img width="1125" alt="image" src="https://user-images.githubusercontent.com/46920942/225858083-38541705-7ab6-46b9-952a-55162aaf9184.png">

**Comment by 1c3z** [comment]
1. 检查硬盘是不是满了。 
2. 看有什么错误信息， docker-compose logs -f  --tail=100
3. 重启。
