### ISSUE TITLE
大佬，想学习一下前端 ARL/docker/frontend/

### ISSUE THREAD

**Issue by GYLQ** [TophantTechnology/ARL#507]
## **大佬方便给一下vue项目build前的前端源码 ARL/docker/frontend/ 学习一下吗**
![WP{A 2W(M~Y)DT@)FL866S8](https://user-images.githubusercontent.com/15842234/226111112-21d40fb9-fd4f-4f95-b0cf-931189d5e7df.gif)

**Comment by 1c3z** [comment]
可以在Github上找一些项目，比如：
https://github.com/buqiyuan/vue3-antd-admin

**Comment by GYLQ** [comment]
谢谢师傅
