### ISSUE TITLE
操作系统识别

### ISSUE THREAD

**Issue by smithjat** [TophantTechnology/ARL#51]
应该最可信度最高的，第一个不定是可信度最高的
需要把所有已知的操作系统识别的结果缓存下为，进行可信度排序，然后取可信度最高的版本

**Comment by 1c3z** [comment]
测了下是第一个最高。
![image](https://user-images.githubusercontent.com/9052484/100847567-f55ce780-34ba-11eb-9a79-6e64de2a9c36.png)
