### ISSUE TITLE
【需求】指纹识别

### ISSUE THREAD

**Issue by flyinbedxyz** [TophantTechnology/ARL#511]
想问下目前指纹识别只能支持逻辑或吗，在使用其他脚本导入其他工具的指纹数据发现因为这个原因存在大量误报，可以优化下，或者参考其他指纹工具做一些设计

**Comment by BigYoungs** [comment]
> 想问下目前指纹识别只能支持逻辑或吗，在使用其他脚本导入其他工具的指纹数据发现因为这个原因存在大量误报，可以优化下，或者参考其他指纹工具做一些设计

确实是，现在只支持逻辑或，导致只匹配一个规则，很容易误报，我导入了一堆规则，发现误报率有点高，不过总比没有强

**Comment by 1c3z** [comment]
@BigYoungs 
指纹规则已强化，欢迎更新v2.6.1 ， issue 先关闭。
