### ISSUE TITLE
更改远程mongodb问题

### ISSUE THREAD

**Issue by freeluyishisan** [TophantTechnology/ARL#529]
ARL 资产灯塔系统配置远程的mongodb除了改变config-docker.yaml还需要改变什么吗?为什么改变之后连不了呢?
sed -i 's|mongodb://admin:admin@mongodb:27017/|mongodb://test:aa123456@txx.xxxxxxb.com:27017/|g' config-docker.yaml

**Comment by 1c3z** [comment]
改这个配置就可以，是不是防火墙什么的没关 。

**Comment by freeluyishisan** [comment]
是的是防火墙的问题!感谢
