### ISSUE TITLE
一直在waiting

### ISSUE THREAD

**Issue by ByCold** [TophantTechnology/ARL#53]
本来正常使用，今天添加任务就一直在waiting

**Comment by 1c3z** [comment]
可以执行下面的命令看看有没有异常
```
docker-compose ps 

tail -f arl_web.log
```

**Comment by ByCold** [comment]
![image](https://user-images.githubusercontent.com/49861259/101614283-b9d89500-3a47-11eb-990b-a0a3a0d15810.png)

之前重新安装了，今天升级后又遇到一直在waiting，两次都是在大量删除任务后，再添加任务就一直在waiting了

**Comment by 1c3z** [comment]
本地复测了下, 大量删除任务后，任务可以正常执行。 

再下发下任务，看下有没有报错， 方便的话可以把日志贴出来。 

```
docker-compose logs -f  --tail=10
tail -f *.log
```

另外主机配置是？

**Comment by ByCold** [comment]
配置2核4G  ，貌似是前台停止任务删了任务了，但是后台还在运行，waiting只是还没轮到这个任务

![image](https://user-images.githubusercontent.com/49861259/101627514-5e41e380-3a16-11eb-8fda-f8d86e075ab6.png)

**Comment by 1c3z** [comment]
那应该是批量删除的时候勾选了还在运行的任务，然后给删除了，然后前台看不到了。

**Comment by ByCold** [comment]
建议后续可以加一个批量停止，或者删了任务就自动停止

**Comment by 1c3z** [comment]
@ByCold   
已发布新版本， 任务停止逻辑做了更改，欢迎更新。
