### ISSUE TITLE
异常占用100%

### ISSUE THREAD

**Issue by Axianke** [TophantTechnology/ARL#537]
![图片](https://user-images.githubusercontent.com/60959602/232646553-b89e39ca-0c21-43a7-b74a-a86ce72f2343.png)

**Comment by 1c3z** [comment]
麻烦参考下这个，看有相关异常日志么

https://tophanttechnology.github.io/ARL-doc/faq/#3

**Comment by Axianke** [comment]
![图片](https://user-images.githubusercontent.com/60959602/233514431-c6629133-7e61-4bad-93b1-d4e93672ecb4.png)

**Comment by Axianke** [comment]
现在解决了

**Comment by bingling123** [comment]
麻烦问一下是怎么解决的，我也出现了这个问题重新pull都不好使

**Comment by excellentoldtv** [comment]
师傅，你是怎么解决的，他的报错日志中一直说我config.yaml文件配置不解析，我改了配置文件一样有这个报错，而且连报错行数都没变，不知道是不是改错文件了
![image](https://user-images.githubusercontent.com/30900715/234335747-566b6c71-712a-4512-b7fc-c6741cc7ebac.png)

**Comment by bingling123** [comment]
> 师傅，你是怎么解决的，他的报错日志中一直说我config.yaml文件配置不解析，我改了配置文件一样有这个报错，而且连报错行数都没变，不知道是不是改错文件了 ![image](https://user-images.githubusercontent.com/30900715/234335747-566b6c71-712a-4512-b7fc-c6741cc7ebac.png)

改config-docker.yaml文件试试

**Comment by excellentoldtv** [comment]
问题已解决
