### ISSUE TITLE
带哥们，安装部署完成之后timeout of 12000ms exceeded 是什么情况

### ISSUE THREAD

**Issue by fppecy** [TophantTechnology/ARL#539]
docker安装完成之后https访问192.168.203.132:5003然后就一直是这个界面，连登录界面都没有，kali和centos7都试了都是这种情况，要不就是502配置文件啥的也没动，求带佬帮忙
![image](https://user-images.githubusercontent.com/44750501/233129814-d8d94daa-43ee-4652-84b5-e69f7cacb395.png)
![image](https://user-images.githubusercontent.com/44750501/233130424-7b6070d0-6f76-41cf-9913-301ec1f96cab.png)

**Comment by fppecy** [comment]
> 我那个docekr一直在restarting，在config文件添加riskiq配置https://github.com/TophantTechnology/ARL/blob/8dd790df6afa22b57591ba20f11a4b3b5570130d/docker/config-docker.yaml#LL11-L11C8
![image](https://user-images.githubusercontent.com/44750501/234812918-6bfed7fe-2642-4b85-a7ee-e03066ed4d55.png)

**Comment by BeastNO** [comment]
> > 我的那个docekr一直在重启，在config文件中添加riskiq配置https://github.com/TophantTechnology/ARL/blob/8dd790df6afa22b57591ba20f11a4b3b5570130d/docker/config-docker.yaml#LL11-L11C8
> > ![图像](https://user-images.githubusercontent.com/44750501/234812918-6bfed7fe-2642-4b85-a7ee-e03066ed4d55.png)

师傅riskiq那个网站不给注册了呀
