### ISSUE TITLE
功能需求监测资产信息

### ISSUE THREAD

**Issue by aiwennba** [TophantTechnology/ARL#54]
能不能添加定期资产监测新增资产信息和部分指纹识别功能

**Comment by 1c3z** [comment]
周期资产监测已经在做了。  

部分指纹识别功能是？

**Comment by 1c3z** [comment]
已更新了新版本，请查看

https://github.com/TophantTechnology/ARL/releases/tag/v2.2

**Comment by aiwennba** [comment]
> 周期资产任务已经在做了。
> 
> 部分指纹识别功能是？

部分指纹 就是能识别出来的应用、框架、系统等

**Comment by aiwennba** [comment]
> 周期资产任务已经在做了。
> 
> 部分指纹识别功能是？

看到有finger了
