### ISSUE TITLE
【资产分组】删除资产组后，【任务管理】能否把对应的任务也一起删除？

### ISSUE THREAD

**Issue by ManUtdPudge** [TophantTechnology/ARL#540]
你好，请问【资产分组】删除资产组后，有没办法把【任务管理】里对应的任务也一起删除？现在看着10000条记录，要一页一页去删除太费时间了。

**Comment by 1c3z** [comment]
10000 条有点多，页面最多可以查看500条，

访问这个看看，然后点批量删除，应该是可以删除1000条。

/taskList?page=1&size=1000

**Comment by ManUtdPudge** [comment]
好的，我先用这个来处理无效数据。
