### ISSUE TITLE
请问在资产搜索中看到截图一列都是"截图失败"，哪里能看见原因。

### ISSUE THREAD

**Issue by menchao1992** [TophantTechnology/ARL#541]
![image](https://user-images.githubusercontent.com/102566526/233827162-56039c49-393b-4e26-999b-30670984a836.png)

**Comment by 1c3z** [comment]
arl_worker.log 日志里看看有没有错误。 


源码安装的么？

是的话执行下面的看有没有报错。 
```
phantomjs /opt/ARL/app/tools/screenshot.js -u=https://www.baidu.com/ -s=baidu.jpg
```

**Comment by menchao1992** [comment]
不是,  docker-compose安装的

**Comment by menchao1992** [comment]
1. docker exec进入arl_web运行时容器
2. 执行cd app/tools/ 目录
3. 执行 phantomjs /opt/ARL/app/tools/screenshot.js -u=https://www.baidu.com/ -s=baidu.jpg
4. 报错如下：
Can't open '/opt/ARL/app/tools/screenshot.js'

**Comment by 1c3z** [comment]
docker 环境下的路径是 `/code/app/tools/screenshot.js `

**Comment by menchao1992** [comment]
报错如下：
[root@5dd743b1bf03 app]# /code/app/tools/screenshot.js  -u=https://www.baidu.com/ -s=baidu.jpg
bash: /code/app/tools/screenshot.js: Permission denied

**Comment by menchao1992** [comment]
重启已解决，谢谢。
