### ISSUE TITLE
最新版2.5.4 arl fofa配置失效

### ISSUE THREAD

**Issue by SummerSec** [TophantTechnology/ARL#543]
<img width="1616" alt="image" src="https://user-images.githubusercontent.com/47944478/233832479-3209c298-8299-4f44-9174-8c10e4d573d6.png">

<img width="396" alt="image" src="https://user-images.githubusercontent.com/47944478/233832515-ecfe28c2-1ea8-4fea-81f4-529cc9cb88b0.png">

<img width="613" alt="image" src="https://user-images.githubusercontent.com/47944478/233832540-e137de0e-ce80-47e4-a854-4b2a12a5a8de.png">

**Comment by 1c3z** [comment]
看错误里包含了fofa.so ， 估计没有更新镜像，需要手动pull 镜像。

**Comment by SummerSec** [comment]
> 看错误里包含了fofa.so ， 估计没有更新镜像，需要手动pull 镜像。

使用命令更新也没有用，还是现实相同的错误。重新安装也还是出现这个问题。
```bash
docker-compose down
docker-compose pull 
docker-compose up -d
```

**Comment by 1c3z** [comment]
手动pull 了的话，没成功是不是配置了镜像源？ 

另外重装可以参考下这个。 
https://tophanttechnology.github.io/ARL-doc/faq/#12-docker

**Comment by SummerSec** [comment]
> 手动pull 了的话，没成功是不是配置了镜像源？
> 
> 另外重装可以参考下这个。 https://tophanttechnology.github.io/ARL-doc/faq/#12-docker

有没有办法可以查看版本呢？因为现在无法确定具体的版本

**Comment by 1c3z** [comment]
登录页面有版本
进系统内底部也有版本

**Comment by SummerSec** [comment]
> 登录页面有版本 进系统内底部也有版本

只有大版本，2.5，没有具体的小版本。

**Comment by 1c3z** [comment]
2.5可以理解为2.5.0 , 没有升级好。

**Comment by SummerSec** [comment]
解决了，确实是镜像源的问题。
