### ISSUE TITLE
关于开发学习上的一个请教

### ISSUE THREAD

**Issue by JYThomas** [TophantTechnology/ARL#546]
hello, 在学习ARL的源码时发现端口扫描用的是python-nmap做端口扫描和主机操作系统识别，在借鉴了项目的源码之后使用python-nmap进行主机操作系统识别时，遇到没有root权限的情况，想请教一下该如何解决呢？
下面是报错信息：
nmap.nmap.PortScannerError: 'TCP/IP fingerprinting (for OS scan) requires root privileges.\nQUITTING!\n'

**Comment by 1c3z** [comment]
可以先判断下有没有root权限，没有root权限，不让进行操作系统识别。

**Comment by JYThomas** [comment]
好的大佬，感谢解惑。还有一个问题想请教一下 就是要设计周期任务执行的话 是不是就得做一个调度器实时监控周期任务的时间来进行调度任务啊？想请教一下你们做这个的时候是怎么设计的？思路和工具有推荐的吗？

**Comment by JYThomas** [comment]
好的好的，感谢解惑^_^
