### ISSUE TITLE
建议增加批量导出

### ISSUE THREAD

**Issue by harris2015** [TophantTechnology/ARL#55]
如题
建议增加批量导出 如批量导出子域名

**Comment by 1c3z** [comment]
批量导出多个文件?   一下下载保存多个文件，这个体验有时候会很差。

**Comment by harris2015** [comment]
可以导出到一个文件里 现在是一个个点 手都点酸了

**Comment by 1c3z** [comment]
哈哈，欢迎来提PR, 解决手酸的问题

**Comment by harris2015** [comment]
另外提个bug 你们的doc文档为啥docker里面没有了？

**Comment by 1c3z** [comment]
什么 doc文档 ?

**Comment by harris2015** [comment]
api那个啊

**Comment by 1c3z** [comment]
docker环境确实有点问题。

可以先手工解决下。 

```
docker-compose exec  web bash
vi /etc/nginx/nginx.conf
nginx -s reload
```

将nginx.conf 48行改成如下

![image](https://user-images.githubusercontent.com/9052484/102183449-d3b32580-3ee8-11eb-9cee-0894a9cd42c6.png)

```
proxy_set_header   Host    $http_host;
```

然后访问`/api/doc` 就可以了。

**Comment by 1c3z** [comment]
@harris2015  
已更新，欢迎体验。
