### ISSUE TITLE
我的风险巡航任务一直是waiting状态

### ISSUE THREAD

**Issue by Ancientmemory** [TophantTechnology/ARL#552]
大佬，我有2个任务类型，一个资产监控，一个风险巡航，是要等资产监控执行完成后，才会执行风险巡航吗？目前风险巡航任务一直是waiting，vps是6c10g的，可以这2个任务一起执行吗？谢谢大佬。

**Comment by 1c3z** [comment]
前面的任务执行完了，风险巡航任务就会执行的，看时间顺序。 

看任务管理里面有任务在运行么，如果没有的话，风险巡航任务一直是waiting，可以把这个删了再下个试试。 

最好配合日志一起排查。
https://tophanttechnology.github.io/ARL-doc/faq/#3

**Comment by Ancientmemory** [comment]
大佬，我运行风险巡航任务，它的状态是error，日志是这样的
我该怎么处理下啊，谢谢大佬
<img width="1782" alt="image" src="https://user-images.githubusercontent.com/46920942/236741219-92a9b431-e587-4575-a687-95a73801449f.png">

**Comment by 1c3z** [comment]
运行超时了，新版本已经加大了运行时间。

**Comment by Ancientmemory** [comment]
谢谢大哥，大哥牛啤，好人一生平安



| |
第十三本书
|
|
***@***.***
|


---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 发送日期 | 2024年05月7日 15:51 |
| 收件人 | ***@***.***> |
| 抄送人 | ***@***.***> ,
***@***.***> |
| 主题 | Re: [TophantTechnology/ARL] 我的风险巡航任务一直是waiting状态 (Issue #552) |

运行超时了，新版本已经加大了运行时间。
