### ISSUE TITLE
灯塔前端源码问题

### ISSUE THREAD

**Issue by HOBOgit** [TophantTechnology/ARL#554]
我想问下有灯塔的前端页面源码吗？  没经过编译加密那种的。

**Comment by 1c3z** [comment]
前端代码目前不开放哦

**Comment by HOBOgit** [comment]
大佬您好， 我想改一下前端的logo和整体颜色， 请问这个使用是否需要商业授权？  



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2023年05月08日 10:36 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [TophantTechnology/ARL] 灯塔前端源码问题 (Issue #554) |

前端代码目前不开放哦
