### ISSUE TITLE
子域名收集过程中，有没有可能把站点爬虫的结果也加入进去？还是说已经有相关功能了？

### ISSUE THREAD

**Issue by JoJenH** [TophantTechnology/ARL#556]
测试过程中，任务目标是360.net，其443端口主页有指向study.360.net的链接。已经启用了站点爬虫模块，但是子域名中并没有收集到study.360.net，是否考虑集成相关功能，还是说该已经实现只是出现了一些Bug？

**Comment by 1c3z** [comment]
目前爬虫只会收集URL ,没有收集域名。   
主要流程不太一样，新发现了域名，但是到了爬虫这一步域名的流程都处理完了，逻辑有点复杂。 

后期可能需要优化下。

**Comment by 1c3z** [comment]
2.6.1 引入了WIH 可以实现，先关闭。
