### ISSUE TITLE
关于ARL历史查询功能结果大幅遗漏问题

### ISSUE THREAD

**Issue by JoJenH** [TophantTechnology/ARL#557]
![image](https://user-images.githubusercontent.com/45531537/236964398-4714f6a8-2753-428f-a09e-a20a56009c8c.png)
如图，创建了两个任务，下面的任务由于截图卡死所以停掉了，该任务共发现305个站点
![image](https://user-images.githubusercontent.com/45531537/236964509-81faf5d3-8ca1-4142-befc-d85ff991b1c9.png)
后新建新任务，只开启了ARL历史以及站点截图
![image](https://user-images.githubusercontent.com/45531537/236964640-bd0d2025-3991-425b-a3a2-8febe5db9e3c.png)
但是其站点信息只有107项，是我对ARL历史查询存在误解吗？还是出现了一定的Bug？

**Comment by 1c3z** [comment]
历史查询只会查域名。 

306个站点的，应该是多了很多非80,443 端口的网页。

后新建新任务，只开启了ARL历史以及站点截图，可以把端口扫描开启试下。
