### ISSUE TITLE
连接Fofa API异常 error:encoding with 'idna' codec failed (UnicodeError: label too long)

### ISSUE THREAD

**Issue by li-baige** [TophantTechnology/ARL#569]
如上，这是为啥报错了呢，检查了配置文件，fofa配置是合适的啊
<img width="433" alt="截屏2023-06-03 17 22 18" src="https://github.com/TophantTechnology/ARL/assets/76275424/bedef6c1-40fd-483a-bfbf-6d5042f2692e">

**Comment by 1c3z** [comment]
输入了全角的字符？
