### ISSUE TITLE
数据源 hunter_qax 处理错误

### ISSUE THREAD

**Issue by ddostest123** [TophantTechnology/ARL#571]
version:v2.5.5
<img width="915" alt="image" src="https://github.com/TophantTechnology/ARL/assets/83945365/d74d1c0d-efc5-470f-ae60-d7bec4353571">

测试结果：发现hunter_qax，成功查询到数据后，在处理的过程中存在问题；在web通过【资产搜索】-【子域名】-【来源】，搜索为hunter_qax的数据，发现不存在，可能没入库。
<img width="1218" alt="image" src="https://github.com/TophantTechnology/ARL/assets/83945365/233c4937-f678-410e-986d-498eeba570f2">

<img width="1585" alt="image" src="https://github.com/TophantTechnology/ARL/assets/83945365/fa82fec8-3a03-409e-815e-05f519e0eab6">

查询信息：
<img width="1218" alt="image" src="https://github.com/TophantTechnology/ARL/assets/83945365/78d74cdc-c3bc-444d-a244-96d7cfd95787">

**Comment by 1c3z** [comment]
图片中的为测试操作，不设计到入库操作。

**Comment by ddostest123** [comment]
非常感谢师傅，是我这边的测试问题。😊
