### ISSUE TITLE
版本ARL 2.5.5 死机问题

### ISSUE THREAD

**Issue by 363401794** [TophantTechnology/ARL#576]
ARL 2.5.5 ，服务器带宽8h8g5m,使用2.5.5版本服务器无响应直接。怀疑有死循环卡死了服务器。

**Comment by anfugui** [comment]
一样 我4h4g  装完任何功能都用不了 直接是响应超时。 登录页面都返回不到。

**Comment by 1c3z** [comment]
看看日志吧，这个描述我也看不出什么问题。

https://tophanttechnology.github.io/ARL-doc/faq/#3

卡死可以看看是CPU问题，还是带宽问题，或者磁盘问题。 内存问题等。 


卡死前下了什么任务，勾选了什么选项。

**Comment by anfugui** [comment]
安装完就这样 ，&nbsp; 安装完 直接访问WEB&nbsp; 就是12000超市，没有任何操作。重装系统，重下ARL几次了都一样，docker_arl/weblog&nbsp; 没内容。 腾讯云的四核4G&nbsp; &nbsp;之前用的老版本 都没问题。selinux也关了






321661676
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "TophantTechnology/ARL"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年6月20日(星期二) 下午2:06
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [TophantTechnology/ARL] 版本ARL 2.5.5 死机问题 (Issue #576)





 
看看日志吧，这个描述我也看不出什么问题。
 
https://tophanttechnology.github.io/ARL-doc/faq/#3
 
卡死可以看看是CPU问题，还是带宽问题，或者磁盘问题。 内存问题等。
 
卡死前下了什么任务，勾选了什么选项。

**Comment by anfugui** [comment]
找到报错了 大佬。



















------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "TophantTechnology/ARL"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年6月20日(星期二) 下午2:06
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [TophantTechnology/ARL] 版本ARL 2.5.5 死机问题 (Issue #576)





 
看看日志吧，这个描述我也看不出什么问题。
 
https://tophanttechnology.github.io/ARL-doc/faq/#3
 
卡死可以看看是CPU问题，还是带宽问题，或者磁盘问题。 内存问题等。
 
卡死前下了什么任务，勾选了什么选项。

**Comment by anfugui** [comment]
现在github上的新版本在安装之后是无法正常运行。原因是配置文件中缺少参数，建议改一下，要不然很多新手找不到问题在哪。


我放在issus了。 感谢大佬昨天的回复，历时两天终于找到问题所在了。。。



















321661676
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "TophantTechnology/ARL"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年6月20日(星期二) 下午2:06
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [TophantTechnology/ARL] 版本ARL 2.5.5 死机问题 (Issue #576)





 
看看日志吧，这个描述我也看不出什么问题。
 
https://tophanttechnology.github.io/ARL-doc/faq/#3
 
卡死可以看看是CPU问题，还是带宽问题，或者磁盘问题。 内存问题等。
 
卡死前下了什么任务，勾选了什么选项。
