### ISSUE TITLE
任务结果中有很多子域名，但是站点、ip等信息都扫描不出来，请问是什么原因了

### ISSUE THREAD

**Issue by fjcom** [TophantTechnology/ARL#577]

**Comment by 1c3z** [comment]
https://tophanttechnology.github.io/ARL-doc/faq/#10 
看是不是这个问题。

**Comment by tonmonkey** [comment]
@1c3z 不像是被拦截了，我重跑了一次，结果一样，：
![image](https://github.com/TophantTechnology/ARL/assets/84943423/b3ba1762-ca8c-4ed8-b837-b72ea4ee2e8c)
然后将一样的子域名放到finger中跑，存活的站点是24个：
![image](https://github.com/TophantTechnology/ARL/assets/84943423/8ce24981-79cc-4d0f-845e-eb4242af11b7)
