### ISSUE TITLE
2.5.5版本 4核4G  CPU直接跑满  系统起不来 无法使用

### ISSUE THREAD

**Issue by anfugui** [TophantTechnology/ARL#578]
2.5.5 使用docker配置文件安装、docker安装、源码安装都试了。 安装完之后 所有功能都是超时用不了，cpu直接跑到100.依赖都装了。还有可能是哪里有问题啊

**Comment by 1c3z** [comment]
看看日志吧，这个描述我也看不出什么问题。

https://tophanttechnology.github.io/ARL-doc/faq/#3

**Comment by anfugui** [comment]
大佬 我查了半天 现在docke有两个镜像 WEB和scheduler&nbsp; &nbsp;一直在重启&nbsp; &nbsp;应该是这里的问题。是我服务器的问题吗？












 
看看日志吧，这个描述我也看不出什么问题。
 
https://tophanttechnology.github.io/ARL-doc/faq/#3

**Comment by 1c3z** [comment]
是不是改过配置，

镜像是不是忘记pull 了？ 

配置了镜像源么？配置了的话要删除，再重新pull镜像。
