### ISSUE TITLE
连接fofa api异常

### ISSUE THREAD

**Issue by hellowchen** [TophantTechnology/ARL#579]
![image](https://github.com/TophantTechnology/ARL/assets/70270477/1820f212-ccd9-4d59-9457-a655d694c763)

连接Fofa API异常 error:HTTPSConnectionPool(host='fofa.so', port=443): Max retries exceeded with url: /api/v1/search/all?email=xxx&key=***&qbase64=ZG9tYWluPSJiYWlkdS5jb20i&size=1 (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7fbd0c4203c8>: Failed to establish a new connection: [Errno -2] Name or service not known',)) 怎么请求的是fofa.so的域名,这个是什么问题。

**Comment by 1c3z** [comment]
应该是镜像没更新。

可以检查下 docker-compose.yml 里面的版本。

**Comment by hellowchen** [comment]
![image](https://github.com/TophantTechnology/ARL/assets/70270477/c8fa95b8-3a95-45d1-aa22-bd987ab09e0c)
版本好像没什么问题，安装了是最新的2.5.5版本，重新安装了一下还是存在这个问题。

**Comment by 1c3z** [comment]
登陆页面底下有个版本，显示的是最新的么？
