### ISSUE TITLE
2.5.5新版本安装完成后（timeout of 12000ms exceeded）问题解决办法

### ISSUE THREAD

**Issue by anfugui** [TophantTechnology/ARL#580]
在/ARL/docker目录下 config-docker.yaml中添加下面内容就可以解决 。  注意代码对齐

RISKIQ:
   EMAIL: "[xxxxxxxxx@qq.com](mailto:xxxxxxxxx@qq.com)"
   KEY: "xxxxxxxxxxx"

**Comment by 1c3z** [comment]
感谢反馈，如果镜像更新了的话这个配置已经不需要配置了。


https://github.com/TophantTechnology/ARL/issues/379

**Comment by hookdd** [comment]
为什么我今天刚安装还是有这个问题！！！
