### ISSUE TITLE
nuclei模块没了

### ISSUE THREAD

**Issue by shad0w0sec** [TophantTechnology/ARL#581]
为什么在任务管理中没有nuclei调用了呢，最新docker版本

![屏幕截图 2023-06-21 162524](https://github.com/TophantTechnology/ARL/assets/73059812/554d0447-55a7-4fb3-b1d6-98c3743966c1)

**Comment by shad0w0sec** [comment]
跳过CDN，域名查询插件也没了

**Comment by shad0w0sec** [comment]
这是之前安装的
![image](https://github.com/TophantTechnology/ARL/assets/73059812/106f1245-fd96-4302-8e7f-bf7283a0bb2a)

**Comment by 1c3z** [comment]
有点奇怪，F5 刷新下呢。

另外最下面显示的版本是什么？ 镜像忘记更新了？

**Comment by shad0w0sec** [comment]
好像是我用了第三方docker源的问题，目前已经解决了
