### ISSUE TITLE
灯塔的nuclei 怎么使用自己的yaml  存放路径在什么位置

### ISSUE THREAD

**Issue by linkk9** [TophantTechnology/ARL#588]

**Comment by linkk9** [comment]
![image](https://github.com/TophantTechnology/ARL/assets/81364075/55ff3684-7b97-4932-b12d-9d23edb035c1)

这个调用是我需要自己下载 存放在什么目录呢
还是内置nuclei   或者更改什么配置调用nuclei

**Comment by 1c3z** [comment]
内置的，nuclei默认路径。

/root/nuclei-templates
