### ISSUE TITLE
更新后不能批量添加c段，域名

### ISSUE THREAD

**Issue by Ethancck** [TophantTechnology/ARL#59]

**Comment by 1c3z** [comment]
资产管理页面内的添加现在还不支持添加ip 和批量加域名。

**Comment by Ethancck** [comment]
还有一个bug就是暂停进行中的任务后，任务删除不了，也不能继续

**Comment by 1c3z** [comment]
目前任务不能暂停的，可能是任务没有执行完。

可以参考下这个。
https://github.com/TophantTechnology/ARL/issues/47

**Comment by LandGrey** [comment]
现在还是不支持批量录入已有域名资产吗？

**Comment by 1c3z** [comment]
![image](https://user-images.githubusercontent.com/9052484/140487496-548082b9-f3f8-4793-8ac3-7f27d5c9d94e.png)
@LandGrey  可以的哦。
