### ISSUE TITLE
超时

### ISSUE THREAD

**Issue by nf592** [TophantTechnology/ARL#590]
docker容器状态不是up
![image](https://github.com/TophantTechnology/ARL/assets/49084918/dfd146a2-3175-4123-b6a3-22dd5e02a2d5)
web显示超时
![image](https://github.com/TophantTechnology/ARL/assets/49084918/98431279-d8b5-4083-a2d8-82ebc9b2a4a4)

**Comment by ox01024** [comment]
docker logs -f arl_schedule 
docker logs -f arl_worker 
看看日志

**Comment by nf592** [comment]
![image](https://github.com/TophantTechnology/ARL/assets/49084918/fe2687cd-74d1-46c0-88ac-ed72e307560d)
这是什么原因呢

**Comment by ox01024** [comment]
docker logs -f arl_scheduler 把日志文件发上来看看吧

**Comment by nf592** [comment]
wait-for-it.sh: waiting 15 seconds for mongodb:27017
wait-for-it.sh: mongodb:27017 is available after 2 seconds
wait-for-it.sh: waiting 15 seconds for rabbitmq:5672
wait-for-it.sh: rabbitmq:5672 is available after 7 seconds
Parse config.yaml error 'RISKIQ'
wait-for-it.sh: waiting 15 seconds for mongodb:27017
wait-for-it.sh: mongodb:27017 is available after 0 seconds
wait-for-it.sh: waiting 15 seconds for rabbitmq:5672
wait-for-it.sh: rabbitmq:5672 is available after 0 seconds
Parse config.yaml error 'RISKIQ'
wait-for-it.sh: waiting 15 seconds for mongodb:27017
wait-for-it.sh: mongodb:27017 is available after 0 seconds
wait-for-it.sh: waiting 15 seconds for rabbitmq:5672
wait-for-it.sh: rabbitmq:5672 is available after 0 seconds
Parse config.yaml error 'RISKIQ'
wait-for-it.sh: waiting 15 seconds for mongodb:27017
wait-for-it.sh: mongodb:27017 is available after 0 seconds
wait-for-it.sh: waiting 15 seconds for rabbitmq:5672
wait-for-it.sh: rabbitmq:5672 is available after 0 seconds
Parse config.yaml error 'RISKIQ'
wait-for-it.sh: waiting 15 seconds for mongodb:27017
wait-for-it.sh: mongodb:27017 is available after 1 seconds
wait-for-it.sh: waiting 15 seconds for rabbitmq:5672
wait-for-it.sh: rabbitmq:5672 is available after 0 seconds
Parse config.yaml error 'RISKIQ'
wait-for-it.sh: waiting 15 seconds for mongodb:27017
wait-for-it.sh: mongodb:27017 is available after 0 seconds
wait-for-it.sh: waiting 15 seconds for rabbitmq:5672
wait-for-it.sh: rabbitmq:5672 is available after 0 seconds
Parse config.yaml error 'RISKIQ'
wait-for-it.sh: waiting 15 seconds for mongodb:27017
wait-for-it.sh: mongodb:27017 is available after 0 seconds
wait-for-it.sh: waiting 15 seconds for rabbitmq:5672
wait-for-it.sh: rabbitmq:5672 is available after 0 seconds
Parse config.yaml error 'RISKIQ'
wait-for-it.sh: waiting 15 seconds for mongodb:27017
wait-for-it.sh: mongodb:27017 is available after 0 seconds
wait-for-it.sh: waiting 15 seconds for rabbitmq:5672
wait-for-it.sh: rabbitmq:5672 is available after 0 seconds
Parse config.yaml error 'RISKIQ'
wait-for-it.sh: waiting 15 seconds for mongodb:27017
wait-for-it.sh: mongodb:27017 is available after 0 seconds
wait-for-it.sh: waiting 15 seconds for rabbitmq:5672
wait-for-it.sh: rabbitmq:5672 is available after 0 seconds
Parse config.yaml error 'RISKIQ'
wait-for-it.sh: waiting 15 seconds for mongodb:27017
wait-for-it.sh: mongodb:27017 is available after 0 seconds
wait-for-it.sh: waiting 15 seconds for rabbitmq:5672
wait-for-it.sh: rabbitmq:5672 is available after 0 seconds
Parse config.yaml error 'RISKIQ'
wait-for-it.sh: waiting 15 seconds for mongodb:27017
wait-for-it.sh: mongodb:27017 is available after 0 seconds
wait-for-it.sh: waiting 15 seconds for rabbitmq:5672
wait-for-it.sh: rabbitmq:5672 is available after 0 seconds
Parse config.yaml error 'RISKIQ'
wait-for-it.sh: waiting 15 seconds for mongodb:27017
wait-for-it.sh: mongodb:27017 is available after 0 seconds
wait-for-it.sh: waiting 15 seconds for rabbitmq:5672
wait-for-it.sh: rabbitmq:5672 is available after 0 seconds
Parse config.yaml error 'RISKIQ'
wait-for-it.sh: waiting 15 seconds for mongodb:27017
wait-for-it.sh: mongodb:27017 is available after 0 seconds
wait-for-it.sh: waiting 15 seconds for rabbitmq:5672
wait-for-it.sh: rabbitmq:5672 is available after 0 seconds
Parse config.yaml error 'RISKIQ'
wait-for-it.sh: waiting 15 seconds for mongodb:27017
wait-for-it.sh: mongodb:27017 is available after 0 seconds
wait-for-it.sh: waiting 15 seconds for rabbitmq:5672
wait-for-it.sh: rabbitmq:5672 is available after 0 seconds
Parse config.yaml error 'RISKIQ'
wait-for-it.sh: waiting 15 seconds for mongodb:27017
wait-for-it.sh: mongodb:27017 is available after 0 seconds
wait-for-it.sh: waiting 15 seconds for rabbitmq:5672
wait-for-it.sh: rabbitmq:5672 is available after 0 seconds
Parse config.yaml error 'RISKIQ'
wait-for-it.sh: waiting 15 seconds for mongodb:27017
wait-for-it.sh: mongodb:27017 is available after 0 seconds
wait-for-it.sh: waiting 15 seconds for rabbitmq:5672
wait-for-it.sh: rabbitmq:5672 is available after 0 seconds
Parse config.yaml error 'RISKIQ'
wait-for-it.sh: waiting 15 seconds for mongodb:27017
wait-for-it.sh: mongodb:27017 is available after 0 seconds
wait-for-it.sh: waiting 15 seconds for rabbitmq:5672
wait-for-it.sh: rabbitmq:5672 is available after 0 seconds
Parse config.yaml error 'RISKIQ'
wait-for-it.sh: waiting 15 seconds for mongodb:27017
wait-for-it.sh: mongodb:27017 is available after 0 seconds
wait-for-it.sh: waiting 15 seconds for rabbitmq:5672
wait-for-it.sh: rabbitmq:5672 is available after 0 seconds
Parse config.yaml error 'RISKIQ'
wait-for-it.sh: waiting 15 seconds for mongodb:27017
wait-for-it.sh: mongodb:27017 is available after 0 seconds
wait-for-it.sh: waiting 15 seconds for rabbitmq:5672
wait-for-it.sh: rabbitmq:5672 is available after 0 seconds
Parse config.yaml error 'RISKIQ'
wait-for-it.sh: waiting 15 seconds for mongodb:27017
wait-for-it.sh: mongodb:27017 is available after 0 seconds
wait-for-it.sh: waiting 15 seconds for rabbitmq:5672
wait-for-it.sh: rabbitmq:5672 is available after 0 seconds
Parse config.yaml error 'RISKIQ'
wait-for-it.sh: waiting 15 seconds for mongodb:27017
wait-for-it.sh: mongodb:27017 is available after 0 seconds
wait-for-it.sh: waiting 15 seconds for rabbitmq:5672
wait-for-it.sh: rabbitmq:5672 is available after 0 seconds
Parse config.yaml error 'RISKIQ'
wait-for-it.sh: waiting 15 seconds for mongodb:27017
wait-for-it.sh: mongodb:27017 is available after 0 seconds
wait-for-it.sh: waiting 15 seconds for rabbitmq:5672
wait-for-it.sh: rabbitmq:5672 is available after 0 seconds
Parse config.yaml error 'RISKIQ'
wait-for-it.sh: waiting 15 seconds for mongodb:27017
wait-for-it.sh: mongodb:27017 is available after 0 seconds
wait-for-it.sh: waiting 15 seconds for rabbitmq:5672
wait-for-it.sh: rabbitmq:5672 is available after 0 seconds
Parse config.yaml error 'RISKIQ'
wait-for-it.sh: waiting 15 seconds for mongodb:27017
wait-for-it.sh: mongodb:27017 is available after 0 seconds
wait-for-it.sh: waiting 15 seconds for rabbitmq:5672
wait-for-it.sh: rabbitmq:5672 is available after 0 seconds
Parse config.yaml error 'RISKIQ'
wait-for-it.sh: waiting 15 seconds for mongodb:27017
wait-for-it.sh: mongodb:27017 is available after 0 seconds
wait-for-it.sh: waiting 15 seconds for rabbitmq:5672
wait-for-it.sh: rabbitmq:5672 is available after 0 seconds
Parse config.yaml error 'RISKIQ'
wait-for-it.sh: waiting 15 seconds for mongodb:27017
wait-for-it.sh: mongodb:27017 is available after 0 seconds
wait-for-it.sh: waiting 15 seconds for rabbitmq:5672
wait-for-it.sh: rabbitmq:5672 is available after 0 seconds
Parse config.yaml error 'RISKIQ'
wait-for-it.sh: waiting 15 seconds for mongodb:27017
wait-for-it.sh: mongodb:27017 is available after 0 seconds
wait-for-it.sh: waiting 15 seconds for rabbitmq:5672
wait-for-it.sh: rabbitmq:5672 is available after 0 seconds
Parse config.yaml error 'RISKIQ'
wait-for-it.sh: waiting 15 seconds for mongodb:27017
wait-for-it.sh: mongodb:27017 is available after 0 seconds
wait-for-it.sh: waiting 15 seconds for rabbitmq:5672
wait-for-it.sh: rabbitmq:5672 is available after 0 seconds
Parse config.yaml error 'RISKIQ'
wait-for-it.sh: waiting 15 seconds for mongodb:27017
wait-for-it.sh: mongodb:27017 is available after 0 seconds
wait-for-it.sh: waiting 15 seconds for rabbitmq:5672
wait-for-it.sh: rabbitmq:5672 is available after 0 seconds
Parse config.yaml error 'RISKIQ'
wait-for-it.sh: waiting 15 seconds for mongodb:27017
wait-for-it.sh: mongodb:27017 is available after 0 seconds
wait-for-it.sh: waiting 15 seconds for rabbitmq:5672
wait-for-it.sh: rabbitmq:5672 is available after 0 seconds
Parse config.yaml error 'RISKIQ'
wait-for-it.sh: waiting 15 seconds for mongodb:27017
wait-for-it.sh: mongodb:27017 is available after 0 seconds
wait-for-it.sh: waiting 15 seconds for rabbitmq:5672
wait-for-it.sh: rabbitmq:5672 is available after 0 seconds
Parse config.yaml error 'RISKIQ'
wait-for-it.sh: waiting 15 seconds for mongodb:27017
wait-for-it.sh: mongodb:27017 is available after 0 seconds
wait-for-it.sh: waiting 15 seconds for rabbitmq:5672
wait-for-it.sh: rabbitmq:5672 is available after 0 seconds
Parse config.yaml error 'RISKIQ'
wait-for-it.sh: waiting 15 seconds for mongodb:27017
wait-for-it.sh: mongodb:27017 is available after 0 seconds
wait-for-it.sh: waiting 15 seconds for rabbitmq:5672
wait-for-it.sh: rabbitmq:5672 is available after 0 seconds
Parse config.yaml error 'RISKIQ'

**Comment by nf592** [comment]
排查是docker容器本身的问题，重装即可。。

**Comment by BeastNO** [comment]
> 

是重装docker？

**Comment by ox01024** [comment]
#580 看一下这个 另外使用最新镜像不会存在该问题 可能是docker镜像源 太老
