### ISSUE TITLE
开发大大好，如何关闭灯塔默认存活检测

### ISSUE THREAD

**Issue by excellentoldtv** [TophantTechnology/ARL#598]
我修改了配置代码：
https://github.com/TophantTechnology/ARL/blob/master/app/services/portScan.py#L15
新增了-Pn参数

1.修改好配置，重启docker
![image](https://github.com/TophantTechnology/ARL/assets/30900715/9328f99f-5fbb-435c-a174-272645e4a582)

![image](https://github.com/TophantTechnology/ARL/assets/30900715/60286ba4-597d-469d-aa16-ae20200059da)

2.端口扫描关闭了icmp响应的主机时还是会 检测存活，导致直接关闭扫描，无法正常扫描站点端口。
![image](https://github.com/TophantTechnology/ARL/assets/30900715/3b7016bd-aa68-445d-962b-ad6fa2add328)

**Comment by 1c3z** [comment]
应该是重启错容器了。 
![image](https://github.com/TophantTechnology/ARL/assets/9052484/c5873646-fa9e-4a68-83a0-2099dc257644)

**Comment by excellentoldtv** [comment]
确实是重启错容器了，问题已解决，谢谢大大
