### ISSUE TITLE
开发大大好，灯塔扫描内网时，为何会自己添加XFF?

### ISSUE THREAD

**Issue by hanqianye** [TophantTechnology/ARL#599]
内网安全设备，检测灯塔伪造XFF

GET /nacos/ HTTP/1.1
Host: XXX
User-Agent: Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.45 Safari/537.36
Accept-Encoding: gzip, deflate
Accept: */*
Connection: keep-alive
X-Real-IP: 10.0.88.146
X-Forwarded-For: 10.0.88.146

**Comment by hanqianye** [comment]
灯塔做10地址段的内网扫描时，伪造了大量XFF的10.0.X.X的地址段。这是为何？如何取消插入XFF字段的功能？

**Comment by 1c3z** [comment]
这个是在NPoC 里面添加的 

https://github.com/1c3z/ARL-NPoC/blob/master/xing/utils/__init__.py#L127


容器目录为  /opt/ARL-NPoC/
