### ISSUE TITLE
扫描增加多网段格式

### ISSUE THREAD

**Issue by zhengjim** [TophantTechnology/ARL#6]
星光大佬，测试发现不支持 127.0.0.1-255 127.0.0.1-127.0.0.255这种格式的网段。
另外有限制qps嘛？

**Comment by zhengjim** [comment]
另外，单账号只允许一个人登录。别人登录，原来登录的会退出。有点不方便

**Comment by 1c3z** [comment]
支持 127.0.0.1-255 这种格式，另一种不支持，另外请注意下发的IP是否在黑名单里面，前端提示不够友好。
https://github.com/TophantTechnology/ARL/blob/master/docker/config-docker.yaml#L29

**Comment by 1c3z** [comment]
帐号问题，可以自己手工再添加一个帐号。 
docker exec -ti arl_mongodb mongo -u admin -p admin 
使用use arl切换数据库
执行
```
db.user.insert({ username: 'user1',  password: hex_md5('arlsalt!@#'+'arlpass') })
```

**Comment by zhaozebuchixiaobinggan** [comment]
可以详细的说明一下怎么添加账户和密码为 admin/admin吗。这么按照你的办法测试还是登录不上去  感谢

**Comment by 1c3z** [comment]
执行下面的就可以。`arlsalt!@#`这个是盐保持不变就行。 

```
db.user.insert({ username: 'admin',  password: hex_md5('arlsalt!@#'+'admin') })
```

@zhaozebuchixiaobinggan

**Comment by zhengjim** [comment]
@1c3z 星光哥，时区不对。
![image](https://user-images.githubusercontent.com/20296689/93035467-9f249900-f66f-11ea-8934-50f2983bc0de.png)
![image](https://user-images.githubusercontent.com/20296689/93035502-b794b380-f66f-11ea-9c89-e44de993dea3.png)

**Comment by 1c3z** [comment]
@zhengjim   
给worker 添加环境遍历
```
TZ=Asia/Shanghai
```
![image](https://user-images.githubusercontent.com/9052484/93042580-021f2b80-f682-11ea-8c48-563883ed05f6.png)

执行
```
docker-compose kill worker
docker-compose up -d
```
