### ISSUE TITLE
风险巡航任务不执行，1c3z哥哥帮忙看一下，谢谢

### ISSUE THREAD

**Issue by Ancientmemory** [TophantTechnology/ARL#600]
1c3z哥哥，我下发了一个风险巡航任务，但是一直不执行，其他任务都停止了，
<img width="1121" alt="image" src="https://github.com/TophantTechnology/ARL/assets/46920942/3bd9a26d-d2eb-46d5-91e2-22ec4be64e7e">
一直是这个状态
<img width="1174" alt="image" src="https://github.com/TophantTechnology/ARL/assets/46920942/50de9768-c3b0-4870-9b9d-cb19f58ecf20">
我看日志，有个这个错误，不知道是不是跟这个有关系，哥哥帮忙看一下，谢谢
<img width="1291" alt="image" src="https://github.com/TophantTechnology/ARL/assets/46920942/627abd7a-8d34-4144-970d-bb3d6e6699e4">
docker状态都是好的
<img width="1156" alt="image" src="https://github.com/TophantTechnology/ARL/assets/46920942/3a006496-456b-4f87-bb35-9abe55d28768">

**Comment by 1c3z** [comment]
把任务停止了，docker-compose restart 看看。 再下个小任务测试看看。 然后再重启这个任务试试。
