### ISSUE TITLE
quake的api添加后灯塔报错

### ISSUE THREAD

**Issue by keyuan15** [TophantTechnology/ARL#601]
quanke的api添加后灯塔就报错了，可能是哪里没弄对。有添加的说明吗？

**Comment by acmglz** [comment]
我除了fofa,所有的api添加后都报错,说没有在config中mapping到

**Comment by 1c3z** [comment]
有报错信息么？ 
应该是格式没有改对。

这个加的key 在冒号后要有个空格。

![image](https://github.com/TophantTechnology/ARL/assets/9052484/0643addf-eac9-4355-b6de-a70590fc39b7)

**Comment by keyuan15** [comment]
是按照要求设置的，但还是报错
![image](https://github.com/TophantTechnology/ARL/assets/56430812/0e8d6290-f393-42f3-9724-30adad827f30)
![image](https://github.com/TophantTechnology/ARL/assets/56430812/fa8094e2-e4bb-4009-8626-65844c3b73c8)
![image](https://github.com/TophantTechnology/ARL/assets/56430812/1637670f-72e1-483e-a423-adeca9ea0a2f)

**Comment by keyuan15** [comment]
> 有报错信息么？ 应该是格式没有改对。
> 
> 这个加的key 在冒号后要有个空格。
> 
> ![图像](https://user-images.githubusercontent.com/9052484/255056702-0643addf-eac9-4355-b6de-a70590fc39b7.png)



> 有报错信息么？ 应该是格式没有改对。
> 
> 这个加的key 在冒号后要有个空格。
> 
> ![图像](https://user-images.githubusercontent.com/9052484/255056702-0643addf-eac9-4355-b6de-a70590fc39b7.png)

是按照要求设置的，但还是报错
![image](https://github.com/TophantTechnology/ARL/assets/56430812/6ee92ff3-b66f-447f-a959-9ff7d8c6de0c)
![image](https://github.com/TophantTechnology/ARL/assets/56430812/1637670f-72e1-483e-a423-adeca9ea0a2f)

**Comment by keyuan15** [comment]
> 有报错信息么？ 应该是格式没有改对。
> 
> 这个加的key 在冒号后要有个空格。
> 
> ![图像](https://user-images.githubusercontent.com/9052484/255056702-0643addf-eac9-4355-b6de-a70590fc39b7.png)

是按照要求设置的，但还是报错
![image](https://github.com/TophantTechnology/ARL/assets/56430812/6ee92ff3-b66f-447f-a959-9ff7d8c6de0c)
![image](https://github.com/TophantTechnology/ARL/assets/56430812/1637670f-72e1-483e-a423-adeca9ea0a2f)

**Comment by keyuan15** [comment]
是按照要求设置的，但还是报错
![image](https://github.com/TophantTechnology/ARL/assets/56430812/6ee92ff3-b66f-447f-a959-9ff7d8c6de0c)
![image](https://github.com/TophantTechnology/ARL/assets/56430812/1637670f-72e1-483e-a423-adeca9ea0a2f)

**Comment by ZFYy1x** [comment]
> 有报错信息么？ 应该是格式没有改对。
> 
> 这个加的key 在冒号后要有个空格。
> 
> ![图像](https://user-images.githubusercontent.com/9052484/255056702-0643addf-eac9-4355-b6de-a70590fc39b7.png)

可以更新一份模板嘛？配置key怎么都会报错，不管留不留空格
