### ISSUE TITLE
ARL network err 报错

### ISSUE THREAD

**Issue by tonmonkey** [TophantTechnology/ARL#603]
在arl页面点击任意按钮都会报错：Network Error 或者页面无法响应
![image](https://github.com/TophantTechnology/ARL/assets/84943423/f344ef55-c8d5-458b-a7fe-2dbe19a00ab7)
但是我浏览器刷新页面后就又一切正常了，但过段时间又Network Error 或者页面无法响应(清除浏览器缓存后也没用)。查看日志任务啥的都是正常在跑，但感觉速度好像变慢了。
![image](https://github.com/TophantTechnology/ARL/assets/84943423/834d692a-6eaf-4b38-9711-6d1db6593a6d)

**Comment by 1c3z** [comment]
我看右上角图标有代理， 走代理了吧。

**Comment by tonmonkey** [comment]
![image](https://github.com/TophantTechnology/ARL/assets/84943423/0f17f86b-c5a0-4d46-be5f-953762a8cdca)
