### ISSUE TITLE
策略配置新建配置的时候弱口令没有选项

### ISSUE THREAD

**Issue by 2103749262** [TophantTechnology/ARL#604]
安装在云服务器上
系统是CentOS 7.4
刚构建成功的情况
策略配置新建配置的时候弱口令没有选项

<img width="914" alt="微信图片_20230724234614" src="https://github.com/TophantTechnology/ARL/assets/77906388/9603230b-28e2-460d-9c0e-b36dc754fbb3">

**Comment by 1c3z** [comment]
![image](https://github.com/TophantTechnology/ARL/assets/9052484/b9f60dc8-3f47-47fc-9007-813b0008d00d)
要手动点下更新。

这个后面优化下。

**Comment by 1c3z** [comment]
已优化。
