### ISSUE TITLE
在centos7上安装后，使用默认账户密码首次在浏览器登录时，显示账户名或密码错误和timeout of 12000ms exceeded，怎么回事

### ISSUE THREAD

**Issue by 15020132669** [TophantTechnology/ARL#606]

**Comment by 15020132669** [comment]
资产灯塔系统和centos7我都重装了几次，但一直显示这个

**Comment by 1c3z** [comment]
可以执行下面的三条命令并尝试触发错误观察输出有什么异常。

```
docker-compose ps
docker-compose logs -f  --tail=10
tail -f *.log
```

参考：
https://tophanttechnology.github.io/ARL-doc/faq/#3

**Comment by 15020132669** [comment]
谢(•‿•)

**Comment by 15020132669** [comment]
一直有两个服务是，咋弄嘞¯_༼ ಥ ‿ ಥ ༽_/¯restarting![mmexport1690891639765.png](https://github.com/TophantTechnology/ARL/assets/130225384/faee15f4-7347-4e6f-a6b1-f97a4f8e6dd2)

**Comment by 15020132669** [comment]
| |
***@***.***
|
|
***@***.***
|




---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2023年07月31日 16:03 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [TophantTechnology/ARL] 在centos7上安装后，使用默认账户密码首次在浏览器登录时，显示账户名或密码错误和timeout of 12000ms exceeded，怎么回事 (Issue #606) |

可以执行下面的三条命令并尝试触发错误观察输出有什么异常。

docker-compose ps
docker-compose logs -f  --tail=10
tail -f *.log


参考：
https://tophanttechnology.github.io/ARL-doc/faq/#3

**Comment by 1c3z** [comment]
有两个容器在重启，要看看日志才能定位到原因。

**Comment by fakefake00** [comment]
> 一样的问题 是什么原因 有解决方案么

版本有问题，拉去的镜像默latest版本并不是最新版本，指定docker pull tophant/arl:v2.5.5

**Comment by handbye** [comment]
一样的问题，应该是配置文件中的RISKIQ有问题
![image](https://github.com/TophantTechnology/ARL/assets/26617058/3e29a724-c35b-4714-a344-af83525de4eb)

**Comment by 1c3z** [comment]
@handbye 镜像没更新

可以看下文档卸载重装。
https://tophanttechnology.github.io/ARL-doc/faq/#11-docker

**Comment by qingtian187** [comment]
重装进去还是一样timeout of 12000ms exceeded
安装成功后访问5003端口是这个目录https://127.0.0.1:5003/taskList

**Comment by ixix1234** [comment]
是的 我安装刚开始也是报错 RISKIQ 有问题 配置完后 就报错confg.yaml 30行有问题不知道问题出在哪儿了

**Comment by 1c3z** [comment]
#720
