### ISSUE TITLE
gunicorn会占用CPU过高

### ISSUE THREAD

**Issue by jinghunsanzu** [TophantTechnology/ARL#608]
gunicorn会占用CPU过高。一个4h8g的机器直接吃完

**Comment by jinghunsanzu** [comment]
![image](https://github.com/TophantTechnology/ARL/assets/54282451/489d894e-be83-48a8-bd19-4275e979d486)

**Comment by 1c3z** [comment]
可以执行下面的三条命令并尝试触发错误观察输出有什么异常。
```
docker-compose ps
docker-compose logs -f  --tail=10
tail -f *.log
```

参考：
https://tophanttechnology.github.io/ARL-doc/faq/#3

**Comment by 11pmsleep** [comment]
> gunicorn会占用CPU过高。一个4h8g的机器直接吃完

问题有解决吗，我灯塔cpu也是直接被拉满，重装还是一样的问题

**Comment by 1757001134** [comment]
> > gunicorn会占用CPU过高。一个4h8g的机器直接吃完
> 
> 问题有解决吗，我灯塔cpu也是直接被拉满，重装还是一样的问题

你解决了吗，我也遇到了，安装完之后直接CPU占用拉满
