### ISSUE TITLE
Ubuntu docker安装 cpu占用极高，请问有莫有过类似情况

### ISSUE THREAD

**Issue by 11pmsleep** [TophantTechnology/ARL#611]
![image](https://github.com/TophantTechnology/ARL/assets/72010343/9f301197-59c5-43ad-b76f-f9ade77999da)
2核4G，一下被拉满cpu了，请问，一般来说是正常现象吗，，，

**Comment by 11pmsleep** [comment]
@1c3z 上面不是我的日志，那个是别人日志哈。
![image](https://github.com/TophantTechnology/ARL/assets/72010343/3222ff4b-9b12-495b-960b-be4f3c9b5782)
可以康康我现在的这个日志

**Comment by 11pmsleep** [comment]
@1c3z 上图是docker-compose logs -f --tail=10的结果，总是提示Parse config.yaml error 'RISKIQ'

**Comment by 1c3z** [comment]
1.是配置了镜像源么？ 导致pull 不是最新的

2.进入登录页面看看版本是不是最新的。

<img width="594" alt="image" src="https://github.com/TophantTechnology/ARL/assets/9052484/48efe1a1-30b6-4c11-a606-3d840dcbf428">

**Comment by 1c3z** [comment]
https://tophanttechnology.github.io/ARL-doc/faq/#12-docker

或者用下面的步骤重装下吧。

**Comment by 11pmsleep** [comment]
> 1.是配置了镜像源么？ 导致pull 不是最新的
> 
> 2.进入登录页面看看版本是不是最新的。
> 
> <img alt="image" width="594" src="https://user-images.githubusercontent.com/9052484/258550318-48efe1a1-30b6-4c11-a606-3d840dcbf428.png">

感谢，确实是镜像问题，原本是docker走阿里云镜像加速，pull的是旧版本。删除镜像加速后就没问题了~
