### ISSUE TITLE
请问一下如何给ARL限制访问？

### ISSUE THREAD

**Issue by caowenjian123** [TophantTechnology/ARL#612]
因为安全因素，需要控制访问。但是在 ARL/docker/nginx.conf 配置后其他网段依然可以访问。请问应该怎么解决。感谢解答

**Comment by 1c3z** [comment]
目前还不支持哦，配下云防火墙？

**Comment by caowenjian123** [comment]
> 目前还不支持哦，配下云防火墙？
 
好的~ 感谢。
