### ISSUE TITLE
BUG：策略配置 - 新建策略时勾选掉了"跳过CDN"，但实际不会生效

### ISSUE THREAD

**Issue by ipsecc** [TophantTechnology/ARL#618]
![78f0b0ca-529b-4f98-84de-d45d04e6ffa9](https://github.com/TophantTechnology/ARL/assets/40918024/0b53ef60-1bdb-4de1-b205-6d35e5972961)

**Comment by 1c3z** [comment]
感谢反馈，是个BUG，我们修下。

**Comment by 1c3z** [comment]
已修复。
