### ISSUE TITLE
反馈bug

### ISSUE THREAD

**Issue by zygds** [TophantTechnology/ARL#62]
### 我为灯塔打kall，其实是蹭热度，多和大佬交互
![image](https://user-images.githubusercontent.com/73819467/102399702-eed28200-401b-11eb-90bd-a007c8c524d9.png)

## bug在此

![image](https://user-images.githubusercontent.com/73819467/102399818-11649b00-401c-11eb-8e65-28cb3c348590.png)

![image](https://user-images.githubusercontent.com/73819467/102399944-36f1a480-401c-11eb-9ad1-826dfb35c074.png)

其实就是image文件不存在，提一嘴，大佬别打我😂

**Comment by 1c3z** [comment]
感谢关注。

我测试了下是会自动创建这个目录的。 

![image](https://user-images.githubusercontent.com/9052484/102442685-f0be3480-405f-11eb-9340-fdf1a4b81fa3.png)


本地用的docker-ce 19.03.1版本
https://docs.docker.com/engine/install/
