### ISSUE TITLE
问题反馈

### ISSUE THREAD

**Issue by robot183** [TophantTechnology/ARL#620]
## 描述问题

想更改下，文件泄露的的配置。 看issues 是要改源码，修改了源码，该怎么重新部署arl呢。 一直是docker  一键 部署 。
可以直接在部署好的项目里，修改源码么

https://github.com/TophantTechnology/ARL/issues/614

请在此处提供对问题的清晰而简洁的描述。

## 环境信息

操作系统：centos7
Docker版本：23.0.5
ARL 版本: 2.5.5

**Comment by 1c3z** [comment]
改了容器里的，重新restart一下就可以
