### ISSUE TITLE
fofa API 无法不能使用

### ISSUE THREAD

**Issue by Deng-Z** [TophantTechnology/ARL#621]
## 描述问题

fofa的email和key都正确，本地工具可以使用，但是fofa任务下发不行

![image](https://github.com/TophantTechnology/ARL/assets/92916343/5906de4c-fce7-4e34-a97c-8afe75dfadd7)

**Comment by Deng-Z** [comment]
这个host=fofa.so，为啥是以前的链接，配置文件也找不到这个fofa.so

**Comment by 1c3z** [comment]
<img width="326" alt="image" src="https://github.com/TophantTechnology/ARL/assets/9052484/18c6d927-fa88-4484-a74a-78e208486d66">
 
没有升级好呢。

**Comment by Deng-Z** [comment]
[root@iZ7xv2ya5ap2bn4ev6ol6iZ ARL]# cat version.txt 
v2.5.5
[root@iZ7xv2ya5ap2bn4ev6ol6iZ ARL]# 

存在version.txt，删了容器，下载最新的docker.zip，重新拉镜像还是2.5版本
![image](https://github.com/TophantTechnology/ARL/assets/92916343/9a8949f0-adce-4e3b-87af-d22f961147e0)

**Comment by Deng-Z** [comment]
已解决，换镜像重拉

**Comment by ahuyuhy** [comment]
> 

大兄弟 换哪个镜像 能不能发下
