### ISSUE TITLE
没有统一的漏洞等安全风险查看页面

### ISSUE THREAD

**Issue by LvK8** [TophantTechnology/ARL#625]
没有统一的漏洞等安全风险查看页面，无法查看所有漏洞信息，需要点进每个任务查看。在资源监控中，每个ip都是一个任务，查看漏洞信息比较麻烦。查看了漏洞信息的接口，目前必须要指定taskid才行。希望能够有个接口能够查看所有漏洞信息、漏洞列表

**Comment by 1c3z** [comment]
可以用这个链接 /taskList/taskDetail 看。后面我们优化下。
