### ISSUE TITLE
新建资产组建议增加c段监控

### ISSUE THREAD

**Issue by MDhost** [TophantTechnology/ARL#63]
目前只能监控域名，建议添加c段监控

**Comment by 1c3z** [comment]
IP监控这个目前还没打算实现。 

这是一个开源项目，如果有好的实现欢迎提交PR.

**Comment by Ethancck** [comment]
顺便还是把批量添加的功能加上吧，手疼，并且监控的一些配置最好可选，不要默认

**Comment by 1c3z** [comment]
@Ethancck  批量添加域名监控已添加。
