### ISSUE TITLE
 源码安装如何修改任务并行数量

### ISSUE THREAD

**Issue by ysdxj** [TophantTechnology/ARL#631]
## 描述问题

 源码安装如何修改任务并行数量

## 环境信息

- 操作系统：centos7
- Docker版本：
- ARL 版本:2.5.5

**Comment by 1c3z** [comment]
https://github.com/TophantTechnology/ARL/blob/master/docker/docker-compose.yml#L43 

改 `-c ` 参数。

**Comment by ysdxj** [comment]
centos7源码安装 非docker

**Comment by 1c3z** [comment]
抱歉，看走眼了。

改这个文件里面的-c 参数。

https://github.com/TophantTechnology/ARL/blob/master/misc/arl-worker.service

cp misc/arl-worker.service /etc/systemd/system/

重启服务。
