### ISSUE TITLE
针对解析到本地或内网的域名单独一页进行整理与索引并且不进行扫描探测

### ISSUE THREAD

**Issue by djerryz** [TophantTechnology/ARL#633]
投料子域名任务时，可能存在解析到内网或本地的域名，这部分任务任务需要单独处理，扫描内网域名在黑盒探测的场景并无意义，是否能提供一个按钮对于该类情况进行过滤整理

**Comment by 1c3z** [comment]
根据你的场景在配置文件里面加要屏蔽的IP

https://github.com/TophantTechnology/ARL/blob/master/docker/config-docker.yaml#L106
