### ISSUE TITLE
功能增加建议

### ISSUE THREAD

**Issue by Evi10x01** [TophantTechnology/ARL#635]
目前相对比较全的子域名发现工具是oneforall，本系统后续子域名发现功能是否可以考虑直接调用oneforall呢？

**Comment by 1c3z** [comment]
不考虑, 不过可以帮忙分析分析是哪块的问题，找到了问题我再对应改。

是在有需要的话可以往这个里面写个插件。
https://github.com/TophantTechnology/ARL/tree/master/app/services/dns_query_plugin
