### ISSUE TITLE
问题反馈

### ISSUE THREAD

**Issue by tonmonkey** [TophantTechnology/ARL#638]
## 描述问题

服务器本地部署,未采用docker，任务下发失败，日志如下：
![image](https://github.com/TophantTechnology/ARL/assets/84943423/6002d2d5-f2e1-4cb0-8ba6-d911f52fbe67)
![image](https://github.com/TophantTechnology/ARL/assets/84943423/55b512d4-1174-4618-bc1b-e9ed19b069d9)

## 环境信息

- 操作系统：CentOS7.5
- Docker版本：
- ARL 版本:当前

**Comment by 1c3z** [comment]
![image](https://github.com/TophantTechnology/ARL/assets/9052484/12e96a66-ae10-4d15-8e46-38f1eb2db3c6)

 这个错误时间匹配不上。找错位置了。

**Comment by tonmonkey** [comment]
![image](https://github.com/TophantTechnology/ARL/assets/84943423/c56e3a5d-b66c-4210-80ce-735122272d81)
![image](https://github.com/TophantTechnology/ARL/assets/84943423/b84c986d-2b17-4d85-9de2-c90519bfa022)

**Comment by tonmonkey** [comment]
![image](https://github.com/TophantTechnology/ARL/assets/84943423/08d576fd-e5c5-4d35-9eec-f371bd837637)
arl_worker.log最新记录只到22:20分。
还有就是执行自动化安装脚本的时候，有的安装包进度太慢或者无法下载安装包。我直接自己手动安装脚本里面所需组件（大概手动安装了两个组件）。最后再启动脚本的完成最后步骤

**Comment by 1c3z** [comment]
应该是nmap 版本有点低，可以升级下。
