### ISSUE TITLE
V2.2无法获取站点、服务、文件泄露、url等信息

### ISSUE THREAD

**Issue by asw3asw** [TophantTechnology/ARL#64]
新任务，无法获取站点、服务、文件泄露、url等信息
如：che168.com

**Comment by yzddmr6** [comment]
似乎设置资产监控之后再扫描都会用默认的选项，就不包含文件泄露，服务等信息了

**Comment by 1c3z** [comment]
是的，直接下发的任务和监控任务在参数上有些区别。
