### ISSUE TITLE
问题反馈 docker-compose部署

### ISSUE THREAD

**Issue by testnet0** [TophantTechnology/ARL#640]
## 描述问题
最新版本的docker-compose默认版本我看到改成了tophant/arl:${ARL_VERSION:-latest}
所以默认会是latest，我现在本地配置了阿里云的镜像加速，所以latest版本是很久之前的：
![image](https://github.com/TophantTechnology/ARL/assets/18673513/12af9a1d-e8dd-4edd-9c8e-701fc02a541e)
版本号能不能恢复成硬编码方式呢？或者加一个提醒需要配置环境变量ARL_VERSION
![image](https://github.com/TophantTechnology/ARL/assets/18673513/192c4a27-d2d2-43a9-8952-bc8608a2807b)

**Comment by 1c3z** [comment]
有个.env 文件，可以修改为
```
ARL_VERSION=v2.6
```
