### ISSUE TITLE
docker构建运行报错

### ISSUE THREAD

**Issue by xz-zone** [TophantTechnology/ARL#641]
## 描述问题

docker构建运行报错，启动报错

## 环境信息

- ARL 版本:2.5

### 错误输出

![image](https://github.com/TophantTechnology/ARL/assets/19305748/ff63ee7a-b434-4e56-81c7-f4451df250f1)

### 解决方法
在config-docker.yaml 增加
RISKIQ:
  EMAIL: ""
  KEY: ""

![image](https://github.com/TophantTechnology/ARL/assets/19305748/b2c2c4b6-b2c6-4f0d-93d4-e37f0c4ff5a2)

**Comment by 1c3z** [comment]
是的，建议升级下程序。

**Comment by xz-zone** [comment]
> 是的，建议升级下程序。

我下载的是最新版本的 https://github.com/TophantTechnology/ARL/archive/refs/tags/v2.6.tar.gz

**Comment by testnet0** [comment]
> > 是的，建议升级下程序。
> 
> 我下载的是最新版本的 https://github.com/TophantTechnology/ARL/archive/refs/tags/v2.6.tar.gz

执行命令 docker image tophant/arl 看下输出呢 可能你的不是最新版的

**Comment by testnet0** [comment]
> > docker images tophant/arl
> 
> ![image](https://user-images.githubusercontent.com/19305748/276132491-5251ff87-5333-4c85-ada5-3bf1c4ab0919.png)

所以你跟我遇到的是同样的问题，这个默认的镜像不是最新版的
https://github.com/TophantTechnology/ARL/issues/640
参考这个 设置环境变量或者修改.env文件强制指定版本
