### ISSUE TITLE
是否考虑进行分布式部署

### ISSUE THREAD

**Issue by dogadmin** [TophantTechnology/ARL#645]
单机性能有限，一次加载任务也有限制，是否考虑基于worker+server的模式进行分布式改造？

**Comment by 1c3z** [comment]
可以参考下这个。
https://github.com/1c3z/ARL-Distributed

**Comment by soapffz** [comment]
分布式部署的代码现在仍然适用吗？遇到大体量的公司即使只扫域名也非常非常地慢，比如tx，ali，zijietiaodong之类的
