### ISSUE TITLE
关于内网资产梳理C段同步问题

### ISSUE THREAD

**Issue by Ecring** [TophantTechnology/ARL#646]
**问题描述：**
想用于内网的资产梳理，发现C段资产好像无法同步
在使用过程中发现使用C段地址如192.168.1.0/24作为`任务管理`中新任务的`目标`，扫描完成后无法同步到`资产分组`中。

**配置过程如下：**

1. 新建了资产分组，资产范围为一个C段

![image](https://github.com/TophantTechnology/ARL/assets/96344256/5167f7d2-cd14-47f3-afc6-18499d23ab3f)

2.配置了监控任务，并开始扫描

![image](https://github.com/TophantTechnology/ARL/assets/96344256/03306b55-0f2b-4adc-97ec-591020fbd6bb)

3.`任务管理`页面可见扫描结果，但是无法同步

![image](https://github.com/TophantTechnology/ARL/assets/96344256/59d58c70-0e13-4a47-a268-5f414535248b)

**求问：**
是否是我的配置姿势有误？还是说目前不支持C段或B段的资产探测管理呢？

**Comment by 1c3z** [comment]
1. IP 任务不支持手动同步的，监控任务会自动把新发现的同步到资产分组中。

2. 我刚测试了下，资产分组中，站点同步出了点bug， ip端口是有数据的。 这个我们下个版本修下。

**Comment by Dido1960** [comment]
大佬，我这里也补充一下IP资产分组没同步的问题
![image](https://github.com/TophantTechnology/ARL/assets/44106495/47325cce-ef21-4588-84ff-f4169264d2d2)
![image](https://github.com/TophantTechnology/ARL/assets/44106495/8decd457-1bd4-4609-bc7f-06d56e45c800)


使用该策略下发任务后，扫描结果没有自动同步到IP资产组
![image](https://github.com/TophantTechnology/ARL/assets/44106495/0500e58e-4ab8-4eb4-bc4d-899a3d088d97)
![image](https://github.com/TophantTechnology/ARL/assets/44106495/be177faf-6e63-4c99-bc09-a0877aa637c2)

**Comment by 1c3z** [comment]
@Dido1960  收到。

**Comment by 1c3z** [comment]
v2.6.1 已修复。
