### ISSUE TITLE
带_的域名无法导入灯塔

### ISSUE THREAD

**Issue by rnsss** [TophantTechnology/ARL#647]
## 描述问题

当域名中包含下划线_时，无法添加到任务中

## 环境信息

- 操作系统：ubuntu
- Docker版本：20.10.24
- ARL 版本:2.5.4

### 错误输出

请执行以下命令，并提供输出结果：

```
docker-compose ps

docker-compose logs -f  --tail=10

tail -f arl_worker.log
```

## 复现步骤

请提供重现问题所需的详细步骤。

1. 将含有_的域名添加入任务中，失败
![Snipaste_2023-10-25_17-43-47](https://github.com/TophantTechnology/ARL/assets/48343279/d78fa2c6-26af-4086-8391-f763a1de9743)

## 预期行为

添加成功

## 实际行为

添加失败

## 附加上下文

在此处提供其他有关问题的任何其他上下文。

## 卸载或者重装文档。
https://tophanttechnology.github.io/ARL-doc/faq/#12-docker

**Comment by 1c3z** [comment]
根据RFC 这个_是无效的。

#602
