### ISSUE TITLE
问题反馈

### ISSUE THREAD

**Issue by myqf23** [TophantTechnology/ARL#649]
## 描述问题

添加任何目标扫描结果均为0
![image](https://github.com/TophantTechnology/ARL/assets/81756571/db0ed8bd-979b-4ea2-b6a5-dccc964379ee)

## 环境信息

- 操作系统：ubantu 20
- Docker版本：24.0.6
- ARL 版本:   docker 搭建 v2.6

### 错误输出

请执行以下命令，并提供输出结果：

```
docker-compose ps

docker-compose logs -f  --tail=10

tail -f arl_worker.log
```
![image](https://github.com/TophantTechnology/ARL/assets/81756571/7cb63ead-4ff8-4342-aa07-f11df518562e)

![image](https://github.com/TophantTechnology/ARL/assets/81756571/4e94cf25-d56e-4aa5-9716-b29f7cb16517)
![image](https://github.com/TophantTechnology/ARL/assets/81756571/21b8dbfc-6fde-4240-aa4f-ad1a917222e9)

## 复现步骤

请提供重现问题所需的详细步骤。

添加目标，点击扫描
![image](https://github.com/TophantTechnology/ARL/assets/81756571/193b7085-5f64-45cd-9b08-8bf2e20cdd2c)

## 预期行为

有结果

## 实际行为

均为0
![image](https://github.com/TophantTechnology/ARL/assets/81756571/193b7085-5f64-45cd-9b08-8bf2e20cdd2c)

## 附加上下文

在此处提供其他有关问题的任何其他上下文。

## 卸载或者重装文档。
https://tophanttechnology.github.io/ARL-doc/faq/#12-docker

**Comment by 1c3z** [comment]
有点奇怪，字典开测试有数据么？

**Comment by myqf23** [comment]
请问具体怎么操作呢，我用虚拟机kali新安装arl又可以

**Comment by myqf23** [comment]
![image](https://github.com/TophantTechnology/ARL/assets/81756571/fccae6bb-a136-414e-b26f-9cadc4a71955)

**Comment by myqf23** [comment]
貌似是这个原因
![图片](https://github.com/TophantTechnology/ARL/assets/81756571/5621261f-d0d6-4b95-89bc-cd88c31ce8cc)

**Comment by myqf23** [comment]
问题解决了
我通过修改容器内的dnsserver.txt解决了问题

**Comment by Gitreny** [comment]
> 问题解决了 我通过修改容器内的dnsserver.txt解决了问题

具体是怎么修改的可以说下吗。现在我也遇到这个问题了
