### ISSUE TITLE
新功能建议：资产搜索增加导出功能

### ISSUE THREAD

**Issue by SundaeFire** [TophantTechnology/ARL#65]
看到前面也有人提到增加批量导出功能，这样可以使用其他工具对导出后的URL进行批量测试
因为资产搜索里面可以看到所有的站点跟子域名列表，建议在这里增加导出功能。

**Comment by 1c3z** [comment]
搜索导出功能确实需求比较常见，预计会在下一版本添加

**Comment by 1c3z** [comment]
@SundaeFire   已更新，可以导出站点域名等字段。
