### ISSUE TITLE
arl_scheduler 和arl_worker 一直在Restarting，selinux为关闭状态

### ISSUE THREAD

**Issue by frt-xue** [TophantTechnology/ARL#651]
## 描述问题

arl_scheduler 和arl_worker 一直在Restarting 
selinux为关闭状态

## 环境信息

- 操作系统：centos7
- Docker版本：Docker version 24.0.7,
- ARL 版本: 最新版

### 错误输出

请执行以下命令，并提供输出结果：

![image](https://github.com/TophantTechnology/ARL/assets/70102445/742d5d9f-9364-4429-b5d9-864616dee49f)
![image](https://github.com/TophantTechnology/ARL/assets/70102445/9905eef9-d8b6-4231-9625-d147b620bb98)

**Comment by 1c3z** [comment]
#379 
#641
