### ISSUE TITLE
arl存在进程bug

### ISSUE THREAD

**Issue by shanxigetanxiaochou** [TophantTechnology/ARL#654]
<img width="794" alt="图片" src="https://github.com/TophantTechnology/ARL/assets/64448262/23306f61-d109-4aa7-bcf4-b23eac5dc8b2">
两个进程均未跑完就已经可以跑下一个进程。看样子是没报error，还是显示file_leak。

**Comment by 1c3z** [comment]
应该是任务进程被kill了，这个状态不会再更新了。

**Comment by shanxigetanxiaochou** [comment]
经过测试，不开启WIH，就不会kill进程，加上wih就会出现上述情况。

**Comment by 1c3z** [comment]
v2.6.2 已更新。
