### ISSUE TITLE
优化建议

### ISSUE THREAD

**Issue by Oldman19** [TophantTechnology/ARL#655]
建议可以批量同步，一个个同步真的好麻烦啊

**Comment by Oldman19** [comment]
还有就是为啥策略里不能配置host碰撞啊，这样我监控域名的时候配置这个策略不就可以在监控到新的域名时进行碰撞了吗，而且建议这个碰撞用的ip是从这个资产组所有的ip里对这个新的域名进行碰撞而不是新域名和新ip

**Comment by Oldman19** [comment]
还有就是对于访问过与没访问过的资产有个标识，因为监控的资产和wih啥的多了以后，一脸懵逼，都不知道哪些自己看过哪些没看过了

**Comment by 1c3z** [comment]
> 建议将监控的任务结束以后，给他放到一个新的栏目，就不放在任务管理下面，然后只有点开访问了以后，可以选择是移动到任务管理下面还是标记已读这种，这样就方便很多，要不然每次返回还得找啊找翻啊翻回想看没看


监控任务有新的数据可以在资产管理里面统一查看。

**Comment by 1c3z** [comment]
> 建议可以批量同步，一个个同步真的好麻烦啊

新建一个策略，关联到资产分组，然后下发的任务会自动同步过去。
