### ISSUE TITLE
IP资产分组站点结果不同步

### ISSUE THREAD

**Issue by Gitreny** [TophantTechnology/ARL#656]
## 描述问题

更新到最新后发现站点识别挂了，没更新前一直都能识别到。更新后就不行了，其他功能正常

## 环境信息

- 操作系统：CentOS Stream release 8
- Docker版本：Docker version 24.0.6, build ed223bc
- ARL 版本: v2.6

### 错误输出

请执行以下命令，并提供输出结果：

```
docker-compose ps
docker-compose logs -f  --tail=10
tail -f arl_worker.log
```
![图片](https://github.com/TophantTechnology/ARL/assets/43869835/a65b45d6-974e-4121-8332-19bd38c8e340)
![图片](https://github.com/TophantTechnology/ARL/assets/43869835/2e371d12-4bee-4124-9ff8-6f0a16506044)
![图片](https://github.com/TophantTechnology/ARL/assets/43869835/200e7627-379d-4d43-8a03-e80277b82162)
![图片](https://github.com/TophantTechnology/ARL/assets/43869835/b703b9af-3bc4-4e28-b533-a151a02ed8a0)

## 复现步骤

请提供重现问题所需的详细步骤。

未更新前，站点识别正常
![图片](https://github.com/TophantTechnology/ARL/assets/43869835/f1a7d416-8a79-4ad1-839d-d4a2fd421bc3)

更新后，站点无法识别
![图片](https://github.com/TophantTechnology/ARL/assets/43869835/0afa4e7b-a21a-4d0a-af6c-1f5ffc8608b1)

## 预期行为

请描述您预期发生的事情。

## 实际行为

请描述实际发生的事情。

## 附加上下文

在此处提供其他有关问题的任何其他上下文。

## 卸载或者重装文档。
https://tophanttechnology.github.io/ARL-doc/faq/#12-docker

**Comment by 1c3z** [comment]
1. 最后一张图是资产分组里没数据么？ 
2. 任务里面点进去有数据么？

**Comment by Gitreny** [comment]
> 1. 最后一张图是资产分组里没数据么？
> 
>     2. 任务里面点进去有数据么？

资产分组有数据 任务里面点进去站点识别没数据，IP里面有
![图片](https://github.com/TophantTechnology/ARL/assets/43869835/de03c623-76f1-4723-b8e7-9a2363febd56)
![图片](https://github.com/TophantTechnology/ARL/assets/43869835/9d5e81ec-a9f5-4094-98e0-25d643c74f51)
![图片](https://github.com/TophantTechnology/ARL/assets/43869835/ff6ba719-2483-4969-8a19-c1103da656a2)

**Comment by 1c3z** [comment]
IP资产分组同步有点问题， 我们后面修下。

**Comment by 1c3z** [comment]
v2.6.1 已修复。

**Comment by Gitreny** [comment]
> v2.6.1 已修复。

感谢大佬！
