### ISSUE TITLE
arl_worker 有bug

### ISSUE THREAD

**Issue by An0nyYEZ1m0us** [TophantTechnology/ARL#657]
## 描述问题

请在此处提供对问题的清晰而简洁的描述。

## 环境信息

- 操作系统：centos7
- ARL 版本:2.6

### 错误输出

请执行以下命令，并提供输出结果：

docker-compose ps
![image](https://github.com/TophantTechnology/ARL/assets/144971870/dc81182b-24c2-4291-821c-3778cd81fe66)

docker-compose logs -f  --tail=10
![image](https://github.com/TophantTechnology/ARL/assets/144971870/d7bc403b-b61e-4071-94a2-fba699f644aa)

tail -f arl_worker.log
![image](https://github.com/TophantTechnology/ARL/assets/144971870/fdce3cc2-738f-408c-bbfe-b309e89fa45e)

## 复现步骤

重装几次 系统也重装了 对分组内大概1000个域名进行24小时子域名监控的时候第二天会发现中间中断了，计划任务也往后推了几个小时，就会导致进度慢，还会导致有的域名一次都没扫描，有的已经扫描了两次了，并且docker ps 发现arl_worker 老是重启，selinux没开
![image](https://github.com/TophantTechnology/ARL/assets/144971870/d41ab7d9-0ab8-4996-97e6-97a19e4763fd)

**Comment by 1c3z** [comment]
给的日志没看到重启相关的，不清楚什么原因。

大量任务建议源码部署，关注下内存和CPU的使用情况。

**Comment by An0nyYEZ1m0us** [comment]
谢谢你的回复  我将尝试用源码部署arl 那请问源码部署在哪改域名插件的配置

**Comment by An0nyYEZ1m0us** [comment]
> 谢谢你的回复 我将尝试用源码部署arl 那请问源码部署在哪改域名插件的配置

我找到在哪设置了 app/config.yaml
我再跑一晚上明天给您回复

**Comment by An0nyYEZ1m0us** [comment]
> 给的日志没看到重启相关的，不清楚什么原因。
> 
> 大量任务建议源码部署，关注下内存和CPU的使用情况。

想问下源码安装查看几个组件是否重启的命令是什么

**Comment by An0nyYEZ1m0us** [comment]
今天看了一下，监控任务出现断层，被我终止后，后面的任务正常进行
![image](https://github.com/TophantTechnology/ARL/assets/144971870/3d09be3f-b9ef-47e7-b231-3309ecbc6f46)
![image](https://github.com/TophantTechnology/ARL/assets/144971870/50a65450-40d1-4f01-978b-592338ebcccc)

**Comment by An0nyYEZ1m0us** [comment]
是否有设置任务超时限制的config

**Comment by An0nyYEZ1m0us** [comment]
![image](https://github.com/TophantTechnology/ARL/assets/144971870/348c8ac8-025e-4b87-a3ec-6d9172285a9a)
一直卡在这里不动了 之前的也是

**Comment by 1c3z** [comment]
一般很少卡这里的。   这个域名子域名多么？   排查下带宽占用。

**Comment by 1c3z** [comment]
> > 给的日志没看到重启相关的，不清楚什么原因。
> > 大量任务建议源码部署，关注下内存和CPU的使用情况。
> 
> 想问下源码安装查看几个组件是否重启的命令是什么

 systemctl status arl-worker

![image](https://github.com/TophantTechnology/ARL/assets/9052484/43d9ca23-b1a8-4038-b524-f4610556ec74)
