### ISSUE TITLE
批量删除建议

### ISSUE THREAD

**Issue by Oldman19** [TophantTechnology/ARL#659]
建议将统计栏目所有项为0的可以批量一键删除，而不是自己全选删除，然后下一页全选删除

**Comment by 1c3z** [comment]
这个不是筛选 结果为0的么。

**Comment by Oldman19** [comment]
> 这个不是筛选 结果为0的么。

任务管理里有筛选统计为0的？？？？只看到了任务名、目标、taskid、任务类型、状态的筛选

**Comment by 1c3z** [comment]
没，后面想办法加下。

**Comment by HHHHDDDDD222** [comment]
> 没，后面想办法加下。

大佬建议加一个真正意义上的批量删除，可以这样就是从第一页到第三页，以勾勾为起点，下一个勾勾为终点批量选中删除，现在的问题就是批量选中的时候并不会选中前面一页的内容

**Comment by 1c3z** [comment]
v2.6.2 已更新，可以筛选。
