### ISSUE TITLE
运行资产监控异常

### ISSUE THREAD

**Issue by R0llingRed** [TophantTechnology/ARL#660]
## 描述问题

运行资产监控服务时出现异常，任务只运行1秒就结束了。
![image](https://github.com/TophantTechnology/ARL/assets/40241513/4f243cee-ec83-40fc-96e7-e71b0360a4a1)

## 环境信息

- 操作系统：ubuntu server22.04
- Docker版本：24.0.6
- ARL 版本: 2.6

### 错误输出

请执行以下命令，并提供输出结果：
![image](https://github.com/TophantTechnology/ARL/assets/40241513/649046dd-a03f-47a0-a77f-24f732c7ddbc)
![image](https://github.com/TophantTechnology/ARL/assets/40241513/c25278b8-732c-421e-a844-537d594a4c55)
策略截图：
![image](https://github.com/TophantTechnology/ARL/assets/40241513/24a4d171-bf88-4c10-a54f-d5f3023c9187)
```
docker-compose ps

docker-compose logs -f  --tail=10

tail -f arl_worker.log

```

## 复现步骤

请提供重现问题所需的详细步骤。

1. 步骤一
2. 步骤二
3. 步骤三

## 预期行为

请描述您预期发生的事情。

## 实际行为

请描述实际发生的事情。

## 附加上下文

在此处提供其他有关问题的任何其他上下文。

## 卸载或者重装文档。
https://tophanttechnology.github.io/ARL-doc/faq/#12-docker

**Comment by 1c3z** [comment]
下发的IP在黑名单（为了防止SSRF）里面 。 


https://github.com/TophantTechnology/ARL/blob/master/docker/config-docker.yaml#L125C7-L125C20

**Comment by R0llingRed** [comment]
哦哦，我之前的改过了，这次更新完新版本忘记改了，感谢。
