### ISSUE TITLE
指纹识别功能优化建议

### ISSUE THREAD

**Issue by Oldman19** [TophantTechnology/ARL#666]
例如shiro规则header="rememberMe="因为最后这个=导致无法正常添加规则，尝试通过转译符号也无法正常添加，但实际情况很多指纹都需要有=xxx这种
![image](https://github.com/TophantTechnology/ARL/assets/58176451/d50a6193-bdc0-4a36-b4df-6c0ea0df77b1)

**Comment by 1c3z** [comment]
收到，这个指纹功能在优化中了。

**Comment by 1c3z** [comment]
指纹规则已强化，欢迎更新v2.6.1 ， issue 先关闭。
