### ISSUE TITLE
ARL通过docker-compose启动失败

### ISSUE THREAD

**Issue by TianwenOVO** [TophantTechnology/ARL#667]
报如下错误：
root@b30eoum69kecplnw:/opt/ARL# docker-compose start
Starting mongodb   ... done
Starting rabbitmq  ... done
Starting scheduler ... done
Starting worker    ... error
Starting web       ... error

ERROR: for worker  Cannot start service worker: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: error during container init: error mounting "/opt/ARL/arl_worker.log" to rootfs at "/code/arl_worker.log": mount /opt/ARL/arl_worker.log:/code/arl_worker.log (via /proc/self/fd/6), flags: 0x5000: not a directory: unknown: Are you trying to mount a directory onto a file (or vice-versa)? Check if the specified host path exists and is the expected type

ERROR: for web  Cannot start service web: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: error during container init: error mounting "/opt/ARL/arl_web.log" to rootfs at "/code/arl_web.log": mount /opt/ARL/arl_web.log:/code/arl_web.log (via /proc/self/fd/6), flags: 0x5000: not a directory: unknown: Are you trying to mount a directory onto a file (or vice-versa)? Check if the specified host path exists and is the expected type
查了一下，没有web、worker日志

**Comment by 1c3z** [comment]
创建一个  /opt/ARL/arl_worker.log 空白文件。
