### ISSUE TITLE
灯塔存在异常结束问题。

### ISSUE THREAD

**Issue by shanxigetanxiaochou** [TophantTechnology/ARL#669]
上述域名，未显示结束，进程却kill了，似乎上个版本没这个问题。
**
<img width="970" alt="图片" src="https://github.com/TophantTechnology/ARL/assets/64448262/5048a379-e457-4807-89a8-7a89f28d7ca9">
**

**Comment by 1c3z** [comment]
进程被kill了，状态没变，一直有这个问题。

**Comment by 1c3z** [comment]
v2.6.2 已更新。
