### ISSUE TITLE
您好，您测试过arl大量子域名收集监控功能吗

### ISSUE THREAD

**Issue by An0nyYEZ1m0us** [TophantTechnology/ARL#670]
经过我的长期测试，发现docker源码安装都会出现问题
![image](https://github.com/TophantTechnology/ARL/assets/144971870/3e12ee85-9511-427e-a91f-4ac2acff3a48)
安装过程应该都没问题，我测试了接近一个月，请问您测试过吗

**Comment by 1c3z** [comment]
看不出来啥问题。 一直有用，已经跑了10万任务了。

<img width="441" alt="image" src="https://github.com/TophantTechnology/ARL/assets/9052484/59bf7625-66a8-4293-a4a7-0e05311573d6">

**Comment by An0nyYEZ1m0us** [comment]
主机的配置是4核8g

**Comment by An0nyYEZ1m0us** [comment]
但是我把所有的根域名都放在同一个资产分组中了 然后点资产分组添加监控任务

**Comment by An0nyYEZ1m0us** [comment]
我是centos7.9  您是哪个版本的 我想按照您的配置试试

**Comment by 1c3z** [comment]
> 但是我把所有的根域名都放在同一个资产分组中了 然后点资产分组添加监控任务

可能是这个问题吧，这个资产分组可能域名太多了，最好分一分。

一样的配置，配置应该没啥问题，最好看看日志排查排查。

**Comment by An0nyYEZ1m0us** [comment]
好的  我后续测试一下

**Comment by An0nyYEZ1m0us** [comment]
还有一个问题 就是我分很多组的话 那我监控循环时间都写24小时合适嘛 您是如何配置的

**Comment by shanxigetanxiaochou** [comment]
温馨提示，这是您的公网ip被封了。你的服务器不支持扫爆。

**Comment by 1c3z** [comment]
> 还有一个问题 就是我分很多组的话 那我监控循环时间都写24小时合适嘛 您是如何配置的

评估下全部跑完要多久，间隔可以搞长点，比如48小时。

**Comment by An0nyYEZ1m0us** [comment]
> 温馨提示，这是您的公网ip被封了。你的服务器不支持扫爆。

不是啊 我是外网的服务器 也没扫国内

**Comment by An0nyYEZ1m0us** [comment]
![image](https://github.com/TophantTechnology/ARL/assets/144971870/e00fb0a2-af12-4968-a84b-5c951e731fdb)
我分了很多组以后 发现还是有部分容器晚上重启了

**Comment by An0nyYEZ1m0us** [comment]
并且同时进行的任务也只有一个了 我设置的两个

**Comment by An0nyYEZ1m0us** [comment]
请问docker情况下我应该给您提供一些什么信息能够帮我排查一下bug

**Comment by 1c3z** [comment]
看看文档吧。
https://tophanttechnology.github.io/ARL-doc/faq/#8

**Comment by An0nyYEZ1m0us** [comment]
可以看出结果差了很多

**Comment by An0nyYEZ1m0us** [comment]
> 看看文档吧。 https://tophanttechnology.github.io/ARL-doc/faq/#8

 我上面说的问题是不是因为arl只获取的是fofa的子域名而不是站点

**Comment by 1c3z** [comment]
fofa结果数59条，不代表子域名有59个

**Comment by 1c3z** [comment]
> > fofa结果数59条，不代表子域名有59个
> 
> 但是我进行大量任务子域名搜集的监控任务的时候老是出bug，体现在碰到那种子域名非常多的就很慢很慢，然后并行任务数量也变成1了

可以在状态中看看哪个步骤用时比较多，分析比较下。

**Comment by An0nyYEZ1m0us** [comment]
[2023-12-07 09:25:46,942: WARNING/ForkPoolWorker-2] ???[???]: ua-85-227-25-36.bbcust.telenor.se The resolution lifetime expired after 5.402 seconds: Server 127.0.0.11 UDP port 53 answered The DNS operation timed out.; Server 127.0.0.11 UDP port 53 answered The DNS operation timed out.; Server 127.0.0.11 UDP port 53 answered The DNS operation timed out.



卡住的任务一直说这个

**Comment by An0nyYEZ1m0us** [comment]
有可能是我扫描top100端口的原因嘛。。。

**Comment by An0nyYEZ1m0us** [comment]
我改为了测试端口扫描后好了一点，有的很慢 但是还在跑
