### ISSUE TITLE
发布新版本之后，没有说能不能升级。所以能不能升级呀，还是说需要重装？

### ISSUE THREAD

**Issue by Junp0** [TophantTechnology/ARL#671]
发布新版本之后，没有说能不能升级。所以能不能升级呀，还是说需要重装？

**Comment by 1c3z** [comment]
可以升级呀。
docker 环境升级不就是更新配置，拉镜像和重启容器么，约等于重装吧。只不过不删除数据。

**Comment by Junp0** [comment]
已经验证，可以直接装，数据还在

**Comment by viplurker** [comment]
> 可以升级呀。 docker 环境升级不就是更新配置，拉镜像和重启容器么，约等于重装吧。只不过不删除数据。

那个，请教下，源码部署的如何升级呢？
wget https://raw.githubusercontent.com/TophantTechnology/ARL/master/misc/setup-arl.sh
chmod +x setup-arl.sh
./setup-arl.sh
执行后版本号并未有变化

**Comment by 1c3z** [comment]
@viplurker 

1. 重启下服务
./misc/manage.sh restart 

2. 浏览器F12，网络-禁用缓存，刷新下网页。

**Comment by viplurker** [comment]
> @viplurker
> 
> 1. 重启下服务
>    ./misc/manage.sh restart
> 2. 浏览器F12，网络-禁用缓存，刷新下网页。

尝试后，底部版本依然显示为
Powered by TCC(Tophant Competence Center) ARL 2.6

**Comment by viplurker** [comment]
> @viplurker
> 
> 1. 重启下服务
>    ./misc/manage.sh restart
> 2. 浏览器F12，网络-禁用缓存，刷新下网页。

看了下，setup-arl.sh没有git pull......您这边确认下呢？我手动到/opt/ARL-NPoC  /opt/ARL下git pull后版本升级了
