### ISSUE TITLE
arl资产分组卡住

### ISSUE THREAD

**Issue by 4ek0** [TophantTechnology/ARL#673]
由于之前导入大量资产，导致web界面访问资产分组时卡住，无法正常加载和修改

**Comment by 4ek0** [comment]
想问一下在哪里可以删除掉这些资产

**Comment by 1c3z** [comment]
直接删库吧。

**Comment by 4ek0** [comment]
> 直接删库吧。 或者删除对应的资产分组。

想问问大哥库在哪个位置，分组加载不出来，直接卡住，只能去删库了

**Comment by 1c3z** [comment]
@4ek0 
docker volume rm arl_db 

https://tophanttechnology.github.io/ARL-doc/faq/#11-docker

**Comment by 4ek0** [comment]
okok，非常感谢发自我的iPhone------------------ 原始邮件 ------------------发件人: 1c3z  ***@***.***>发送时间: 2023年12月8日 19:32收件人: TophantTechnology/ARL ***@***.***>抄送: 4ek0 ***@***.***>, Mention ***@***.***>主题: Re: [TophantTechnology/ARL] arl资产分组卡住 (Issue #673)
@4ek0
docker volume rm arl_db
https://tophanttechnology.github.io/ARL-doc/faq/#11-docker

—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you were mentioned.Message ID: ***@***.***>
[
{
***@***.***": "http://schema.org",
***@***.***": "EmailMessage",
"potentialAction": {
***@***.***": "ViewAction",
"target": "https://github.com/TophantTechnology/ARL/issues/673#issuecomment-1847025923",
"url": "https://github.com/TophantTechnology/ARL/issues/673#issuecomment-1847025923",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
***@***.***": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]
