### ISSUE TITLE
源码安装，已经修改、/opt/ARL/docker/config-docker.yaml   fofa api   测试时候还是提示为修改配置文件

### ISSUE THREAD

**Issue by xyongsec** [TophantTechnology/ARL#674]
![image](https://github.com/TophantTechnology/ARL/assets/48509164/f92ee7cf-5442-4e59-9f2f-2618421315e4)

**Comment by xyongsec** [comment]
centos7 系统

**Comment by lluze** [comment]
我也遇到了一样的问题，安装完之后查看了服务的配置文件发现服务启动的ARL工作目录在`/opt/ARL/`，灯塔配置文件的路径在`/opt/ARL/app/config.yaml`。

只需要将写好的配置文件覆盖掉工作目录的配置文件`/opt/ARL/app/config.yaml`然后重启ARL服务就行了。

重启ARL服务可以用`/opt/ARL/misc/manage.sh restart`。你可以尝试下这个方法。
