### ISSUE TITLE
问题反馈

### ISSUE THREAD

**Issue by tonmonkey** [TophantTechnology/ARL#676]
## 描述问题

批量扫ip报错，扫几个可以正常运行，像一下扫20个，甚至更多就报错了
![image](https://github.com/TophantTechnology/ARL/assets/84943423/aeee5694-cbf0-41d2-9b78-1d52572714ce)

## 环境信息

- 操作系统：centos7.5
- Docker版本：
- ARL 版本:最新

### 错误输出

请执行以下命令，并提供输出结果：

```
docker-compose ps
![image](https://github.com/TophantTechnology/ARL/assets/84943423/60c2e48e-b456-4255-9f59-8b74018e0ba0)

docker-compose logs -f  --tail=10
![image](https://github.com/TophantTechnology/ARL/assets/84943423/ab96bb66-6377-4149-9d47-250a0538077b)


tail -f arl_worker.log
![image](https://github.com/TophantTechnology/ARL/assets/84943423/fa21ca4b-0d5a-46f8-a245-f41c2b320d18)





## 卸载或者重装文档。
https://tophanttechnology.github.io/ARL-doc/faq/#12-docker

**Comment by tonmonkey** [comment]
![image](https://github.com/TophantTechnology/ARL/assets/84943423/6041396d-8c68-4686-93d3-62228dafaa09)
![image](https://github.com/TophantTechnology/ARL/assets/84943423/7407c116-07a8-4071-9514-d9dabd6943a6)
![image](https://github.com/TophantTechnology/ARL/assets/84943423/4f77d412-e981-4ac5-b657-8470c56a1530)

**Comment by 1c3z** [comment]
arl_worker.log 中的日志被刷了。

可以看下这个，看看错误原因是啥。
https://tophanttechnology.github.io/ARL-doc/faq/#8

**Comment by 1c3z** [comment]
红框里面的是warning，可以不用管。
下面的1024， 应该是打开文件数限制了。 

https://forums.docker.com/t/docker-compose-yml-ulimits/59330
