### ISSUE TITLE
建议优化端口扫描功能

### ISSUE THREAD

**Issue by Oldman19** [TophantTechnology/ARL#68]
遇到的问题：如果目标网站存在waf等防护设备，在端口扫描top100/1000时，会拦截，从而导致原本80端口开放的网站都无法探测成功。
建议：建议隐藏扫描端口工具的特征或者先把爆破出来的子域名存活站点探测出来，保存后，再进行端口探测，以免原本默认web端口就存活的，给探测成不存活了。

**Comment by 1c3z** [comment]
可以把端口扫描勾选去掉，会默认探测80,443端口是否存在站点。
