### ISSUE TITLE
问题反馈arl分布式，节点扫描立马结束，无结果

### ISSUE THREAD

**Issue by Cedric1314** [TophantTechnology/ARL#680]
## 描述问题
主节点正常
![图片](https://github.com/TophantTechnology/ARL/assets/42855430/5ebd63a4-3203-4d3c-8dc1-6a2307bf9598)
其他work节点，无结果，秒结束。配置文件也成功写入worker的docker中。
![图片](https://github.com/TophantTechnology/ARL/assets/42855430/b24894ba-bb5a-4cb4-b16b-12d7b85dd08a)

**Comment by 1c3z** [comment]
有多个mongo数据库？
