### ISSUE TITLE
问题反馈

### ISSUE THREAD

**Issue by krymoje** [TophantTechnology/ARL#682]
如何配置带有账号密码的socks5代理，能否在配置文档中给出对应选项

**Comment by krymoje** [comment]
修改config-docker.yaml、config.py和config.yaml.example 文件中的proxy，以socks5://admin:admin@xx.xx.xxx.xxx:xxxx，但未扫描到结果

**Comment by 1c3z** [comment]
端口扫描不支持代理，对HTTP请求只支持HTTP代理。
