### ISSUE TITLE
问题反馈

### ISSUE THREAD

**Issue by honmashironeko** [TophantTechnology/ARL#683]
## 描述问题

2.6的docker已经挂了
ERROR: error creating temporary lease: connection error: desc = "transport: Error while dialing dial unix /run/containerd/containerd.sock: connect: connection refused": unavailable
error creating temporary lease: connection error: desc = "transport: Error while dialing dial unix /run/containerd/containerd.sock: connect: connection refused": unavailable
error creating temporary lease: connection error: desc = "transport: Error while dialing dial unix /run/containerd/containerd.sock: connect: connection refused": unavailable
error creating temporary lease: connection error: desc = "transport: Error while dialing dial unix /run/containerd/containerd.sock: connect: connection refused": unavailable
error creating temporary lease: connection error: desc = "transport: Error while dialing dial unix /run/containerd/containerd.sock: connect: connection refused": unavailable

**Comment by 1c3z** [comment]
感觉是docker服务挂了，重启看看。

**Comment by honmashironeko** [comment]
docker服务应该是没问题的，我测了4台不同地方的vps，那时候都会这样报错，昨天未进行任何操作，只进行pull，已经成功获取docker，可能是docker库挂了
