### ISSUE TITLE
通过最新的docker.zip 无法升级ARL

### ISSUE THREAD

**Issue by Silery** [TophantTechnology/ARL#686]
下载最新的docker环境通过docker-compose up -d 升级发现还是2.5 ,有师傅遇到过这个问题吗？感谢~
![image](https://github.com/TophantTechnology/ARL/assets/61609966/01bd92e7-c6c9-446a-a321-ebf2b680e7fe)

![image](https://github.com/TophantTechnology/ARL/assets/61609966/36150654-38d7-4be2-99b2-4c866403ebdc)

**Comment by 1c3z** [comment]
是不是忘记 Pull 了。

**Comment by luckly2021** [comment]
我也是一样的问题，解决了吗

**Comment by Silery** [comment]
> 是不是忘记拉了。

忘记拉了是什么意思？能细说吗

**Comment by luckly2021** [comment]
你好，你的邮件已收到。我现在无法立刻回复你的邮件。我将在查看后，尽快给你回复。

**Comment by 1c3z** [comment]
#720 参考这里面的解决方法，issue 先关闭。
