### ISSUE TITLE
问题反馈 - 上传指纹 功能

### ISSUE THREAD

**Issue by WasteMaterial** [TophantTechnology/ARL#687]
## 上传指纹 功能

选择上传指纹后选择了一个带有部分指纹的文件进行上传，提示`Request failed with status code 413`

![image](https://github.com/TophantTechnology/ARL/assets/32891131/cb22e187-a3a5-4eaa-97a4-50d92833881e)

**Comment by 1c3z** [comment]
上传的文件太大，多大的文件？。

**Comment by BigYoungs** [comment]
> 上传的文件太大，多大的文件？。

2.6版本，实测是指纹文件超过1M，就会提示这个413。2.6.1版本，还未测试。我的解决方案如下：

> 以下内容针对ARL容器部署的情况，如果是源码部署的，同理

1. 进入到arl-web容器里，执行：docker exec -it arl-web /bin/bash

2. vim /etc/nginx/nginx.conf

3. 在http块下，添加以下内容：
    client_max_body_size 20m;

4. 重启nginx：nginx -s reload

5. 退出容器：exit

6. 重新导入指纹文件，正常导入。
