### ISSUE TITLE
 ARM版本支持源码安装吗

### ISSUE THREAD

**Issue by Murphy857** [TophantTechnology/ARL#688]
## 描述问题

ARM版本支持源码安装吗

## 环境信息

- 操作系统：centos7
- Docker版本：
- ARL 版本:

### 错误输出

请执行以下命令，并提供输出结果：

```
docker-compose ps

docker-compose logs -f  --tail=10

tail -f arl_worker.log
```

## 复现步骤

请提供重现问题所需的详细步骤。

1. 步骤一
2. 步骤二
3. 步骤三

## 预期行为

请描述您预期发生的事情。

## 实际行为

请描述实际发生的事情。

## 附加上下文

在此处提供其他有关问题的任何其他上下文。

## 卸载或者重装文档。
https://tophanttechnology.github.io/ARL-doc/faq/#12-docker

**Comment by 1c3z** [comment]
支持，是差不多的。 


arm 镜像是build出来的，参考。
https://github.com/TophantTechnology/ARL/blob/master/docker/ARMWorker/Dockerfile
