### ISSUE TITLE
问题反馈

### ISSUE THREAD

**Issue by shiwujie123** [TophantTechnology/ARL#691]
fofa的api接口域名还是fofa.so,现在已经是fofa.info了可以更新下。
还有为啥GitHub创建的任务都是error。
![image](https://github.com/TophantTechnology/ARL/assets/55862426/a59aeea0-a043-45d6-bcbd-79dc585ad74c)

**Comment by shiwujie123** [comment]
GitHub检查又可以使用了，可能是因为网络原因吧。

**Comment by 1c3z** [comment]
github 任务是error，看下配key 了么。 


哥，升级下吧。

![image](https://github.com/TophantTechnology/ARL/assets/9052484/b09a09e9-84c7-4a8d-b7c1-286e184d7746)

**Comment by shiwujie123** [comment]
谢谢，我这边没更新的问题，还以为下载的最新版本呢。
