### ISSUE TITLE
2.6.1版本推送消息失败

### ISSUE THREAD

**Issue by ordshine** [TophantTechnology/ARL#699]
## 描述问题

运行python3.6 -m test.test_utils_push测试推送，会爆错误。

![image](https://github.com/TophantTechnology/ARL/assets/77093989/ddc4834b-896c-4beb-85a5-3ef1cee33e79)

## 环境信息

- 操作系统：linux
- Docker版本：Docker version 20.10.23+dfsg1, build 7155243
- ARL 版本: 2.6.1

### 错误输出

请执行以下命令，并提供输出结果：

```
docker-compose ps

docker-compose logs -f  --tail=10

tail -f arl_worker.log
```

## 复现步骤

请提供重现问题所需的详细步骤。

1. 步骤一
2. 步骤二
3. 步骤三

## 预期行为

请描述您预期发生的事情。

## 实际行为

请描述实际发生的事情。

## 附加上下文

在此处提供其他有关问题的任何其他上下文。

## 卸载或者重装文档。
https://tophanttechnology.github.io/ARL-doc/faq/#12-docker

重装很多次，也更换版本，仍然报错。

**Comment by 1c3z** [comment]
感谢反馈，导入有点问题。 
可以先在test_utils_push.py 前面加上。
```
from app.helpers.domain import find_domain_by_task_id
```

**Comment by ordshine** [comment]
> 感谢反馈，导入有点问题。 可以先在test_utils_push.py 前面加上。
> 
> ```
> from app.helpers.domain import find_domain_by_task_id
> ```

![image](https://github.com/TophantTechnology/ARL/assets/77093989/4fcefac0-d65a-4681-9505-dd232c1e03a3)
还是会报错

**Comment by 1c3z** [comment]
这个是没有配置相关配置项。

**Comment by 1c3z** [comment]
@Arrowzzzzzz 

添加任务没有推送，目前只是资产分组中发现新的域名有推送和资产变化有推送。

**Comment by 1c3z** [comment]
已修复。
