### ISSUE TITLE
FOFA 数据源 缺少页数大小等配置

### ISSUE THREAD

**Issue by C2yb8er** [TophantTechnology/ARL#701]
## 描述问题

先说结论，是由于Fofa_api的限制而不是ARL本身的问题,是FOFA_API一次只能返回最多10000条的限制。来源于我之前的使用体验，使用同样的Fofa语句，比如能搜到大量地的资产，但是ARL只会跑几千条，然后我们反复运行发现得到的资产结果是一致的，这样就大大地影响了配合Fofa使用好处，只能自己更换不同的Fofa语句来实现降重，非常麻烦。

## 环境信息

- 操作系统：linux
- ARL 版本:最新版本

## 解决建议

经过我的查阅arl源码过后，arl调用fofa_api是对应的默认参数page是没有指定的，所以对于大资产的处理上我们获取的总是第一页的数据，在这里我认为可以在fofa任务调用处，提供一个功能其实也比较简单就是可以提供增加page参数的指定。这样就可以大大解决在使用大资产比如十几万条，使用相同的语句，ARL只会跑重复的资产的问题。

**Comment by 1c3z** [comment]
没太明白要说明的问题。

比如能搜到大量地的资产，但是ARL只会跑几千条,   里面有重复数据，目前是取IP。 


默认是查9999条。
![image](https://github.com/TophantTechnology/ARL/assets/9052484/747f3cd2-6cdf-4c29-885e-e2e0cd60cb01)

**Comment by C2yb8er** [comment]
作者大大可能是我的描述没让你理解我提出来的问题。假如我们使用FOFA语句例如收集所有教育网的资产，然后他本来是有几千万条，去重取得独立ip后可能也有十几万几百万的样子，但是如果直接使用fofa api的话他默认只会搜集fofa按照时间顺序更新的前9999条非取独立ip后的资产，最后跑进ARL可能也就几千条。当我们跑完一次后，我们在使用同样的fofa语句的话，通过ARL调用fofa api获取的资产大概率是跟第一次获取到的是差不多的，这样就会导致重复，大量的资产没有跑出来。为了解决我们可以增加一个自主指定page参数（不指定就是第一页的数据），比如说第一次我用的是第一页的数据，第二次用的是第二页的数据，个人感觉这样会降低很多重复率。而不是总是获取的资产是来自第一页。

**Comment by 1c3z** [comment]
已更新。
