### ISSUE TITLE
自写的指纹为什么不生效

### ISSUE THREAD

**Issue by luckly2021** [TophantTechnology/ARL#713]
请教大佬一个问题，麻烦帮忙看一下。

## 描述问题

       自己写的springboot 指纹f规则，springboot 框架在出现404或503错误时页面会显示包含关键字Whitelabel Error Page等详细信息，

![image](https://github.com/TophantTechnology/ARL/assets/95059157/cc0e5bc3-3eee-4490-aeaa-e97e98e1cf93)

      详细规则为：body="Whitelabel Error Page" || icon_hash="116323821"
![image](https://github.com/TophantTechnology/ARL/assets/95059157/e39ee034-11b4-41de-b840-d0255711b5c2)
资产发现过程中，仅识别 icon_hash="116323821" 的规则，而body="Whitelabel Error Page" 始终识别不到，是什么原因。
![image](https://github.com/TophantTechnology/ARL/assets/95059157/a8ea3ea7-f514-475c-92a9-a64ce8529d47)

**Comment by 1c3z** [comment]
可以用这个

```
body=",\"status\":404,\"error\":\"Not Found\",\"message\":\"No message available\",\"path\""

```
