### ISSUE TITLE
2.6.1版本URL信息、WIH内容无法删除

### ISSUE THREAD

**Issue by luckly2021** [TophantTechnology/ARL#715]
2.6.1版本扫描有大量URL信息、WIH内容无法删除，建议WIH增加导出excel功能。

**Comment by 1c3z** [comment]
1. url 收集默认是不开的，这个功能不适合你。
2.  导出功能后面可以考虑加下。

**Comment by 1c3z** [comment]
v2.6.2 已更新。

**Comment by luckly2021** [comment]
你好，你的邮件已收到。我现在无法立刻回复你的邮件。我将在查看后，尽快给你回复。
