### ISSUE TITLE
问题反馈

### ISSUE THREAD

**Issue by ordshine** [TophantTechnology/ARL#718]
## 描述问题

下发任务后，状态一直是waiting
在这之前是大量删除了一些任务，出现了找不到Celery id 的问题，我是通过删除mongodb中的task，清空了所有任务后，重新下发的任务。

## 环境信息

- 操作系统：
- Docker版本：
- ARL 版本: 2.6.1

### 错误输出

请执行以下命令，并提供输出结果：
docker-compose ps
![image](https://github.com/TophantTechnology/ARL/assets/77093989/d26fae34-3f70-4581-bc11-7d1eecad197b)

docker-compose logs -f  --tail=10
![image](https://github.com/TophantTechnology/ARL/assets/77093989/a4dd9ed1-bc39-4eef-86f0-168660a725a5)

tail -f arl_worker.log
![image](https://github.com/TophantTechnology/ARL/assets/77093989/985bd388-4ab3-4fe0-928b-55e7d0ffe068)

## 复现步骤

请提供重现问题所需的详细步骤。

1. 步骤一
2. 步骤二
3. 步骤三

## 预期行为

请描述您预期发生的事情。

## 实际行为

请描述实际发生的事情。

## 附加上下文

在此处提供其他有关问题的任何其他上下文。

## 卸载或者重装文档。
https://tophanttechnology.github.io/ARL-doc/faq/#12-docker

**Comment by 1c3z** [comment]
看日志是卡在了 文件泄露 这个任务选项。 

下面是一些建议操作。

用源码安装
并发任务数改成1
https://tophanttechnology.github.io/ARL-doc/faq/
