### ISSUE TITLE
问题反馈

### ISSUE THREAD

**Issue by ixix1234** [TophantTechnology/ARL#719]
## 描述问题
安装完打开ARL 老是提示  报错 timeout of 12000ms exceeded

## 环境信息

- 操作系统：centos:7.6
- Docker版本： 25.0.2
- ARL 版本:2.6.1

### 错误输出

请执行以下命令，并提供输出结果：

```
docker-compose ps
![1](https://github.com/TophantTechnology/ARL/assets/141918848/d9bf482c-340c-46c8-83a9-b2f060b0581e)

docker-compose logs -f  --tail=10
![2](https://github.com/TophantTechnology/ARL/assets/141918848/789299b1-a4f5-4046-8325-7931bb6b36ad)


tail -f arl_worker.log
输出为空
```

## 复现步骤

请提供重现问题所需的详细步骤。

1. 步骤一
2. 步骤二
3. 步骤三

## 预期行为

请描述您预期发生的事情。

## 实际行为

请描述实际发生的事情。

## 附加上下文

在此处提供其他有关问题的任何其他上下文。

## 卸载或者重装文档。
https://tophanttechnology.github.io/ARL-doc/faq/#12-docker

**Comment by ixix1234** [comment]
步骤1：
![1707058354718](https://github.com/TophantTechnology/ARL/assets/141918848/706b068e-e859-46a9-8ddc-b5a2f56be175)
步骤2：
![1707058407697](https://github.com/TophantTechnology/ARL/assets/141918848/e3185db6-4b5b-4722-9c5f-6d6df4c1b754)
步骤3：
![1707058447857](https://github.com/TophantTechnology/ARL/assets/141918848/21f27624-32a2-4c6a-bae4-cb76a450374e)

搞一晚上了  麻烦大神帮忙看看   @1c3z

**Comment by 1c3z** [comment]
#720

**Comment by ixix1234** [comment]
1.按照文档重装了 还是那个问题      没有登录界面直接进系统了  @1c3z 
![1707114326473](https://github.com/TophantTechnology/ARL/assets/141918848/5851186c-bd5c-48d7-b307-0b50a518b93c)
2.
![1707114432209](https://github.com/TophantTechnology/ARL/assets/141918848/7827dd7d-3634-4970-b9f5-6cc07d3d522b)
3.
![1707114403911](https://github.com/TophantTechnology/ARL/assets/141918848/f5ccf632-e5bd-47cc-819a-c6027582b1d3)

**Comment by 1c3z** [comment]
1. 镜像没更新好。
2. 在　ChatGPT　学习下容器的基本知识吧。
