### ISSUE TITLE
Parse config.yaml error 'RISKIQ'

### ISSUE THREAD

**Issue by 1c3z** [TophantTechnology/ARL#720]
容器反复重启，出现错误，Parse config.yaml error 'RISKIQ'，是容器镜像没有更新导致的。

先排查是否配置了镜像源，配置了最好删除，可以查看 `/etc/docker/daemon.json`  的配置。
再执行pull命令更新镜像。

```
docker compose down
docker compose pull
docker compose up -d
```

如果还是不行，参考这个重装。
https://tophanttechnology.github.io/ARL-doc/faq/#11-docker

**Comment by SwordSSR** [comment]
昨天我也遇到这个问题了，经过排查后解决了。出现这个问题是因为国内封禁docker后，通过配置的docker加速器去拉去ARL lastest版本会出现版本不准确的情况，针对最新的v2.6.1版本，可以通过修改解压缩文件中的.env文件，指定版本方式解决，如（ARL_VERSION=v2.6.1）。
同时也建议官方，发布docker.zip时，在.env用正确的版本替换lastest，降低出问题的概率。

**Comment by 1c3z** [comment]
@SwordSSR  后面.env 文件不写latest
