### ISSUE TITLE
前台删除任务失败，问题与#632相同

### ISSUE THREAD

**Issue by ordshine** [TophantTechnology/ARL#724]
## 描述问题

通过前台停止并删除任务，但是查看任务日志发现，仍然还在进行该任务，导致其他任务一直在等待状态。

是否可以服务器上停止掉该任务？

相似问题：
https://github.com/TophantTechnology/ARL/issues/632

## 环境信息

- 操作系统：
- Docker版本：
- ARL 版本: 2.6.1

### 错误输出

请执行以下命令，并提供输出结果：

docker-compose ps
![image](https://github.com/TophantTechnology/ARL/assets/77093989/79c8f982-1deb-444a-a88e-b0d018e8f008)

docker-compose logs -f  --tail=10
![image](https://github.com/TophantTechnology/ARL/assets/77093989/b436d577-df93-4b2e-b35e-7a226a9ad11b)

tail -f arl_worker.log
![image](https://github.com/TophantTechnology/ARL/assets/77093989/17479814-b999-4117-b8eb-eeb4f7c02eda)

查看db
![image](https://github.com/TophantTechnology/ARL/assets/77093989/bba43980-44a5-468e-8d89-90104df56490)

## 复现步骤

请提供重现问题所需的详细步骤。

1. 步骤一
2. 步骤二
3. 步骤三

## 预期行为

请描述您预期发生的事情。

## 实际行为

请描述实际发生的事情。

## 附加上下文

在此处提供其他有关问题的任何其他上下文。

## 卸载或者重装文档。
https://tophanttechnology.github.io/ARL-doc/faq/#12-docker

**Comment by 1c3z** [comment]
卡在文件泄露这个选项了，临时方法是，重启worker容器。

在旧版本有这个问题，新的版本修复了。
