### ISSUE TITLE
下任务时无效的url 

### ISSUE THREAD

**Issue by ixix1234** [TophantTechnology/ARL#725]
## 描述问题

请在此处提供对问题的清晰而简洁的描述。

## 环境信息

- 操作系统：
- Docker版本：
- ARL 版本:

### 错误输出
![c41442954c89c4e4e3892fdc72e1640](https://github.com/TophantTechnology/ARL/assets/141918848/db4b365f-6fd8-4e19-833f-77b13e3cdddb)

请执行以下命令，并提供输出结果：

```
docker-compose ps

docker-compose logs -f  --tail=10

tail -f arl_worker.log
```

## 复现步骤

请提供重现问题所需的详细步骤。

1. 步骤一
2. 步骤二
3. 步骤三

## 预期行为

请描述您预期发生的事情。

## 实际行为

请描述实际发生的事情。

## 附加上下文

在此处提供其他有关问题的任何其他上下文。

## 卸载或者重装文档。
https://tophanttechnology.github.io/ARL-doc/faq/#12-docker

**Comment by 1c3z** [comment]
不支持下发URL。  灯塔不是漏扫。
