### ISSUE TITLE
资产监控通知失败问题

### ISSUE THREAD

**Issue by haski-lib** [TophantTechnology/ARL#729]
## 描述问题

升级至最新版本后配置邮箱\企业微信通知,使用python3.6 -m test.test_utils_push测试执行失败

## 环境信息

- 操作系统：Linux
- Docker版本：
- ARL 版本:2.6.1

### 错误输出

请执行以下命令，并提供输出结果：

```
docker-compose exec worker bash
python3.6 -m test.test_utils_push
```
![image](https://github.com/TophantTechnology/ARL/assets/67529192/5a1944fb-3a4c-47ec-9f4c-aedf60e49d6c)
![image](https://github.com/TophantTechnology/ARL/assets/67529192/5e81fc65-1185-482f-b882-8eda63c95d9b)

**Comment by 1c3z** [comment]
感谢反馈，还没修。 

#699

**Comment by whiT3-web** [comment]
> 感谢反馈，还没修。
> 
> 可以先在test_utils_push.py 前面加上。
> 
> from app.helpers.domain import find_domain_by_task_id
> 
> #699

已在test_utils_push.py添加from app.helpers.domain import find_domain_by_task_id
执行报错：
[root@d80e78f87d15 code]# python3.6 -m test.test_utils_push
FFFF
======================================================================
FAIL: test_push_dingding (__main__.TestUtilsPush)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/code/test/test_utils_push.py", line 100, in test_push_dingding
    self.assert_dingding_config()
  File "/code/test/test_utils_push.py", line 85, in assert_dingding_config
    self.assertTrue(Config.DINGDING_SECRET)
AssertionError: '' is not true

======================================================================
FAIL: test_push_email (__main__.TestUtilsPush)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/code/test/test_utils_push.py", line 111, in test_push_email
    self.assert_email_config()
  File "/code/test/test_utils_push.py", line 89, in assert_email_config
    self.assertTrue(Config.EMAIL_PASSWORD)
AssertionError: '' is not true

======================================================================
FAIL: test_push_feishu (__main__.TestUtilsPush)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/code/test/test_utils_push.py", line 122, in test_push_feishu
    self.assert_feishu_config()
  File "/code/test/test_utils_push.py", line 93, in assert_feishu_config
    self.assertTrue(Config.FEISHU_SECRET)
AssertionError: '' is not true

======================================================================
FAIL: test_wx_work_push (__main__.TestUtilsPush)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/code/test/test_utils_push.py", line 133, in test_wx_work_push
    self.assert_wx_work_config()
  File "/code/test/test_utils_push.py", line 97, in assert_wx_work_config
    self.assertTrue(Config.WX_WORK_WEBHOOK)
AssertionError: '' is not true

----------------------------------------------------------------------
Ran 4 tests in 0.001s

FAILED (failures=4)

**Comment by 1c3z** [comment]
v2.6.2 已修复
