### ISSUE TITLE
问题反馈

### ISSUE THREAD

**Issue by TianwenOVO** [TophantTechnology/ARL#730]
## 描述问题

用centos7通过源码全新安装的ARL，运行/opt/ARL/misc/manage.sh start，会爆如下错误：
[root@xxxx ~]# /opt/ARL/misc/manage.sh start
Job for nginx.service failed because the control process exited with error code. See "systemctl status nginx.service" and "journalctl -xe" for details.

[root@xxxx ~]# systemctl status nginx.service
● nginx.service - The nginx HTTP and reverse proxy server
   Loaded: loaded (/usr/lib/systemd/system/nginx.service; enabled; vendor preset: disabled)
   Active: failed (Result: exit-code) since Wed 2024-02-21 23:29:55 EST; 19s ago
  Process: 1936 ExecStartPre=/usr/sbin/nginx -t (code=exited, status=1/FAILURE)
  Process: 1935 ExecStartPre=/usr/bin/rm -f /run/nginx.pid (code=exited, status=0/SUCCESS)

Feb 21 23:29:55 yingk systemd[1]: Starting The nginx HTTP and reverse proxy server...
Feb 21 23:29:55 yingk nginx[1936]: nginx: the configuration file /etc/nginx/nginx.conf syntax is ok
Feb 21 23:29:55 yingk nginx[1936]: nginx: [emerg] bind() to 0.0.0.0:5003 failed (13: Permission denied)
Feb 21 23:29:55 yingk nginx[1936]: nginx: configuration file /etc/nginx/nginx.conf test failed
Feb 21 23:29:55 yingk systemd[1]: nginx.service: control process exited, code=exited status=1
Feb 21 23:29:55 yingk systemd[1]: Failed to start The nginx HTTP and reverse proxy server.
Feb 21 23:29:55 yingk systemd[1]: Unit nginx.service entered failed state.
Feb 21 23:29:55 yingk systemd[1]: nginx.service failed.

## 环境信息

- 操作系统：CentOS7
- Docker版本：
- ARL 版本: 2.6.1

重装过两次，未做任何修改。。。

**Comment by 1c3z** [comment]
bind() to 0.0.0.0:5003 failed (13: Permission denied)  是不是端口呗占用了？

**Comment by N4ick** [comment]
是centos7的selinux的问题，放行5003端口就行了，semanage port -m -t http_port_t -p tcp 5003,同时改/etc/nginx/nginx.conf 里面的用户名为你当前系统的用户后就可以正常运行了。

**Comment by N4ick** [comment]
@TianwenOVO 是centos7的selinux的问题，放行5003端口就行了，semanage port -m -t http_port_t -p tcp 5003,同时改/etc/nginx/nginx.conf 里面的用户名为你当前系统的用户后就可以正常运行了。

**Comment by 101apa** [comment]
nginx -s stop

**Comment by 101apa** [comment]
nginx -s stop
nginx -c /opt/ARL/docker/nginx.conf
