### ISSUE TITLE
问题反馈 -指纹导入异常

### ISSUE THREAD

**Issue by ChenZIDu** [TophantTechnology/ARL#731]
## 描述问题

灯塔 指纹导入异常，指纹是从另一个灯塔上导出的，导入到现有灯塔中导入不进去
![image](https://github.com/TophantTechnology/ARL/assets/49174343/320cfad2-ea90-4933-bd52-fee128099228)

## 环境信息

- 操作系统：ubuntu
- ARL 版本: Powered by TCC(Tophant Competence Center) ARL 2.6.1

**Comment by 1c3z** [comment]
新版本指纹格式改成了yml格式了。需要手动转换下。 

https://tophanttechnology.github.io/ARL-doc/function_desc/finger/
