### ISSUE TITLE
配置代理后，扫描内网IP也会走代理

### ISSUE THREAD

**Issue by Fluorescence9** [TophantTechnology/ARL#733]
## 描述问题

配置代理后，扫描内网IP也会走代理

## 环境信息

- 操作系统：centos 7.9
- Docker版本：
- ARL 版本: 2.6.1

## 预期行为

希望可以增加配置，哪些IP扫描不使用代理，或者针对内网IP默认不使用代理

## 实际行为

配置代理后，扫描内网IP也会走代理，导致内网IP的站点爬取结果不正确
每次扫描内网或外网，都需要手动更改配置文件中的代理配置

## 卸载或者重装文档。
https://tophanttechnology.github.io/ARL-doc/faq/#12-docker

**Comment by 1c3z** [comment]
和 #734 重复，先关闭。
