### ISSUE TITLE
希望增加特定一个或多个端口 不扫描

### ISSUE THREAD

**Issue by heywiorld** [TophantTechnology/ARL#735]
## 描述问题

希望增加特定一个或多个端口 不扫描

## 环境信息

- 操作系统：linux
- Docker版本： 20.10.11
- ARL 版本:2.6.1

### 错误输出

请执行以下命令，并提供输出结果：

```
docker-compose ps

docker-compose logs -f  --tail=10

tail -f arl_worker.log
```

## 复现步骤

请提供重现问题所需的详细步骤。

1. 自定义端口建议增加一个或多个端口不扫描

## 预期行为

针对输入的端口不进行扫描

## 实际行为

暂时无此功能

## 附加上下文

建议增加此功能。

## 卸载或者重装文档。
https://tophanttechnology.github.io/ARL-doc/faq/#12-docker

**Comment by 1c3z** [comment]
v2.6.2 已更新。
