### ISSUE TITLE
docker-compose 弃用了，用 docker compose pull

### ISSUE THREAD

**Issue by ixix1234** [TophantTechnology/ARL#737]
## 描述问题

请在此处提供对问题的清晰而简洁的描述。

## 环境信息

- 操作系统：
unbuntu 22.0.4
- Docker版本：25.0.3
- ARL 版本:2.6.1

你好 unbuntu 22.0.4 是安装不了灯塔吗 为什么 docker-compose pull 的时候会报错

![1709622248846](https://github.com/TophantTechnology/ARL/assets/141918848/ef334af0-dd56-4df5-9bc2-92a6dd112ae9)
![1709622248846](https://github.com/TophantTechnology/ARL/assets/141918848/ee2e8168-e663-40c6-91c3-286db5d60b8b)

**Comment by 1c3z** [comment]
docker-compose 弃用了，用 docker compose pull

**Comment by 1c3z** [comment]
v2.6.2 文档已更新。
