### ISSUE TITLE
2核4G服务器占用率100%

### ISSUE THREAD

**Issue by gotosleeping** [TophantTechnology/ARL#743]
## 描述问题

我的机器是重装后  新装的arl，很干净  只有arl

一开arl的web我的机器cpu占用率就百分百了
![image](https://github.com/TophantTechnology/ARL/assets/64306303/edb91afb-44b0-47b0-ad3b-a458bf676d9d)
一关web就正常了

![image](https://github.com/TophantTechnology/ARL/assets/64306303/ffbd9fe7-078f-4344-9b43-56cf95d816e6)

**Comment by 1c3z** [comment]
web容器在疯狂重启

https://tophanttechnology.github.io/ARL-doc/faq/#3
