### ISSUE TITLE
问题反馈

### ISSUE THREAD

**Issue by alair074** [TophantTechnology/ARL#744]
## 描述问题

源代码安装，报错：Request failed with status code 502
![image](https://github.com/TophantTechnology/ARL/assets/41234701/e06391de-8f6b-48b3-9d03-d865c26a7a21)

## 环境信息

- 操作系统：Centos7
- ARL 版本: v2.6.1

**Comment by 1c3z** [comment]
检查 arl-web 服务是否已启用。

**Comment by alair074** [comment]
> 检查 arl-web 服务是否已启用。

![image](https://github.com/TophantTechnology/ARL/assets/41234701/0bf5f6c2-11d0-4d59-9f87-c39096e717b1)
这个是算启动了的吧

**Comment by 1c3z** [comment]
看5013 端口是否正常。
curl  http://127.0.0.1:5013/api/

**Comment by alair074** [comment]
> curl http://127.0.0.1:5013/api/

![image](https://github.com/TophantTechnology/ARL/assets/41234701/20cdfda5-2344-48e8-83e7-24e57746390b)
404

**Comment by 1c3z** [comment]
看下nginx 的错误日志， /var/log/nginx/error.log

感觉nginx proxy配错端口了。

https://github.com/TophantTechnology/ARL/blob/master/misc/arl.conf

**Comment by alair074** [comment]
> 看下nginx 的错误日志， /var/log/nginx/error.log
> 
> 感觉nginx proxy配错端口了。
> 
> https://github.com/TophantTechnology/ARL/blob/master/misc/arl.conf

可以了，SeLinux没关。。。谢谢
