### ISSUE TITLE
问题反馈

### ISSUE THREAD

**Issue by licongliyu** [TophantTechnology/ARL#745]
## 描述问题

FOFA任务下发测试,报错如下
<img width="350" alt="1711503635271" src="https://github.com/TophantTechnology/ARL/assets/48317622/657297a8-5c67-4bd2-a285-396a083a63af">

arl_web.log日志请求都是正常的
<img width="1236" alt="1711504557384" src="https://github.com/TophantTechnology/ARL/assets/48317622/2d069db0-b5e0-4ee2-be6a-292869a0bb50">

arl_worker.log日志正常
<img width="600" alt="1711504581564" src="https://github.com/TophantTechnology/ARL/assets/48317622/c15511ea-ecde-4da4-9045-682f7ff2da39">

## 环境信息

- 操作系统：Debian 5.10.46
- Docker版本：20.10.25
- ARL 版本: 2.6.1

### 错误输出

请执行以下命令，并提供输出结果：

```
docker-compose ps

docker-compose logs -f  --tail=10

tail -f arl_worker.log
```

## 复现步骤

请提供重现问题所需的详细步骤。

1. 步骤一
2. 步骤二
3. 步骤三

## 预期行为

请描述您预期发生的事情。

## 实际行为

请描述实际发生的事情。

## 附加上下文

在此处提供其他有关问题的任何其他上下文。

## 卸载或者重装文档。
https://tophanttechnology.github.io/ARL-doc/faq/#12-docker

**Comment by 1c3z** [comment]
服务器上curl 看是否返回json

curl https://fofa.info/api/v1/search/all

**Comment by licongliyu** [comment]
> 服务器上curl 看是否返回json
> 
> curl https://fofa.info/api/v1/search/all

<img width="286" alt="1711510841412" src="https://github.com/TophantTechnology/ARL/assets/48317622/84931e70-ef5e-4add-8e9d-9de2be7bba77">
也是正常

**Comment by licongliyu** [comment]
加了key也是返回json数据
![image](https://github.com/TophantTechnology/ARL/assets/48317622/dd822144-7d20-479d-bbfd-ec3671a43ad3)

**Comment by 1c3z** [comment]
怀疑版本没升级好，访问的是fofa.so， 可以看下容器中的[version.txt](https://github.com/TophantTechnology/ARL/blob/master/version.txt) 版本号。

**Comment by licongliyu** [comment]
> 怀疑版本没升级好，访问的是fofa.so， 可以看下容器中的[version.txt](https://github.com/TophantTechnology/ARL/blob/master/version.txt) 版本号。

解决了 确实是镜像版本问题  但是无论怎么拉latest标签的镜像都是2年前的版本 指定docker pull tophant/arl:v2.6.1才能拉到现在的
