### ISSUE TITLE
centos7源码安装nginx服务未启动

### ISSUE THREAD

**Issue by zilyl** [TophantTechnology/ARL#747]
centos7 源码安装web服务未启动

[root@localhost ~]# /opt/ARL/misc/manage.sh status
Unit arl-web.service could not be found.
Unit arl-worker.service could not be found.
Unit arl-worker-github.service could not be found.
Unit arl-scheduler.service could not be found.
● nginx.service - The nginx HTTP and reverse proxy server
   Loaded: loaded (/usr/lib/systemd/system/nginx.service; disabled; vendor preset: disabled)
   Active: inactive (dead)
● mongod.service - MongoDB Database Server
   Loaded: loaded (/usr/lib/systemd/system/mongod.service; enabled; vendor preset: disabled)
   Active: active (running) since Thu 2024-03-28 07:27:04 PDT; 5min ago
     Docs: https://docs.mongodb.org/manual
 Main PID: 6979 (mongod)
    Tasks: 28
   CGroup: /system.slice/mongod.service
           └─6979 /usr/bin/mongod -f /etc/mongod.conf

Mar 28 07:27:04 localhost.localdomain systemd[1]: Starting MongoDB Database Server...
Mar 28 07:27:04 localhost.localdomain mongod[6975]: about to fork child process, waiting until server is ready for connections.
Mar 28 07:27:04 localhost.localdomain mongod[6975]: forked process: 6979
Mar 28 07:27:04 localhost.localdomain systemd[1]: Started MongoDB Database Server.
● rabbitmq-server.service - RabbitMQ broker
   Loaded: loaded (/usr/lib/systemd/system/rabbitmq-server.service; enabled; vendor preset: disabled)
   Active: active (running) since Thu 2024-03-28 07:27:05 PDT; 5min ago
 Main PID: 7055 (beam.smp)
    Tasks: 42
   CGroup: /system.slice/rabbitmq-server.service
           ├─7055 /usr/lib64/erlang/erts-5.10.4/bin/beam.smp -W w -K true -A30 -P 1048576 -- -root /usr/lib64/erlang -progname erl -- -home /var/lib/rabbitmq -- -pa /usr/lib/rabbitmq/lib...
           ├─7073 /usr/lib64/erlang/erts-5.10.4/bin/epmd -daemon
           ├─7159 inet_gethost 4
           └─7160 inet_gethost 4

Mar 28 07:27:04 localhost.localdomain systemd[1]: Got notification message from PID 7102, but reception only permitted for main PID 7055
Mar 28 07:27:04 localhost.localdomain systemd[1]: Got notification message from PID 7103, but reception only permitted for main PID 7055
Mar 28 07:27:04 localhost.localdomain rabbitmq-server[7055]: RabbitMQ 3.3.5. Copyright (C) 2007-2014 GoPivotal, Inc.
Mar 28 07:27:04 localhost.localdomain rabbitmq-server[7055]: ##  ##      Licensed under the MPL.  See http://www.rabbitmq.com/
Mar 28 07:27:04 localhost.localdomain rabbitmq-server[7055]: ##  ##
Mar 28 07:27:04 localhost.localdomain rabbitmq-server[7055]: ##########  Logs: /var/log/rabbitmq/rabbit@localhost.log
Mar 28 07:27:04 localhost.localdomain rabbitmq-server[7055]: ######  ##        /var/log/rabbitmq/rabbit@localhost-sasl.log
Mar 28 07:27:04 localhost.localdomain rabbitmq-server[7055]: ##########
Mar 28 07:27:05 localhost.localdomain rabbitmq-server[7055]: Starting broker... completed with 0 plugins.
Mar 28 07:27:05 localhost.localdomain systemd[1]: Started RabbitMQ broker.

[root@localhost ~]# /opt/ARL/misc/manage.sh start
Failed to start arl-web.service: Unit not found.
Failed to start arl-worker.service: Unit not found.
Failed to start arl-worker-github.service: Unit not found.
Failed to start arl-scheduler.service: Unit not found.

**Comment by 1c3z** [comment]
看这个文件吧，
https://github.com/TophantTechnology/ARL/blob/master/misc/setup-arl.sh

不明白的地方可以问ChatGPT
