### ISSUE TITLE
请问如何将wih添加到新建任务界面进行勾选？

### ISSUE THREAD

**Issue by gongyu0217** [TophantTechnology/ARL#748]
<img width="263" alt="微信图片_20240329150028" src="https://github.com/TophantTechnology/ARL/assets/55569414/445fb338-a2ec-48ed-aa22-8a2130e2b06f">

**Comment by 1c3z** [comment]
没升级，更新下就有了。

**Comment by gongyu0217** [comment]
<img width="190" alt="屏幕截图 2024-03-29 163655" src="https://github.com/TophantTechnology/ARL/assets/55569414/cf0674a7-38c5-4bd5-8287-f99e5129b276">
已经是zui新版了，但是还是没有wih。。。

**Comment by 1c3z** [comment]
把服务down了，删除镜像，再pull看看
