### ISSUE TITLE
V2.6.1任务全部删除后，全局查看依然存在

### ISSUE THREAD

**Issue by Passwords404** [TophantTechnology/ARL#753]
## 描述问题

V2.6.1任务全部删除后资产搜索功能没有站点，但是全局查看文件泄露，nuclei，WIH依然存在内容。

## 环境信息

- 操作系统：
- Docker版本： 20.10.21
- ARL 版本:V2.6.1

**Comment by 1c3z** [comment]
2.6.1 有删除的，核对下系统登陆页面的版本吧。 


https://github.com/TophantTechnology/ARL/blob/master/app/routes/task.py#L210
