### ISSUE TITLE
fofa任务下发超时

### ISSUE THREAD

**Issue by YamiKurumi** [TophantTechnology/ARL#754]
配置完fofa的api后点击fofa任务下发，
测试成功了但是点确定后超时了
![image](https://github.com/TophantTechnology/ARL/assets/145330698/f2648602-48d0-4ec3-b9d3-bdf7323d0afa)

**Comment by 1c3z** [comment]
1. 普通任务下发也会超时么？
2. 服务是不是在正常运行
3. 可以排查日志看看有什么报错信息

**Comment by YamiKurumi** [comment]
> 1. 普通任务下发也会超时么？
> 2. 服务是不是在正常运行
> 3. 可以排查日志看看有什么报错信息

1.普通任务能正常下发
2.服务在正常运行
3.报错信息是指这个吗：WARNING/ForkPoolWorker-1] ???[???]: error on ('Connection broken: IncompleteRead(0 bytes read)', IncompleteRead(0 bytes read))

**Comment by 1c3z** [comment]
Connection broken ， rabbitmq 没连上。

**Comment by YamiKurumi** [comment]
![image](https://github.com/TophantTechnology/ARL/assets/145330698/ae8c388b-385d-4726-92f0-2c075b4177d8)
