### ISSUE TITLE
问题反馈-风险巡航问题

### ISSUE THREAD

**Issue by whiT3-web** [TophantTechnology/ARL#756]
## 描述问题

1.我发现当我添加资产监控任务的话，第二次任务的结果比第一次少，不确定第二次任务还会对第一次任务发现的URL进行扫描吗？
![image](https://github.com/TophantTechnology/ARL/assets/55690087/7c82b8c1-b1df-4bc6-a395-d6c5c6543b9f)

2.那我设置风险巡航任务下发，但该功能又不支持扫端口，且一般为URL。
![image](https://github.com/TophantTechnology/ARL/assets/55690087/503f34de-cce7-41a5-97a9-bb926d95b227)

需求：对一堆公网IP进行风险巡航，定期扫描这些IP的风险，如端口、弱口令、敏感路径与文件等安全隐患，且每次扫描都是一个新的任务，不会因为上一次扫到而这一次就不扫了，请问大佬该如何进行操作设置？

是不是进行如下图设置就可以呢大佬？
![image](https://github.com/TophantTechnology/ARL/assets/55690087/9ede0377-4030-43c9-bc6c-7991c84afeca)
![image](https://github.com/TophantTechnology/ARL/assets/55690087/8119242d-ac58-43d1-be37-ce3cfd2a7da3)

## 环境信息

- 操作系统：ubuntu20.4
- Docker版本：24.0.5
- ARL 版本：2.6.1

**Comment by 1c3z** [comment]
1. 资产监控任务会和资产分组里的数据进行比对，任务里面的站点是新发现的站点数据。

2. 计划任务下发的任务都是独立的，只是可以定时执行或者周期执行

3.  不会因为上一次扫到而这一次就不扫了，可以在监控任务配置策略，这样新出来的站点才会扫描，资产分组里已经有的站点就不会扫描了。

**Comment by whiT3-web** [comment]
> 1. 资产监控任务会和资产分组里的数据进行比对，任务里面的站点是新发现的站点数据。
> 2. 计划任务下发的任务都是独立的，只是可以定时执行或者周期执行
> 3. 不会因为上一次扫到而这一次就不扫了，可以在监控任务配置策略，这样新出来的站点才会扫描，资产分组里已经有的站点就不会扫描了。

谢谢大佬！
