### ISSUE TITLE
文件泄漏扫描到的文件如何查找

### ISSUE THREAD

**Issue by soapffz** [TophantTechnology/ARL#759]
最新2.6.2 docker版本

在文件泄漏界面看到了200访问成功一个备份文件，再访问已经被删除了

arl中是否保存了，在worker容器里翻了一下并没有找到

谢谢大佬

**Comment by soapffz** [comment]
#368

**Comment by soapffz** [comment]
[似乎获得长度之后就直接关闭了](https://github.com/TophantTechnology/ARL/blob/25b7e5afb9259c625cbbbbbcd20c329e5755cdcf/arl_tool/fileleakV2.py#L212)

**Comment by 1c3z** [comment]
没有文件内容本身
