### ISSUE TITLE
日志出现报错Permission denied: '/code/app/config.yaml'

### ISSUE THREAD

**Issue by shellsec** [TophantTechnology/ARL#76]
日志出现报错 docker-compose logs -f  --tail=10

arl_mongodb  | 2021-01-14T03:30:40.219+0000 I NETWORK  [initandlisten] waiting for connections on port 27017
arl_scheduler | Parse config.yaml error [Errno 13] Permission denied: '/code/app/config.yaml'
arl_scheduler | Parse config.yaml error [Errno 13] Permission denied: '/code/app/config.yaml'
arl_scheduler | Parse config.yaml error [Errno 13] Permission denied: '/code/app/config.yaml'
arl_scheduler | Parse config.yaml error [Errno 13] Permission denied: '/code/app/config.yaml'
arl_scheduler | Parse config.yaml error [Errno 13] Permission denied: '/code/app/config.yaml'
arl_scheduler | Parse config.yaml error [Errno 13] Permission denied: '/code/app/config.yaml'
arl_scheduler | Parse config.yaml error [Errno 13] Permission denied: '/code/app/config.yaml'
arl_scheduler | Parse config.yaml error [Errno 13] Permission denied: '/code/app/config.yaml'
arl_scheduler | Parse config.yaml error [Errno 13] Permission denied: '/code/app/config.yaml'
arl_rabbitmq | 2021-01-14 03:30:48.484 [info] <0.681.0> Ready to start client connection listeners
arl_rabbitmq | 2021-01-14 03:30:48.484 [info] <0.44.0> Application rabbitmq_prometheus started on node rabbit@8db7920d4a2e
arl_rabbitmq | 2021-01-14 03:30:48.488 [info] <0.985.0> started TCP listener on [::]:5672
arl_rabbitmq | 2021-01-14 03:30:48.704 [info] <0.681.0> Server startup complete; 4 plugins started.
arl_rabbitmq |  * rabbitmq_prometheus
arl_rabbitmq |  * rabbitmq_management
arl_rabbitmq |  * rabbitmq_web_dispatch
arl_rabbitmq |  * rabbitmq_management_agent
arl_rabbitmq |  completed with 4 plugins.
arl_rabbitmq | 2021-01-14 03:30:48.704 [info] <0.681.0> Resetting node maintenance status
arl_worker   | Parse config.yaml error [Errno 13] Permission denied: '/code/app/config.yaml'
arl_worker   | Parse config.yaml error [Errno 13] Permission denied: '/code/app/config.yaml'
arl_worker   | Parse config.yaml error [Errno 13] Permission denied: '/code/app/config.yaml'
arl_worker   | Parse config.yaml error [Errno 13] Permission denied: '/code/app/config.yaml'
arl_worker   | Parse config.yaml error [Errno 13] Permission denied: '/code/app/config.yaml'
arl_worker   | Parse config.yaml error [Errno 13] Permission denied: '/code/app/config.yaml'
arl_worker   | Parse config.yaml error [Errno 13] Permission denied: '/code/app/config.yaml'
arl_worker   | Parse config.yaml error [Errno 13] Permission denied: '/code/app/config.yaml'
arl_worker   | Parse config.yaml error [Errno 13] Permission denied: '/code/app/config.yaml'
arl_web exited with code 1
arl_scheduler exited with code 255

**Comment by shellsec** [comment]
临时关闭selinux：

获取当前selinux状态

getenforce 

 

Enforcing为开启，Permissive为关闭

临时关闭：setenforce 0

永久关闭selinux：

vim /etc/sysconfig/selinux

SELINUX=enforcing 替换为SELINUX=disabled

重启后，运行命令sestatus

SELinux status ：  disabled

**Comment by 1c3z** [comment]
关闭selinux 可以不？

**Comment by shellsec** [comment]
已解决
