### ISSUE TITLE
批量导入超时

### ISSUE THREAD

**Issue by m4ra7h0n** [TophantTechnology/ARL#763]
你好师傅，好像是超过12s钟的解析后面就停止了，对于很大资产这种需求好像比较麻烦。
<img width="613" alt="image" src="https://github.com/TophantTechnology/ARL/assets/71647398/15015192-f6fa-460a-bf12-7dc57b028821">
或者可以增加一个文件导入功能吗，非常感谢!

**Comment by 1c3z** [comment]
1. 这里一般是下主域名。

2. 如果要下很多很多子域，可以考虑Burp 启动。
