### ISSUE TITLE
资产分组页面相关需求

### ISSUE THREAD

**Issue by ki9mu** [TophantTechnology/ARL#78]
在任务管理页面添加了大量二级域名后，在资产分组页面将所有二级域名整合，但SSL证书、服务、文件泄露、URL信息部分并未整合到资产分组中,希望能一并整合。
这样，例如在看所有的文件泄露时，无需再一点开每一个二级域名。

**Comment by 1c3z** [comment]
资产分组这个添加是为了监控域名有个比对的地方才添加的。

有个折中的办法，可以访问下面的URL查看所有的文件泄露的检出
```
http://ip/taskList/taskDetail?target=x&page=1&size=10&tabIndex=6&ts=1610627555457
```

**Comment by 0d9y** [comment]
这个需求有办法自己改一下么？

**Comment by 1c3z** [comment]
@0d9y 访问一个任务详情页面，将页面上的task_id删除就可以查看所有的SSL证书、服务、文件泄露、URL信息。
