### ISSUE TITLE
建议

### ISSUE THREAD

**Issue by BY86381557** [TophantTechnology/ARL#83]
可以像goby那样联动xray主动扫描

添加域名，选择是否需要扫描

**Comment by 1c3z** [comment]
这个要加的话，估计要到下下个版本了。

**Comment by byr0nchan** [comment]
建议添加告警功能，邮件、钉钉、Freebuf私信等方式

**Comment by 1c3z** [comment]
@byr0nchan    监控任务结果邮件、钉钉推送已经加上了，等下个版本发布。

**Comment by 1c3z** [comment]
@byr0nchan  告警功能已加。 欢迎更新。

**Comment by 1c3z** [comment]
@BY86381557  先关闭issue了。
