### ISSUE TITLE
扫描资产准确度

### ISSUE THREAD

**Issue by ymbzd** [TophantTechnology/ARL#85]
选择全端口扫描时，并不扫描。

**Comment by ymbzd** [comment]
> 经过测试扫描资产的准确度很低，会有很多漏的

**Comment by 1c3z** [comment]
可以执行下面的三条命令观察输出有什么异常。
```
docker-compose ps 
docker-compose logs -f  --tail=10
tail -f *.log
```

**Comment by 1c3z** [comment]
@ymbzd 
麻烦使用下面的命令看下有端口结果么
```
nmap -p- --min-rate 100 --max-rtt-timeout 50ms --max-retries 5 -sS -n -PE -Pn --open ip
```

**Comment by ymbzd** [comment]
我是docker搭建的 要进入哪个容器去执行吗  还是直接在搭建的服务器上跑就行

**Comment by ymbzd** [comment]
我直接在搭建的服务器上执行是没问题的，只是很慢
![image](https://user-images.githubusercontent.com/39881690/110901443-4ba1b800-833f-11eb-9c46-0abc18b8b6fd.png)

**Comment by ymbzd** [comment]
另外反馈一下，不只是全端口不扫描，其他选项也是什么都扫不到

**Comment by ymbzd** [comment]
![image](https://user-images.githubusercontent.com/39881690/110902352-bb647280-8340-11eb-8ccb-5d351ea032ad.png)
扫描另外一个IP  用搭建的服务器扫描结果如上  在ARL无论选择全端口或TOP1000 100都没有扫描结果

**Comment by ymbzd** [comment]
![image](https://user-images.githubusercontent.com/39881690/110902352-bb647280-8340-11eb-8ccb-5d351ea032ad.png)
扫描另外一个IP  用搭建的服务器扫描结果如上  在ARL无论选择全端口或TOP1000 100都没有扫描结果

**Comment by 1c3z** [comment]
@ymbzd 

top 1000 扫描的时候，用的是下面这个命令。（nmap 6.4 会有参数错误，服务器可以升级下nmap）
```
nmap ip  -sS -n --open --defeat-rst-ratelimit -PE -PS22,80,443,3389,8007-8011,8443,9090,8080-8091,8093,8099,5000-5004,2222,3306,1433,21,25 --max-rtt-timeout 50ms  --initial-rtt-timeout 100ms --min-rate 64 --script-timeout 6s --host-timeout 300s --min-hostgroup 64 --min-parallelism 64 --max-retries 3
```

对于图片中的站点，有点问题，发现 删除`--max-rtt-timeout 50ms ` 这个参数可以运行，这个下个版本会修复

**Comment by 1c3z** [comment]
下面是全端口扫描的时候的命令
```
nmap ip -p 0-65535 -sS -n --open --defeat-rst-ratelimit -PE -PS22,80,443,3389,8007-8011,8443,9090,8080-8091,8093,8099,5000-5004,2222,3306,1433,21,25 --max-rtt-timeout 50ms --initial-rtt-timeout 100ms --min-rate 64 --script-timeout 6s --host-timeout 900s --min-hostgroup 64 --min-parallelism 64 --max-retries 2
```
对于第一个IP, 全端口扫描没结果是扫描过程超时了, 通过host-timeout设置为超时时间900s。

**Comment by 1c3z** [comment]
已修复，欢迎更新

**Comment by ymbzd** [comment]
好的大佬&nbsp; 马上来更新试试看！



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年3月19日(星期五) 下午3:33
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [TophantTechnology/ARL] 扫描资产准确度 (#85)





 
已修复，欢迎更新

**Comment by m2hxs** [comment]
> ![image](https://user-images.githubusercontent.com/39881690/110902352-bb647280-8340-11eb-8ccb-5d351ea032ad.png) 扫描另外一个IP 用搭建的服务器扫描结果如上 在ARL无论选择全端口或TOP1000 100都没有扫描结果

大佬你好，我在执行扫描的时候，发现类似的端口忽略问题，可以找你请教一下测试的方法吗？ @ymbzd
