### ISSUE TITLE
只有子域名有信息记录，其他都没有数据

### ISSUE THREAD

**Issue by Stowaway-y** [TophantTechnology/ARL#87]
![image](https://user-images.githubusercontent.com/42023732/106247545-a9c08300-624a-11eb-9ca9-25f6dd9d1785.png)
![image](https://user-images.githubusercontent.com/42023732/106247566-b218be00-624a-11eb-8a87-ca3960f3517f.png)
![image](https://user-images.githubusercontent.com/42023732/106247599-bba22600-624a-11eb-9b70-0aa7948b2f96.png)
这是什么原因啊，我已经重新装了2遍了

**Comment by 1c3z** [comment]
可以再下个任务, 执行下面的三条命令并尝试触发错误观察输出有什么异常。

```
docker-compose ps 
docker-compose logs -f  --tail=10
tail -f *.log
```

**Comment by Stowaway-y** [comment]
arl_rabbitmq | 2021-01-29 15:27:21.643 [info] <0.423.0>磁盘空闲限制设置为50MB
是这个限制磁盘空间导致空间不足，系统崩溃退出了么？

**Comment by 1c3z** [comment]
应该不是这个原因，可以把日志发上来，我看下。

**Comment by Jamalmo** [comment]
我也出现这个问题了，我是手动安装的，没用docker，该怎么调试，看哪里的问题呢？

**Comment by 1c3z** [comment]
@Jamalmo  开全端口了？  可能是扫描端口过程出现了异常。

**Comment by Jamalmo** [comment]
我刚开始开了全端口、服务识别，不行，刚试了关闭端口扫描，只开了前四个都不行，第一次耗时长一些，第二次，刚开始扫描，然后一秒以后点进任务，出来，就可以看到alt-dns，带端口扫描的任务，直接报error

**Comment by 1c3z** [comment]
报error的话，可以看下worker的日志，里面有报错信息  @Jamalmo

**Comment by Jamalmo** [comment]
/usr/local/lib/python3.6/site-packages/celery/platforms.py:796: RuntimeWarning: You're running the worker with superuser privileges: this is
absolutely not recommended!

Please specify a different user using the --uid option.

User information: uid=0 euid=0 gid=0 egid=0

  uid=uid, euid=euid, gid=gid, egid=egid,

worker: Warm shutdown (MainProcess)


worker日志只有这些，没有别的。

**Comment by Jamalmo** [comment]
worker日志指的是arl_worker吧，我找到问题了，是nmap版本的问题，需要，在7.25beta2以后才加入的script-timeout参数存在问题导致出错，我用了目前官网的最新版nmap，问题解决。
