### ISSUE TITLE
每次关闭容器后在重新启动就会丢失全部数据，请问有没有新增数据同步功能的计划？

### ISSUE THREAD

**Issue by MrWQ** [TophantTechnology/ARL#88]
每次关闭容器后在重新启动就会丢失全部数据，请问有没有新增数据同步功能的计划？

目前我的临时解决方案是修改docker-compose.yaml：先使用命令docker-compose up -d正常启动ARL的五个容器，然后修改docker-compose.yaml文件中的arl_mongo容器和对它的依赖，然后使用docker-compose down可以正常关闭其余四个容器。
当再次使用docker-compose up -d启动时可以正常启动其余四个容器，然后访问web页面是可以有数据保留的。

我尝试通过volumes参数./data:data来给mongo容器指定db存储目录，发现当关闭容器后在重新启动还是会丢失全部数据。可能是我找到数据库存储目录错了

我的建议是可以配置volumes参数来讲灯塔的结果保存到物理硬盘上，这样可以很方便的在关闭容器后再启动容器可以同步数据

**Comment by 1c3z** [comment]
只要mongo容器没有被删除过，数据就还在。(有点草率了，逃)

停止的话可以用 docker-compose stop， 容器不会被删除。 

下个版本将会改用 volumes。

**Comment by 1c3z** [comment]
已更新，欢迎更新

https://github.com/TophantTechnology/ARL/wiki/ARL-2.3-%E6%96%B0%E6%B7%BB%E5%8A%A0%E5%8A%9F%E8%83%BD%E8%AF%A6%E7%BB%86%E8%AF%B4%E6%98%8E
