### ISSUE TITLE
添加任务显示提交失败？

### ISSUE THREAD

**Issue by LTDR** [TophantTechnology/ARL#9]
管理权限
正常操作
首次添加
直接失败
当场懵逼

**Comment by 1c3z** [comment]
IP 任务？ 
看下是否在 屏蔽IP列表里面

https://github.com/TophantTechnology/ARL/blob/master/docker/config-docker.yaml#L29

**Comment by LTDR** [comment]
> IP 任务？
> 看下是否在 屏蔽IP列表里面
> 
> https://github.com/TophantTechnology/ARL/blob/master/docker/config-docker.yaml#L29
学到了！完美解决！
