### ISSUE TITLE
报错之后，任务终止

### ISSUE THREAD

**Issue by Stowaway-y** [TophantTechnology/ARL#90]
arl_scheduler | [2021-02-18 18:37:13] [INFO] [MainThread] [scheduler.py:145] 1613644633.6102352
arl_scheduler | [2021-02-18 18:37:43] [INFO] [MainThread] [scheduler.py:145] 1613644663.5836225
arl_scheduler | [2021-02-18 18:38:13] [INFO] [MainThread] [scheduler.py:145] 1613644693.5684073
arl_scheduler | [2021-02-18 18:38:43] [INFO] [MainThread] [scheduler.py:145] 1613644723.56294
arl_scheduler | [2021-02-18 18:39:13] [INFO] [MainThread] [scheduler.py:145] 1613644753.5573828
arl_scheduler | [2021-02-18 18:39:43] [INFO] [MainThread] [scheduler.py:145] 1613644783.5546982
arl_scheduler | [2021-02-18 18:40:13] [INFO] [MainThread] [scheduler.py:145] 1613644813.5473566
arl_rabbitmq | 2021-02-18 10:40:25.877 [error] <0.1056.0> closing AMQP connection <0.1056.0> (172.18.0.6:39494 -> 172.18.0.2:5672):
arl_rabbitmq | missed heartbeats from client, timeout: 60s
arl_rabbitmq | 2021-02-18 10:40:25.877 [info] <0.1176.0> Closing all channels from connection '<<"172.18.0.6:39494 -> 172.18.0.2:5672">>' because it has been closed
arl_rabbitmq | 2021-02-18 10:40:40.779 [error] <0.1107.0> closing AMQP connection <0.1107.0> (172.18.0.5:32976 -> 172.18.0.2:5672):
arl_rabbitmq | missed heartbeats from client, timeout: 60s
arl_rabbitmq | 2021-02-18 10:40:40.780 [info] <0.1183.0> Closing all channels from connection '<<"172.18.0.5:32976 -> 172.18.0.2:5672">>' because it has been closed
arl_scheduler | [2021-02-18 18:40:43] [INFO] [MainThread] [scheduler.py:145] 1613644843.5275393
arl_mongodb  | 2021-02-18T10:40:54.034+0000 I STORAGE  [conn10] createCollection: arl.ip with generated UUID: 538576a0-53c7-4e03-8b65-283a5f8b8fc3
arl_scheduler | [2021-02-18 18:41:13] [INFO] [MainThread] [scheduler.py:145] 1613644873.5250497
arl_scheduler | [2021-02-18 18:41:43] [INFO] [MainThread] [scheduler.py:145] 1613644903.520822
![image](https://user-images.githubusercontent.com/42023732/108345404-2e366e00-7219-11eb-9c16-13d13845bac7.png)

**Comment by 1c3z** [comment]
任务已经是完成状态了 。

**Comment by Stowaway-y** [comment]
我把所有任务全勾选了，但是只能扫出来域名和ip

**Comment by 1c3z** [comment]
可能任务下发时开启了全端口扫描，目标可能存在防护设备的情况大量端口扫描会出现异常。 可以选择Top 10端口扫描，或者关闭端口扫描，将只会探测80,443端口。
