### ISSUE TITLE
监控能不能自定义配置项

### ISSUE THREAD

**Issue by tomdogs1** [TophantTechnology/ARL#92]
监控能不能自定义配置项

**Comment by 1c3z** [comment]
目前不支持配置， 是想要加什么配置呀？ 场景可以举例说下么。

**Comment by tomdogs1** [comment]
觉得可以做一个和添加任务一样的选项，比如fofa，端口自定义啊，这些。而且添加的任务结束了，是不是要弄一个添加到监控，或者手动重新开始的按钮

**Comment by 1c3z** [comment]
对于新发现的域名，业务状态会经常变动，也许当时端口是关闭的，过几天又是开放的，多关注，可以手动根据自己的需求进行端口扫描。

**Comment by 1c3z** [comment]
@tomdogs1 
手动下发的任务在任务结束后可以点击同步按钮会将资产同步到相应的资产组。

![image](https://user-images.githubusercontent.com/9052484/110272209-98feec00-8004-11eb-836e-75322cf73f1a.png)
