### ISSUE TITLE
CDN IP 端口扫描跳过

### ISSUE THREAD

**Issue by 1c3z** [TophantTechnology/ARL#93]
对于公网资产扫端口时，大部分IP可能都是CDN节点（重点关注国内），扫描端口的意义不是很大，浪费了时间和带宽。

CDN IP 判断方法
1. 可以收集CDN相关的IP段, 可以判断目标IP是否在段呢。
2. CDN常用的 cname, 可以判断域名的cname是否包含在里面。
3.  还有就是如果一个域名解析的IP有多个，直接判断该IP为CDN节点。

对于1和2 不知道哪里可以找到一些相关的资料。

**Comment by icxtoken** [comment]
https://github.com/shmilylty/OneForAll/blob/master/modules/iscdn.py

**Comment by 1c3z** [comment]
http://cdn.chinaz.com/
