### ISSUE TITLE
停止任务显示，没有找到Celery id

### ISSUE THREAD

**Issue by ByCold** [TophantTechnology/ARL#95]
停止任务显示，没有找到Celery id

**Comment by 1c3z** [comment]
可能任务下发的时候出了点问题，。这个是在出任务停止功能前下的任务么？

**Comment by union-cmd** [comment]
<img width="1027" alt="image" src="https://user-images.githubusercontent.com/61687719/112837027-f0f1b580-90cd-11eb-8449-7367e8aa74d3.png">

**Comment by union-cmd** [comment]
就像这样

**Comment by 1c3z** [comment]
@union-cmd   
这个是新版本的？目前还不知道为啥会出现这个错误。

或者参考这个 #47, 手动进容器删除。 

```
docker exec -ti arl_mongodb mongo -u admin -p admin 
use arl
db.task.remove({"status":"waiting"}) 
```

**Comment by Mr-xn** [comment]
> @union-cmd
> 这个是新版本的？目前还不知道为啥会出现这个错误。
> 
> 或者参考这个 #47, 手动进容器删除。
> 
> ```
> docker exec -ti arl_mongodb mongo -u admin -p admin 
> use arl
> db.task.remove({"status":"waiting"}) 
> ```

同样的情况，出现场景是在批量停止大量的任务时候，因为重启了后 之前属于 waiting 状态的任务不会自动开始，希望可以修复一下 waiting 状态 任务重启自动进行，其次就是删除的时候 自动跳过 状态为 waiting 状态的，就 nice 了。

**Comment by 1c3z** [comment]
> > @union-cmd
> > 这个是新版本的？目前还不知道为啥会出现这个错误。
> > 或者参考这个 #47, 手动进容器删除。
> > ```
> > docker exec -ti arl_mongodb mongo -u admin -p admin 
> > use arl
> > db.task.remove({"status":"waiting"}) 
> > ```
> 
> 同样的情况，出现场景是在批量停止大量的任务时候，因为重启了后 之前属于 waiting 状态的任务不会自动开始，希望可以修复一下 waiting 状态 任务重启自动进行，其次就是删除的时候 自动跳过 状态为 waiting 状态的，就 nice 了。


1.属于 waiting 状态的任务不会自动开始， 这个有可能是没有成功下发到队列。‘
 2.waiting 状态 任务重启自动进行， 后面右边添加一个重新下发任务的操作。
3.是删除的时候 自动跳过 状态为 waiting 状态的， 我后面优化下。
