### ISSUE TITLE
关于添加多个域名，如何统一导出

### ISSUE THREAD

**Issue by xtzxtz** [TophantTechnology/ARL#98]
我在页面添加多个域名时，每个域名都是区分进行扫描，无法进行批量导出，请问如何可以设置成批量导出

**Comment by 1c3z** [comment]
目前可以先通过资产分组功能，将添加的多个域名添加一个分组。
然后再通过任务同步功能同步到资产分组。
![image](https://user-images.githubusercontent.com/9052484/111251587-8448d680-864a-11eb-99fe-07c2838abb71.png)

在通过资产分组，域名tab页面内导出域名功能导出。
![image](https://user-images.githubusercontent.com/9052484/111251638-97f43d00-864a-11eb-9435-ee5d7deed20e.png)



下个版本会添加批量导出的功能。

**Comment by 1c3z** [comment]
已发布，欢迎更新
